// SPDX-License-Identifier: LGPL-2.1-or-later WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2025 newmassrael
//
// This file is part of SCE (SCXML Core Engine).
//
// Dual Licensed:
// 1. LGPL-2.1: Free for unmodified use (see LICENSE-LGPL-2.1.md)
// 2. Commercial: For modifications (contact newmassrael@gmail.com)
//
// Commercial License:
//   Individual: $5000 cumulative
//   Enterprise: Contact for pricing
//   Contact: https://github.com/newmassrael
//
// Full terms: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE

//! # SCE Rust Runtime
//!
//! Runtime support library for W3C SCXML 1.0 state machines generated by
//! `sce-codegen generate -l rust`. This crate provides:
//!
//! - [`StatePolicy`]: the trait contract generated code implements
//! - [`Engine`]: the execution engine parameterized on a `StatePolicy`
//! - `scripting::IScriptEngine`: trait for runtime ECMAScript evaluation
//!   (implementations: [`sce-rust-lua`](../sce_rust_lua/index.html))
//! - `helpers::*`: W3C algorithm helpers (LCA, entry/exit chains, conflict
//!   resolution, event matching, etc.), ported 1:1 from C++ `sce/include/core/`
//!   and `sce/include/common/`
//!
//! ## Source of Truth
//!
//! This crate is a 1:1 port of the C++ runtime at
//! `sce/include/static/StaticExecutionEngine.h` and related headers. Method
//! names, field layouts, and semantics match C++ exactly. When C++ and Kotlin
//! diverge, C++ wins.
//!
//! ## Threading Model
//!
//! [`Engine<P>`] is **single-threaded**. It is `Send` but **not** `Sync`.
//! Callers that need multi-threaded access must wrap in `Arc<Mutex<Engine<P>>>`.
//! This matches the C++ `StaticExecutionEngine` model — the microstep loop is
//! single-threaded by design ("you don't pay for what you don't use").
//!
//! ## Script Engine Access
//!
//! Engine DI Parity RFC (Path B+): script engines are constructed per
//! [`Engine`] instance and injected via the generated `Policy::new(engine)`
//! constructor. Pick a backend by depending on the relevant crate
//! (`sce-rust-lua`, future `sce-rust-quickjs`) and pass `Arc::new(LuaEngine::new())`
//! to your machine's `Policy::new`. No process-global singleton is involved.
//!
//! ## Example
//!
//! ```ignore
//! use sce_rust_runtime::{Engine, StatePolicy};
//!
//! // MyPolicy is generated by `sce-codegen generate -l rust`.
//! let policy = MyPolicy::new();
//! let mut engine = Engine::new(policy);
//! engine.initialize();
//! // ...process events via engine.process_event(...) / engine.tick() ...
//! ```

#![cfg_attr(feature = "no_std", no_std)]
#![deny(clippy::undocumented_unsafe_blocks)]
#![warn(missing_docs)]
#![warn(clippy::all)]

// Watching-zenoh RFC §5.J.2 (C3 Atomic B-β): cfg-assert the
// incompatible feature combinations at compile time. The `no_std`
// feature is mutually exclusive with `http-send` (tokio/reqwest are
// std-coupled) and with both script-engine features (Lua and QuickJS
// require `alloc`, which `no_std` forbids per spec line 1989 zero-
// alloc mandate). `compile_error!` fires a clear, actionable message
// before the build reaches its first std-coupled symbol — without
// this guard a misconfigured Cargo profile would otherwise surface as
// "cannot find type `Vec` in module `core`" deep in the std-coupled
// modules, which is the textbook silent-broken-hook anti-pattern.
#[cfg(all(feature = "no_std", feature = "http-send"))]
compile_error!(
    "`no_std` and `http-send` are mutually exclusive: tokio/reqwest are std-coupled. \
     Either drop `http-send` (and any `<send type=\"BasicHTTPEventProcessor\">` from \
     your SCXML), or drop `no_std`. Watching-zenoh RFC §5.J.2 line 1983."
);

// ── Bounded-collection type aliases (watching-zenoh RFC §5.J.2) ──────
//
// Under `--features=no_std` the runtime crate is `#![no_std]` with **no
// `alloc` dependency** per spec line 1989-1994 ("zero `alloc`
// dependency"). String-typed event payload fields (`_event.data`,
// `_event.sendid`, `_event.origin`, `_event.origintype`,
// `_event.invokeid`) bound their capacity at `MAX_EVENT_STRING_LEN`
// bytes. `SceString` is `std::string::String` under the default std
// build (unchanged API) and `heapless::String<MAX_EVENT_STRING_LEN>`
// under `--features=no_std` (stack-allocated, `Result`-returning
// `push_str`). 256 is the v1 cap, sized to fit RFC §5.D telemetry-event
// payloads + an origin URI without truncation; per-document tunable via
// `<scxml sce:event-string-capacity="N">` is deferred until a consumer
// surfaces a documented overflow.
//
// Pattern mirrors the §5.D event-queue capacity (`EVENT_QUEUE_CAPACITY`
// emitted from codegen via `<sce:capacity>` per B-γ1) plus B-γ2b's
// microstep-dedup cap (`heapless::FnvIndexSet<_, 64>` reasoned
// constant). When the no_std consumer signals a per-document
// requirement, the codegen can grow a parallel `EVENT_STRING_CAPACITY`
// const and this alias becomes generic over the const.

/// Maximum FIFO depth of the no_std event queue (internal + external).
///
/// Bounds the `heapless::Deque<T, _>` capacity of
/// [`EventQueueManager`](crate::helpers::event_queue::EventQueueManager) under
/// `--features=no_std`. Distinct from [`MAX_SCHEDULED_EVENTS`] — the queue
/// holds events *waiting to be processed*, while the scheduler holds events
/// *waiting on a delay timer*. Distinct from
/// [`MAX_SCHEDULED_EVENTS`] (delay table) and from the
/// per-document `<sce:capacity>` author-tunable that B-γ1 emits as the
/// generated `EVENT_QUEUE_CAPACITY` const — wiring the per-document value into
/// the runtime crate requires either stabilised `generic_const_exprs` or a
/// const-traits architecture and is deferred until consumer signal demands it.
///
/// v1 value 64 covers typical statechart microstep depth: W3C SCXML §C.1
/// mandates the internal queue is drained between external events, so the
/// peak depth is the maximum chained `<raise>` count in a single macrostep.
/// The W3C 202 test corpus tops out at ~16 chained raises (test 224's
/// `done.invoke.*` fan-out); 64 gives a 4× safety margin without bloating
/// stack footprint (64 × sizeof(EventWithMetadata) ≈ 64 × 32 bytes = 2 KiB).
///
/// The std build's [`EventQueueManager`] keeps `std::collections::VecDeque<T>`
/// (unbounded) so this constant only affects the `--features=no_std` variant.
pub const MAX_EVENT_QUEUE_DEPTH: usize = 64;

/// Maximum number of simultaneously-pending delayed events in the no_std
/// [`PullScheduler`](crate::engine::PullScheduler) ring.
///
/// Bounds the `heapless::Vec<ScheduledEntry<E>, _>` capacity of the no_std
/// variant of the scheduler. `<send delay>` author surface; this is the
/// in-flight delay-pending dimension, distinct from the event queue capacity
/// (`<sce:capacity>` populates `EVENT_QUEUE_CAPACITY` per-document for the
/// ready-to-process queue — that's a different dimension).
///
/// v1 value 32 covers typical statechart in-flight `<send delay>` parallelism
/// (1-5 simultaneous timers in the W3C 202 test corpus) with a ~6× safety
/// margin. Profiler-driven per-document tunable (via a future
/// `StatePolicy::SCHEDULER_CAPACITY: usize` associated const + matching
/// `<sce:scheduler-capacity>` parser surface, mirroring B-γ1's `<sce:capacity>`
/// architecture) is deferred until an MCU consumer surfaces a concrete
/// over/under-fit signal — per `feedback_planned_not_yagni` discipline
/// (capacities ride consumer signal, not speculation).
///
/// The std build's `PullScheduler` keeps `Vec<ScheduledEntry<E>>` (unbounded)
/// so this constant only affects the `--features=no_std` variant.
pub const MAX_SCHEDULED_EVENTS: usize = 32;

/// Maximum byte length of an event metadata string under `--features=no_std`.
///
/// Bounds the capacity of [`SceString`] for `EventMetadata.data`,
/// `EventMetadata.send_id`, `EventMetadata.origin`, `EventMetadata.origin_type`,
/// and `EventMetadata.invoke_id`. The std build's `SceString = String` is
/// unbounded; this constant only affects the no_std variant.
///
/// v1 value 256 covers W3C SCXML 5.10.1 platform-event payloads + send-target
/// URIs without truncation. Author-tunable cap deferred to a future atomic
/// once an MCU consumer surfaces a concrete overflow signal (per
/// `feedback_planned_not_yagni` discipline — capacities ride consumer
/// signal, not speculation).
pub const MAX_EVENT_STRING_LEN: usize = 256;

/// Owned-string type used for event metadata fields across both std and
/// no_std builds.
///
/// - std build: `std::string::String` (unbounded, heap-allocated).
/// - no_std build: `heapless::String<MAX_EVENT_STRING_LEN>` (stack-allocated,
///   `push_str` is `Result`-returning).
///
/// Construction sites that need to convert from `&str` to `SceString` should
/// use [`sce_string_from_str`] which abstracts the API divergence.
#[cfg(not(feature = "no_std"))]
pub type SceString = ::std::string::String;
/// no_std variant of [`SceString`]: stack-allocated `heapless::String` capped
/// at [`MAX_EVENT_STRING_LEN`]. See the std-variant doc-comment above for the
/// full contract.
#[cfg(feature = "no_std")]
pub type SceString = ::heapless::String<MAX_EVENT_STRING_LEN>;

/// Convert a borrowed `&str` into an owned [`SceString`].
///
/// Under std this is `s.to_string()`. Under no_std this is
/// `heapless::String::try_from(s).unwrap_or_default()` — strings longer than
/// [`MAX_EVENT_STRING_LEN`] truncate to empty rather than panic, matching the
/// behavior `unwrap_or_default` provides on the std side for malformed inputs.
/// Callers that need to detect the truncation should use heapless's `try_from`
/// directly under `cfg(feature = "no_std")`.
#[inline]
pub fn sce_string_from_str(s: &str) -> SceString {
    #[cfg(not(feature = "no_std"))]
    {
        s.to_string()
    }
    #[cfg(feature = "no_std")]
    {
        SceString::try_from(s).unwrap_or_default()
    }
}

pub mod engine;
pub mod event;
pub mod hal;
pub mod helpers;
/// W3C SCXML C.2 BasicHTTPEventProcessor send payload shapes.
///
/// Gated out of `no_std` builds because the module body uses
/// `std::collections::HashMap`. B-γ swaps in a `heapless::FnvIndexMap`
/// equivalent for the no_std variant; until then the no_std build
/// excludes the module entirely and the cfg-assert above rejects
/// any consumer that enables `http-send` together with `no_std`.
#[cfg(not(feature = "no_std"))]
pub mod http;
/// W3C SCXML 6.4 invoke lifecycle helpers.
///
/// Watching-zenoh RFC §5.J.2: whole-module gated to `!no_std`. `<invoke>` is
/// rejected upstream at codegen time via `codegen/no-std-invoke-not-supported`
/// (B-γ2c `591979e5`), so the lifecycle helpers (PendingInvoke / ChildSession
/// / defer_invoke / cancel_invokes_for_state / execute_pending_invokes /
/// create_done_invoke_event_name) are unreachable from emitted no_std code.
/// Mirrors `helpers::invoke_processing` whole-module gate (same atomic).
#[cfg(not(feature = "no_std"))]
pub mod invoke;
pub mod policy;
/// ECMAScript engine abstraction.
///
/// Gated out of `no_std` builds because the trait impls land in
/// `sce-rust-lua` / future `sce-rust-quickjs`, both of which require
/// `alloc` (the cfg-assert above rejects the combination at
/// compile time). The trait surface itself is `core::`-portable;
/// re-introducing it under no_std is B-γ's call when consumer demand
/// materialises.
#[cfg(not(feature = "no_std"))]
pub mod scripting;

// Public re-exports — the primary API surface
pub use engine::Engine;
pub use event::{EventMetadata, EventType, EventWithMetadata};
pub use hal::{Hal, NoOpHal, StdHal};
#[cfg(not(feature = "no_std"))]
pub use http::{HttpSendRequest, HttpSendResponse};
pub use policy::StatePolicy;
#[cfg(not(feature = "no_std"))]
pub use scripting::{IScriptEngine, ScriptError, ScriptResult, ScriptValue, SetCurrentEventArgs};
