// SCE-GENERATED — DO NOT EDIT
// source-hash: c97edcb094613d8138825758fc943d853d23ad4854f2fa7dcf6ff6f58539b674
// template-hash: 40688f16ecbedc989f96890868d75e825c91fd7775d66bfd37b45df9857c9aa5
// generated-at: 0


// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 [Author of input SCXML file]
//
// Generated by SCE Code Generator (Go backend)
// From: integration_resources/empty_finalize_updates_the_location/empty_finalize_updates_the_location__sce_synth_invoke__inv_empty.scxml
//
// This generated code is MIT licensed and may be freely used in any project.
// Runtime engine dependency (sce-go-runtime): LGPL-2.1-or-later WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// Full license: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE
// Generated Go state machine for `empty_finalize_updates_the_location__sce_synth_invoke__inv_empty`.
//
// Generated by SCE Code Generator (Go backend).
// Implements sce.StatePolicy with full transition logic,
// entry/exit actions, and event processing.


// SCE-MAP: empty_finalize_updates_the_location__sce_synth_invoke__inv_empty.scxml:3 :: _machine

package empty_finalize_updates_the_location

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	sce "github.com/newmassrael/sce-go-runtime"
)

// Ensure imports are used
var (
	_ = fmt.Sprintf
	_ = filepath.Join
	_ = strings.HasPrefix
	_ = time.Duration(0)
)

// ======================================================================
// State type (W3C SCXML 3.3)
// ======================================================================

type EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState int

const (
	EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateAnswer EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState = 0
	EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateDone EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState = 1
)

func (s EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) String() string {
	switch s {
	case EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateAnswer:
		return "answer"
	case EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateDone:
		return "done"
	}
	return "unknown"
}

// ======================================================================
// Event type (W3C SCXML 3.12)
// ======================================================================

type EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent int

const (
	EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventErrorExecution EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent = 0
	EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventFromEmptyChild EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent = 1
	// W3C SCXML 3.13: Sentinel for eventless transition dispatch
	EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventNull EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent = 2
)

func (e EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent) String() string {
	switch e {
	case EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventErrorExecution:
		return "error.execution"
	case EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventFromEmptyChild:
		return "fromEmptyChild"
	case EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventNull:
		return ""
	}
	return "unknown"
}

// ======================================================================
// Policy struct
// ======================================================================

type EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy struct {
	// W3C SCXML 3.13: Last transition metadata
	lastTransitionIsInternal  bool
	lastTransitionIsTargetless bool
	lastTransitionSourceState EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState
	// W3C SCXML 3.13: Transition action tracking
	lastTransitionIndex   int
	hasTransitionActions   bool
	// W3C SCXML 5.10.1: External event flag
	nextEventIsExternal bool
	pendingEventName string
	pendingEventData string
	pendingEventType string
	pendingEventSendid string
	pendingEventOrigin string
	pendingEventOrigintype string
	pendingEventInvokeid string
	// W3C SCXML 5.10: Session ID
	SessionID string
	// W3C SCXML B.1: Script engine handle (per-instance, Path B+ Q1=(d) Go=interface ref)
	ScriptEngine sce.IScriptEngine
	scriptEngineInitialized bool
	// W3C SCXML C.2.3: inbound BasicHTTP endpoint serving this machine,
	// declared by the deployment before Initialize(). The address belongs to
	// whoever runs the listener, so the machine takes it from here rather than
	// guessing one. Empty means no such endpoint is deployed, and no BasicHTTP
	// entry is published in _ioprocessors.
	BasicHTTPAccessURI string
	// W3C SCXML 6.4: Parent communication
	ParentExternalQueue chan sce.ParentEvent
	InvokeID           string
	ChildSessionID     string
	// §scxml-6.4.3: invoke param VALUES staged by the parent, applied after
	// this machine's datamodel init so they override its `<data>` defaults.
	pendingParams      map[string]interface{}
}

// NewEmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy creates a new policy with default values.
func NewEmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy() EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy {
	return EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy{
		lastTransitionSourceState: EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateAnswer,
	}
}




// ensureScriptEngine lazily initializes the script engine session.
//
// Engine DI Parity RFC: panics if ScriptEngine was not set on the policy
// before Initialize() — mirrors Kotlin's mandatory constructor parameter
// contract. Silent no-op would otherwise turn missed injection into a
// hidden runtime regression (every <assign>/<log>/guard becomes a no-op
// and the SM walks to its default-state final without diagnostic).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) ensureScriptEngine() {
	if p.scriptEngineInitialized {
		return
	}
	engine := p.ScriptEngine
	if engine == nil {
		panic("EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy: ScriptEngine field must be set before Initialize()")
	}
	sessionID := p.SessionID
	if sessionID == "" {
		sessionID = sce.GenerateSessionID()
		p.SessionID = sessionID
	}
	if !engine.HasSession(sessionID) {
		_ = engine.CreateSession(sessionID)
	}
	// W3C SCXML C.1.1 / C.2.3: the _ioprocessors entries come from the same
	// helper every other backend uses, so a machine reads the same entry names
	// and the same addresses whichever one runs it.
	_ = engine.SetupSystemVariables(sessionID, "empty_finalize_updates_the_location__sce_synth_invoke__inv_empty",
		sce.BuildIoProcessors(sessionID, p.BasicHTTPAccessURI))
	p.scriptEngineInitialized = true
}

// InitializeDataModel sets up datamodel via script engine (W3C SCXML 5.3).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) InitializeDataModel(eng *sce.Engine[EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent]) {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	sessionID := p.SessionID

	// W3C SCXML 5.3: Initialize _sessionid
	_ = engine.SetVariable(sessionID, "_sessionid", sessionID)

	// W3C SCXML 5.3: Initialize _name
	_ = engine.SetVariable(sessionID, "_name", "empty_finalize_updates_the_location__sce_synth_invoke__inv_empty")

	// W3C SCXML 5.2.2: Initialize global datamodel variables
	// W3C SCXML 5.2: Runtime variable tally (init to nil)
	_ = engine.SetVariable(sessionID, "tally", nil)



	// §scxml-6.4.3: apply the invoke params the parent staged — overriding the
	// `<data>` default this block just seeded, and only for a name the child
	// declares ("if the names do not match, the Processor MUST NOT add the
	// value ... to the invoked session's data model"). `HasVariable` is that
	// filter, and it is this channel's only copy of the rule.
	if len(p.pendingParams) > 0 {
		for paramName, paramValue := range p.pendingParams {
			if engine.HasVariable(sessionID, paramName) {
				_ = engine.SetVariable(sessionID, paramName, paramValue)
			}
		}
		p.pendingParams = nil
	}
}

// evaluateGuard evaluates a guard condition via script engine.
// W3C SCXML 4.3.2: If a condition expression cannot be evaluated, the processor
// MUST treat it as false and MUST raise error.execution.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) evaluateGuard(guard string, eng *sce.Engine[EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent]) bool {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	result, err := engine.EvaluateExpression(p.SessionID, guard)
	if err != nil {
		eng.Raise(sce.NewPlatformError(EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventErrorExecution, "a <transition> cond failed to evaluate"))
		return false
	}
	return sce.ScriptToBool(result)
}

// executeScript executes a script block via script engine.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) executeScript(script string) error {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	return engine.ExecuteScript(p.SessionID, script)
}

// setCurrentEvent binds _event system variable (W3C SCXML 5.10) and answers
// which rung of §scxml-B-2-8-1 the payload got, because the binding is the
// only place that knows.
//
// This used to be `_ = engine.SetCurrentEvent(...)`: the ladder decided
// between a DOM, a value and a space-normalized string, and the decision was
// dropped one line later. A payload that announced structure and would not
// parse therefore reached the document as raw characters, every
// _event.data.<field> read empty, and nothing anywhere could say so — see
// sce.PayloadReading.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) setCurrentEvent(name string) sce.PayloadReading {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	data := p.pendingEventData
	eventType := p.pendingEventType
	sendID := p.pendingEventSendid
	// W3C SCXML C.1: `_event.origin` is the sender's published
	// `_ioprocessors` location, not its bare session id — and this is the one
	// place that publishes `_event` to the document, so this is where the id
	// becomes a location. The engine keeps the bare id in
	// `EventMetadata.Origin` because its session-keyed lookups (<finalize>
	// dispatch, cancelled-invoke filtering) match on it; converting at the
	// raise would make one value serve two consumers that need different
	// spellings. The conversion itself lives in `sce.PublishedOrigin`, the
	// port of the `IOProcessorHelper::publishedOrigin` the C++ engines share:
	// a second spelling of the rule is how the backends would stop agreeing.
	origin := sce.PublishedOrigin(p.pendingEventOrigin)
	originType := p.pendingEventOrigintype
	invokeID := p.pendingEventInvokeid
	reading, err := engine.SetCurrentEvent(p.SessionID, sce.SetCurrentEventArgs{
		Name:       name,
		Data:       data,
		Type:       eventType,
		SendID:     sendID,
		Origin:     origin,
		OriginType: originType,
		InvokeID:   invokeID,
	})
	if err != nil {
		// An engine that could not bind _event at all has a larger problem
		// than an unreadable payload, and reporting PayloadUndecodable for it
		// would point a host at the wrong thing.
		return sce.PayloadAbsent
	}
	return reading
}

// assignVariable assigns a value to a datamodel variable via script engine.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) assignVariable(location, expr string) error {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	script := location + " = " + expr
	return engine.ExecuteScript(p.SessionID, script)
}

// getVariable reads a datamodel variable from the script engine.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) getVariable(name string) interface{} {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	result, err := engine.GetVariable(p.SessionID, name)
	if err != nil {
		return nil
	}
	return result
}

// SetParamValueInScriptEngine stores an invoke param's VALUE for deferred
// application after datamodel init (§scxml-6.4.3).
//
// Params are applied at the end of InitializeDataModel, overriding the
// `<data>` default only for names the child declares. The value crosses as a
// value: this took the parent's value rendered as Lua source and
// re-evaluated it here until 2026-08-21, which survived every value a test
// had tried and lost the ones Lua cannot spell — `ToScriptLiteral` renders a
// non-finite number as `+Inf`, which is not a Lua expression, so an
// `<invoke>` `<param expr="1/0"/>` arrived as nothing at all.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) SetParamValueInScriptEngine(name string, value interface{}) {
	if p.pendingParams == nil {
		p.pendingParams = make(map[string]interface{})
	}
	p.pendingParams[name] = value
}


// ExecutePendingInvokes is a no-op (no invokes in this SM).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) ExecutePendingInvokes(engine *sce.Engine[EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent]) {}

// TickChildren is a no-op (no invokes in this SM).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) TickChildren(engine *sce.Engine[EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent]) {}

// ======================================================================
// StatePolicy interface implementation
// ======================================================================

// InitialState returns the initial state (W3C SCXML 3.3).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) InitialState() EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState {
	return EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateAnswer
}

// IsFinalState returns true if state is a <final> state (W3C SCXML 3.7).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) IsFinalState(state EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) bool {
	switch state {
	case EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateDone:
		return true
	}
	return false
}

// GetParent returns the parent of state, or (zero, false) if root (W3C SCXML 3.3).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) GetParent(state EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) (EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, bool) {
	switch state {
	}
	return 0, false
}

// IsCompoundState returns true if state has children (W3C SCXML 3.3).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) IsCompoundState(state EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) bool {
	switch state {
	}
	return false
}

func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) IsParallelState(_ EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) bool { return false }
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) GetParallelRegions(_ EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) []EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState { return nil }

// IsDescendantOf returns true if desc is a descendant of anc (W3C SCXML 3.12).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) IsDescendantOf(desc, anc EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) bool {
	current := desc
	for {
		parent, ok := p.GetParent(current)
		if !ok {
			return false
		}
		if parent == anc {
			return true
		}
		current = parent
	}
}

// GetDocumentOrder returns the document order index (W3C SCXML Appendix D).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) GetDocumentOrder(state EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) int {
	switch state {
	case EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateAnswer:
		return 0
	case EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateDone:
		return 1
	}
	return -1
}

// GetEventName returns the string name of an event (W3C SCXML 3.12).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) GetEventName(event EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent) string {
	return event.String()
}

// GetEventFromName looks up an event by name (W3C SCXML 3.12).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) GetEventFromName(name string) (EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent, bool) {
	switch name {
	case "error.execution":
		return EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventErrorExecution, true
	case "fromEmptyChild":
		return EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventFromEmptyChild, true
	}
	return EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventNull, false
}

// GetStateName returns the string name of a state (W3C SCXML 3.3).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) GetStateName(state EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) string {
	return state.String()
}

// NullEvent returns the sentinel for eventless transition dispatch (W3C SCXML 3.13).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) NullEvent() EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent {
	return EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventNull
}

// GetInitialChildren returns initial children of a compound state (W3C SCXML 3.6).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) GetInitialChildren(state EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) []EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState {
	switch state {
	}
	return nil
}

// LastTransitionIsInternal returns the internal transition flag (W3C SCXML 3.13).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) LastTransitionIsInternal() bool {
	return p.lastTransitionIsInternal
}

// SetLastTransitionIsInternal sets the internal transition flag.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) SetLastTransitionIsInternal(value bool) {
	p.lastTransitionIsInternal = value
}

// LastTransitionIsTargetless returns the targetless transition flag (W3C SCXML 3.13).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) LastTransitionIsTargetless() bool {
	return p.lastTransitionIsTargetless
}

// SetLastTransitionIsTargetless sets the targetless transition flag.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) SetLastTransitionIsTargetless(value bool) {
	p.lastTransitionIsTargetless = value
}

// LastTransitionSourceState returns the source state of the last transition.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) LastTransitionSourceState() EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState {
	return p.lastTransitionSourceState
}

// SetLastTransitionSourceState sets the source state of the last transition.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) SetLastTransitionSourceState(state EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) {
	p.lastTransitionSourceState = state
}


// SetNextEventIsExternal sets the external event flag (W3C SCXML 5.10.1).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) SetNextEventIsExternal(value bool) {
	p.nextEventIsExternal = value
}

// HasParallelStates returns whether the SM has parallel states.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) HasParallelStates() bool {
	return false
}

// NeedsScriptEngine returns whether the SM needs a script engine.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) NeedsScriptEngine() bool {
	return true
}

// NeedsEventScheduler reports whether a host must drive this machine with
// Tick rather than Step alone.
//
// W3C SCXML 6.2: Step runs a macrostep and never drains the delayed-send
// scheduler nor ticks an invoked child, so a host that only ever calls it
// waits forever with nothing said. Same verdict the generate manifest
// publishes as needs_event_scheduler.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) NeedsEventScheduler() bool {
	return false
}

// NeedsDataModelInit returns whether the SM needs datamodel init.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) NeedsDataModelInit() bool {
	return true
}

func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) HasInvokeSupport() bool { return false }
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) HasChildTick() bool { return false }
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) HasFinalize() bool { return false }
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) HasAutoforward() bool { return false }
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) HasActiveStates() bool { return false }
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) GetActiveStates() []EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState { return nil }
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) HasExternalEventFlag() bool { return true }
// GetInitialOrHistoryChild returns the initial child considering history (W3C SCXML 3.11).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) GetInitialOrHistoryChild(state EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState {
	children := p.GetInitialChildren(state)
	if len(children) > 0 {
		return children[0]
	}
	return state
}
// ExecuteFinalizeForChildEvent is a no-op (no finalize invokes).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) ExecuteFinalizeForChildEvent(_ *sce.EventWithMetadata[EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent], _ *sce.Engine[EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent]) {}
// ForwardToAutoforwardChildren is a no-op (no autoforward invokes).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) ForwardToAutoforwardChildren(_ string, _ sce.EventMetadata, _ *sce.Engine[EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent]) {}

// PopulateEventMetadata stores pending event metadata (W3C SCXML 5.10).
// Note: event name is set separately via setCurrentEvent(), not from metadata.
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) PopulateEventMetadata(meta *sce.EventMetadata) {
	p.pendingEventData = meta.Data
	p.pendingEventType = meta.EventType.String()
	p.pendingEventSendid = meta.SendID
	p.pendingEventOrigin = meta.Origin
	p.pendingEventOrigintype = meta.OriginType
	p.pendingEventInvokeid = meta.InvokeID
}

// ClearEventMetadata resets pending event metadata (W3C SCXML 5.10).
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) ClearEventMetadata() {
	p.pendingEventName = ""
	p.pendingEventData = ""
	p.pendingEventType = ""
	p.pendingEventSendid = ""
	p.pendingEventOrigin = ""
	p.pendingEventOrigintype = ""
	p.pendingEventInvokeid = ""
}




// ExecuteEntryActions executes onentry actions for a state (W3C SCXML 3.8).
//line empty_finalize_updates_the_location__sce_synth_invoke__inv_empty.scxml:3
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) ExecuteEntryActions(state EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, engine *sce.Engine[EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent], pathChild *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) {
	// Only a `<parallel>` machine descends into defaults here, so a machine
	// without one has nothing to tell an ancestor entry from a target entry.
	_ = pathChild
	p.ensureScriptEngine()
	switch state {
	default:
		// No entry actions
	}
}

// ExecuteExitActions executes onexit actions for a state (W3C SCXML 3.9).
//line empty_finalize_updates_the_location__sce_synth_invoke__inv_empty.scxml:3
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) ExecuteExitActions(state EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, engine *sce.Engine[EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent], preTransitionActive []EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState) {
	p.ensureScriptEngine()
	switch state {
	default:
		// No exit actions
	}
}

// ProcessTransition evaluates guards and takes a matching transition (W3C SCXML 3.13).
// Returns true if a transition was taken.
//line empty_finalize_updates_the_location__sce_synth_invoke__inv_empty.scxml:3
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) ProcessTransition(currentState *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, event EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent, engine *sce.Engine[EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent]) bool {
	// W3C SCXML 5.10: Bind _event system variable for guard evaluation
	if event != EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventNull {
		// §scxml-B-2-8-1: the rung the payload got, handed to the engine
		// rather than dropped. This is the only frame that has both the
		// reading and the event it belongs to.
		engine.NotePayloadReading(event, p.setCurrentEvent(p.GetEventName(event)))
	}

	// W3C SCXML 3.12: Try transitions in current state first
	if p.tryTransitionInState(*currentState, event, currentState, engine) {
		return true
	}


	return false
}


// tryTransitionInState checks transitions for a single state.
//line empty_finalize_updates_the_location__sce_synth_invoke__inv_empty.scxml:3
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) tryTransitionInState(checkState EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, event EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent, currentState *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, engine *sce.Engine[EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent]) bool {
	switch checkState {
	case EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateAnswer:
		// Eventless transition 0
		if event == EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventNull {
			*currentState = EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateDone
			p.lastTransitionIsInternal = false
			p.lastTransitionIsTargetless = false
			p.lastTransitionSourceState = EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateAnswer
			p.lastTransitionIndex = 0
			p.hasTransitionActions = true
			return true
		}
	}
	return false
}

// ExecuteTransitionActions executes actions for the last taken transition (W3C SCXML 3.13).
//line empty_finalize_updates_the_location__sce_synth_invoke__inv_empty.scxml:3
func (p *EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyPolicy) ExecuteTransitionActions(engine *sce.Engine[EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyState, EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEvent]) {
	p.ensureScriptEngine()
	if !p.hasTransitionActions {
		return
	}
	source := p.lastTransitionSourceState
	idx := p.lastTransitionIndex
	if source == EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyStateAnswer && idx == 0 {
		//line empty_finalize_updates_the_location__sce_synth_invoke__inv_empty.scxml:9

	// W3C SCXML 6.2: send id="__send_0"
	// W3C SCXML 6.2: Evaluate <param>/namelist expressions at send time
	{
		p.ensureScriptEngine()
		se := p.ScriptEngine
		// W3C SCXML 6.2 / test178: a name may repeat and every value must be
		// delivered, so this is an ordered list rather than a map. The typed
		// value is kept rather than its text — a receiver reading
		// `_event.data.value === 42` finds the string "42" unequal.
		parts := make([]sce.EventDataParam, 0)
		if paramVal, paramErr := se.EvaluateExpression(p.SessionID, `7`); paramErr == nil {
			parts = append(parts, sce.EventDataParam{Name: "tally", Value: paramVal})
		} else {
			engine.Raise(sce.NewPlatformError(EmptyFinalizeUpdatesTheLocationSceSynthInvokeInvEmptyEventErrorExecution, "<send> <param name='tally'> expr failed to evaluate"))
		}
		eventDataStr := sce.BuildJSONFromTypedParams(parts)
		_ = eventDataStr
	// W3C SCXML 6.2: Send to parent
	if p.ParentExternalQueue != nil {
		p.ParentExternalQueue <- sce.ParentEvent{Name: "fromEmptyChild", Data: eventDataStr}
	}
	}

		return
	}
}
