// SCE-GENERATED — DO NOT EDIT
// source-hash: 4e6429b83bcaf7486fcebf0bd3d8457e9484662e476d9f68336b36b99ab225f5


// SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 [Author of input SCXML file] (content derived from the input document)
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 newmassrael (content copied from SCE templates)
//
// Generated by SCE Code Generator (Go backend)
// From: sce-build/tests/fixtures/static_datamodel/static_donedata_record.scxml
//
// This generated code is usable under terms of your choice when it was produced
// by an unmodified sce-codegen and is not part of a competing product
// (SCE Linking Exception, section 3; see LICENSE-GENERATED.md).
// Full license: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE
// Generated Go state machine for `static_donedata_record`.
//
// Generated by SCE Code Generator (Go backend).
// Implements sce.StatePolicy with full transition logic,
// entry/exit actions, and event processing.


// SCE-MAP: static_donedata_record.scxml:13 :: _machine

package static_donedata_record

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	sce "github.com/newmassrael/sce-go-runtime"
	scealgorithm "github.com/newmassrael/sce-forge-runtime/algorithm"
)

// Ensure imports are used
var (
	_ = fmt.Sprintf
	_ = filepath.Join
	_ = strings.HasPrefix
	_ = time.Duration(0)
	_ scealgorithm.Failure
)

// ======================================================================
// State type (W3C SCXML 3.3)
// ======================================================================

type StaticDonedataRecordState int

const (
	StaticDonedataRecordStateCounting StaticDonedataRecordState = 0
	StaticDonedataRecordStateDone StaticDonedataRecordState = 1
)

func (s StaticDonedataRecordState) String() string {
	switch s {
	case StaticDonedataRecordStateCounting:
		return "counting"
	case StaticDonedataRecordStateDone:
		return "done"
	}
	return "unknown"
}

// StaticDonedataRecordStateFromName is the read half of the pair above — a state
// id back into the state it names (W3C SCXML 3.3).
//
// A host that persists where a machine was has to write it down as TEXT: the
// constants above are a build artefact of one binary, and the process that
// resumes is a different one. String publishes the name and this reads it back,
// which is what lets a journal survive its own record and reach
// sce.Engine.EnterAt.
//
// The second return is false for a name this document does not declare. A name
// guessed at rather than refused is how a restore reaches a configuration
// nobody recorded — and the refusal is what makes a typo in a journal a
// reported failure instead of a machine quietly somewhere else.
//
// Emitted from the same loop over the document's states as String, so the two
// age together.
func StaticDonedataRecordStateFromName(name string) (StaticDonedataRecordState, bool) {
	switch name {
	case "counting":
		return StaticDonedataRecordStateCounting, true
	case "done":
		return StaticDonedataRecordStateDone, true
	}
	var zero StaticDonedataRecordState
	return zero, false
}

// StaticDonedataRecordAllStates is every state this document declares, in the
// order the constants above are issued.
//
// Emitted from the same loop, so a walk over it is a walk over the document
// rather than over a list somebody maintained beside it — a test that spells
// its own list goes on passing when the document grows a state.
var StaticDonedataRecordAllStates = []StaticDonedataRecordState{
	StaticDonedataRecordStateCounting,
	StaticDonedataRecordStateDone,
}

// StaticDonedataRecordTarget is one token of a target list, as the document wrote
// it (W3C SCXML 3.13): a state, or a <history> the engine dereferences.
type StaticDonedataRecordTarget = sce.EntryTarget[StaticDonedataRecordState, sce.HistoryID]

// ======================================================================
// Document structure (W3C SCXML 3.2-3.4, 3.10)
//
// Package-level tables, because the structure is a fact about the document
// and not about a run: the engine's Appendix D procedures read them through
// the policy methods below, and a transition's target list is handed out as
// a slice of them rather than rebuilt on every selection.
// ======================================================================

// childStatesOfStaticDonedataRecord is §scxml-D-getChildStates per state: its
// <state>, <parallel> and <final> children, in document order.
var childStatesOfStaticDonedataRecord = [2][]StaticDonedataRecordState{
}

// initialTargetsOfStaticDonedataRecord is each compound state's initial transition
// target, as written (§scxml-3.3).
var initialTargetsOfStaticDonedataRecord = [2][]StaticDonedataRecordTarget{
}

// documentInitialTargetsOfStaticDonedataRecord is the target of the document's own
// initial transition, as written (§scxml-3.2).
var documentInitialTargetsOfStaticDonedataRecord = []StaticDonedataRecordTarget{sce.StateTarget[StaticDonedataRecordState, sce.HistoryID](StaticDonedataRecordStateCounting)}

// transitionTargetsOfStaticDonedataRecord is each transition's target list, as
// written (§scxml-3.13), by source state and the transition's index among its
// source's own transitions. A targetless transition's entry is empty.
var transitionTargetsOfStaticDonedataRecord = [2][][]StaticDonedataRecordTarget{
	StaticDonedataRecordStateCounting: {
		1: {sce.StateTarget[StaticDonedataRecordState, sce.HistoryID](StaticDonedataRecordStateDone)},
	},
}

// ======================================================================
// Event type (W3C SCXML 3.12)
// ======================================================================

type StaticDonedataRecordEvent int

const (
	StaticDonedataRecordEventBump StaticDonedataRecordEvent = 0
	StaticDonedataRecordEventErrorExecution StaticDonedataRecordEvent = 1
	StaticDonedataRecordEventFinish StaticDonedataRecordEvent = 2
	// W3C SCXML 3.13: Sentinel for eventless transition dispatch
	StaticDonedataRecordEventNull StaticDonedataRecordEvent = 3
)

func (e StaticDonedataRecordEvent) String() string {
	switch e {
	case StaticDonedataRecordEventBump:
		return "bump"
	case StaticDonedataRecordEventErrorExecution:
		return "error.execution"
	case StaticDonedataRecordEventFinish:
		return "finish"
	case StaticDonedataRecordEventNull:
		return ""
	}
	return "unknown"
}

// ── SCE Accepted Subset §2.15: the types the static variables are held in ──
// SCE Accepted Subset §2.15: an `enum:ViewMode` datamodel value.
type StaticDonedataRecordViewModeEnum uint8

const (
	EnumViewModeMonth StaticDonedataRecordViewModeEnum = 0
	EnumViewModeWeek StaticDonedataRecordViewModeEnum = 1
	EnumViewModeDay StaticDonedataRecordViewModeEnum = 2
	EnumViewModeAgendaList StaticDonedataRecordViewModeEnum = 3
)

// String is the name the enum document declares for the value.
func (v StaticDonedataRecordViewModeEnum) String() string {
	switch v {
	case EnumViewModeMonth:
		return "month"
	case EnumViewModeWeek:
		return "week"
	case EnumViewModeDay:
		return "day"
	case EnumViewModeAgendaList:
		return "agenda_list"
	}
	return ""
}

// SCE Accepted Subset §2.15: a `record:View` datamodel value.
type StaticDonedataRecordViewRecord struct {
	layout StaticDonedataRecordViewModeEnum
	zoom uint8
}

// Layout reports the `layout` field.
func (r StaticDonedataRecordViewRecord) Layout() StaticDonedataRecordViewModeEnum {
	return r.layout
}

// Zoom reports the `zoom` field.
func (r StaticDonedataRecordViewRecord) Zoom() uint8 {
	return r.zoom
}


// ======================================================================
// Policy struct
// ======================================================================

type StaticDonedataRecordPolicy struct {
	// W3C SCXML 5.10: Session ID
	SessionID string
	// ── SCE Accepted Subset §2.15: the datamodel="sce-static" variables ──
	// W3C SCXML 5.2: the `shown` datamodel variable, published (`sce:direction="out"`).
	vShown StaticDonedataRecordViewRecord
	// W3C SCXML 6.4: Parent communication (unbounded — see sce.ParentEventQueue)
	ParentExternalQueue *sce.ParentEventQueue
	InvokeID           string
	ChildSessionID     string
	// §scxml-6.4.3: invoke param VALUES staged by the parent, applied after
	// this machine's datamodel init so they override its `<data>` defaults.
	pendingParams      map[string]interface{}
}

// NewStaticDonedataRecordPolicy creates a new policy with default values.
func NewStaticDonedataRecordPolicy() StaticDonedataRecordPolicy {
	return StaticDonedataRecordPolicy{
		vShown: StaticDonedataRecordViewRecord{layout: EnumViewModeDay, zoom: 2},
	}
}

// Shown reports what the published `shown` datamodel
// variable holds now (W3C SCXML 5.2). Only the machine writes it.
func (p *StaticDonedataRecordPolicy) Shown() StaticDonedataRecordViewRecord {
	return p.vShown
}



// No script engine needed for this state machine.
func (p *StaticDonedataRecordPolicy) InitializeDataModel(eng *sce.Engine[StaticDonedataRecordState, StaticDonedataRecordEvent]) {}

// SetParamValueInScriptEngine is a no-op for state machines without script engine.
func (p *StaticDonedataRecordPolicy) SetParamValueInScriptEngine(name string, value interface{}) {}


// ExecutePendingInvokes is a no-op (no invokes in this SM).
func (p *StaticDonedataRecordPolicy) ExecutePendingInvokes(engine *sce.Engine[StaticDonedataRecordState, StaticDonedataRecordEvent]) {}

// TickChildren is a no-op (no invokes in this SM).
func (p *StaticDonedataRecordPolicy) TickChildren(engine *sce.Engine[StaticDonedataRecordState, StaticDonedataRecordEvent]) {}

// DeliverToParent delivers a delayed `<send target="#_parent">` whose wait is
// over, with the payload an immediate one carries (W3C SCXML 6.2 + 6.4). It
// waited in this machine's own queue, so `<cancel>` reached it and a child that
// ended first dropped it — the engine dispatches nothing once final. Emitted for
// every machine, since the one that needs it is an invoked child, which need not
// invoke anything itself.
func (p *StaticDonedataRecordPolicy) DeliverToParent(eventName, eventData string) bool {
	if p.ParentExternalQueue == nil {
		return false
	}
	p.ParentExternalQueue.Push(sce.ParentEvent{Name: eventName, Data: eventData})
	return true
}

// HasParentSession answers whether a session invoked this one (W3C SCXML C.1):
// the queue the invoking parent installs is the link to it.
func (p *StaticDonedataRecordPolicy) HasParentSession() bool {
	return p.ParentExternalQueue != nil
}

// ======================================================================
// StatePolicy interface implementation
// ======================================================================

// InitialState returns the initial state (W3C SCXML 3.3).
func (p *StaticDonedataRecordPolicy) InitialState() StaticDonedataRecordState {
	return StaticDonedataRecordStateCounting
}

// IsFinalState returns true if state is a <final> state (W3C SCXML 3.7).
func (p *StaticDonedataRecordPolicy) IsFinalState(state StaticDonedataRecordState) bool {
	switch state {
	case StaticDonedataRecordStateDone:
		return true
	}
	return false
}

// GetParent returns the parent of state, or (zero, false) if root (W3C SCXML 3.3).
func (p *StaticDonedataRecordPolicy) GetParent(state StaticDonedataRecordState) (StaticDonedataRecordState, bool) {
	switch state {
	}
	return 0, false
}

// IsCompoundState returns true if state is a <state> with child states — exactly
// the states that have an initial transition. A <parallel> is not compound
// (W3C SCXML 3.3).
func (p *StaticDonedataRecordPolicy) IsCompoundState(state StaticDonedataRecordState) bool {
	return len(initialTargetsOfStaticDonedataRecord[state]) > 0
}

func (p *StaticDonedataRecordPolicy) IsParallelState(_ StaticDonedataRecordState) bool { return false }

// GetChildStates returns state's <state>, <parallel> and <final> children, in
// document order — for a <parallel>, its regions (§scxml-D-getChildStates).
func (p *StaticDonedataRecordPolicy) GetChildStates(state StaticDonedataRecordState) []StaticDonedataRecordState {
	return childStatesOfStaticDonedataRecord[state]
}

// GetInitialTargets returns a compound state's initial transition target, as
// written; the engine's entry procedures dereference a <history> among them
// (W3C SCXML 3.3).
func (p *StaticDonedataRecordPolicy) GetInitialTargets(state StaticDonedataRecordState) []StaticDonedataRecordTarget {
	return initialTargetsOfStaticDonedataRecord[state]
}

// GetDocumentInitialTargets returns the target of the document's own initial
// transition, as written (W3C SCXML 3.2).
func (p *StaticDonedataRecordPolicy) GetDocumentInitialTargets() []StaticDonedataRecordTarget {
	return documentInitialTargetsOfStaticDonedataRecord
}

// W3C SCXML 3.10: this document declares no <history>, so no target list names
// one and the engine never asks the two below; answering would mean inventing
// one.
func (p *StaticDonedataRecordPolicy) GetHistoryParent(history sce.HistoryID) StaticDonedataRecordState {
	panic(fmt.Sprintf("StaticDonedataRecordPolicy declares no <history>; asked for %d", history))
}
func (p *StaticDonedataRecordPolicy) GetHistoryDefaultTargets(history sce.HistoryID) []StaticDonedataRecordTarget {
	panic(fmt.Sprintf("StaticDonedataRecordPolicy declares no <history>; asked for %d", history))
}
func (p *StaticDonedataRecordPolicy) HistoryValue(_ sce.HistoryID) ([]StaticDonedataRecordState, bool) {
	return nil, false
}

// GetDocumentOrder returns the document order index (W3C SCXML Appendix D).
func (p *StaticDonedataRecordPolicy) GetDocumentOrder(state StaticDonedataRecordState) int {
	switch state {
	case StaticDonedataRecordStateCounting:
		return 0
	case StaticDonedataRecordStateDone:
		return 1
	}
	return -1
}

// GetEventName returns the string name of an event (W3C SCXML 3.12).
func (p *StaticDonedataRecordPolicy) GetEventName(event StaticDonedataRecordEvent) string {
	return event.String()
}

// GetEventFromName looks up an event by name (W3C SCXML 3.12).
func (p *StaticDonedataRecordPolicy) GetEventFromName(name string) (StaticDonedataRecordEvent, bool) {
	switch name {
	case "bump":
		return StaticDonedataRecordEventBump, true
	case "error.execution":
		return StaticDonedataRecordEventErrorExecution, true
	case "finish":
		return StaticDonedataRecordEventFinish, true
	}
	return StaticDonedataRecordEventNull, false
}

// GetStateName returns the string name of a state (W3C SCXML 3.3).
func (p *StaticDonedataRecordPolicy) GetStateName(state StaticDonedataRecordState) string {
	return state.String()
}

// GetStateFromName reads a state id back into the state it names (W3C SCXML 3.3).
// The reverse of GetStateName, and what turns a host's recorded configuration
// back into the argument sce.Engine.EnterAt takes.
func (p *StaticDonedataRecordPolicy) GetStateFromName(name string) (StaticDonedataRecordState, bool) {
	return StaticDonedataRecordStateFromName(name)
}

// NullEvent returns the sentinel for eventless transition dispatch (W3C SCXML 3.13).
func (p *StaticDonedataRecordPolicy) NullEvent() StaticDonedataRecordEvent {
	return StaticDonedataRecordEventNull
}


// HasParallelStates returns whether the SM has parallel states.
func (p *StaticDonedataRecordPolicy) HasParallelStates() bool {
	return false
}

// NeedsScriptEngine returns whether the SM needs a script engine.
func (p *StaticDonedataRecordPolicy) NeedsScriptEngine() bool {
	return false
}

// NeedsEventScheduler reports whether a host must drive this machine with
// Tick rather than Step alone.
//
// W3C SCXML 6.2: Step runs a macrostep and never drains the delayed-send
// scheduler nor ticks an invoked child, so a host that only ever calls it
// waits forever with nothing said. Same verdict the generate manifest
// publishes as needs_event_scheduler.
func (p *StaticDonedataRecordPolicy) NeedsEventScheduler() bool {
	return false
}

// NeedsParent reports whether the document sends to its parent session — the
// generate manifest's needs_parent, read by Engine.RootStartRefusal.
func (p *StaticDonedataRecordPolicy) NeedsParent() bool {
	return false
}

// NeedsDataModelInit returns whether the SM needs datamodel init.
func (p *StaticDonedataRecordPolicy) NeedsDataModelInit() bool {
	return false
}

func (p *StaticDonedataRecordPolicy) HasInvokeSupport() bool { return false }
func (p *StaticDonedataRecordPolicy) HasChildTick() bool { return false }
func (p *StaticDonedataRecordPolicy) HasFinalize() bool { return false }
func (p *StaticDonedataRecordPolicy) HasAutoforward() bool { return false }
func (p *StaticDonedataRecordPolicy) HasActiveStates() bool { return false }
func (p *StaticDonedataRecordPolicy) GetActiveStates() []StaticDonedataRecordState { return nil }
// W3C SCXML 3.4: this machine keeps no active set — its configuration is the
// parent walk from the current state — so there is nothing for a restore to
// hand back here. sce.Engine.EnterAt reaches this only through HasActiveStates,
// which is false above; the method exists because the interface is one contract.
func (p *StaticDonedataRecordPolicy) SetActiveStates(_ []StaticDonedataRecordState) {}
// ExecuteFinalizeForChildEvent is a no-op (no finalize invokes).
func (p *StaticDonedataRecordPolicy) ExecuteFinalizeForChildEvent(_ *sce.EventWithMetadata[StaticDonedataRecordEvent], _ *sce.Engine[StaticDonedataRecordState, StaticDonedataRecordEvent]) {}
// ForwardToAutoforwardChildren is a no-op (no autoforward invokes).
func (p *StaticDonedataRecordPolicy) ForwardToAutoforwardChildren(_ string, _ sce.EventMetadata, _ *sce.Engine[StaticDonedataRecordState, StaticDonedataRecordEvent]) {}

// PopulateEventMetadata stores pending event metadata (W3C SCXML 5.10).
// Note: event name is set separately via setCurrentEvent(); metadata supplies
// only the name the event ARRIVED under, when that is not its value's own.
func (p *StaticDonedataRecordPolicy) PopulateEventMetadata(meta *sce.EventMetadata) {
}

// LiftTypedPayload binds the dequeued event's typed `_event.data` view from
// the data it carries (NL→IR Item C1 Path A).
//
// The typed carrier PopulateEventMetadata reads is filled by one producer, the
// generated Raise<Event> inject seam. Every other producer — <send> with
// <param>, an invoke forwarding either way, autoforward, BasicHTTP, mesh —
// fills EventMetadata.Data, so the schema's fields are read out of that here.
// A refusal is returned for the engine to raise as error.execution, which is
// what W3C SCXML 3.13 gives for a guard that cannot be evaluated.
func (p *StaticDonedataRecordPolicy) LiftTypedPayload(event StaticDonedataRecordEvent, meta *sce.EventMetadata) error {
	// This document lowered no typed guard, so no event carries a typed view.
	return nil
}

// ClearEventMetadata resets pending event metadata (W3C SCXML 5.10).
func (p *StaticDonedataRecordPolicy) ClearEventMetadata() {
}



// ExecuteEntryActions enters one state (W3C SCXML 3.8): adds it to the
// configuration, runs its <onentry>, and its <initial> transition's content when
// its initial state is entered by default.
//line static_donedata_record.scxml:13
func (p *StaticDonedataRecordPolicy) ExecuteEntryActions(state StaticDonedataRecordState, engine *sce.Engine[StaticDonedataRecordState, StaticDonedataRecordEvent], isDefaultEntry bool) {
	switch state {
	case StaticDonedataRecordStateDone:
		//line static_donedata_record.scxml:30
		// W3C SCXML 5.5: Evaluate donedata for final state
		doneEventData := ""
		{
			{
				var jsonParts []string
				{
					sceValue := (p.vShown.layout).String()
					{
						jsonParts = append(jsonParts, "\"layout\":" + sce.ScriptValueToJSON(sceValue))
					}
				}
				{
					sceValue := int64(p.vShown.zoom)
					{
						jsonParts = append(jsonParts, "\"zoom\":" + sce.ScriptValueToJSON(sceValue))
					}
				}
				// §scxml-5.5: the pairs that survived, `{}` when none did.
				doneEventData = "{" + strings.Join(jsonParts, ",") + "}"
			}
		}
		_ = doneEventData
		// W3C SCXML 5.5 + 6.3.1: Top-level <final> — stash donedata so the
		// invoking parent's RaiseDoneInvoke can lift it onto
		// done.invoke.<id>._event.data. Mirrors the C++ AOT
		// stashDonedataAtFinal contract and Rust
		// Engine::stash_donedata_at_final.
		engine.StashDonedataAtFinal(doneEventData)
	default:
		// No entry actions
	}
}

// ExecuteHistoryDefaultContent runs a <history>'s default transition content
// (W3C SCXML 3.10.2), after its parent's onentry (and after the parent's own
// <initial> content) when the history was taken with nothing recorded. The
// engine asks for it by the entry set's defaultHistoryContent answer; a history
// that restored what it recorded runs nothing.
//line static_donedata_record.scxml:13
func (p *StaticDonedataRecordPolicy) ExecuteHistoryDefaultContent(history sce.HistoryID, engine *sce.Engine[StaticDonedataRecordState, StaticDonedataRecordEvent]) {
	// W3C SCXML 3.10.2: no <history> in this document has default content.
}

// ExecuteExitActions exits one state (W3C SCXML 3.9): records its histories,
// runs its <onexit>, cancels its invocations and removes it from the
// configuration — §scxml-D-exitStates's order.
//line static_donedata_record.scxml:13
func (p *StaticDonedataRecordPolicy) ExecuteExitActions(state StaticDonedataRecordState, engine *sce.Engine[StaticDonedataRecordState, StaticDonedataRecordEvent], configurationBeforeExit []StaticDonedataRecordState) {
	// §scxml-D-exitStates orders one state's exit as onexit, then
	// cancelInvoke, then configuration.delete(s), so `In(s)` inside s's own
	// handler is true: the <onexit> switch comes first and the removal from
	// the configuration last.
	switch state {
	default:
		// No exit actions
	}
}



// BindCurrentEvent binds the event whose transitions are about to be selected as
// the _event their guards read (W3C SCXML 5.10) — before the first guard runs,
// and not for an eventless selection, which has no event of its own.
//line static_donedata_record.scxml:13
func (p *StaticDonedataRecordPolicy) BindCurrentEvent(event StaticDonedataRecordEvent, engine *sce.Engine[StaticDonedataRecordState, StaticDonedataRecordEvent]) {
	// This document's guards never read _event, so there is nothing to bind.
}

// FirstEnabledTransition is Appendix D selectTransitions, the half only this
// document can answer: the first of state's own transitions, in document order,
// that event enables and whose guard holds. The engine walks the atomic states
// and their ancestors and keeps the ordered set; the null event asks for
// eventless transitions.
//line static_donedata_record.scxml:13
func (p *StaticDonedataRecordPolicy) FirstEnabledTransition(state StaticDonedataRecordState, event StaticDonedataRecordEvent, engine *sce.Engine[StaticDonedataRecordState, StaticDonedataRecordEvent]) (sce.EnabledTransition[StaticDonedataRecordState, sce.HistoryID], bool) {
	switch state {
	case StaticDonedataRecordStateCounting:
		if event == StaticDonedataRecordEventBump {
			{
				return sce.EnabledTransition[StaticDonedataRecordState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 0,
					HasActions:      true,
					IsInternal:      true,
				}, true
			}
		}
		if event == StaticDonedataRecordEventFinish {
			{
				return sce.EnabledTransition[StaticDonedataRecordState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfStaticDonedataRecord[state][1],
					TransitionIndex: 1,
					HasActions:      false,
					IsInternal:      false,
				}, true
			}
		}
	}
	return sce.EnabledTransition[StaticDonedataRecordState, sce.HistoryID]{}, false
}

// ExecuteTransitionContent runs one transition's executable content (W3C SCXML
// 3.13), between the microstep's exits and its entries.
//line static_donedata_record.scxml:13
func (p *StaticDonedataRecordPolicy) ExecuteTransitionContent(source StaticDonedataRecordState, transitionIndex int, engine *sce.Engine[StaticDonedataRecordState, StaticDonedataRecordEvent]) {
	switch source {
	case StaticDonedataRecordStateCounting:
		switch transitionIndex {
		case 0:
			//line static_donedata_record.scxml:24
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {


	if func() bool { var sceFailure scealgorithm.Failure; sceValue := scealgorithm.AddUint8(&sceFailure, p.vShown.zoom, 1); if sceFailure.Failed() { engine.Raise(sce.NewPlatformError(StaticDonedataRecordEventErrorExecution, "<assign location='shown.zoom'>: an integer operation overflowed or failed")); return true }; p.vShown.zoom = sceValue; return false }() {
		return  // W3C SCXML 4.9: the error ends the block
	}



	p.vShown.layout = EnumViewModeAgendaList

			}()
		}
	}
}
