// SCE-GENERATED — DO NOT EDIT
// source-hash: 15abee63eca48c0d096ade54003293e94f23f9dffeaf437e4cf29a0ed73c4eb2


// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 [Author of input SCXML file]
//
// Generated by SCE Code Generator (Go backend)
// From: integration_resources/send_param_payload/send_param_payload__sce_synth_invoke__inv_emitter.scxml
//
// This generated code is MIT licensed and may be freely used in any project.
// Runtime engine dependency (sce-go-runtime): LGPL-2.1-or-later WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// Full license: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE
// Generated Go state machine for `send_param_payload__sce_synth_invoke__inv_emitter`.
//
// Generated by SCE Code Generator (Go backend).
// Implements sce.StatePolicy with full transition logic,
// entry/exit actions, and event processing.


// SCE-MAP: send_param_payload__sce_synth_invoke__inv_emitter.scxml:3 :: _machine

package send_param_payload

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	sce "github.com/newmassrael/sce-go-runtime"
)

// Ensure imports are used
var (
	_ = fmt.Sprintf
	_ = filepath.Join
	_ = strings.HasPrefix
	_ = time.Duration(0)
)

// ======================================================================
// State type (W3C SCXML 3.3)
// ======================================================================

type SendParamPayloadSceSynthInvokeInvEmitterState int

const (
	SendParamPayloadSceSynthInvokeInvEmitterStateEmit SendParamPayloadSceSynthInvokeInvEmitterState = 0
	SendParamPayloadSceSynthInvokeInvEmitterStateSent SendParamPayloadSceSynthInvokeInvEmitterState = 1
)

func (s SendParamPayloadSceSynthInvokeInvEmitterState) String() string {
	switch s {
	case SendParamPayloadSceSynthInvokeInvEmitterStateEmit:
		return "emit"
	case SendParamPayloadSceSynthInvokeInvEmitterStateSent:
		return "sent"
	}
	return "unknown"
}

// SendParamPayloadSceSynthInvokeInvEmitterStateFromName is the read half of the pair above — a state
// id back into the state it names (W3C SCXML 3.3).
//
// A host that persists where a machine was has to write it down as TEXT: the
// constants above are a build artefact of one binary, and the process that
// resumes is a different one. String publishes the name and this reads it back,
// which is what lets a journal survive its own record and reach
// sce.Engine.EnterAt.
//
// The second return is false for a name this document does not declare. A name
// guessed at rather than refused is how a restore reaches a configuration
// nobody recorded — and the refusal is what makes a typo in a journal a
// reported failure instead of a machine quietly somewhere else.
//
// Emitted from the same loop over the document's states as String, so the two
// age together.
func SendParamPayloadSceSynthInvokeInvEmitterStateFromName(name string) (SendParamPayloadSceSynthInvokeInvEmitterState, bool) {
	switch name {
	case "emit":
		return SendParamPayloadSceSynthInvokeInvEmitterStateEmit, true
	case "sent":
		return SendParamPayloadSceSynthInvokeInvEmitterStateSent, true
	}
	var zero SendParamPayloadSceSynthInvokeInvEmitterState
	return zero, false
}

// SendParamPayloadSceSynthInvokeInvEmitterAllStates is every state this document declares, in the
// order the constants above are issued.
//
// Emitted from the same loop, so a walk over it is a walk over the document
// rather than over a list somebody maintained beside it — a test that spells
// its own list goes on passing when the document grows a state.
var SendParamPayloadSceSynthInvokeInvEmitterAllStates = []SendParamPayloadSceSynthInvokeInvEmitterState{
	SendParamPayloadSceSynthInvokeInvEmitterStateEmit,
	SendParamPayloadSceSynthInvokeInvEmitterStateSent,
}

// SendParamPayloadSceSynthInvokeInvEmitterTarget is one token of a target list, as the document wrote
// it (W3C SCXML 3.13): a state, or a <history> the engine dereferences.
type SendParamPayloadSceSynthInvokeInvEmitterTarget = sce.EntryTarget[SendParamPayloadSceSynthInvokeInvEmitterState, sce.HistoryID]

// ======================================================================
// Document structure (W3C SCXML 3.2-3.4, 3.10)
//
// Package-level tables, because the structure is a fact about the document
// and not about a run: the engine's Appendix D procedures read them through
// the policy methods below, and a transition's target list is handed out as
// a slice of them rather than rebuilt on every selection.
// ======================================================================

// childStatesOfSendParamPayloadSceSynthInvokeInvEmitter is §scxml-D-getChildStates per state: its
// <state>, <parallel> and <final> children, in document order.
var childStatesOfSendParamPayloadSceSynthInvokeInvEmitter = [2][]SendParamPayloadSceSynthInvokeInvEmitterState{
}

// initialTargetsOfSendParamPayloadSceSynthInvokeInvEmitter is each compound state's initial transition
// target, as written (§scxml-3.3).
var initialTargetsOfSendParamPayloadSceSynthInvokeInvEmitter = [2][]SendParamPayloadSceSynthInvokeInvEmitterTarget{
}

// documentInitialTargetsOfSendParamPayloadSceSynthInvokeInvEmitter is the target of the document's own
// initial transition, as written (§scxml-3.2).
var documentInitialTargetsOfSendParamPayloadSceSynthInvokeInvEmitter = []SendParamPayloadSceSynthInvokeInvEmitterTarget{sce.StateTarget[SendParamPayloadSceSynthInvokeInvEmitterState, sce.HistoryID](SendParamPayloadSceSynthInvokeInvEmitterStateEmit)}

// transitionTargetsOfSendParamPayloadSceSynthInvokeInvEmitter is each transition's target list, as
// written (§scxml-3.13), by source state and the transition's index among its
// source's own transitions. A targetless transition's entry is empty.
var transitionTargetsOfSendParamPayloadSceSynthInvokeInvEmitter = [2][][]SendParamPayloadSceSynthInvokeInvEmitterTarget{
	SendParamPayloadSceSynthInvokeInvEmitterStateEmit: {
		0: {sce.StateTarget[SendParamPayloadSceSynthInvokeInvEmitterState, sce.HistoryID](SendParamPayloadSceSynthInvokeInvEmitterStateSent)},
	},
}

// ======================================================================
// Event type (W3C SCXML 3.12)
// ======================================================================

type SendParamPayloadSceSynthInvokeInvEmitterEvent int

const (
	SendParamPayloadSceSynthInvokeInvEmitterEventErrorExecution SendParamPayloadSceSynthInvokeInvEmitterEvent = 0
	SendParamPayloadSceSynthInvokeInvEmitterEventFromChild SendParamPayloadSceSynthInvokeInvEmitterEvent = 1
	// W3C SCXML 3.13: Sentinel for eventless transition dispatch
	SendParamPayloadSceSynthInvokeInvEmitterEventNull SendParamPayloadSceSynthInvokeInvEmitterEvent = 2
)

func (e SendParamPayloadSceSynthInvokeInvEmitterEvent) String() string {
	switch e {
	case SendParamPayloadSceSynthInvokeInvEmitterEventErrorExecution:
		return "error.execution"
	case SendParamPayloadSceSynthInvokeInvEmitterEventFromChild:
		return "fromChild"
	case SendParamPayloadSceSynthInvokeInvEmitterEventNull:
		return ""
	}
	return "unknown"
}

// ======================================================================
// Policy struct
// ======================================================================

type SendParamPayloadSceSynthInvokeInvEmitterPolicy struct {
	// W3C SCXML 5.10: Session ID
	SessionID string
	// W3C SCXML 6.4: Parent communication
	ParentExternalQueue chan sce.ParentEvent
	InvokeID           string
	ChildSessionID     string
	// §scxml-6.4.3: invoke param VALUES staged by the parent, applied after
	// this machine's datamodel init so they override its `<data>` defaults.
	pendingParams      map[string]interface{}
}

// NewSendParamPayloadSceSynthInvokeInvEmitterPolicy creates a new policy with default values.
func NewSendParamPayloadSceSynthInvokeInvEmitterPolicy() SendParamPayloadSceSynthInvokeInvEmitterPolicy {
	return SendParamPayloadSceSynthInvokeInvEmitterPolicy{
	}
}



// No script engine needed for this state machine.
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) InitializeDataModel(eng *sce.Engine[SendParamPayloadSceSynthInvokeInvEmitterState, SendParamPayloadSceSynthInvokeInvEmitterEvent]) {}

// SetParamValueInScriptEngine is a no-op for state machines without script engine.
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) SetParamValueInScriptEngine(name string, value interface{}) {}


// ExecutePendingInvokes is a no-op (no invokes in this SM).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) ExecutePendingInvokes(engine *sce.Engine[SendParamPayloadSceSynthInvokeInvEmitterState, SendParamPayloadSceSynthInvokeInvEmitterEvent]) {}

// TickChildren is a no-op (no invokes in this SM).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) TickChildren(engine *sce.Engine[SendParamPayloadSceSynthInvokeInvEmitterState, SendParamPayloadSceSynthInvokeInvEmitterEvent]) {}

// ======================================================================
// StatePolicy interface implementation
// ======================================================================

// InitialState returns the initial state (W3C SCXML 3.3).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) InitialState() SendParamPayloadSceSynthInvokeInvEmitterState {
	return SendParamPayloadSceSynthInvokeInvEmitterStateEmit
}

// IsFinalState returns true if state is a <final> state (W3C SCXML 3.7).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) IsFinalState(state SendParamPayloadSceSynthInvokeInvEmitterState) bool {
	switch state {
	case SendParamPayloadSceSynthInvokeInvEmitterStateSent:
		return true
	}
	return false
}

// GetParent returns the parent of state, or (zero, false) if root (W3C SCXML 3.3).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) GetParent(state SendParamPayloadSceSynthInvokeInvEmitterState) (SendParamPayloadSceSynthInvokeInvEmitterState, bool) {
	switch state {
	}
	return 0, false
}

// IsCompoundState returns true if state is a <state> with child states — exactly
// the states that have an initial transition. A <parallel> is not compound
// (W3C SCXML 3.3).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) IsCompoundState(state SendParamPayloadSceSynthInvokeInvEmitterState) bool {
	return len(initialTargetsOfSendParamPayloadSceSynthInvokeInvEmitter[state]) > 0
}

func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) IsParallelState(_ SendParamPayloadSceSynthInvokeInvEmitterState) bool { return false }

// GetChildStates returns state's <state>, <parallel> and <final> children, in
// document order — for a <parallel>, its regions (§scxml-D-getChildStates).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) GetChildStates(state SendParamPayloadSceSynthInvokeInvEmitterState) []SendParamPayloadSceSynthInvokeInvEmitterState {
	return childStatesOfSendParamPayloadSceSynthInvokeInvEmitter[state]
}

// GetInitialTargets returns a compound state's initial transition target, as
// written; the engine's entry procedures dereference a <history> among them
// (W3C SCXML 3.3).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) GetInitialTargets(state SendParamPayloadSceSynthInvokeInvEmitterState) []SendParamPayloadSceSynthInvokeInvEmitterTarget {
	return initialTargetsOfSendParamPayloadSceSynthInvokeInvEmitter[state]
}

// GetDocumentInitialTargets returns the target of the document's own initial
// transition, as written (W3C SCXML 3.2).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) GetDocumentInitialTargets() []SendParamPayloadSceSynthInvokeInvEmitterTarget {
	return documentInitialTargetsOfSendParamPayloadSceSynthInvokeInvEmitter
}

// W3C SCXML 3.10: this document declares no <history>, so no target list names
// one and the engine never asks the two below; answering would mean inventing
// one.
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) GetHistoryParent(history sce.HistoryID) SendParamPayloadSceSynthInvokeInvEmitterState {
	panic(fmt.Sprintf("SendParamPayloadSceSynthInvokeInvEmitterPolicy declares no <history>; asked for %d", history))
}
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) GetHistoryDefaultTargets(history sce.HistoryID) []SendParamPayloadSceSynthInvokeInvEmitterTarget {
	panic(fmt.Sprintf("SendParamPayloadSceSynthInvokeInvEmitterPolicy declares no <history>; asked for %d", history))
}
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) HistoryValue(_ sce.HistoryID) ([]SendParamPayloadSceSynthInvokeInvEmitterState, bool) {
	return nil, false
}

// GetDocumentOrder returns the document order index (W3C SCXML Appendix D).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) GetDocumentOrder(state SendParamPayloadSceSynthInvokeInvEmitterState) int {
	switch state {
	case SendParamPayloadSceSynthInvokeInvEmitterStateEmit:
		return 0
	case SendParamPayloadSceSynthInvokeInvEmitterStateSent:
		return 1
	}
	return -1
}

// GetEventName returns the string name of an event (W3C SCXML 3.12).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) GetEventName(event SendParamPayloadSceSynthInvokeInvEmitterEvent) string {
	return event.String()
}

// GetEventFromName looks up an event by name (W3C SCXML 3.12).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) GetEventFromName(name string) (SendParamPayloadSceSynthInvokeInvEmitterEvent, bool) {
	switch name {
	case "error.execution":
		return SendParamPayloadSceSynthInvokeInvEmitterEventErrorExecution, true
	case "fromChild":
		return SendParamPayloadSceSynthInvokeInvEmitterEventFromChild, true
	}
	return SendParamPayloadSceSynthInvokeInvEmitterEventNull, false
}

// GetStateName returns the string name of a state (W3C SCXML 3.3).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) GetStateName(state SendParamPayloadSceSynthInvokeInvEmitterState) string {
	return state.String()
}

// GetStateFromName reads a state id back into the state it names (W3C SCXML 3.3).
// The reverse of GetStateName, and what turns a host's recorded configuration
// back into the argument sce.Engine.EnterAt takes.
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) GetStateFromName(name string) (SendParamPayloadSceSynthInvokeInvEmitterState, bool) {
	return SendParamPayloadSceSynthInvokeInvEmitterStateFromName(name)
}

// NullEvent returns the sentinel for eventless transition dispatch (W3C SCXML 3.13).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) NullEvent() SendParamPayloadSceSynthInvokeInvEmitterEvent {
	return SendParamPayloadSceSynthInvokeInvEmitterEventNull
}



// HasParallelStates returns whether the SM has parallel states.
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) HasParallelStates() bool {
	return false
}

// NeedsScriptEngine returns whether the SM needs a script engine.
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) NeedsScriptEngine() bool {
	return false
}

// NeedsEventScheduler reports whether a host must drive this machine with
// Tick rather than Step alone.
//
// W3C SCXML 6.2: Step runs a macrostep and never drains the delayed-send
// scheduler nor ticks an invoked child, so a host that only ever calls it
// waits forever with nothing said. Same verdict the generate manifest
// publishes as needs_event_scheduler.
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) NeedsEventScheduler() bool {
	return false
}

// NeedsDataModelInit returns whether the SM needs datamodel init.
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) NeedsDataModelInit() bool {
	return false
}

func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) HasInvokeSupport() bool { return false }
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) HasChildTick() bool { return false }
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) HasFinalize() bool { return false }
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) HasAutoforward() bool { return false }
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) HasActiveStates() bool { return false }
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) GetActiveStates() []SendParamPayloadSceSynthInvokeInvEmitterState { return nil }
// W3C SCXML 3.4: this machine keeps no active set — its configuration is the
// parent walk from the current state — so there is nothing for a restore to
// hand back here. sce.Engine.EnterAt reaches this only through HasActiveStates,
// which is false above; the method exists because the interface is one contract.
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) SetActiveStates(_ []SendParamPayloadSceSynthInvokeInvEmitterState) {}
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) HasExternalEventFlag() bool { return false }
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) SetNextEventIsExternal(_ bool) {}
// ExecuteFinalizeForChildEvent is a no-op (no finalize invokes).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) ExecuteFinalizeForChildEvent(_ *sce.EventWithMetadata[SendParamPayloadSceSynthInvokeInvEmitterEvent], _ *sce.Engine[SendParamPayloadSceSynthInvokeInvEmitterState, SendParamPayloadSceSynthInvokeInvEmitterEvent]) {}
// ForwardToAutoforwardChildren is a no-op (no autoforward invokes).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) ForwardToAutoforwardChildren(_ string, _ sce.EventMetadata, _ *sce.Engine[SendParamPayloadSceSynthInvokeInvEmitterState, SendParamPayloadSceSynthInvokeInvEmitterEvent]) {}

// PopulateEventMetadata stores pending event metadata (W3C SCXML 5.10).
// Note: event name is set separately via setCurrentEvent(), not from metadata.
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) PopulateEventMetadata(meta *sce.EventMetadata) {
}

// LiftTypedPayload binds the dequeued event's typed `_event.data` view from
// the data it carries (NL→IR Item C1 Path A).
//
// The typed carrier PopulateEventMetadata reads is filled by one producer, the
// generated Raise<Event> inject seam. Every other producer — <send> with
// <param>, an invoke forwarding either way, autoforward, BasicHTTP, mesh —
// fills EventMetadata.Data, so the schema's fields are read out of that here.
// A refusal is returned for the engine to raise as error.execution, which is
// what W3C SCXML 3.13 gives for a guard that cannot be evaluated.
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) LiftTypedPayload(event SendParamPayloadSceSynthInvokeInvEmitterEvent, meta *sce.EventMetadata) error {
	// This document lowered no typed guard, so no event carries a typed view.
	return nil
}

// ClearEventMetadata resets pending event metadata (W3C SCXML 5.10).
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) ClearEventMetadata() {
}



// ExecuteEntryActions enters one state (W3C SCXML 3.8): adds it to the
// configuration, runs its <onentry>, and its <initial> transition's content when
// its initial state is entered by default.
//line send_param_payload__sce_synth_invoke__inv_emitter.scxml:3
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) ExecuteEntryActions(state SendParamPayloadSceSynthInvokeInvEmitterState, engine *sce.Engine[SendParamPayloadSceSynthInvokeInvEmitterState, SendParamPayloadSceSynthInvokeInvEmitterEvent], isDefaultEntry bool) {
	switch state {
	case SendParamPayloadSceSynthInvokeInvEmitterStateEmit:
		//line send_param_payload__sce_synth_invoke__inv_emitter.scxml:5
		// W3C SCXML 3.8: onentry block 0 (break on error stops subsequent actions)
		for actionBlock0 := 0; actionBlock0 < 1; actionBlock0++ {
			_ = actionBlock0

	// W3C SCXML 6.2: send id="__send_0"
	{
		// W3C SCXML 6.2 + B-2-9: every value is a literal, so the payload is
		// finished at codegen time. It has to be — this arm is what a machine
		// with no script engine emits, and the wire it used to write (a
		// `_scxml_params(...)` call in Lua) could only be read back by an
		// interpreter.
		//
		// The author name/value cross two literal boundaries, the JSON text
		// the filter assembles and the Go string literal carrying it, so each
		// is escaped once per boundary.
		eventDataStr := "{\"value\":\"42\"}"
		_ = eventDataStr
	// W3C SCXML 6.2: Send to parent
	if p.ParentExternalQueue != nil {
		p.ParentExternalQueue <- sce.ParentEvent{Name: "fromChild", Data: eventDataStr}
	}
	}

		}
	default:
		// No entry actions
	}
}

// ExecuteHistoryDefaultContent runs a <history>'s default transition content
// (W3C SCXML 3.10.2), after its parent's onentry (and after the parent's own
// <initial> content) when the history was taken with nothing recorded. The
// engine asks for it by the entry set's defaultHistoryContent answer; a history
// that restored what it recorded runs nothing.
//line send_param_payload__sce_synth_invoke__inv_emitter.scxml:3
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) ExecuteHistoryDefaultContent(history sce.HistoryID, engine *sce.Engine[SendParamPayloadSceSynthInvokeInvEmitterState, SendParamPayloadSceSynthInvokeInvEmitterEvent]) {
	// W3C SCXML 3.10.2: no <history> in this document has default content.
}

// ExecuteExitActions exits one state (W3C SCXML 3.9): records its histories,
// runs its <onexit>, cancels its invocations and removes it from the
// configuration — §scxml-D-exitStates's order.
//line send_param_payload__sce_synth_invoke__inv_emitter.scxml:3
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) ExecuteExitActions(state SendParamPayloadSceSynthInvokeInvEmitterState, engine *sce.Engine[SendParamPayloadSceSynthInvokeInvEmitterState, SendParamPayloadSceSynthInvokeInvEmitterEvent], configurationBeforeExit []SendParamPayloadSceSynthInvokeInvEmitterState) {
	// §scxml-D-exitStates orders one state's exit as onexit, then
	// cancelInvoke, then configuration.delete(s), so `In(s)` inside s's own
	// handler is true: the <onexit> switch comes first and the removal from
	// the configuration last.
	switch state {
	default:
		// No exit actions
	}
}



// BindCurrentEvent binds the event whose transitions are about to be selected as
// the _event their guards read (W3C SCXML 5.10) — before the first guard runs,
// and not for an eventless selection, which has no event of its own.
//line send_param_payload__sce_synth_invoke__inv_emitter.scxml:3
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) BindCurrentEvent(event SendParamPayloadSceSynthInvokeInvEmitterEvent, engine *sce.Engine[SendParamPayloadSceSynthInvokeInvEmitterState, SendParamPayloadSceSynthInvokeInvEmitterEvent]) {
	// This document's guards never read _event, so there is nothing to bind.
}

// FirstEnabledTransition is Appendix D selectTransitions, the half only this
// document can answer: the first of state's own transitions, in document order,
// that event enables and whose guard holds. The engine walks the atomic states
// and their ancestors and keeps the ordered set; the null event asks for
// eventless transitions.
//line send_param_payload__sce_synth_invoke__inv_emitter.scxml:3
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) FirstEnabledTransition(state SendParamPayloadSceSynthInvokeInvEmitterState, event SendParamPayloadSceSynthInvokeInvEmitterEvent, engine *sce.Engine[SendParamPayloadSceSynthInvokeInvEmitterState, SendParamPayloadSceSynthInvokeInvEmitterEvent]) (sce.EnabledTransition[SendParamPayloadSceSynthInvokeInvEmitterState, sce.HistoryID], bool) {
	switch state {
	case SendParamPayloadSceSynthInvokeInvEmitterStateEmit:
		if event == SendParamPayloadSceSynthInvokeInvEmitterEventNull {
			{
				return sce.EnabledTransition[SendParamPayloadSceSynthInvokeInvEmitterState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfSendParamPayloadSceSynthInvokeInvEmitter[state][0],
					TransitionIndex: 0,
					HasActions:      false,
					IsInternal:      false,
				}, true
			}
		}
	}
	return sce.EnabledTransition[SendParamPayloadSceSynthInvokeInvEmitterState, sce.HistoryID]{}, false
}

// ExecuteTransitionContent runs one transition's executable content (W3C SCXML
// 3.13), between the microstep's exits and its entries.
//line send_param_payload__sce_synth_invoke__inv_emitter.scxml:3
func (p *SendParamPayloadSceSynthInvokeInvEmitterPolicy) ExecuteTransitionContent(source SendParamPayloadSceSynthInvokeInvEmitterState, transitionIndex int, engine *sce.Engine[SendParamPayloadSceSynthInvokeInvEmitterState, SendParamPayloadSceSynthInvokeInvEmitterEvent]) {
	// W3C SCXML 3.13: no transition in this document has content.
}
