// SCE-GENERATED — DO NOT EDIT
// source-hash: 223286088e3261c9c6ae4869649bfba8df4425fada9f5fea9c4df27a3c6d833b


// SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 [Author of input SCXML file] (content derived from the input document)
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 newmassrael (content copied from SCE templates)
//
// Generated by SCE Code Generator (Go backend)
// From: sce-build/tests/fixtures/host_processor/statechart_static_host_params.scxml
//
// This generated code is usable under terms of your choice when it was produced
// by an unmodified sce-codegen and is not part of a competing product
// (SCE Linking Exception, section 3; see LICENSE-GENERATED.md).
// Full license: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE
// Generated Go state machine for `statechart_static_host_params`.
//
// Generated by SCE Code Generator (Go backend).
// Implements sce.StatePolicy with full transition logic,
// entry/exit actions, and event processing.


// SCE-MAP: statechart_static_host_params.scxml:80 :: _machine

package statechart_static_host_params

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	sce "github.com/newmassrael/sce-go-runtime"
	scealgorithm "github.com/newmassrael/sce-forge-runtime/algorithm"
)

// Ensure imports are used
var (
	_ = fmt.Sprintf
	_ = filepath.Join
	_ = strings.HasPrefix
	_ = time.Duration(0)
	_ scealgorithm.Failure
)

// ======================================================================
// State type (W3C SCXML 3.3)
// ======================================================================

type StatechartStaticHostParamsState int

const (
	StatechartStaticHostParamsStateDone StatechartStaticHostParamsState = 0
	StatechartStaticHostParamsStateIdle StatechartStaticHostParamsState = 1
	StatechartStaticHostParamsStateWorking StatechartStaticHostParamsState = 2
)

func (s StatechartStaticHostParamsState) String() string {
	switch s {
	case StatechartStaticHostParamsStateDone:
		return "done"
	case StatechartStaticHostParamsStateIdle:
		return "idle"
	case StatechartStaticHostParamsStateWorking:
		return "working"
	}
	return "unknown"
}

// StatechartStaticHostParamsStateFromName is the read half of the pair above — a state
// id back into the state it names (W3C SCXML 3.3).
//
// A host that persists where a machine was has to write it down as TEXT: the
// constants above are a build artefact of one binary, and the process that
// resumes is a different one. String publishes the name and this reads it back,
// which is what lets a journal survive its own record and reach
// sce.Engine.EnterAt.
//
// The second return is false for a name this document does not declare. A name
// guessed at rather than refused is how a restore reaches a configuration
// nobody recorded — and the refusal is what makes a typo in a journal a
// reported failure instead of a machine quietly somewhere else.
//
// Emitted from the same loop over the document's states as String, so the two
// age together.
func StatechartStaticHostParamsStateFromName(name string) (StatechartStaticHostParamsState, bool) {
	switch name {
	case "done":
		return StatechartStaticHostParamsStateDone, true
	case "idle":
		return StatechartStaticHostParamsStateIdle, true
	case "working":
		return StatechartStaticHostParamsStateWorking, true
	}
	var zero StatechartStaticHostParamsState
	return zero, false
}

// StatechartStaticHostParamsAllStates is every state this document declares, in the
// order the constants above are issued.
//
// Emitted from the same loop, so a walk over it is a walk over the document
// rather than over a list somebody maintained beside it — a test that spells
// its own list goes on passing when the document grows a state.
var StatechartStaticHostParamsAllStates = []StatechartStaticHostParamsState{
	StatechartStaticHostParamsStateDone,
	StatechartStaticHostParamsStateIdle,
	StatechartStaticHostParamsStateWorking,
}

// StatechartStaticHostParamsTarget is one token of a target list, as the document wrote
// it (W3C SCXML 3.13): a state, or a <history> the engine dereferences.
type StatechartStaticHostParamsTarget = sce.EntryTarget[StatechartStaticHostParamsState, sce.HistoryID]

// ======================================================================
// Document structure (W3C SCXML 3.2-3.4, 3.10)
//
// Package-level tables, because the structure is a fact about the document
// and not about a run: the engine's Appendix D procedures read them through
// the policy methods below, and a transition's target list is handed out as
// a slice of them rather than rebuilt on every selection.
// ======================================================================

// childStatesOfStatechartStaticHostParams is §scxml-D-getChildStates per state: its
// <state>, <parallel> and <final> children, in document order.
var childStatesOfStatechartStaticHostParams = [3][]StatechartStaticHostParamsState{
}

// initialTargetsOfStatechartStaticHostParams is each compound state's initial transition
// target, as written (§scxml-3.3).
var initialTargetsOfStatechartStaticHostParams = [3][]StatechartStaticHostParamsTarget{
}

// documentInitialTargetsOfStatechartStaticHostParams is the target of the document's own
// initial transition, as written (§scxml-3.2).
var documentInitialTargetsOfStatechartStaticHostParams = []StatechartStaticHostParamsTarget{sce.StateTarget[StatechartStaticHostParamsState, sce.HistoryID](StatechartStaticHostParamsStateIdle)}

// transitionTargetsOfStatechartStaticHostParams is each transition's target list, as
// written (§scxml-3.13), by source state and the transition's index among its
// source's own transitions. A targetless transition's entry is empty.
var transitionTargetsOfStatechartStaticHostParams = [3][][]StatechartStaticHostParamsTarget{
	StatechartStaticHostParamsStateIdle: {
		3: {sce.StateTarget[StatechartStaticHostParamsState, sce.HistoryID](StatechartStaticHostParamsStateWorking)},
	},
	StatechartStaticHostParamsStateWorking: {
		1: {sce.StateTarget[StatechartStaticHostParamsState, sce.HistoryID](StatechartStaticHostParamsStateDone)},
	},
}

// ======================================================================
// Event type (W3C SCXML 3.12)
// ======================================================================

type StatechartStaticHostParamsEvent int

const (
	StatechartStaticHostParamsEventAfter StatechartStaticHostParamsEvent = 0
	StatechartStaticHostParamsEventBig StatechartStaticHostParamsEvent = 1
	StatechartStaticHostParamsEventBloat StatechartStaticHostParamsEvent = 2
	StatechartStaticHostParamsEventBump StatechartStaticHostParamsEvent = 3
	StatechartStaticHostParamsEventDoneInvoke StatechartStaticHostParamsEvent = 4
	StatechartStaticHostParamsEventDoneInvokeH StatechartStaticHostParamsEvent = 5
	StatechartStaticHostParamsEventErrorExecution StatechartStaticHostParamsEvent = 6
	StatechartStaticHostParamsEventGo StatechartStaticHostParamsEvent = 7
	StatechartStaticHostParamsEventLost StatechartStaticHostParamsEvent = 8
	StatechartStaticHostParamsEventNotify StatechartStaticHostParamsEvent = 9
	StatechartStaticHostParamsEventText StatechartStaticHostParamsEvent = 10
	StatechartStaticHostParamsEventValue StatechartStaticHostParamsEvent = 11
	// W3C SCXML 3.13: Sentinel for eventless transition dispatch
	StatechartStaticHostParamsEventNull StatechartStaticHostParamsEvent = 12
)

func (e StatechartStaticHostParamsEvent) String() string {
	switch e {
	case StatechartStaticHostParamsEventAfter:
		return "after"
	case StatechartStaticHostParamsEventBig:
		return "big"
	case StatechartStaticHostParamsEventBloat:
		return "bloat"
	case StatechartStaticHostParamsEventBump:
		return "bump"
	case StatechartStaticHostParamsEventDoneInvoke:
		return "done.invoke"
	case StatechartStaticHostParamsEventDoneInvokeH:
		return "done.invoke.h"
	case StatechartStaticHostParamsEventErrorExecution:
		return "error.execution"
	case StatechartStaticHostParamsEventGo:
		return "go"
	case StatechartStaticHostParamsEventLost:
		return "lost"
	case StatechartStaticHostParamsEventNotify:
		return "notify"
	case StatechartStaticHostParamsEventText:
		return "text"
	case StatechartStaticHostParamsEventValue:
		return "value"
	case StatechartStaticHostParamsEventNull:
		return ""
	}
	return "unknown"
}

// ======================================================================
// Policy struct
// ======================================================================

type StatechartStaticHostParamsPolicy struct {
	pendingEventInvokeid string
	// W3C SCXML 5.10: Session ID
	SessionID string
	// ── SCE Accepted Subset §2.15: the datamodel="sce-static" variables ──
	// W3C SCXML 5.2: the `count` datamodel variable.
	vCount uint32
	// W3C SCXML 5.2: the `ready` datamodel variable.
	vReady bool
	// W3C SCXML 5.2: the `label` datamodel variable.
	vLabel string
	// W3C SCXML 5.2: the `delta` datamodel variable.
	vDelta int16
	// W3C SCXML 5.2: the `ratio` datamodel variable.
	vRatio float64
	// W3C SCXML 5.2: the `tag` datamodel variable.
	vTag string
	// W3C SCXML 5.2: the `huge` datamodel variable.
	vHuge uint32
	// W3C SCXML 5.2: the `errors` datamodel variable, published (`sce:direction="out"`).
	vErrors uint32
	pendingInvokes []sce.PendingInvoke[StatechartStaticHostParamsState]
	activeInvokes  map[string]*sce.ChildSession
	// W3C SCXML 6.4: Parent communication (unbounded — see sce.ParentEventQueue)
	ParentExternalQueue *sce.ParentEventQueue
	InvokeID           string
	ChildSessionID     string
	// §scxml-6.4.3: invoke param VALUES staged by the parent, applied after
	// this machine's datamodel init so they override its `<data>` defaults.
	pendingParams      map[string]interface{}
}

// NewStatechartStaticHostParamsPolicy creates a new policy with default values.
func NewStatechartStaticHostParamsPolicy() StatechartStaticHostParamsPolicy {
	return StatechartStaticHostParamsPolicy{
		vCount: 3,
		vReady: false,
		vLabel: "idle",
		vDelta: -5,
		vRatio: 1.5,
		vTag: "job://params",
		vHuge: 1,
		vErrors: 0,
		pendingInvokes: make([]sce.PendingInvoke[StatechartStaticHostParamsState], 0),
		activeInvokes:  make(map[string]*sce.ChildSession),
	}
}

// Errors reports what the published `errors` datamodel
// variable holds now (W3C SCXML 5.2). Only the machine writes it.
func (p *StatechartStaticHostParamsPolicy) Errors() uint32 {
	return p.vErrors
}

// StatechartStaticHostParamsInvokeParams holds the values a parent's `<param>` and
// `namelist` give this machine's variables before it starts (§scxml-6.4.1). A
// variable left nil keeps the value its `<data>` gave it.
type StatechartStaticHostParamsInvokeParams struct {
	VCount *uint32
	VReady *bool
	VLabel *string
	VDelta *int16
	VRatio *float64
	VTag *string
	VHuge *uint32
	VErrors *uint32
}

// AcceptParams gives this machine the values params carries, in place of the
// ones its `<data>` gave. Called before it initializes (§scxml-6.4.1).
func (p *StatechartStaticHostParamsPolicy) AcceptParams(params StatechartStaticHostParamsInvokeParams) {
	if params.VCount != nil {
		p.vCount = *params.VCount
	}
	if params.VReady != nil {
		p.vReady = *params.VReady
	}
	if params.VLabel != nil {
		p.vLabel = *params.VLabel
	}
	if params.VDelta != nil {
		p.vDelta = *params.VDelta
	}
	if params.VRatio != nil {
		p.vRatio = *params.VRatio
	}
	if params.VTag != nil {
		p.vTag = *params.VTag
	}
	if params.VHuge != nil {
		p.vHuge = *params.VHuge
	}
	if params.VErrors != nil {
		p.vErrors = *params.VErrors
	}
}



// No script engine needed for this state machine.
func (p *StatechartStaticHostParamsPolicy) InitializeDataModel(eng *sce.Engine[StatechartStaticHostParamsState, StatechartStaticHostParamsEvent]) {}

// SetParamValueInScriptEngine is a no-op for state machines without script engine.
func (p *StatechartStaticHostParamsPolicy) SetParamValueInScriptEngine(name string, value interface{}) {}


// ExecutePendingInvokes starts deferred child state machines (W3C SCXML 6.4).
// Port of Rust do_execute_pending_invokes().
func (p *StatechartStaticHostParamsPolicy) ExecutePendingInvokes(engine *sce.Engine[StatechartStaticHostParamsState, StatechartStaticHostParamsEvent]) {
	if len(p.pendingInvokes) == 0 {
		return
	}

	// W3C SCXML 6.4: Copy-and-clear to prevent iterator invalidation
	invokesToExecute := make([]sce.PendingInvoke[StatechartStaticHostParamsState], len(p.pendingInvokes))
	copy(invokesToExecute, p.pendingInvokes)
	p.pendingInvokes = p.pendingInvokes[:0]

	for _, pending := range invokesToExecute {
		if pending.DocumentID == "h" {
			// W3C SCXML 6.4.1: the host declared this `type`, so START the
			// invocation rather than refusing it. The id handed over is the
			// DOCUMENT's, not the per-instance one the pending queue carries:
			// `done.invoke.<id>` is the name the author wrote a transition
			// for, so it is the name the host must answer on.
			// W3C SCXML 6.4.1: what the request says is evaluated now, when the
			// invocation starts, by the rules the other invoke kinds follow: an
			// attribute that cannot be evaluated starts nothing, and a `<param>`
			// that cannot is reported and left out (W3C SCXML 5.7.1).
			hostInvokeSrc := ""
			hostInvokeContent := ""
			{
				var sceFailure scealgorithm.Failure
				computedSrc := func() string { if scealgorithm.MulUint32(&sceFailure, p.vCount, 2) > 0 { return p.vTag }; return p.vTag }()
				if sceFailure.Failed() {
					engine.Raise(sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<invoke srcexpr> could not be evaluated"))
					continue
				}
				hostInvokeSrc = computedSrc
			}
			{
				var sceFailure scealgorithm.Failure
				computedContent := func() string { if scealgorithm.MulUint32(&sceFailure, p.vHuge, 2) > 0 { return p.vLabel }; return p.vLabel }()
				if sceFailure.Failed() {
					engine.Raise(sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<invoke> content expr could not be evaluated"))
					continue
				}
				hostInvokeContent = computedContent
			}
			hostInvokeParams := map[string][]string{}
			// The same pairs as the data model holds them, for the request's
			// EventData: one evaluation, read as text for Params and typed for
			// the JSON.
			hostInvokePayload := make([]sce.EventDataParam, 0)
			{
				sceValue := int64(p.vCount)
				hostInvokeParams["count"] = append(hostInvokeParams["count"], sce.ToWireString(sceValue))
				hostInvokePayload = append(hostInvokePayload, sce.EventDataParam{Name: "count", Value: sceValue})
			}
			{
				sceValue := p.vReady
				hostInvokeParams["ready"] = append(hostInvokeParams["ready"], sce.ToWireString(sceValue))
				hostInvokePayload = append(hostInvokePayload, sce.EventDataParam{Name: "ready", Value: sceValue})
			}
			{
				sceValue := p.vLabel
				hostInvokeParams["label"] = append(hostInvokeParams["label"], sce.ToWireString(sceValue))
				hostInvokePayload = append(hostInvokePayload, sce.EventDataParam{Name: "label", Value: sceValue})
			}
			{
				var sceFailure scealgorithm.Failure
				sceValue := int64(scealgorithm.MulUint32(&sceFailure, p.vCount, 2))
				if !sceFailure.Failed() {
				hostInvokeParams["twice"] = append(hostInvokeParams["twice"], sce.ToWireString(sceValue))
				hostInvokePayload = append(hostInvokePayload, sce.EventDataParam{Name: "twice", Value: sceValue})
				} else {
					engine.Raise(sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<invoke> <param name='twice'> failed to evaluate"))
				}
			}
			{
				var sceFailure scealgorithm.Failure
				sceValue := int64(scealgorithm.MulUint32(&sceFailure, p.vCount, 2000000000))
				if !sceFailure.Failed() {
				hostInvokeParams["boom"] = append(hostInvokeParams["boom"], sce.ToWireString(sceValue))
				hostInvokePayload = append(hostInvokePayload, sce.EventDataParam{Name: "boom", Value: sceValue})
				} else {
					engine.Raise(sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<invoke> <param name='boom'> failed to evaluate"))
				}
			}
			{
				sceValue := int64(p.vDelta)
				hostInvokeParams["delta"] = append(hostInvokeParams["delta"], sce.ToWireString(sceValue))
				hostInvokePayload = append(hostInvokePayload, sce.EventDataParam{Name: "delta", Value: sceValue})
			}
			{
				sceValue := float64(p.vRatio)
				hostInvokeParams["ratio"] = append(hostInvokeParams["ratio"], sce.ToWireString(sceValue))
				hostInvokePayload = append(hostInvokePayload, sce.EventDataParam{Name: "ratio", Value: sceValue})
			}
			hostInvokeEventData := ""
			if len(hostInvokePayload) > 0 {
				hostInvokeEventData = sce.BuildJSONFromTypedParams(hostInvokePayload)
			}
			if !engine.PerformHostInvoke(sce.HostInvokeRequest{
				ProcessorType: "x-sce-host",
				InvokeID:      "h",
				Src:           hostInvokeSrc,
				Params:        hostInvokeParams,
				EventData:     hostInvokeEventData,
				Content:       hostInvokeContent,
			}) {
				// W3C SCXML 6.4.1: declared but no invoker registered. The
				// document asked for a process to be run and none was, which
				// is the same fact as an unsupported type — so the same
				// event, rather than a silence that reads as started.
				engine.Raise(sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<invoke> names an invoker the host declared but never registered"))
			}
			continue
		}
	}
}

// TickChildren ticks child state machines (W3C SCXML 6.4).
// Port of Rust do_tick_children().
func (p *StatechartStaticHostParamsPolicy) TickChildren(engine *sce.Engine[StatechartStaticHostParamsState, StatechartStaticHostParamsEvent]) {
}

// NextChildDeadline reports the nearest deadline among the running children
// (W3C SCXML 6.4), so a host that walks time by TimeUntilNextScheduled does not
// step over a timer a child armed. The ticking above is what makes it this
// machine's. A child that has ended (pendingDoneInvoke) is skipped: the policy
// keeps it until its state exits, and what it armed is no longer owed.
func (p *StatechartStaticHostParamsPolicy) NextChildDeadline() (time.Duration, bool) {
	var soonest time.Duration
	found := false
	return soonest, found
}


// DeliverToInvocation delivers a delayed `<send target="#_<invokeid>">` whose
// wait is over, by name — a child need not declare every event its parent
// sends (W3C SCXML 6.2 + 6.4). It answers whether the invocation was there to
// take it: one whose session has reached its final state has ended, and the
// engine reports the send it could not deliver (W3C SCXML C.1).
func (p *StatechartStaticHostParamsPolicy) DeliverToInvocation(invokeID, eventName, eventData, sendID string) bool {
	return false
}

// IsInvocationRunning reports whether `#_<invokeid>` names an invocation running
// now (W3C SCXML 6.4 + C.1) — one whose session has reached its final state has
// ended, and a send naming it is reported when it is made.
func (p *StatechartStaticHostParamsPolicy) IsInvocationRunning(invokeID string) bool {
	return false
}



// ── Child engine wrappers (implement sce.ChildEngine interface) ──



// DeliverToParent delivers a delayed `<send target="#_parent">` whose wait is
// over, with the payload an immediate one carries (W3C SCXML 6.2 + 6.4). It
// waited in this machine's own queue, so `<cancel>` reached it and a child that
// ended first dropped it — the engine dispatches nothing once final. Emitted for
// every machine, since the one that needs it is an invoked child, which need not
// invoke anything itself.
func (p *StatechartStaticHostParamsPolicy) DeliverToParent(eventName, eventData string) bool {
	if p.ParentExternalQueue == nil {
		return false
	}
	p.ParentExternalQueue.Push(sce.ParentEvent{Name: eventName, Data: eventData})
	return true
}

// HasParentSession answers whether a session invoked this one (W3C SCXML C.1):
// the queue the invoking parent installs is the link to it.
func (p *StatechartStaticHostParamsPolicy) HasParentSession() bool {
	return p.ParentExternalQueue != nil
}

// ======================================================================
// StatePolicy interface implementation
// ======================================================================

// InitialState returns the initial state (W3C SCXML 3.3).
func (p *StatechartStaticHostParamsPolicy) InitialState() StatechartStaticHostParamsState {
	return StatechartStaticHostParamsStateIdle
}

// IsFinalState returns true if state is a <final> state (W3C SCXML 3.7).
func (p *StatechartStaticHostParamsPolicy) IsFinalState(state StatechartStaticHostParamsState) bool {
	switch state {
	case StatechartStaticHostParamsStateDone:
		return true
	}
	return false
}

// GetParent returns the parent of state, or (zero, false) if root (W3C SCXML 3.3).
func (p *StatechartStaticHostParamsPolicy) GetParent(state StatechartStaticHostParamsState) (StatechartStaticHostParamsState, bool) {
	switch state {
	}
	return 0, false
}

// IsCompoundState returns true if state is a <state> with child states — exactly
// the states that have an initial transition. A <parallel> is not compound
// (W3C SCXML 3.3).
func (p *StatechartStaticHostParamsPolicy) IsCompoundState(state StatechartStaticHostParamsState) bool {
	return len(initialTargetsOfStatechartStaticHostParams[state]) > 0
}

func (p *StatechartStaticHostParamsPolicy) IsParallelState(_ StatechartStaticHostParamsState) bool { return false }

// GetChildStates returns state's <state>, <parallel> and <final> children, in
// document order — for a <parallel>, its regions (§scxml-D-getChildStates).
func (p *StatechartStaticHostParamsPolicy) GetChildStates(state StatechartStaticHostParamsState) []StatechartStaticHostParamsState {
	return childStatesOfStatechartStaticHostParams[state]
}

// GetInitialTargets returns a compound state's initial transition target, as
// written; the engine's entry procedures dereference a <history> among them
// (W3C SCXML 3.3).
func (p *StatechartStaticHostParamsPolicy) GetInitialTargets(state StatechartStaticHostParamsState) []StatechartStaticHostParamsTarget {
	return initialTargetsOfStatechartStaticHostParams[state]
}

// GetDocumentInitialTargets returns the target of the document's own initial
// transition, as written (W3C SCXML 3.2).
func (p *StatechartStaticHostParamsPolicy) GetDocumentInitialTargets() []StatechartStaticHostParamsTarget {
	return documentInitialTargetsOfStatechartStaticHostParams
}

// W3C SCXML 3.10: this document declares no <history>, so no target list names
// one and the engine never asks the two below; answering would mean inventing
// one.
func (p *StatechartStaticHostParamsPolicy) GetHistoryParent(history sce.HistoryID) StatechartStaticHostParamsState {
	panic(fmt.Sprintf("StatechartStaticHostParamsPolicy declares no <history>; asked for %d", history))
}
func (p *StatechartStaticHostParamsPolicy) GetHistoryDefaultTargets(history sce.HistoryID) []StatechartStaticHostParamsTarget {
	panic(fmt.Sprintf("StatechartStaticHostParamsPolicy declares no <history>; asked for %d", history))
}
func (p *StatechartStaticHostParamsPolicy) HistoryValue(_ sce.HistoryID) ([]StatechartStaticHostParamsState, bool) {
	return nil, false
}

// GetDocumentOrder returns the document order index (W3C SCXML Appendix D).
func (p *StatechartStaticHostParamsPolicy) GetDocumentOrder(state StatechartStaticHostParamsState) int {
	switch state {
	case StatechartStaticHostParamsStateDone:
		return 2
	case StatechartStaticHostParamsStateIdle:
		return 0
	case StatechartStaticHostParamsStateWorking:
		return 1
	}
	return -1
}

// GetEventName returns the string name of an event (W3C SCXML 3.12).
func (p *StatechartStaticHostParamsPolicy) GetEventName(event StatechartStaticHostParamsEvent) string {
	return event.String()
}

// GetEventFromName looks up an event by name (W3C SCXML 3.12).
func (p *StatechartStaticHostParamsPolicy) GetEventFromName(name string) (StatechartStaticHostParamsEvent, bool) {
	switch name {
	case "after":
		return StatechartStaticHostParamsEventAfter, true
	case "big":
		return StatechartStaticHostParamsEventBig, true
	case "bloat":
		return StatechartStaticHostParamsEventBloat, true
	case "bump":
		return StatechartStaticHostParamsEventBump, true
	case "done.invoke":
		return StatechartStaticHostParamsEventDoneInvoke, true
	case "done.invoke.h":
		return StatechartStaticHostParamsEventDoneInvokeH, true
	case "error.execution":
		return StatechartStaticHostParamsEventErrorExecution, true
	case "go":
		return StatechartStaticHostParamsEventGo, true
	case "lost":
		return StatechartStaticHostParamsEventLost, true
	case "notify":
		return StatechartStaticHostParamsEventNotify, true
	case "text":
		return StatechartStaticHostParamsEventText, true
	case "value":
		return StatechartStaticHostParamsEventValue, true
	}
	return StatechartStaticHostParamsEventNull, false
}

// HostInvokeIDs lists the invokes the host runs (sce.HostInvokePolicy). W3C
// SCXML 6.4: their `done.invoke` is accepted only through
// Engine.CompleteHostInvoke.
func (p *StatechartStaticHostParamsPolicy) HostInvokeIDs() []string {
	return []string{
		"h",
	}
}

// GetStateName returns the string name of a state (W3C SCXML 3.3).
func (p *StatechartStaticHostParamsPolicy) GetStateName(state StatechartStaticHostParamsState) string {
	return state.String()
}

// GetStateFromName reads a state id back into the state it names (W3C SCXML 3.3).
// The reverse of GetStateName, and what turns a host's recorded configuration
// back into the argument sce.Engine.EnterAt takes.
func (p *StatechartStaticHostParamsPolicy) GetStateFromName(name string) (StatechartStaticHostParamsState, bool) {
	return StatechartStaticHostParamsStateFromName(name)
}

// NullEvent returns the sentinel for eventless transition dispatch (W3C SCXML 3.13).
func (p *StatechartStaticHostParamsPolicy) NullEvent() StatechartStaticHostParamsEvent {
	return StatechartStaticHostParamsEventNull
}


// HasParallelStates returns whether the SM has parallel states.
func (p *StatechartStaticHostParamsPolicy) HasParallelStates() bool {
	return false
}

// NeedsScriptEngine returns whether the SM needs a script engine.
func (p *StatechartStaticHostParamsPolicy) NeedsScriptEngine() bool {
	return false
}

// NeedsEventScheduler reports whether a host must drive this machine with
// Tick rather than Step alone.
//
// W3C SCXML 6.2: Step runs a macrostep and never drains the delayed-send
// scheduler nor ticks an invoked child, so a host that only ever calls it
// waits forever with nothing said. Same verdict the generate manifest
// publishes as needs_event_scheduler.
func (p *StatechartStaticHostParamsPolicy) NeedsEventScheduler() bool {
	return false
}

// NeedsParent reports whether the document sends to its parent session — the
// generate manifest's needs_parent, read by Engine.RootStartRefusal.
func (p *StatechartStaticHostParamsPolicy) NeedsParent() bool {
	return false
}

// NeedsDataModelInit returns whether the SM needs datamodel init.
func (p *StatechartStaticHostParamsPolicy) NeedsDataModelInit() bool {
	return false
}

// HasInvokeSupport returns true for invoke-capable SMs.
func (p *StatechartStaticHostParamsPolicy) HasInvokeSupport() bool { return true }
func (p *StatechartStaticHostParamsPolicy) HasChildTick() bool { return false }
func (p *StatechartStaticHostParamsPolicy) HasFinalize() bool { return false }
func (p *StatechartStaticHostParamsPolicy) HasAutoforward() bool { return false }
func (p *StatechartStaticHostParamsPolicy) HasActiveStates() bool { return false }
func (p *StatechartStaticHostParamsPolicy) GetActiveStates() []StatechartStaticHostParamsState { return nil }
// W3C SCXML 3.4: this machine keeps no active set — its configuration is the
// parent walk from the current state — so there is nothing for a restore to
// hand back here. sce.Engine.EnterAt reaches this only through HasActiveStates,
// which is false above; the method exists because the interface is one contract.
func (p *StatechartStaticHostParamsPolicy) SetActiveStates(_ []StatechartStaticHostParamsState) {}
// ExecuteFinalizeForChildEvent is a no-op (no finalize invokes).
func (p *StatechartStaticHostParamsPolicy) ExecuteFinalizeForChildEvent(_ *sce.EventWithMetadata[StatechartStaticHostParamsEvent], _ *sce.Engine[StatechartStaticHostParamsState, StatechartStaticHostParamsEvent]) {}
// ForwardToAutoforwardChildren is a no-op (no autoforward invokes).
func (p *StatechartStaticHostParamsPolicy) ForwardToAutoforwardChildren(_ string, _ sce.EventMetadata, _ *sce.Engine[StatechartStaticHostParamsState, StatechartStaticHostParamsEvent]) {}

// PopulateEventMetadata stores pending event metadata (W3C SCXML 5.10).
// Note: event name is set separately via setCurrentEvent(); metadata supplies
// only the name the event ARRIVED under, when that is not its value's own.
func (p *StatechartStaticHostParamsPolicy) PopulateEventMetadata(meta *sce.EventMetadata) {
	p.pendingEventInvokeid = meta.InvokeID
}

// LiftTypedPayload binds the dequeued event's typed `_event.data` view from
// the data it carries (NL→IR Item C1 Path A).
//
// The typed carrier PopulateEventMetadata reads is filled by one producer, the
// generated Raise<Event> inject seam. Every other producer — <send> with
// <param>, an invoke forwarding either way, autoforward, BasicHTTP, mesh —
// fills EventMetadata.Data, so the schema's fields are read out of that here.
// A refusal is returned for the engine to raise as error.execution, which is
// what W3C SCXML 3.13 gives for a guard that cannot be evaluated.
func (p *StatechartStaticHostParamsPolicy) LiftTypedPayload(event StatechartStaticHostParamsEvent, meta *sce.EventMetadata) error {
	// This document lowered no typed guard, so no event carries a typed view.
	return nil
}

// ClearEventMetadata resets pending event metadata (W3C SCXML 5.10).
func (p *StatechartStaticHostParamsPolicy) ClearEventMetadata() {
	p.pendingEventInvokeid = ""
}



// ExecuteEntryActions enters one state (W3C SCXML 3.8): adds it to the
// configuration, runs its <onentry>, and its <initial> transition's content when
// its initial state is entered by default.
//line statechart_static_host_params.scxml:80
func (p *StatechartStaticHostParamsPolicy) ExecuteEntryActions(state StatechartStaticHostParamsState, engine *sce.Engine[StatechartStaticHostParamsState, StatechartStaticHostParamsEvent], isDefaultEntry bool) {
	switch state {
	case StatechartStaticHostParamsStateWorking:
		//line statechart_static_host_params.scxml:109
		// W3C SCXML 3.8 + 4.9: onentry block 0, its own function so an
		// error ends it with `return` from however deep a <foreach> it came.
		func() {

	// W3C SCXML 6.2: send id="__send_0"
	{
	// W3C SCXML 6.2: Evaluate <param> expressions at send time
	{
		// W3C SCXML 5.7.1 + 4.9: a <param> that cannot be read is reported
		// and its pair left out, and the message still goes; the error ends
		// the block once it has. Read at the end of this element.
		paramFailed := false
		// W3C SCXML 6.2 / test178: a name may repeat and every value must be
		// delivered, so this is an ordered list rather than a map. The typed
		// value is kept rather than its text — a receiver reading
		// `_event.data.value === 42` finds the string "42" unequal.
		parts := make([]sce.EventDataParam, 0)
		{
			sceValue := int64(p.vCount)
			parts = append(parts, sce.EventDataParam{Name: "count", Value: sceValue})
		}
		{
			sceValue := p.vReady
			parts = append(parts, sce.EventDataParam{Name: "ready", Value: sceValue})
		}
		{
			sceValue := p.vLabel
			parts = append(parts, sce.EventDataParam{Name: "label", Value: sceValue})
		}
		{
			var sceFailure scealgorithm.Failure
			sceValue := int64(scealgorithm.MulUint32(&sceFailure, p.vCount, 2))
			if !sceFailure.Failed() {
				parts = append(parts, sce.EventDataParam{Name: "twice", Value: sceValue})
			} else {
				engine.Raise(sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<send> <param name='twice'> failed to evaluate"))
				paramFailed = true
			}
		}
		{
			sceValue := int64(p.vDelta)
			parts = append(parts, sce.EventDataParam{Name: "delta", Value: sceValue})
		}
		{
			sceValue := float64(p.vRatio)
			parts = append(parts, sce.EventDataParam{Name: "ratio", Value: sceValue})
		}
		{
			var sceFailure scealgorithm.Failure
			sceValue := int64(scealgorithm.MulUint32(&sceFailure, p.vCount, 2000000000))
			if !sceFailure.Failed() {
				parts = append(parts, sce.EventDataParam{Name: "boom", Value: sceValue})
			} else {
				engine.Raise(sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<send> <param name='boom'> failed to evaluate"))
				paramFailed = true
			}
		}
		eventDataStr := sce.BuildJSONFromTypedParams(parts)
		_ = eventDataStr
	// §scxml-6.2.5: "x-sce-host" is served by the host, which
	// declared it to this build. Dispatch rather than refuse — and take the
	// whole send, because a processor the host serves owns delivery; falling
	// through would also enqueue the event locally and the document would see
	// the act twice.
	{
		hostParams := sce.WireParamsFromTypedParams(parts)
		hostRequest := sce.HostSendRequest{
			ProcessorType: "x-sce-host",
			EventName:     "notify",
			Target:        "somewhere",
			Content:       "",
			Params:        hostParams,
			SendID:        "__send_0",
			// W3C SCXML 5.10: the payload computed above, once, for every arm.
			EventData: eventDataStr,
			// SCE_MESH.md §mesh-10.7: the invokeid of the event being
			// processed now, carried back out as a W3C child's send to its
			// parent carries it (§scxml-6.4.1). Analysis keeps the field on
			// every machine with a host-served send.
			InvokeID: p.pendingEventInvokeid,
		}
		_, hostServed := engine.PerformHostSend(hostRequest)
		// W3C SCXML 6.2: a declared type with no handler registered is, from
		// the document's side, a processor the platform does not support — the
		// act it asked for was performed by nobody. Same event as an
		// undeclared type, so a wiring mistake cannot read as success.
		if !hostServed && !engine.HasEventProcessor("x-sce-host") {
			errEvt := sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<send type='x-sce-host'> names a processor the host declared but never registered")
			errEvt.Metadata.SendID = "__send_0"
			engine.Raise(errEvt)
		}
	}
		// W3C SCXML 4.9: the <param> error ends the block, from however deep a
		// <foreach> it came — the block is its own function.
		if paramFailed {
			return
		}
	}
	}
		}()
		// W3C SCXML 3.8 + 4.9: onentry block 1, its own function so an
		// error ends it with `return` from however deep a <foreach> it came.
		func() {

	// W3C SCXML 6.2: send id="__send_1"
	{
	{
		// W3C SCXML 5.6.2: the value of <content expr> is the output of
		// <content>, the event's data. Under `datamodel="sce-static"` it is one
		// value lowered to native code (`Action::native_content_value`), read
		// from the machine's own fields now and kept, so the event's data and
		// the text a host takes as `content` are renderings of the one reading.
		// "If the evaluation of 'expr' produces an error, the Processor MUST
		// place error.execution in the internal event queue and use the empty
		// string as the value of the <content> element."
		paramFailed := false
		var sceFailure scealgorithm.Failure
		var contentValue interface{} = int64(scealgorithm.MulUint32(&sceFailure, p.vCount, 2))
		if sceFailure.Failed() {
			engine.Raise(sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<send> contentexpr failed to evaluate"))
			paramFailed = true
			contentValue = ""
		}
		eventDataStr := sce.ScriptValueToJSON(contentValue)
		_ = eventDataStr
	// §scxml-6.2.5: "x-sce-host" is served by the host, which
	// declared it to this build. Dispatch rather than refuse — and take the
	// whole send, because a processor the host serves owns delivery; falling
	// through would also enqueue the event locally and the document would see
	// the act twice.
	{
		hostParams := map[string][]string{}
		hostRequest := sce.HostSendRequest{
			ProcessorType: "x-sce-host",
			EventName:     "value",
			Target:        "somewhere",
			Content:       sce.ToWireString(contentValue),
			Params:        hostParams,
			SendID:        "__send_1",
			// W3C SCXML 5.10: the payload computed above, once, for every arm.
			EventData: eventDataStr,
			// SCE_MESH.md §mesh-10.7: the invokeid of the event being
			// processed now, carried back out as a W3C child's send to its
			// parent carries it (§scxml-6.4.1). Analysis keeps the field on
			// every machine with a host-served send.
			InvokeID: p.pendingEventInvokeid,
		}
		_, hostServed := engine.PerformHostSend(hostRequest)
		// W3C SCXML 6.2: a declared type with no handler registered is, from
		// the document's side, a processor the platform does not support — the
		// act it asked for was performed by nobody. Same event as an
		// undeclared type, so a wiring mistake cannot read as success.
		if !hostServed && !engine.HasEventProcessor("x-sce-host") {
			errEvt := sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<send type='x-sce-host'> names a processor the host declared but never registered")
			errEvt.Metadata.SendID = "__send_1"
			engine.Raise(errEvt)
		}
	}
		// W3C SCXML 4.9: the <param> error ends the block, from however deep a
		// <foreach> it came — the block is its own function.
		if paramFailed {
			return
		}
	}
	}

	// W3C SCXML 6.2: send id="__send_2"
	{
	{
		// W3C SCXML 5.6.2: the value of <content expr> is the output of
		// <content>, the event's data. Under `datamodel="sce-static"` it is one
		// value lowered to native code (`Action::native_content_value`), read
		// from the machine's own fields now and kept, so the event's data and
		// the text a host takes as `content` are renderings of the one reading.
		// "If the evaluation of 'expr' produces an error, the Processor MUST
		// place error.execution in the internal event queue and use the empty
		// string as the value of the <content> element."
		var contentValue interface{} = p.vLabel
		eventDataStr := sce.ScriptValueToJSON(contentValue)
		_ = eventDataStr
	// §scxml-6.2.5: "x-sce-host" is served by the host, which
	// declared it to this build. Dispatch rather than refuse — and take the
	// whole send, because a processor the host serves owns delivery; falling
	// through would also enqueue the event locally and the document would see
	// the act twice.
	{
		hostParams := map[string][]string{}
		hostRequest := sce.HostSendRequest{
			ProcessorType: "x-sce-host",
			EventName:     "text",
			Target:        "somewhere",
			Content:       sce.ToWireString(contentValue),
			Params:        hostParams,
			SendID:        "__send_2",
			// W3C SCXML 5.10: the payload computed above, once, for every arm.
			EventData: eventDataStr,
			// SCE_MESH.md §mesh-10.7: the invokeid of the event being
			// processed now, carried back out as a W3C child's send to its
			// parent carries it (§scxml-6.4.1). Analysis keeps the field on
			// every machine with a host-served send.
			InvokeID: p.pendingEventInvokeid,
		}
		_, hostServed := engine.PerformHostSend(hostRequest)
		// W3C SCXML 6.2: a declared type with no handler registered is, from
		// the document's side, a processor the platform does not support — the
		// act it asked for was performed by nobody. Same event as an
		// undeclared type, so a wiring mistake cannot read as success.
		if !hostServed && !engine.HasEventProcessor("x-sce-host") {
			errEvt := sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<send type='x-sce-host'> names a processor the host declared but never registered")
			errEvt.Metadata.SendID = "__send_2"
			engine.Raise(errEvt)
		}
	}
	}
	}
		}()
		// W3C SCXML 3.8 + 4.9: onentry block 2, its own function so an
		// error ends it with `return` from however deep a <foreach> it came.
		func() {

	// W3C SCXML 6.2: send id="__send_3"
	{
	{
		// W3C SCXML 5.6.2: the value of <content expr> is the output of
		// <content>, the event's data. Under `datamodel="sce-static"` it is one
		// value lowered to native code (`Action::native_content_value`), read
		// from the machine's own fields now and kept, so the event's data and
		// the text a host takes as `content` are renderings of the one reading.
		// "If the evaluation of 'expr' produces an error, the Processor MUST
		// place error.execution in the internal event queue and use the empty
		// string as the value of the <content> element."
		paramFailed := false
		var sceFailure scealgorithm.Failure
		var contentValue interface{} = int64(scealgorithm.MulUint32(&sceFailure, p.vCount, 2000000000))
		if sceFailure.Failed() {
			engine.Raise(sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<send> contentexpr failed to evaluate"))
			paramFailed = true
			contentValue = ""
		}
		eventDataStr := sce.ScriptValueToJSON(contentValue)
		_ = eventDataStr
	// §scxml-6.2.5: "x-sce-host" is served by the host, which
	// declared it to this build. Dispatch rather than refuse — and take the
	// whole send, because a processor the host serves owns delivery; falling
	// through would also enqueue the event locally and the document would see
	// the act twice.
	{
		hostParams := map[string][]string{}
		hostRequest := sce.HostSendRequest{
			ProcessorType: "x-sce-host",
			EventName:     "lost",
			Target:        "somewhere",
			Content:       sce.ToWireString(contentValue),
			Params:        hostParams,
			SendID:        "__send_3",
			// W3C SCXML 5.10: the payload computed above, once, for every arm.
			EventData: eventDataStr,
			// SCE_MESH.md §mesh-10.7: the invokeid of the event being
			// processed now, carried back out as a W3C child's send to its
			// parent carries it (§scxml-6.4.1). Analysis keeps the field on
			// every machine with a host-served send.
			InvokeID: p.pendingEventInvokeid,
		}
		_, hostServed := engine.PerformHostSend(hostRequest)
		// W3C SCXML 6.2: a declared type with no handler registered is, from
		// the document's side, a processor the platform does not support — the
		// act it asked for was performed by nobody. Same event as an
		// undeclared type, so a wiring mistake cannot read as success.
		if !hostServed && !engine.HasEventProcessor("x-sce-host") {
			errEvt := sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<send type='x-sce-host'> names a processor the host declared but never registered")
			errEvt.Metadata.SendID = "__send_3"
			engine.Raise(errEvt)
		}
	}
		// W3C SCXML 4.9: the <param> error ends the block, from however deep a
		// <foreach> it came — the block is its own function.
		if paramFailed {
			return
		}
	}
	}

	// W3C SCXML 6.2: send id="__send_4"
	{
	{
		// W3C SCXML 5.6.2: the value of <content expr> is the output of
		// <content>, the event's data. Under `datamodel="sce-static"` it is one
		// value lowered to native code (`Action::native_content_value`), read
		// from the machine's own fields now and kept, so the event's data and
		// the text a host takes as `content` are renderings of the one reading.
		// "If the evaluation of 'expr' produces an error, the Processor MUST
		// place error.execution in the internal event queue and use the empty
		// string as the value of the <content> element."
		var contentValue interface{} = int64(p.vCount)
		eventDataStr := sce.ScriptValueToJSON(contentValue)
		_ = eventDataStr
	// §scxml-6.2.5: "x-sce-host" is served by the host, which
	// declared it to this build. Dispatch rather than refuse — and take the
	// whole send, because a processor the host serves owns delivery; falling
	// through would also enqueue the event locally and the document would see
	// the act twice.
	{
		hostParams := map[string][]string{}
		hostRequest := sce.HostSendRequest{
			ProcessorType: "x-sce-host",
			EventName:     "after",
			Target:        "somewhere",
			Content:       sce.ToWireString(contentValue),
			Params:        hostParams,
			SendID:        "__send_4",
			// W3C SCXML 5.10: the payload computed above, once, for every arm.
			EventData: eventDataStr,
			// SCE_MESH.md §mesh-10.7: the invokeid of the event being
			// processed now, carried back out as a W3C child's send to its
			// parent carries it (§scxml-6.4.1). Analysis keeps the field on
			// every machine with a host-served send.
			InvokeID: p.pendingEventInvokeid,
		}
		_, hostServed := engine.PerformHostSend(hostRequest)
		// W3C SCXML 6.2: a declared type with no handler registered is, from
		// the document's side, a processor the platform does not support — the
		// act it asked for was performed by nobody. Same event as an
		// undeclared type, so a wiring mistake cannot read as success.
		if !hostServed && !engine.HasEventProcessor("x-sce-host") {
			errEvt := sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<send type='x-sce-host'> names a processor the host declared but never registered")
			errEvt.Metadata.SendID = "__send_4"
			engine.Raise(errEvt)
		}
	}
	}
	}
		}()
		// W3C SCXML 6.4.1: `type` names no processor this platform implements.
		// Defer only — the error.execution raise happens in
		// ExecutePendingInvokes, so §scxml-6.4 ordering holds and
		// CancelInvokesForState drops the entry if the state exits first.
		{
			generatedInvokeID := fmt.Sprintf("%s.%d.h", "working", sce.NextInvokeCounter())
			sce.DeferInvoke(&p.pendingInvokes, sce.PendingInvoke[StatechartStaticHostParamsState]{
				InvokeID:   generatedInvokeID,
				State:      StatechartStaticHostParamsStateWorking,
				DocumentID: "h",
			})
		}
	default:
		// No entry actions
	}
}

// ExecuteHistoryDefaultContent runs a <history>'s default transition content
// (W3C SCXML 3.10.2), after its parent's onentry (and after the parent's own
// <initial> content) when the history was taken with nothing recorded. The
// engine asks for it by the entry set's defaultHistoryContent answer; a history
// that restored what it recorded runs nothing.
//line statechart_static_host_params.scxml:80
func (p *StatechartStaticHostParamsPolicy) ExecuteHistoryDefaultContent(history sce.HistoryID, engine *sce.Engine[StatechartStaticHostParamsState, StatechartStaticHostParamsEvent]) {
	// W3C SCXML 3.10.2: no <history> in this document has default content.
}

// ExecuteExitActions exits one state (W3C SCXML 3.9): records its histories,
// runs its <onexit>, cancels its invocations and removes it from the
// configuration — §scxml-D-exitStates's order.
//line statechart_static_host_params.scxml:80
func (p *StatechartStaticHostParamsPolicy) ExecuteExitActions(state StatechartStaticHostParamsState, engine *sce.Engine[StatechartStaticHostParamsState, StatechartStaticHostParamsEvent], configurationBeforeExit []StatechartStaticHostParamsState) {
	// §scxml-D-exitStates orders one state's exit as onexit, then
	// cancelInvoke, then configuration.delete(s), so `In(s)` inside s's own
	// handler is true: the <onexit> switch comes first and the removal from
	// the configuration last.
	switch state {
	default:
		// No exit actions
	}
	// W3C SCXML 6.4: Cancel pending invokes and cleanup active children on state exit
	switch state {
	case StatechartStaticHostParamsStateWorking:
		sce.CancelInvokesForState(&p.pendingInvokes, StatechartStaticHostParamsStateWorking)
		// W3C SCXML 6.4: the host's invocation ends with the state that
		// started it. Unconditional here: the engine knows whether this one
		// ever started and stays silent when it did not, so the emitted chain
		// does not need its own bookkeeping.
		engine.CancelHostInvoke("x-sce-host", "h")
	default:
	}
}



// BindCurrentEvent binds the event whose transitions are about to be selected as
// the _event their guards read (W3C SCXML 5.10) — before the first guard runs,
// and not for an eventless selection, which has no event of its own.
//line statechart_static_host_params.scxml:80
func (p *StatechartStaticHostParamsPolicy) BindCurrentEvent(event StatechartStaticHostParamsEvent, engine *sce.Engine[StatechartStaticHostParamsState, StatechartStaticHostParamsEvent]) {
	// This document's guards never read _event, so there is nothing to bind.
}

// FirstEnabledTransition is Appendix D selectTransitions, the half only this
// document can answer: the first of state's own transitions, in document order,
// that event enables and whose guard holds. The engine walks the atomic states
// and their ancestors and keeps the ordered set; the null event asks for
// eventless transitions.
//line statechart_static_host_params.scxml:80
func (p *StatechartStaticHostParamsPolicy) FirstEnabledTransition(state StatechartStaticHostParamsState, event StatechartStaticHostParamsEvent, engine *sce.Engine[StatechartStaticHostParamsState, StatechartStaticHostParamsEvent]) (sce.EnabledTransition[StatechartStaticHostParamsState, sce.HistoryID], bool) {
	switch state {
	case StatechartStaticHostParamsStateIdle:
		if event == StatechartStaticHostParamsEventBump {
			{
				return sce.EnabledTransition[StatechartStaticHostParamsState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 0,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
		if event == StatechartStaticHostParamsEventBig {
			{
				return sce.EnabledTransition[StatechartStaticHostParamsState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 1,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
		if event == StatechartStaticHostParamsEventBloat {
			{
				return sce.EnabledTransition[StatechartStaticHostParamsState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 2,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
		if event == StatechartStaticHostParamsEventGo {
			{
				return sce.EnabledTransition[StatechartStaticHostParamsState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfStatechartStaticHostParams[state][3],
					TransitionIndex: 3,
					HasActions:      false,
					IsInternal:      false,
				}, true
			}
		}
	case StatechartStaticHostParamsStateWorking:
		if event == StatechartStaticHostParamsEventErrorExecution {
			{
				return sce.EnabledTransition[StatechartStaticHostParamsState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 0,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
		if event == StatechartStaticHostParamsEventDoneInvokeH {
			{
				return sce.EnabledTransition[StatechartStaticHostParamsState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfStatechartStaticHostParams[state][1],
					TransitionIndex: 1,
					HasActions:      false,
					IsInternal:      false,
				}, true
			}
		}
	}
	return sce.EnabledTransition[StatechartStaticHostParamsState, sce.HistoryID]{}, false
}

// ExecuteTransitionContent runs one transition's executable content (W3C SCXML
// 3.13), between the microstep's exits and its entries.
//line statechart_static_host_params.scxml:80
func (p *StatechartStaticHostParamsPolicy) ExecuteTransitionContent(source StatechartStaticHostParamsState, transitionIndex int, engine *sce.Engine[StatechartStaticHostParamsState, StatechartStaticHostParamsEvent]) {
	switch source {
	case StatechartStaticHostParamsStateIdle:
		switch transitionIndex {
		case 0:
			//line statechart_static_host_params.scxml:95
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {


	if func() bool { var sceFailure scealgorithm.Failure; sceValue := scealgorithm.AddUint32(&sceFailure, p.vCount, 1); if sceFailure.Failed() { engine.Raise(sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<assign location='count'>: an integer operation overflowed or failed")); return true }; p.vCount = sceValue; return false }() {
		return  // W3C SCXML 4.9: the error ends the block
	}



	p.vReady = true



	if func() bool { var sceFailure scealgorithm.Failure; sceValue := scealgorithm.Bounded(&sceFailure, "busy", 16); if sceFailure.Failed() { engine.Raise(sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<assign location='label'>: an integer operation overflowed or failed")); return true }; p.vLabel = sceValue; return false }() {
		return  // W3C SCXML 4.9: the error ends the block
	}

			}()
		case 1:
			//line statechart_static_host_params.scxml:100
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {


	p.vCount = 3000000000

			}()
		case 2:
			//line statechart_static_host_params.scxml:103
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {


	p.vHuge = 3000000000

			}()
		}
	case StatechartStaticHostParamsStateWorking:
		switch transitionIndex {
		case 0:
			//line statechart_static_host_params.scxml:146
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {


	if func() bool { var sceFailure scealgorithm.Failure; sceValue := scealgorithm.AddUint32(&sceFailure, p.vErrors, 1); if sceFailure.Failed() { engine.Raise(sce.NewPlatformError(StatechartStaticHostParamsEventErrorExecution, "<assign location='errors'>: an integer operation overflowed or failed")); return true }; p.vErrors = sceValue; return false }() {
		return  // W3C SCXML 4.9: the error ends the block
	}

			}()
		}
	}
}
