// SPDX-License-Identifier: LGPL-2.1-or-later WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael
//
// A forge document is named by its file stem, and the generated output
// must not claim otherwise.
//
// The root `<scxml>` element accepts a `name` attribute — the grammar
// makes it optional, and 164 committed forge documents carry one, 53 of
// them declaring a value that differs from their own file stem. For
// every kind but one those values do not reach the model:
// `label.identifier` is the stem, by design, and the compiled name
// follows it. Rejecting the attribute was considered and is the wrong
// fix; it would redefine the language against its own corpus rather than
// repair anything.
//
// The exception is `sce:kind="algorithm"`, whose artifact is a function
// rather than a type: it takes its emitted symbol from the root `name`,
// and the file stem does not appear in the output. This file used to
// claim the rule held everywhere, because the probe below reads a
// hand-written list of two fixtures and neither is an algorithm.
// `the_identity_rule_holds_for_every_kind_the_corpus_declares` replaces
// the list with the corpus, so a kind joins the test by existing.
//
// What was actually broken is narrower and had two halves.
//
// The first was a false statement in the artifact. Eight templates
// (link / worker / buffer_pool / bounded_collection, in their rust and
// c arms) opened generated files with
//
//     // Generated from `name="{{ name }}"` with section `sram1`,
//
// which reads as a quotation of the source. It is not one — `{{ name }}`
// is the stem — so for any document whose attribute disagreed, the
// generated file attributed to the source an attribute value the source
// did not contain. Measured on a document declaring
// `name="PoolNameInSource"` in `probe_pool_stem.scxml`, the emitted
// comment read ``Generated from `name="probe_pool_stem"` ``. No
// committed tree carries such a line — every kind that reaches these
// templates is MCU-class and generated by consumers rather than checked
// in — which is exactly why nothing in this repository noticed.
//
// The second was that none of it was written down. The grammar admits
// the attribute, this document's own enum example shows one, and no
// prose said it was inert. `acceptance_doc_states_the_naming_rule`
// below is what keeps that from drifting back.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};

fn sce_codegen_bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_sce-codegen"))
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("sce-build has a parent")
        .to_path_buf()
}

static SCRATCH_ID: AtomicU64 = AtomicU64::new(0);

struct ScratchDir(PathBuf);

impl ScratchDir {
    fn new(label: &str) -> Self {
        let id = SCRATCH_ID.fetch_add(1, Ordering::SeqCst);
        let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR"))
            .join(format!("{label}-{}-{id}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("create scratch dir");
        Self(dir)
    }
    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for ScratchDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// Copy `fixture` under a new stem, rewriting its root `name` attribute
/// to `declared`, and return the path written.
fn restage(fixture: &str, stem: &str, declared: &str, into: &Path) -> PathBuf {
    let text = std::fs::read_to_string(repo_root().join(fixture))
        .unwrap_or_else(|e| panic!("read {fixture}: {e}"));
    // The first `<scxml` that is not inside a comment. Neither shortcut
    // survives these fixtures: the first `>` in the file belongs to the
    // XML declaration, and the first `<scxml` belongs to a header
    // comment that quotes the root element it is describing.
    // `match_indices` rather than a byte range: these fixtures carry
    // non-ASCII prose in their comments, and indexing by raw byte
    // offset lands mid-character.
    let root_start = text
        .match_indices("<scxml")
        .map(|(i, _)| i)
        .find(|&i| {
            let before = &text[..i];
            before.matches("<!--").count() == before.matches("-->").count()
        })
        .expect("a root element outside any comment");
    let root_end = root_start + text[root_start..].find('>').expect("root element closes");
    let (root, rest) = text.split_at(root_end);
    let re = regex::Regex::new(r#"\bname="[^"]*""#).expect("name pattern");
    let root = if re.is_match(root) {
        re.replace(root, format!(r#"name="{declared}""#).as_str())
            .into_owned()
    } else {
        panic!("{fixture} has no root name attribute to rewrite");
    };
    let path = into.join(format!("{stem}.scxml"));
    let staged = format!("{root}{rest}");
    // Without this the negative assertions downstream are vacuous: a
    // rewrite that quietly wrote nothing would let "the source name is
    // absent from the output" pass because it was never in the input.
    assert!(
        staged.contains(&format!(r#"name="{declared}""#)),
        "restaged {fixture} does not declare name=\"{declared}\"; the probe \
         would then assert the absence of something it never staged"
    );
    std::fs::write(&path, staged).expect("write restaged fixture");
    path
}

fn generate(doc: &Path, language: &str, out: &Path) -> String {
    let result = Command::new(sce_codegen_bin())
        .args(["generate"])
        .arg(doc)
        .args(["-l", language, "-o"])
        .arg(out)
        .current_dir(repo_root())
        .output()
        .expect("sce-codegen runs");
    assert!(
        result.status.success(),
        "generate -l {language} failed for {}: {}",
        doc.display(),
        String::from_utf8_lossy(&result.stderr),
    );
    let mut all = String::new();
    for entry in std::fs::read_dir(out).expect("read output dir") {
        let p = entry.expect("dir entry").path();
        if p.is_file() {
            all.push_str(&std::fs::read_to_string(&p).unwrap_or_default());
        }
    }
    assert!(
        !all.is_empty(),
        "generate -l {language} wrote nothing for {}",
        doc.display()
    );
    all
}

/// `(fixture, kind label)` — one per template family that opens its
/// output with a provenance comment, plus an enum for the naming half.
const KINDS: [(&str, &str); 2] = [
    ("tests/forge/resources/enum_ast_export_min.scxml", "enum"),
    (
        "tests/forge/resources/buffer_pool_ast_export_min.scxml",
        "buffer-pool",
    ),
];

#[test]
fn the_root_name_attribute_does_not_name_the_compiled_model() {
    let scratch = ScratchDir::new("name-stem");
    let inputs = scratch.path().join("in");
    std::fs::create_dir_all(&inputs).expect("create input dir");

    for (fixture, label) in KINDS {
        let doc = restage(fixture, "probe_stem_decides", "NameInTheSource", &inputs);
        for language in ["rust", "c"] {
            let out = ScratchDir::new("name-stem-out");
            let text = generate(&doc, language, out.path());
            // The stem, camel-cased, is the identity the backends use.
            assert!(
                text.contains("ProbeStemDecides") || text.contains("probe_stem_decides"),
                "{label}/{language}: output carries neither the stem nor its \
                 camel-cased form, so this probe is not reading the identity \
                 it claims to"
            );
            assert!(
                !text.contains("NameInTheSource"),
                "{label}/{language}: the root `name` attribute reached the \
                 output. Either it is no longer inert — in which case \
                 SCE_ACCEPTED_SUBSET.md §2.1 is now wrong — or it leaked into \
                 a comment."
            );
        }
    }
}

/// Every committed forge document whose root `name` disagrees with its file
/// stem, and the kind it declares.
fn documents_whose_declared_name_differs() -> Vec<(PathBuf, String, String, String)> {
    let root = repo_root();
    let listing = Command::new("git")
        .args(["ls-files", "*.scxml"])
        .current_dir(&root)
        .output()
        .expect("git ls-files");
    assert!(listing.status.success(), "git ls-files failed: {listing:?}");

    let mut out = Vec::new();
    for rel in String::from_utf8_lossy(&listing.stdout).split_whitespace() {
        let path = root.join(rel);
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue;
        };
        let Some(header) = text.split_once("<scxml").map(|(_, rest)| {
            rest.split_once('>')
                .map(|(h, _)| h)
                .unwrap_or(rest)
                .to_string()
        }) else {
            continue;
        };
        let attr = |name: &str| -> Option<String> {
            let pat = format!("{name}=\"");
            header
                .find(&pat)
                .map(|i| &header[i + pat.len()..])
                .and_then(|r| r.split_once('"'))
                .map(|(v, _)| v.to_string())
        };
        let (Some(kind), Some(declared)) = (attr("sce:kind"), attr(" name")) else {
            continue;
        };
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("a file stem")
            .to_string();
        if declared != stem {
            out.push((path, kind, stem, declared));
        }
    }
    out
}

#[test]
fn the_identity_rule_holds_for_every_kind_the_corpus_declares() {
    // The rule is about every forge kind, and the probe above reads two
    // fixtures — a hand-written list, which is how the one kind that breaks
    // the rule stayed outside it. `algorithm` names its emitted function from
    // the root `name` attribute: `algorithm_bytes_equal.scxml` declaring
    // `name="bytes_equal"` emits `bytes_equal.rs` with `pub fn bytes_equal`,
    // and the cross-document callers in c7_keyexpr_field_match resolve against
    // that name in all three backends. The acceptance doc said "accepted and
    // ignored" without qualification, and nothing measured it.
    //
    // So the corpus decides which kinds are covered. A kind that gains a
    // document with a disagreeing name joins this test by existing.
    let mut kinds_seen: std::collections::BTreeSet<String> = Default::default();
    let mut checked = 0;
    let mut offenders: Vec<String> = Vec::new();

    for (path, kind, stem, declared) in documents_whose_declared_name_differs() {
        let out = ScratchDir::new("corpus-identity");
        let result = Command::new(sce_codegen_bin())
            .arg("generate")
            .arg(&path)
            .arg("-o")
            .arg(out.path())
            .args(["-l", "rust"])
            .current_dir(repo_root())
            .output()
            .expect("sce-codegen runs");
        if !result.status.success() {
            continue; // a negative fixture: it is here to be rejected
        }
        let artifacts: Vec<String> = std::fs::read_dir(out.path())
            .expect("read output dir")
            .flatten()
            .filter_map(|e| {
                e.path()
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .map(str::to_string)
            })
            .collect();
        if artifacts.is_empty() {
            continue;
        }
        kinds_seen.insert(kind.clone());
        checked += 1;

        // `algorithm` is the exception; every other kind takes the stem. An
        // inline-eligible document is emitted inside its host statechart, so
        // its artifact carries the stem as a prefix rather than whole.
        let follows_name = artifacts.contains(&declared);
        let follows_stem = artifacts.iter().any(|a| a.starts_with(&stem));
        let ok = if kind == "algorithm" {
            follows_name
        } else {
            follows_stem && !follows_name
        };
        if !ok {
            offenders.push(format!(
                "{}: kind={kind} stem={stem} declared={declared} artifacts={artifacts:?}",
                path.display()
            ));
        }
    }

    assert!(
        checked >= 20 && kinds_seen.len() >= 6,
        "only {checked} document(s) across {} kind(s) reached the assertion — \
         this test passes by reading nothing",
        kinds_seen.len()
    );
    assert!(
        offenders.is_empty(),
        "forge document(s) take an identity the naming rule does not predict:\
         \n  {}\n Either the behaviour moved or SCE_ACCEPTED_SUBSET.md §2.1 \
         describes it wrongly.",
        offenders.join("\n  ")
    );
}

#[test]
fn generated_output_does_not_quote_a_name_attribute_the_source_lacks() {
    let scratch = ScratchDir::new("name-quote");
    let inputs = scratch.path().join("in");
    std::fs::create_dir_all(&inputs).expect("create input dir");

    // buffer-pool reaches the template family that carried the false
    // quotation; the enum is the control that the scan is not simply
    // finding nothing everywhere.
    let mut saw_provenance = false;
    for (fixture, label) in KINDS {
        let doc = restage(fixture, "probe_quotation", "NameInTheSource", &inputs);
        for language in ["rust", "c"] {
            let out = ScratchDir::new("name-quote-out");
            let text = generate(&doc, language, out.path());
            if text.contains("Generated from") {
                saw_provenance = true;
            }
            assert!(
                !text.contains(r#"name=""#),
                "{label}/{language}: generated output writes a `name=\"...\"` \
                 quotation. The model name is the file stem, so a quotation \
                 shaped like a source attribute states something the document \
                 may not contain — this is the exact line that read \
                 ``Generated from `name=\"probe_pool_stem\"` `` while the \
                 source declared `name=\"PoolNameInSource\"`."
            );
        }
    }
    assert!(
        saw_provenance,
        "no generated file carried a `Generated from` line, so the assertion \
         above never reached the comment it guards"
    );
}

#[test]
fn acceptance_doc_states_the_naming_rule() {
    let doc = std::fs::read_to_string(repo_root().join("docs/SCE_ACCEPTED_SUBSET.md"))
        .expect("read SCE_ACCEPTED_SUBSET.md");

    // The rule, the exception, and the reason it is stated rather than
    // enforced — a reader who finds only the first would still not know
    // why a `name` they wrote was accepted and had no effect.
    for needle in [
        "the file stem, not the `name` attribute",
        "accepted and ignored",
        "`sce:kind=\"statechart\"`",
        "_name",
    ] {
        assert!(
            doc.contains(needle),
            "SCE_ACCEPTED_SUBSET.md no longer states {needle:?}. The naming \
             rule is not enforced by any validator — prose is the only place \
             it exists, so removing the prose removes the contract."
        );
    }
}
