// SCE-GENERATED — DO NOT EDIT
// source-hash: ca5f07e498f08e9c44fe0c543fc369f243205362af8b0e260e1a44e3bfa1bd0d


// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 [Author of input SCXML file]
//
// Generated by SCE Code Generator (Go backend)
// From: sce-build/tests/fixtures/event_schema/statechart_lifted.scxml
//
// This generated code is MIT licensed and may be freely used in any project.
// Runtime engine dependency (sce-go-runtime): LGPL-2.1-or-later WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// Full license: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE
// Generated Go state machine for `statechart_lifted`.
//
// Generated by SCE Code Generator (Go backend).
// Implements sce.StatePolicy with full transition logic,
// entry/exit actions, and event processing.


// SCE-MAP: statechart_lifted.scxml:23 :: _machine

package statechart_lifted

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	sce "github.com/newmassrael/sce-go-runtime"
)

// Ensure imports are used
var (
	_ = fmt.Sprintf
	_ = filepath.Join
	_ = strings.HasPrefix
	_ = time.Duration(0)
)

// ======================================================================
// State type (W3C SCXML 3.3)
// ======================================================================

type StatechartLiftedState int

const (
	StatechartLiftedStateDone StatechartLiftedState = 0
	StatechartLiftedStateRefused StatechartLiftedState = 1
	StatechartLiftedStateWaiting StatechartLiftedState = 2
)

func (s StatechartLiftedState) String() string {
	switch s {
	case StatechartLiftedStateDone:
		return "done"
	case StatechartLiftedStateRefused:
		return "refused"
	case StatechartLiftedStateWaiting:
		return "waiting"
	}
	return "unknown"
}

// StatechartLiftedStateFromName is the read half of the pair above — a state
// id back into the state it names (W3C SCXML 3.3).
//
// A host that persists where a machine was has to write it down as TEXT: the
// constants above are a build artefact of one binary, and the process that
// resumes is a different one. String publishes the name and this reads it back,
// which is what lets a journal survive its own record and reach
// sce.Engine.EnterAt.
//
// The second return is false for a name this document does not declare. A name
// guessed at rather than refused is how a restore reaches a configuration
// nobody recorded — and the refusal is what makes a typo in a journal a
// reported failure instead of a machine quietly somewhere else.
//
// Emitted from the same loop over the document's states as String, so the two
// age together.
func StatechartLiftedStateFromName(name string) (StatechartLiftedState, bool) {
	switch name {
	case "done":
		return StatechartLiftedStateDone, true
	case "refused":
		return StatechartLiftedStateRefused, true
	case "waiting":
		return StatechartLiftedStateWaiting, true
	}
	var zero StatechartLiftedState
	return zero, false
}

// StatechartLiftedAllStates is every state this document declares, in the
// order the constants above are issued.
//
// Emitted from the same loop, so a walk over it is a walk over the document
// rather than over a list somebody maintained beside it — a test that spells
// its own list goes on passing when the document grows a state.
var StatechartLiftedAllStates = []StatechartLiftedState{
	StatechartLiftedStateDone,
	StatechartLiftedStateRefused,
	StatechartLiftedStateWaiting,
}

// StatechartLiftedTarget is one token of a target list, as the document wrote
// it (W3C SCXML 3.13): a state, or a <history> the engine dereferences.
type StatechartLiftedTarget = sce.EntryTarget[StatechartLiftedState, sce.HistoryID]

// ======================================================================
// Document structure (W3C SCXML 3.2-3.4, 3.10)
//
// Package-level tables, because the structure is a fact about the document
// and not about a run: the engine's Appendix D procedures read them through
// the policy methods below, and a transition's target list is handed out as
// a slice of them rather than rebuilt on every selection.
// ======================================================================

// childStatesOfStatechartLifted is §scxml-D-getChildStates per state: its
// <state>, <parallel> and <final> children, in document order.
var childStatesOfStatechartLifted = [3][]StatechartLiftedState{
}

// initialTargetsOfStatechartLifted is each compound state's initial transition
// target, as written (§scxml-3.3).
var initialTargetsOfStatechartLifted = [3][]StatechartLiftedTarget{
}

// documentInitialTargetsOfStatechartLifted is the target of the document's own
// initial transition, as written (§scxml-3.2).
var documentInitialTargetsOfStatechartLifted = []StatechartLiftedTarget{sce.StateTarget[StatechartLiftedState, sce.HistoryID](StatechartLiftedStateWaiting)}

// transitionTargetsOfStatechartLifted is each transition's target list, as
// written (§scxml-3.13), by source state and the transition's index among its
// source's own transitions. A targetless transition's entry is empty.
var transitionTargetsOfStatechartLifted = [3][][]StatechartLiftedTarget{
	StatechartLiftedStateWaiting: {
		0: {sce.StateTarget[StatechartLiftedState, sce.HistoryID](StatechartLiftedStateRefused)},
		1: {sce.StateTarget[StatechartLiftedState, sce.HistoryID](StatechartLiftedStateDone)},
	},
}

// ======================================================================
// Event type (W3C SCXML 3.12)
// ======================================================================

type StatechartLiftedEvent int

const (
	StatechartLiftedEventErrorExecution StatechartLiftedEvent = 0
	StatechartLiftedEventJobCompleted StatechartLiftedEvent = 1
	// W3C SCXML 3.13: Sentinel for eventless transition dispatch
	StatechartLiftedEventNull StatechartLiftedEvent = 2
)

func (e StatechartLiftedEvent) String() string {
	switch e {
	case StatechartLiftedEventErrorExecution:
		return "error.execution"
	case StatechartLiftedEventJobCompleted:
		return "job.completed"
	case StatechartLiftedEventNull:
		return ""
	}
	return "unknown"
}

// ── NL→IR Item C1 Path A: typed `_event.data` payload channel ─────────
// NL→IR Item C1 Path A (EventSchema MCU native lowering): typed
// `_event.data` payload channel for the EventSchema-imported events whose
// transition guards lowered to a native Go comparison (no script engine).
// The Go twin of the Rust `StatechartLiftedPayload` enum / C11 tagged union: a tag
// plus one `pending<Event>Payload` field per guarded event on the policy.
type StatechartLiftedPayloadTag int

const (
	StatechartLiftedPayloadTagNone StatechartLiftedPayloadTag = iota
	StatechartLiftedPayloadTagJobCompleted
)

// StatechartLiftedJobCompletedPayload is the NL→IR Item C1 Path A typed `_event.data`
// payload for `job.completed`. Internal to the package; consumers inject it via
// the `RaiseJobCompleted` seam below (fields are unexported by design).
type StatechartLiftedJobCompletedPayload struct {
	elapsed_ms uint32
}

// RaiseJobCompleted is the NL→IR Item C1 Path A per-event typed `_event.data`
// inject seam for `job.completed` — binds the event name and the payload field
// values in one call so the name↔type pairing cannot be constructed
// inconsistently. Twin of the Rust `RaiseJobCompleted` extension-trait method
// and the C11 `raise_<event>_typed` entry.
func RaiseJobCompleted(e *sce.Engine[StatechartLiftedState, StatechartLiftedEvent], elapsed_ms uint32) {
	e.RaiseExternalWithMeta(sce.EventWithMetadata[StatechartLiftedEvent]{
		Event:    StatechartLiftedEventJobCompleted,
		Metadata: sce.EventMetadata{
			EventType:    sce.EventTypeExternal,
			TypedPayload: StatechartLiftedJobCompletedPayload{elapsed_ms: elapsed_ms, },
			// Both carriers are filled: the typed one a native guard reads,
			// and `Data`, which is what the script engine binds `_event.data`
			// from. Filling only the first left an `<assign expr="_event.data.x">`
			// on this event reading nothing, on every backend alike.
			Data: sce.PayloadJSON(map[string]any{"elapsed_ms": elapsed_ms, }),
		},
	})
}


// ======================================================================
// Policy struct
// ======================================================================

type StatechartLiftedPolicy struct {
	// NL→IR Item C1 Path A: the current event's typed `_event.data` payload,
	// lifted from the dequeued event by PopulateEventMetadata and read by the
	// native transition guards (`p.pending<Event>Payload.<field>`). Mirrors
	// the Rust policy's `pending_payload` / the C11 `sm->pending_payload`.
	pendingPayloadTag StatechartLiftedPayloadTag
	pendingJobCompletedPayload StatechartLiftedJobCompletedPayload

	// W3C SCXML 5.10: Session ID
	SessionID string
	// W3C SCXML 6.4: Parent communication
	ParentExternalQueue chan sce.ParentEvent
	InvokeID           string
	ChildSessionID     string
	// §scxml-6.4.3: invoke param VALUES staged by the parent, applied after
	// this machine's datamodel init so they override its `<data>` defaults.
	pendingParams      map[string]interface{}
}

// NewStatechartLiftedPolicy creates a new policy with default values.
func NewStatechartLiftedPolicy() StatechartLiftedPolicy {
	return StatechartLiftedPolicy{
	}
}



// No script engine needed for this state machine.
func (p *StatechartLiftedPolicy) InitializeDataModel(eng *sce.Engine[StatechartLiftedState, StatechartLiftedEvent]) {}

// SetParamValueInScriptEngine is a no-op for state machines without script engine.
func (p *StatechartLiftedPolicy) SetParamValueInScriptEngine(name string, value interface{}) {}


// ExecutePendingInvokes is a no-op (no invokes in this SM).
func (p *StatechartLiftedPolicy) ExecutePendingInvokes(engine *sce.Engine[StatechartLiftedState, StatechartLiftedEvent]) {}

// TickChildren is a no-op (no invokes in this SM).
func (p *StatechartLiftedPolicy) TickChildren(engine *sce.Engine[StatechartLiftedState, StatechartLiftedEvent]) {}

// ======================================================================
// StatePolicy interface implementation
// ======================================================================

// InitialState returns the initial state (W3C SCXML 3.3).
func (p *StatechartLiftedPolicy) InitialState() StatechartLiftedState {
	return StatechartLiftedStateWaiting
}

// IsFinalState returns true if state is a <final> state (W3C SCXML 3.7).
func (p *StatechartLiftedPolicy) IsFinalState(state StatechartLiftedState) bool {
	switch state {
	}
	return false
}

// GetParent returns the parent of state, or (zero, false) if root (W3C SCXML 3.3).
func (p *StatechartLiftedPolicy) GetParent(state StatechartLiftedState) (StatechartLiftedState, bool) {
	switch state {
	}
	return 0, false
}

// IsCompoundState returns true if state is a <state> with child states — exactly
// the states that have an initial transition. A <parallel> is not compound
// (W3C SCXML 3.3).
func (p *StatechartLiftedPolicy) IsCompoundState(state StatechartLiftedState) bool {
	return len(initialTargetsOfStatechartLifted[state]) > 0
}

func (p *StatechartLiftedPolicy) IsParallelState(_ StatechartLiftedState) bool { return false }

// GetChildStates returns state's <state>, <parallel> and <final> children, in
// document order — for a <parallel>, its regions (§scxml-D-getChildStates).
func (p *StatechartLiftedPolicy) GetChildStates(state StatechartLiftedState) []StatechartLiftedState {
	return childStatesOfStatechartLifted[state]
}

// GetInitialTargets returns a compound state's initial transition target, as
// written; the engine's entry procedures dereference a <history> among them
// (W3C SCXML 3.3).
func (p *StatechartLiftedPolicy) GetInitialTargets(state StatechartLiftedState) []StatechartLiftedTarget {
	return initialTargetsOfStatechartLifted[state]
}

// GetDocumentInitialTargets returns the target of the document's own initial
// transition, as written (W3C SCXML 3.2).
func (p *StatechartLiftedPolicy) GetDocumentInitialTargets() []StatechartLiftedTarget {
	return documentInitialTargetsOfStatechartLifted
}

// W3C SCXML 3.10: this document declares no <history>, so no target list names
// one and the engine never asks the two below; answering would mean inventing
// one.
func (p *StatechartLiftedPolicy) GetHistoryParent(history sce.HistoryID) StatechartLiftedState {
	panic(fmt.Sprintf("StatechartLiftedPolicy declares no <history>; asked for %d", history))
}
func (p *StatechartLiftedPolicy) GetHistoryDefaultTargets(history sce.HistoryID) []StatechartLiftedTarget {
	panic(fmt.Sprintf("StatechartLiftedPolicy declares no <history>; asked for %d", history))
}
func (p *StatechartLiftedPolicy) HistoryValue(_ sce.HistoryID) ([]StatechartLiftedState, bool) {
	return nil, false
}

// GetDocumentOrder returns the document order index (W3C SCXML Appendix D).
func (p *StatechartLiftedPolicy) GetDocumentOrder(state StatechartLiftedState) int {
	switch state {
	case StatechartLiftedStateDone:
		return 1
	case StatechartLiftedStateRefused:
		return 2
	case StatechartLiftedStateWaiting:
		return 0
	}
	return -1
}

// GetEventName returns the string name of an event (W3C SCXML 3.12).
func (p *StatechartLiftedPolicy) GetEventName(event StatechartLiftedEvent) string {
	return event.String()
}

// GetEventFromName looks up an event by name (W3C SCXML 3.12).
func (p *StatechartLiftedPolicy) GetEventFromName(name string) (StatechartLiftedEvent, bool) {
	switch name {
	case "error.execution":
		return StatechartLiftedEventErrorExecution, true
	case "job.completed":
		return StatechartLiftedEventJobCompleted, true
	}
	return StatechartLiftedEventNull, false
}

// GetStateName returns the string name of a state (W3C SCXML 3.3).
func (p *StatechartLiftedPolicy) GetStateName(state StatechartLiftedState) string {
	return state.String()
}

// GetStateFromName reads a state id back into the state it names (W3C SCXML 3.3).
// The reverse of GetStateName, and what turns a host's recorded configuration
// back into the argument sce.Engine.EnterAt takes.
func (p *StatechartLiftedPolicy) GetStateFromName(name string) (StatechartLiftedState, bool) {
	return StatechartLiftedStateFromName(name)
}

// NullEvent returns the sentinel for eventless transition dispatch (W3C SCXML 3.13).
func (p *StatechartLiftedPolicy) NullEvent() StatechartLiftedEvent {
	return StatechartLiftedEventNull
}



// HasParallelStates returns whether the SM has parallel states.
func (p *StatechartLiftedPolicy) HasParallelStates() bool {
	return false
}

// NeedsScriptEngine returns whether the SM needs a script engine.
func (p *StatechartLiftedPolicy) NeedsScriptEngine() bool {
	return false
}

// NeedsEventScheduler reports whether a host must drive this machine with
// Tick rather than Step alone.
//
// W3C SCXML 6.2: Step runs a macrostep and never drains the delayed-send
// scheduler nor ticks an invoked child, so a host that only ever calls it
// waits forever with nothing said. Same verdict the generate manifest
// publishes as needs_event_scheduler.
func (p *StatechartLiftedPolicy) NeedsEventScheduler() bool {
	return false
}

// NeedsDataModelInit returns whether the SM needs datamodel init.
func (p *StatechartLiftedPolicy) NeedsDataModelInit() bool {
	return false
}

func (p *StatechartLiftedPolicy) HasInvokeSupport() bool { return false }
func (p *StatechartLiftedPolicy) HasChildTick() bool { return false }
func (p *StatechartLiftedPolicy) HasFinalize() bool { return false }
func (p *StatechartLiftedPolicy) HasAutoforward() bool { return false }
func (p *StatechartLiftedPolicy) HasActiveStates() bool { return false }
func (p *StatechartLiftedPolicy) GetActiveStates() []StatechartLiftedState { return nil }
// W3C SCXML 3.4: this machine keeps no active set — its configuration is the
// parent walk from the current state — so there is nothing for a restore to
// hand back here. sce.Engine.EnterAt reaches this only through HasActiveStates,
// which is false above; the method exists because the interface is one contract.
func (p *StatechartLiftedPolicy) SetActiveStates(_ []StatechartLiftedState) {}
func (p *StatechartLiftedPolicy) HasExternalEventFlag() bool { return false }
func (p *StatechartLiftedPolicy) SetNextEventIsExternal(_ bool) {}
// ExecuteFinalizeForChildEvent is a no-op (no finalize invokes).
func (p *StatechartLiftedPolicy) ExecuteFinalizeForChildEvent(_ *sce.EventWithMetadata[StatechartLiftedEvent], _ *sce.Engine[StatechartLiftedState, StatechartLiftedEvent]) {}
// ForwardToAutoforwardChildren is a no-op (no autoforward invokes).
func (p *StatechartLiftedPolicy) ForwardToAutoforwardChildren(_ string, _ sce.EventMetadata, _ *sce.Engine[StatechartLiftedState, StatechartLiftedEvent]) {}

// PopulateEventMetadata stores pending event metadata (W3C SCXML 5.10).
// Note: event name is set separately via setCurrentEvent(), not from metadata.
func (p *StatechartLiftedPolicy) PopulateEventMetadata(meta *sce.EventMetadata) {
	// NL→IR Item C1 Path A: lift the dequeued event's typed payload from the
	// type-erased carrier into the typed policy field the native guards read
	// (twin of the C11 pop loop's `sm->pending_payload = evt.payload`).
	p.pendingPayloadTag = StatechartLiftedPayloadTagNone
	switch v := meta.TypedPayload.(type) {
	case StatechartLiftedJobCompletedPayload:
		p.pendingPayloadTag = StatechartLiftedPayloadTagJobCompleted
		p.pendingJobCompletedPayload = v
	}

}

// LiftTypedPayload binds the dequeued event's typed `_event.data` view from
// the data it carries (NL→IR Item C1 Path A).
//
// The typed carrier PopulateEventMetadata reads is filled by one producer, the
// generated Raise<Event> inject seam. Every other producer — <send> with
// <param>, an invoke forwarding either way, autoforward, BasicHTTP, mesh —
// fills EventMetadata.Data, so the schema's fields are read out of that here.
// A refusal is returned for the engine to raise as error.execution, which is
// what W3C SCXML 3.13 gives for a guard that cannot be evaluated.
func (p *StatechartLiftedPolicy) LiftTypedPayload(event StatechartLiftedEvent, meta *sce.EventMetadata) error {
	// A typed carrier already bound the view, so the producer was the
	// inject seam and there is nothing to read out of `Data`.
	if p.pendingPayloadTag != StatechartLiftedPayloadTagNone {
		return nil
	}
	switch event {
	case StatechartLiftedEventJobCompleted:
		fields, err := sce.LiftPayload(meta.Data)
		if err != nil {
			return err
		}
		var payload StatechartLiftedJobCompletedPayload
		if payload.elapsed_ms, err = sce.PayloadUnsigned[uint32](fields, "elapsed_ms"); err != nil {
			return err
		}
		p.pendingJobCompletedPayload = payload
		p.pendingPayloadTag = StatechartLiftedPayloadTagJobCompleted
	}
	return nil

}

// ClearEventMetadata resets pending event metadata (W3C SCXML 5.10).
func (p *StatechartLiftedPolicy) ClearEventMetadata() {
	// NL→IR Item C1 Path A: reset the typed-payload tag (PopulateEventMetadata
	// always re-establishes it for the next event; this keeps a stale payload
	// from being read between macrosteps).
	p.pendingPayloadTag = StatechartLiftedPayloadTagNone

}



// ExecuteEntryActions enters one state (W3C SCXML 3.8): adds it to the
// configuration, runs its <onentry>, and its <initial> transition's content when
// its initial state is entered by default.
//line statechart_lifted.scxml:23
func (p *StatechartLiftedPolicy) ExecuteEntryActions(state StatechartLiftedState, engine *sce.Engine[StatechartLiftedState, StatechartLiftedEvent], isDefaultEntry bool) {
	switch state {
	default:
		// No entry actions
	}
}

// ExecuteHistoryDefaultContent runs a <history>'s default transition content
// (W3C SCXML 3.10.2), after its parent's onentry (and after the parent's own
// <initial> content) when the history was taken with nothing recorded. The
// engine asks for it by the entry set's defaultHistoryContent answer; a history
// that restored what it recorded runs nothing.
//line statechart_lifted.scxml:23
func (p *StatechartLiftedPolicy) ExecuteHistoryDefaultContent(history sce.HistoryID, engine *sce.Engine[StatechartLiftedState, StatechartLiftedEvent]) {
	// W3C SCXML 3.10.2: no <history> in this document has default content.
}

// ExecuteExitActions exits one state (W3C SCXML 3.9): records its histories,
// removes it from the configuration, cancels its invocations and runs its
// <onexit>.
//line statechart_lifted.scxml:23
func (p *StatechartLiftedPolicy) ExecuteExitActions(state StatechartLiftedState, engine *sce.Engine[StatechartLiftedState, StatechartLiftedEvent], configurationBeforeExit []StatechartLiftedState) {
	switch state {
	default:
		// No exit actions
	}
}



// BindCurrentEvent binds the event whose transitions are about to be selected as
// the _event their guards read (W3C SCXML 5.10) — before the first guard runs,
// and not for an eventless selection, which has no event of its own.
//line statechart_lifted.scxml:23
func (p *StatechartLiftedPolicy) BindCurrentEvent(event StatechartLiftedEvent, engine *sce.Engine[StatechartLiftedState, StatechartLiftedEvent]) {
	// This document's guards never read _event, so there is nothing to bind.
}

// FirstEnabledTransition is Appendix D selectTransitions, the half only this
// document can answer: the first of state's own transitions, in document order,
// that event enables and whose guard holds. The engine walks the atomic states
// and their ancestors and keeps the ordered set; the null event asks for
// eventless transitions.
//line statechart_lifted.scxml:23
func (p *StatechartLiftedPolicy) FirstEnabledTransition(state StatechartLiftedState, event StatechartLiftedEvent, engine *sce.Engine[StatechartLiftedState, StatechartLiftedEvent]) (sce.EnabledTransition[StatechartLiftedState, sce.HistoryID], bool) {
	switch state {
	case StatechartLiftedStateWaiting:
		if event == StatechartLiftedEventErrorExecution {
			{
				return sce.EnabledTransition[StatechartLiftedState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfStatechartLifted[state][0],
					TransitionIndex: 0,
					HasActions:      false,
					IsInternal:      false,
				}, true
			}
		}
		if event == StatechartLiftedEventJobCompleted {
			// NL→IR Item C1 Path A: native typed `_event.data` guard — cond
			// "_event.data.elapsed_ms === 0" lowered to a tag-checked field comparison on
			// the lifted `pending<Event>Payload` (no script engine).
			if p.pendingPayloadTag == StatechartLiftedPayloadTagJobCompleted && (p.pendingJobCompletedPayload.elapsed_ms == 0) {
				return sce.EnabledTransition[StatechartLiftedState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfStatechartLifted[state][1],
					TransitionIndex: 1,
					HasActions:      false,
					IsInternal:      false,
				}, true
			}
		}
	}
	return sce.EnabledTransition[StatechartLiftedState, sce.HistoryID]{}, false
}

// ExecuteTransitionContent runs one transition's executable content (W3C SCXML
// 3.13), between the microstep's exits and its entries.
//line statechart_lifted.scxml:23
func (p *StatechartLiftedPolicy) ExecuteTransitionContent(source StatechartLiftedState, transitionIndex int, engine *sce.Engine[StatechartLiftedState, StatechartLiftedEvent]) {
	// W3C SCXML 3.13: no transition in this document has content.
}
