// SCE-GENERATED — DO NOT EDIT
// source-hash: ef4ca0a4dd7e55791acb35707aca0211307a64b1955f47f3e92b31829dc36eec


// SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 [Author of input SCXML file] (content derived from the input document)
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 newmassrael (content copied from SCE templates)
//
// Generated by SCE Code Generator (Go backend)
// From: sce-build/tests/fixtures/static_datamodel/static_record_list_index.scxml
//
// This generated code is usable under terms of your choice when it was produced
// by an unmodified sce-codegen and is not part of a competing product
// (SCE Linking Exception, section 3; see LICENSE-GENERATED.md).
// Full license: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE
// Generated Go state machine for `static_record_list_index`.
//
// Generated by SCE Code Generator (Go backend).
// Implements sce.StatePolicy with full transition logic,
// entry/exit actions, and event processing.


// SCE-MAP: static_record_list_index.scxml:21 :: _machine

package static_record_list_index

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	sce "github.com/newmassrael/sce-go-runtime"
	scealgorithm "github.com/newmassrael/sce-forge-runtime/algorithm"
)

// Ensure imports are used
var (
	_ = fmt.Sprintf
	_ = filepath.Join
	_ = strings.HasPrefix
	_ = time.Duration(0)
	_ scealgorithm.Failure
)

// ======================================================================
// State type (W3C SCXML 3.3)
// ======================================================================

type StaticRecordListIndexState int

const (
	StaticRecordListIndexStateReading StaticRecordListIndexState = 0
)

func (s StaticRecordListIndexState) String() string {
	switch s {
	case StaticRecordListIndexStateReading:
		return "reading"
	}
	return "unknown"
}

// StaticRecordListIndexStateFromName is the read half of the pair above — a state
// id back into the state it names (W3C SCXML 3.3).
//
// A host that persists where a machine was has to write it down as TEXT: the
// constants above are a build artefact of one binary, and the process that
// resumes is a different one. String publishes the name and this reads it back,
// which is what lets a journal survive its own record and reach
// sce.Engine.EnterAt.
//
// The second return is false for a name this document does not declare. A name
// guessed at rather than refused is how a restore reaches a configuration
// nobody recorded — and the refusal is what makes a typo in a journal a
// reported failure instead of a machine quietly somewhere else.
//
// Emitted from the same loop over the document's states as String, so the two
// age together.
func StaticRecordListIndexStateFromName(name string) (StaticRecordListIndexState, bool) {
	switch name {
	case "reading":
		return StaticRecordListIndexStateReading, true
	}
	var zero StaticRecordListIndexState
	return zero, false
}

// StaticRecordListIndexAllStates is every state this document declares, in the
// order the constants above are issued.
//
// Emitted from the same loop, so a walk over it is a walk over the document
// rather than over a list somebody maintained beside it — a test that spells
// its own list goes on passing when the document grows a state.
var StaticRecordListIndexAllStates = []StaticRecordListIndexState{
	StaticRecordListIndexStateReading,
}

// StaticRecordListIndexTarget is one token of a target list, as the document wrote
// it (W3C SCXML 3.13): a state, or a <history> the engine dereferences.
type StaticRecordListIndexTarget = sce.EntryTarget[StaticRecordListIndexState, sce.HistoryID]

// ======================================================================
// Document structure (W3C SCXML 3.2-3.4, 3.10)
//
// Package-level tables, because the structure is a fact about the document
// and not about a run: the engine's Appendix D procedures read them through
// the policy methods below, and a transition's target list is handed out as
// a slice of them rather than rebuilt on every selection.
// ======================================================================

// childStatesOfStaticRecordListIndex is §scxml-D-getChildStates per state: its
// <state>, <parallel> and <final> children, in document order.
var childStatesOfStaticRecordListIndex = [1][]StaticRecordListIndexState{
}

// initialTargetsOfStaticRecordListIndex is each compound state's initial transition
// target, as written (§scxml-3.3).
var initialTargetsOfStaticRecordListIndex = [1][]StaticRecordListIndexTarget{
}

// documentInitialTargetsOfStaticRecordListIndex is the target of the document's own
// initial transition, as written (§scxml-3.2).
var documentInitialTargetsOfStaticRecordListIndex = []StaticRecordListIndexTarget{sce.StateTarget[StaticRecordListIndexState, sce.HistoryID](StaticRecordListIndexStateReading)}

// transitionTargetsOfStaticRecordListIndex is each transition's target list, as
// written (§scxml-3.13), by source state and the transition's index among its
// source's own transitions. A targetless transition's entry is empty.
var transitionTargetsOfStaticRecordListIndex = [1][][]StaticRecordListIndexTarget{
}

// ======================================================================
// Event type (W3C SCXML 3.12)
// ======================================================================

type StaticRecordListIndexEvent int

const (
	StaticRecordListIndexEventDayPicked StaticRecordListIndexEvent = 0
	StaticRecordListIndexEventErrorExecution StaticRecordListIndexEvent = 1
	StaticRecordListIndexEventLast StaticRecordListIndexEvent = 2
	StaticRecordListIndexEventNext StaticRecordListIndexEvent = 3
	StaticRecordListIndexEventOrder StaticRecordListIndexEvent = 4
	StaticRecordListIndexEventTotal StaticRecordListIndexEvent = 5
	// W3C SCXML 3.13: Sentinel for eventless transition dispatch
	StaticRecordListIndexEventNull StaticRecordListIndexEvent = 6
)

func (e StaticRecordListIndexEvent) String() string {
	switch e {
	case StaticRecordListIndexEventDayPicked:
		return "day.picked"
	case StaticRecordListIndexEventErrorExecution:
		return "error.execution"
	case StaticRecordListIndexEventLast:
		return "last"
	case StaticRecordListIndexEventNext:
		return "next"
	case StaticRecordListIndexEventOrder:
		return "order"
	case StaticRecordListIndexEventTotal:
		return "total"
	case StaticRecordListIndexEventNull:
		return ""
	}
	return "unknown"
}

// ── NL→IR Item C1 Path A: typed `_event.data` payload channel ─────────
// NL→IR Item C1 Path A (EventSchema MCU native lowering): typed
// `_event.data` payload channel for the EventSchema-imported events whose
// transition guards lowered to a native Go comparison (no script engine).
// The Go twin of the Rust `StaticRecordListIndexPayload` enum / C11 tagged union: a tag
// plus one `pending<Event>Payload` field per guarded event on the policy.
type StaticRecordListIndexPayloadTag int

const (
	StaticRecordListIndexPayloadTagNone StaticRecordListIndexPayloadTag = iota
	StaticRecordListIndexPayloadTagDayPicked
)

// StaticRecordListIndexDayPickedPayload is the NL→IR Item C1 Path A typed `_event.data`
// payload for `day.picked`. Internal to the package; consumers inject it via
// the `RaiseDayPicked` seam below (fields are unexported by design).
type StaticRecordListIndexDayPickedPayload struct {
	year uint16
	month uint8
	dayOfMonth uint8
}

// RaiseDayPicked is the NL→IR Item C1 Path A per-event typed `_event.data`
// inject seam for `day.picked` — binds the event name and the payload field
// values in one call so the name↔type pairing cannot be constructed
// inconsistently. Twin of the Rust `RaiseDayPicked` extension-trait method
// and the C11 `raise_<event>_typed` entry.
func RaiseDayPicked(e *sce.Engine[StaticRecordListIndexState, StaticRecordListIndexEvent], year uint16, month uint8, dayOfMonth uint8) {
	e.RaiseExternalWithMeta(sce.EventWithMetadata[StaticRecordListIndexEvent]{
		Event:    StaticRecordListIndexEventDayPicked,
		Metadata: sce.EventMetadata{
			EventType:    sce.EventTypeExternal,
			TypedPayload: StaticRecordListIndexDayPickedPayload{year: year, month: month, dayOfMonth: dayOfMonth, },
			// Both carriers are filled: the typed one a native guard reads,
			// and `Data`, which is what the script engine binds `_event.data`
			// from. Filling only the first left an `<assign expr="_event.data.x">`
			// on this event reading nothing, on every backend alike.
			Data: sce.PayloadJSON(sce.Pair("year", year), sce.Pair("month", month), sce.Pair("dayOfMonth", dayOfMonth)),
		},
	})
}


// ── SCE Accepted Subset §2.15: the types the static variables are held in ──
// SCE Accepted Subset §2.15: a `record:Day` datamodel value.
type StaticRecordListIndexDayRecord struct {
	year uint16
	month uint8
	dayOfMonth uint8
}

// Year reports the `year` field.
func (r StaticRecordListIndexDayRecord) Year() uint16 {
	return r.year
}

// Month reports the `month` field.
func (r StaticRecordListIndexDayRecord) Month() uint8 {
	return r.month
}

// DayOfMonth reports the `dayOfMonth` field.
func (r StaticRecordListIndexDayRecord) DayOfMonth() uint8 {
	return r.dayOfMonth
}


// ======================================================================
// Policy struct
// ======================================================================

type StaticRecordListIndexPolicy struct {
	// NL→IR Item C1 Path A: the current event's typed `_event.data` payload,
	// lifted from the dequeued event by PopulateEventMetadata and read by the
	// native transition guards (`p.pending<Event>Payload.<field>`). Mirrors
	// the Rust policy's `pending_payload` / the C11 `sm->pending_payload`.
	pendingPayloadTag StaticRecordListIndexPayloadTag
	pendingDayPickedPayload StaticRecordListIndexDayPickedPayload

	pendingEventData string
	// W3C SCXML 5.10: Session ID
	SessionID string
	// ── SCE Accepted Subset §2.15: the datamodel="sce-static" variables ──
	// W3C SCXML 5.2: the `draft` datamodel variable.
	vDraft StaticRecordListIndexDayRecord
	// W3C SCXML 5.2: the `days` datamodel variable.
	vDays []StaticRecordListIndexDayRecord
	// W3C SCXML 5.2: the `cursor` datamodel variable, published (`sce:direction="out"`).
	vCursor int32
	// W3C SCXML 5.2: the `day` datamodel variable, published (`sce:direction="out"`).
	vDay uint8
	// W3C SCXML 5.2: the `year` datamodel variable, published (`sce:direction="out"`).
	vYear uint16
	// W3C SCXML 5.2: the `sum` datamodel variable, published (`sce:direction="out"`).
	vSum uint32
	// W3C SCXML 5.2: the `ordered` datamodel variable, published (`sce:direction="out"`).
	vOrdered bool
	// W3C SCXML 5.2: the `refusals` datamodel variable, published (`sce:direction="out"`).
	vRefusals uint32
	// W3C SCXML 6.4: Parent communication (unbounded — see sce.ParentEventQueue)
	ParentExternalQueue *sce.ParentEventQueue
	InvokeID           string
	ChildSessionID     string
	// §scxml-6.4.3: invoke param VALUES staged by the parent, applied after
	// this machine's datamodel init so they override its `<data>` defaults.
	pendingParams      map[string]interface{}
}

// NewStaticRecordListIndexPolicy creates a new policy with default values.
func NewStaticRecordListIndexPolicy() StaticRecordListIndexPolicy {
	return StaticRecordListIndexPolicy{
		vDraft: StaticRecordListIndexDayRecord{year: 2026, month: 1, dayOfMonth: 1},
		vDays: nil,
		vCursor: 0,
		vDay: 0,
		vYear: 0,
		vSum: 0,
		vOrdered: false,
		vRefusals: 0,
	}
}

// Cursor reports what the published `cursor` datamodel
// variable holds now (W3C SCXML 5.2). Only the machine writes it.
func (p *StaticRecordListIndexPolicy) Cursor() int32 {
	return p.vCursor
}

// Day reports what the published `day` datamodel
// variable holds now (W3C SCXML 5.2). Only the machine writes it.
func (p *StaticRecordListIndexPolicy) Day() uint8 {
	return p.vDay
}

// Year reports what the published `year` datamodel
// variable holds now (W3C SCXML 5.2). Only the machine writes it.
func (p *StaticRecordListIndexPolicy) Year() uint16 {
	return p.vYear
}

// Sum reports what the published `sum` datamodel
// variable holds now (W3C SCXML 5.2). Only the machine writes it.
func (p *StaticRecordListIndexPolicy) Sum() uint32 {
	return p.vSum
}

// Ordered reports what the published `ordered` datamodel
// variable holds now (W3C SCXML 5.2). Only the machine writes it.
func (p *StaticRecordListIndexPolicy) Ordered() bool {
	return p.vOrdered
}

// Refusals reports what the published `refusals` datamodel
// variable holds now (W3C SCXML 5.2). Only the machine writes it.
func (p *StaticRecordListIndexPolicy) Refusals() uint32 {
	return p.vRefusals
}

// StaticRecordListIndexInvokeParams holds the values a parent's `<param>` and
// `namelist` give this machine's variables before it starts (§scxml-6.4.1). A
// variable left nil keeps the value its `<data>` gave it.
type StaticRecordListIndexInvokeParams struct {
	VCursor *int32
	VDay *uint8
	VYear *uint16
	VSum *uint32
	VOrdered *bool
	VRefusals *uint32
}

// AcceptParams gives this machine the values params carries, in place of the
// ones its `<data>` gave. Called before it initializes (§scxml-6.4.1).
func (p *StaticRecordListIndexPolicy) AcceptParams(params StaticRecordListIndexInvokeParams) {
	if params.VCursor != nil {
		p.vCursor = *params.VCursor
	}
	if params.VDay != nil {
		p.vDay = *params.VDay
	}
	if params.VYear != nil {
		p.vYear = *params.VYear
	}
	if params.VSum != nil {
		p.vSum = *params.VSum
	}
	if params.VOrdered != nil {
		p.vOrdered = *params.VOrdered
	}
	if params.VRefusals != nil {
		p.vRefusals = *params.VRefusals
	}
}



// No script engine needed for this state machine.
func (p *StaticRecordListIndexPolicy) InitializeDataModel(eng *sce.Engine[StaticRecordListIndexState, StaticRecordListIndexEvent]) {}

// SetParamValueInScriptEngine is a no-op for state machines without script engine.
func (p *StaticRecordListIndexPolicy) SetParamValueInScriptEngine(name string, value interface{}) {}


// ExecutePendingInvokes is a no-op (no invokes in this SM).
func (p *StaticRecordListIndexPolicy) ExecutePendingInvokes(engine *sce.Engine[StaticRecordListIndexState, StaticRecordListIndexEvent]) {}

// TickChildren is a no-op (no invokes in this SM).
func (p *StaticRecordListIndexPolicy) TickChildren(engine *sce.Engine[StaticRecordListIndexState, StaticRecordListIndexEvent]) {}

// DeliverToParent delivers a delayed `<send target="#_parent">` whose wait is
// over, with the payload an immediate one carries (W3C SCXML 6.2 + 6.4). It
// waited in this machine's own queue, so `<cancel>` reached it and a child that
// ended first dropped it — the engine dispatches nothing once final. Emitted for
// every machine, since the one that needs it is an invoked child, which need not
// invoke anything itself.
func (p *StaticRecordListIndexPolicy) DeliverToParent(eventName, eventData string) bool {
	if p.ParentExternalQueue == nil {
		return false
	}
	p.ParentExternalQueue.Push(sce.ParentEvent{Name: eventName, Data: eventData})
	return true
}

// HasParentSession answers whether a session invoked this one (W3C SCXML C.1):
// the queue the invoking parent installs is the link to it.
func (p *StaticRecordListIndexPolicy) HasParentSession() bool {
	return p.ParentExternalQueue != nil
}

// ======================================================================
// StatePolicy interface implementation
// ======================================================================

// InitialState returns the initial state (W3C SCXML 3.3).
func (p *StaticRecordListIndexPolicy) InitialState() StaticRecordListIndexState {
	return StaticRecordListIndexStateReading
}

// IsFinalState returns true if state is a <final> state (W3C SCXML 3.7).
func (p *StaticRecordListIndexPolicy) IsFinalState(state StaticRecordListIndexState) bool {
	switch state {
	}
	return false
}

// GetParent returns the parent of state, or (zero, false) if root (W3C SCXML 3.3).
func (p *StaticRecordListIndexPolicy) GetParent(state StaticRecordListIndexState) (StaticRecordListIndexState, bool) {
	switch state {
	}
	return 0, false
}

// IsCompoundState returns true if state is a <state> with child states — exactly
// the states that have an initial transition. A <parallel> is not compound
// (W3C SCXML 3.3).
func (p *StaticRecordListIndexPolicy) IsCompoundState(state StaticRecordListIndexState) bool {
	return len(initialTargetsOfStaticRecordListIndex[state]) > 0
}

func (p *StaticRecordListIndexPolicy) IsParallelState(_ StaticRecordListIndexState) bool { return false }

// GetChildStates returns state's <state>, <parallel> and <final> children, in
// document order — for a <parallel>, its regions (§scxml-D-getChildStates).
func (p *StaticRecordListIndexPolicy) GetChildStates(state StaticRecordListIndexState) []StaticRecordListIndexState {
	return childStatesOfStaticRecordListIndex[state]
}

// GetInitialTargets returns a compound state's initial transition target, as
// written; the engine's entry procedures dereference a <history> among them
// (W3C SCXML 3.3).
func (p *StaticRecordListIndexPolicy) GetInitialTargets(state StaticRecordListIndexState) []StaticRecordListIndexTarget {
	return initialTargetsOfStaticRecordListIndex[state]
}

// GetDocumentInitialTargets returns the target of the document's own initial
// transition, as written (W3C SCXML 3.2).
func (p *StaticRecordListIndexPolicy) GetDocumentInitialTargets() []StaticRecordListIndexTarget {
	return documentInitialTargetsOfStaticRecordListIndex
}

// W3C SCXML 3.10: this document declares no <history>, so no target list names
// one and the engine never asks the two below; answering would mean inventing
// one.
func (p *StaticRecordListIndexPolicy) GetHistoryParent(history sce.HistoryID) StaticRecordListIndexState {
	panic(fmt.Sprintf("StaticRecordListIndexPolicy declares no <history>; asked for %d", history))
}
func (p *StaticRecordListIndexPolicy) GetHistoryDefaultTargets(history sce.HistoryID) []StaticRecordListIndexTarget {
	panic(fmt.Sprintf("StaticRecordListIndexPolicy declares no <history>; asked for %d", history))
}
func (p *StaticRecordListIndexPolicy) HistoryValue(_ sce.HistoryID) ([]StaticRecordListIndexState, bool) {
	return nil, false
}

// GetDocumentOrder returns the document order index (W3C SCXML Appendix D).
func (p *StaticRecordListIndexPolicy) GetDocumentOrder(state StaticRecordListIndexState) int {
	switch state {
	case StaticRecordListIndexStateReading:
		return 0
	}
	return -1
}

// GetEventName returns the string name of an event (W3C SCXML 3.12).
func (p *StaticRecordListIndexPolicy) GetEventName(event StaticRecordListIndexEvent) string {
	return event.String()
}

// GetEventFromName looks up an event by name (W3C SCXML 3.12).
func (p *StaticRecordListIndexPolicy) GetEventFromName(name string) (StaticRecordListIndexEvent, bool) {
	switch name {
	case "day.picked":
		return StaticRecordListIndexEventDayPicked, true
	case "error.execution":
		return StaticRecordListIndexEventErrorExecution, true
	case "last":
		return StaticRecordListIndexEventLast, true
	case "next":
		return StaticRecordListIndexEventNext, true
	case "order":
		return StaticRecordListIndexEventOrder, true
	case "total":
		return StaticRecordListIndexEventTotal, true
	}
	return StaticRecordListIndexEventNull, false
}

// GetStateName returns the string name of a state (W3C SCXML 3.3).
func (p *StaticRecordListIndexPolicy) GetStateName(state StaticRecordListIndexState) string {
	return state.String()
}

// GetStateFromName reads a state id back into the state it names (W3C SCXML 3.3).
// The reverse of GetStateName, and what turns a host's recorded configuration
// back into the argument sce.Engine.EnterAt takes.
func (p *StaticRecordListIndexPolicy) GetStateFromName(name string) (StaticRecordListIndexState, bool) {
	return StaticRecordListIndexStateFromName(name)
}

// NullEvent returns the sentinel for eventless transition dispatch (W3C SCXML 3.13).
func (p *StaticRecordListIndexPolicy) NullEvent() StaticRecordListIndexEvent {
	return StaticRecordListIndexEventNull
}


// HasParallelStates returns whether the SM has parallel states.
func (p *StaticRecordListIndexPolicy) HasParallelStates() bool {
	return false
}

// NeedsScriptEngine returns whether the SM needs a script engine.
func (p *StaticRecordListIndexPolicy) NeedsScriptEngine() bool {
	return false
}

// NeedsEventScheduler reports whether a host must drive this machine with
// Tick rather than Step alone.
//
// W3C SCXML 6.2: Step runs a macrostep and never drains the delayed-send
// scheduler nor ticks an invoked child, so a host that only ever calls it
// waits forever with nothing said. Same verdict the generate manifest
// publishes as needs_event_scheduler.
func (p *StaticRecordListIndexPolicy) NeedsEventScheduler() bool {
	return false
}

// NeedsParent reports whether the document sends to its parent session — the
// generate manifest's needs_parent, read by Engine.RootStartRefusal.
func (p *StaticRecordListIndexPolicy) NeedsParent() bool {
	return false
}

// NeedsDataModelInit returns whether the SM needs datamodel init.
func (p *StaticRecordListIndexPolicy) NeedsDataModelInit() bool {
	return false
}

func (p *StaticRecordListIndexPolicy) HasInvokeSupport() bool { return false }
func (p *StaticRecordListIndexPolicy) HasChildTick() bool { return false }
func (p *StaticRecordListIndexPolicy) HasFinalize() bool { return false }
func (p *StaticRecordListIndexPolicy) HasAutoforward() bool { return false }
func (p *StaticRecordListIndexPolicy) HasActiveStates() bool { return false }
func (p *StaticRecordListIndexPolicy) GetActiveStates() []StaticRecordListIndexState { return nil }
// W3C SCXML 3.4: this machine keeps no active set — its configuration is the
// parent walk from the current state — so there is nothing for a restore to
// hand back here. sce.Engine.EnterAt reaches this only through HasActiveStates,
// which is false above; the method exists because the interface is one contract.
func (p *StaticRecordListIndexPolicy) SetActiveStates(_ []StaticRecordListIndexState) {}
// ExecuteFinalizeForChildEvent is a no-op (no finalize invokes).
func (p *StaticRecordListIndexPolicy) ExecuteFinalizeForChildEvent(_ *sce.EventWithMetadata[StaticRecordListIndexEvent], _ *sce.Engine[StaticRecordListIndexState, StaticRecordListIndexEvent]) {}
// ForwardToAutoforwardChildren is a no-op (no autoforward invokes).
func (p *StaticRecordListIndexPolicy) ForwardToAutoforwardChildren(_ string, _ sce.EventMetadata, _ *sce.Engine[StaticRecordListIndexState, StaticRecordListIndexEvent]) {}

// PopulateEventMetadata stores pending event metadata (W3C SCXML 5.10).
// Note: event name is set separately via setCurrentEvent(); metadata supplies
// only the name the event ARRIVED under, when that is not its value's own.
func (p *StaticRecordListIndexPolicy) PopulateEventMetadata(meta *sce.EventMetadata) {
	// NL→IR Item C1 Path A: lift the dequeued event's typed payload from the
	// type-erased carrier into the typed policy field the native guards read
	// (twin of the C11 pop loop's `sm->pending_payload = evt.payload`).
	p.pendingPayloadTag = StaticRecordListIndexPayloadTagNone
	switch v := meta.TypedPayload.(type) {
	case StaticRecordListIndexDayPickedPayload:
		p.pendingPayloadTag = StaticRecordListIndexPayloadTagDayPicked
		p.pendingDayPickedPayload = v
	}

	p.pendingEventData = meta.Data
}

// LiftTypedPayload binds the dequeued event's typed `_event.data` view from
// the data it carries (NL→IR Item C1 Path A).
//
// The typed carrier PopulateEventMetadata reads is filled by one producer, the
// generated Raise<Event> inject seam. Every other producer — <send> with
// <param>, an invoke forwarding either way, autoforward, BasicHTTP, mesh —
// fills EventMetadata.Data, so the schema's fields are read out of that here.
// A refusal is returned for the engine to raise as error.execution, which is
// what W3C SCXML 3.13 gives for a guard that cannot be evaluated.
func (p *StaticRecordListIndexPolicy) LiftTypedPayload(event StaticRecordListIndexEvent, meta *sce.EventMetadata) error {
	// A typed carrier already bound the view, so the producer was the
	// inject seam and there is nothing to read out of `Data`.
	if p.pendingPayloadTag != StaticRecordListIndexPayloadTagNone {
		return nil
	}
	switch event {
	case StaticRecordListIndexEventDayPicked:
		fields, err := sce.LiftPayload(meta.Data)
		if err != nil {
			return err
		}
		var payload StaticRecordListIndexDayPickedPayload
		if payload.year, err = sce.PayloadUnsigned[uint16](fields, "year"); err != nil {
			return err
		}
		if payload.month, err = sce.PayloadUnsigned[uint8](fields, "month"); err != nil {
			return err
		}
		if payload.dayOfMonth, err = sce.PayloadUnsigned[uint8](fields, "dayOfMonth"); err != nil {
			return err
		}
		p.pendingDayPickedPayload = payload
		p.pendingPayloadTag = StaticRecordListIndexPayloadTagDayPicked
	}
	return nil

}

// ClearEventMetadata resets pending event metadata (W3C SCXML 5.10).
func (p *StaticRecordListIndexPolicy) ClearEventMetadata() {
	// NL→IR Item C1 Path A: reset the typed-payload tag (PopulateEventMetadata
	// always re-establishes it for the next event; this keeps a stale payload
	// from being read between macrosteps).
	p.pendingPayloadTag = StaticRecordListIndexPayloadTagNone

	p.pendingEventData = ""
}



// ExecuteEntryActions enters one state (W3C SCXML 3.8): adds it to the
// configuration, runs its <onentry>, and its <initial> transition's content when
// its initial state is entered by default.
//line static_record_list_index.scxml:21
func (p *StaticRecordListIndexPolicy) ExecuteEntryActions(state StaticRecordListIndexState, engine *sce.Engine[StaticRecordListIndexState, StaticRecordListIndexEvent], isDefaultEntry bool) {
	switch state {
	default:
		// No entry actions
	}
}

// ExecuteHistoryDefaultContent runs a <history>'s default transition content
// (W3C SCXML 3.10.2), after its parent's onentry (and after the parent's own
// <initial> content) when the history was taken with nothing recorded. The
// engine asks for it by the entry set's defaultHistoryContent answer; a history
// that restored what it recorded runs nothing.
//line static_record_list_index.scxml:21
func (p *StaticRecordListIndexPolicy) ExecuteHistoryDefaultContent(history sce.HistoryID, engine *sce.Engine[StaticRecordListIndexState, StaticRecordListIndexEvent]) {
	// W3C SCXML 3.10.2: no <history> in this document has default content.
}

// ExecuteExitActions exits one state (W3C SCXML 3.9): records its histories,
// runs its <onexit>, cancels its invocations and removes it from the
// configuration — §scxml-D-exitStates's order.
//line static_record_list_index.scxml:21
func (p *StaticRecordListIndexPolicy) ExecuteExitActions(state StaticRecordListIndexState, engine *sce.Engine[StaticRecordListIndexState, StaticRecordListIndexEvent], configurationBeforeExit []StaticRecordListIndexState) {
	// §scxml-D-exitStates orders one state's exit as onexit, then
	// cancelInvoke, then configuration.delete(s), so `In(s)` inside s's own
	// handler is true: the <onexit> switch comes first and the removal from
	// the configuration last.
	switch state {
	default:
		// No exit actions
	}
}



// BindCurrentEvent binds the event whose transitions are about to be selected as
// the _event their guards read (W3C SCXML 5.10) — before the first guard runs,
// and not for an eventless selection, which has no event of its own.
//line static_record_list_index.scxml:21
func (p *StaticRecordListIndexPolicy) BindCurrentEvent(event StaticRecordListIndexEvent, engine *sce.Engine[StaticRecordListIndexState, StaticRecordListIndexEvent]) {
	// This document's guards never read _event, so there is nothing to bind.
}

// FirstEnabledTransition is Appendix D selectTransitions, the half only this
// document can answer: the first of state's own transitions, in document order,
// that event enables and whose guard holds. The engine walks the atomic states
// and their ancestors and keeps the ordered set; the null event asks for
// eventless transitions.
//line static_record_list_index.scxml:21
func (p *StaticRecordListIndexPolicy) FirstEnabledTransition(state StaticRecordListIndexState, event StaticRecordListIndexEvent, engine *sce.Engine[StaticRecordListIndexState, StaticRecordListIndexEvent]) (sce.EnabledTransition[StaticRecordListIndexState, sce.HistoryID], bool) {
	switch state {
	case StaticRecordListIndexStateReading:
		if event == StaticRecordListIndexEventDayPicked {
			{
				return sce.EnabledTransition[StaticRecordListIndexState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 0,
					HasActions:      true,
					IsInternal:      true,
				}, true
			}
		}
		if event == StaticRecordListIndexEventNext {
			{
				return sce.EnabledTransition[StaticRecordListIndexState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 1,
					HasActions:      true,
					IsInternal:      true,
				}, true
			}
		}
		if event == StaticRecordListIndexEventLast {
			{
				return sce.EnabledTransition[StaticRecordListIndexState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 2,
					HasActions:      true,
					IsInternal:      true,
				}, true
			}
		}
		if event == StaticRecordListIndexEventTotal {
			{
				return sce.EnabledTransition[StaticRecordListIndexState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 3,
					HasActions:      true,
					IsInternal:      true,
				}, true
			}
		}
		if event == StaticRecordListIndexEventOrder {
			// NL→IR Item C1 Path A: native typed `_event.data` guard — cond
			// "days[0].dayOfMonth < days[1].dayOfMonth" lowered to a tag-checked field comparison on
			// the lifted `pending<Event>Payload` (no script engine).
			if func() bool { var sceFailure scealgorithm.Failure; sceValue := scealgorithm.At(&sceFailure, p.vDays[:], int64(0)).dayOfMonth < scealgorithm.At(&sceFailure, p.vDays[:], int64(1)).dayOfMonth; if sceFailure.Failed() { engine.Raise(sce.NewPlatformError(StaticRecordListIndexEventErrorExecution, "<transition cond='days[0].dayOfMonth < days[1].dayOfMonth'>: an integer operation overflowed or failed")); return false }; return sceValue }() {
				return sce.EnabledTransition[StaticRecordListIndexState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 4,
					HasActions:      true,
					IsInternal:      true,
				}, true
			}
		}
		if event == StaticRecordListIndexEventOrder {
			{
				return sce.EnabledTransition[StaticRecordListIndexState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 5,
					HasActions:      true,
					IsInternal:      true,
				}, true
			}
		}
		if event == StaticRecordListIndexEventErrorExecution {
			{
				return sce.EnabledTransition[StaticRecordListIndexState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 6,
					HasActions:      true,
					IsInternal:      true,
				}, true
			}
		}
	}
	return sce.EnabledTransition[StaticRecordListIndexState, sce.HistoryID]{}, false
}

// ExecuteTransitionContent runs one transition's executable content (W3C SCXML
// 3.13), between the microstep's exits and its entries.
//line static_record_list_index.scxml:21
func (p *StaticRecordListIndexPolicy) ExecuteTransitionContent(source StaticRecordListIndexState, transitionIndex int, engine *sce.Engine[StaticRecordListIndexState, StaticRecordListIndexEvent]) {
	switch source {
	case StaticRecordListIndexStateReading:
		switch transitionIndex {
		case 0:
			//line static_record_list_index.scxml:39
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {
				if p.pendingPayloadTag != StaticRecordListIndexPayloadTagDayPicked {
					return
				}


	p.vDraft.year = p.pendingDayPickedPayload.year



	p.vDraft.month = p.pendingDayPickedPayload.month



	p.vDraft.dayOfMonth = p.pendingDayPickedPayload.dayOfMonth


	// SCE Accepted Subset §2.15: <sce:append target="days">

	if func() bool { var sceFailure scealgorithm.Failure; if len(p.vDays) >= 3 { engine.Raise(sce.NewPlatformError(StaticRecordListIndexEventErrorExecution, "<sce:append target='days'>: the list already holds its capacity of 3")); return true }; sceValue := scealgorithm.ElementOf(p.vDays, p.vDraft); if sceFailure.Failed() { engine.Raise(sce.NewPlatformError(StaticRecordListIndexEventErrorExecution, "<sce:append target='days'>: an integer operation overflowed or failed")); return true }; p.vDays = append(p.vDays, sceValue); return false }() {
		return  // W3C SCXML 4.9: the error ends the block
	}

			}()
		case 1:
			//line static_record_list_index.scxml:45
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {


	if func() bool { var sceFailure scealgorithm.Failure; sceValue := scealgorithm.At(&sceFailure, p.vDays[:], int64(p.vCursor)).dayOfMonth; if sceFailure.Failed() { engine.Raise(sce.NewPlatformError(StaticRecordListIndexEventErrorExecution, "<assign location='day'>: an integer operation overflowed or failed")); return true }; p.vDay = sceValue; return false }() {
		return  // W3C SCXML 4.9: the error ends the block
	}



	if func() bool { var sceFailure scealgorithm.Failure; sceValue := scealgorithm.At(&sceFailure, p.vDays[:], int64(p.vCursor)).year; if sceFailure.Failed() { engine.Raise(sce.NewPlatformError(StaticRecordListIndexEventErrorExecution, "<assign location='year'>: an integer operation overflowed or failed")); return true }; p.vYear = sceValue; return false }() {
		return  // W3C SCXML 4.9: the error ends the block
	}



	if func() bool { var sceFailure scealgorithm.Failure; sceValue := scealgorithm.AddInt32(&sceFailure, p.vCursor, 1); if sceFailure.Failed() { engine.Raise(sce.NewPlatformError(StaticRecordListIndexEventErrorExecution, "<assign location='cursor'>: an integer operation overflowed or failed")); return true }; p.vCursor = sceValue; return false }() {
		return  // W3C SCXML 4.9: the error ends the block
	}

			}()
		case 2:
			//line static_record_list_index.scxml:50
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {


	if func() bool { var sceFailure scealgorithm.Failure; sceValue := scealgorithm.AtU(&sceFailure, p.vDays[:], uint64(scealgorithm.SubUint32(&sceFailure, uint32(len(p.vDays)), 1))).dayOfMonth; if sceFailure.Failed() { engine.Raise(sce.NewPlatformError(StaticRecordListIndexEventErrorExecution, "<assign location='day'>: an integer operation overflowed or failed")); return true }; p.vDay = sceValue; return false }() {
		return  // W3C SCXML 4.9: the error ends the block
	}

			}()
		case 3:
			//line static_record_list_index.scxml:53
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {


	if func() bool { var sceFailure scealgorithm.Failure; sceValue := uint32(scealgorithm.AddUint8(&sceFailure, scealgorithm.At(&sceFailure, p.vDays[:], int64(0)).dayOfMonth, scealgorithm.At(&sceFailure, p.vDays[:], int64(1)).dayOfMonth)); if sceFailure.Failed() { engine.Raise(sce.NewPlatformError(StaticRecordListIndexEventErrorExecution, "<assign location='sum'>: an integer operation overflowed or failed")); return true }; p.vSum = sceValue; return false }() {
		return  // W3C SCXML 4.9: the error ends the block
	}

			}()
		case 4:
			//line static_record_list_index.scxml:56
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {


	p.vOrdered = true

			}()
		case 5:
			//line static_record_list_index.scxml:59
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {


	p.vOrdered = false

			}()
		case 6:
			//line static_record_list_index.scxml:62
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {


	if func() bool { var sceFailure scealgorithm.Failure; sceValue := scealgorithm.AddUint32(&sceFailure, p.vRefusals, 1); if sceFailure.Failed() { engine.Raise(sce.NewPlatformError(StaticRecordListIndexEventErrorExecution, "<assign location='refusals'>: an integer operation overflowed or failed")); return true }; p.vRefusals = sceValue; return false }() {
		return  // W3C SCXML 4.9: the error ends the block
	}

			}()
		}
	}
}
