// SCE-GENERATED — DO NOT EDIT
// source-hash: f55f0d50f2ff05a8b6dba1e27e40d55e81b13b70ab29ebc5ee03738d4ee0ecd4


// SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 [Author of input SCXML file] (content derived from the input document)
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 newmassrael (content copied from SCE templates)
//
// Generated by SCE Code Generator (Go backend)
// From: integration_resources/a_delayed_send_reaches_what_its_target_names/a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid.scxml
//
// This generated code is usable under terms of your choice when it was produced
// by an unmodified sce-codegen and is not part of a competing product
// (SCE Linking Exception, section 3; see LICENSE-GENERATED.md).
// Full license: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE
// Generated Go state machine for `a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid`.
//
// Generated by SCE Code Generator (Go backend).
// Implements sce.StatePolicy with full transition logic,
// entry/exit actions, and event processing.


// SCE-MAP: a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid.scxml:3 :: _machine

package a_delayed_send_reaches_what_its_target_names

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	sce "github.com/newmassrael/sce-go-runtime"
)

// Ensure imports are used
var (
	_ = fmt.Sprintf
	_ = filepath.Join
	_ = strings.HasPrefix
	_ = time.Duration(0)
)

// ======================================================================
// State type (W3C SCXML 3.3)
// ======================================================================

type ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState int

const (
	ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateWait ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState = 0
)

func (s ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState) String() string {
	switch s {
	case ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateWait:
		return "wait"
	}
	return "unknown"
}

// ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateFromName is the read half of the pair above — a state
// id back into the state it names (W3C SCXML 3.3).
//
// A host that persists where a machine was has to write it down as TEXT: the
// constants above are a build artefact of one binary, and the process that
// resumes is a different one. String publishes the name and this reads it back,
// which is what lets a journal survive its own record and reach
// sce.Engine.EnterAt.
//
// The second return is false for a name this document does not declare. A name
// guessed at rather than refused is how a restore reaches a configuration
// nobody recorded — and the refusal is what makes a typo in a journal a
// reported failure instead of a machine quietly somewhere else.
//
// Emitted from the same loop over the document's states as String, so the two
// age together.
func ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateFromName(name string) (ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, bool) {
	switch name {
	case "wait":
		return ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateWait, true
	}
	var zero ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState
	return zero, false
}

// ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidAllStates is every state this document declares, in the
// order the constants above are issued.
//
// Emitted from the same loop, so a walk over it is a walk over the document
// rather than over a list somebody maintained beside it — a test that spells
// its own list goes on passing when the document grows a state.
var ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidAllStates = []ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState{
	ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateWait,
}

// ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidTarget is one token of a target list, as the document wrote
// it (W3C SCXML 3.13): a state, or a <history> the engine dereferences.
type ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidTarget = sce.EntryTarget[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, sce.HistoryID]

// ======================================================================
// Document structure (W3C SCXML 3.2-3.4, 3.10)
//
// Package-level tables, because the structure is a fact about the document
// and not about a run: the engine's Appendix D procedures read them through
// the policy methods below, and a transition's target list is handed out as
// a slice of them rather than rebuilt on every selection.
// ======================================================================

// childStatesOfADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKid is §scxml-D-getChildStates per state: its
// <state>, <parallel> and <final> children, in document order.
var childStatesOfADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKid = [1][]ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState{
}

// initialTargetsOfADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKid is each compound state's initial transition
// target, as written (§scxml-3.3).
var initialTargetsOfADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKid = [1][]ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidTarget{
}

// documentInitialTargetsOfADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKid is the target of the document's own
// initial transition, as written (§scxml-3.2).
var documentInitialTargetsOfADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKid = []ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidTarget{sce.StateTarget[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, sce.HistoryID](ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateWait)}

// transitionTargetsOfADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKid is each transition's target list, as
// written (§scxml-3.13), by source state and the transition's index among its
// source's own transitions. A targetless transition's entry is empty.
var transitionTargetsOfADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKid = [1][][]ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidTarget{
}

// ======================================================================
// Event type (W3C SCXML 3.12)
// ======================================================================

type ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent int

const (
	ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventErrorExecution ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent = 0
	ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventHello ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent = 1
	ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventLate ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent = 2
	ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventPing ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent = 3
	ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventPong ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent = 4
	// W3C SCXML 3.13: Sentinel for eventless transition dispatch
	ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventNull ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent = 5
)

func (e ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent) String() string {
	switch e {
	case ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventErrorExecution:
		return "error.execution"
	case ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventHello:
		return "hello"
	case ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventLate:
		return "late"
	case ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventPing:
		return "ping"
	case ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventPong:
		return "pong"
	case ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventNull:
		return ""
	}
	return "unknown"
}

// ======================================================================
// Policy struct
// ======================================================================

type ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy struct {
	pendingEventName string
	pendingEventData string
	pendingEventType string
	pendingEventSendid string
	pendingEventOrigin string
	pendingEventOrigintype string
	pendingEventInvokeid string
	// W3C SCXML 5.10: Session ID
	SessionID string
	// W3C SCXML B.1: Script engine handle (per-instance, Path B+ Q1=(d) Go=interface ref)
	ScriptEngine sce.IScriptEngine
	scriptEngineInitialized bool
	// W3C SCXML C.2.3: inbound BasicHTTP endpoint serving this machine,
	// declared by the deployment before Initialize(). The address belongs to
	// whoever runs the listener, so the machine takes it from here rather than
	// guessing one. Empty means no such endpoint is deployed, and no BasicHTTP
	// entry is published in _ioprocessors.
	BasicHTTPAccessURI string
	// W3C SCXML 6.4: Parent communication (unbounded — see sce.ParentEventQueue)
	ParentExternalQueue *sce.ParentEventQueue
	InvokeID           string
	ChildSessionID     string
	// §scxml-6.4.3: invoke param VALUES staged by the parent, applied after
	// this machine's datamodel init so they override its `<data>` defaults.
	pendingParams      map[string]interface{}
}

// NewADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy creates a new policy with default values.
func NewADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy() ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy {
	return ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy{
	}
}




// ensureScriptEngine lazily initializes the script engine session.
//
// Engine DI Parity RFC: panics if ScriptEngine was not set on the policy
// before Initialize() — mirrors Kotlin's mandatory constructor parameter
// contract. Silent no-op would otherwise turn missed injection into a
// hidden runtime regression (every <assign>/<log>/guard becomes a no-op
// and the SM walks to its default-state final without diagnostic).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) ensureScriptEngine() {
	if p.scriptEngineInitialized {
		return
	}
	engine := p.ScriptEngine
	if engine == nil {
		panic("ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy: ScriptEngine field must be set before Initialize()")
	}
	sessionID := p.SessionID
	if sessionID == "" {
		sessionID = sce.GenerateSessionID()
		p.SessionID = sessionID
	}
	if !engine.HasSession(sessionID) {
		_ = engine.CreateSession(sessionID)
	}
	// W3C SCXML C.1.1 / C.2.3: the _ioprocessors entries come from the same
	// helper every other backend uses, so a machine reads the same entry names
	// and the same addresses whichever one runs it.
	_ = engine.SetupSystemVariables(sessionID, "a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid",
		sce.BuildIoProcessors(sessionID, p.BasicHTTPAccessURI))
	p.scriptEngineInitialized = true
}


// InitializeDataModel sets up datamodel via script engine (W3C SCXML 5.3).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) InitializeDataModel(eng *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent]) {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	sessionID := p.SessionID

	// W3C SCXML 5.3: Initialize _sessionid
	_ = engine.SetVariable(sessionID, "_sessionid", sessionID)

	// W3C SCXML 5.3: Initialize _name
	_ = engine.SetVariable(sessionID, "_name", "a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid")

	// W3C SCXML 5.2.2: Initialize global datamodel variables



	// §scxml-6.4.3: apply the invoke params the parent staged — overriding the
	// `<data>` default this block just seeded, and only for a name the child
	// declares ("if the names do not match, the Processor MUST NOT add the
	// value ... to the invoked session's data model"). `HasVariable` is that
	// filter, and it is this channel's only copy of the rule.
	if len(p.pendingParams) > 0 {
		for paramName, paramValue := range p.pendingParams {
			if engine.HasVariable(sessionID, paramName) {
				_ = engine.SetVariable(sessionID, paramName, paramValue)
			}
		}
		p.pendingParams = nil
	}
}

// evaluateGuard evaluates a guard condition via script engine.
// W3C SCXML 4.3.2: If a condition expression cannot be evaluated, the processor
// MUST treat it as false and MUST raise error.execution.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) evaluateGuard(guard string, eng *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent]) bool {
	value, _ := p.evaluateGuardRaising(guard, eng, "a <transition> cond failed to evaluate")
	return value
}

// evaluateIfCond evaluates an <if> or <elseif> cond as evaluateGuard does, and
// also records a failure in condFailed. W3C SCXML 5.9.1 + 4.9: the <if> still
// selects on false, and is then the element whose processing raised, so its
// block ends after it.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) evaluateIfCond(guard string, eng *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent], condFailed *bool) bool {
	value, ok := p.evaluateGuardRaising(guard, eng, "an <if> cond failed to evaluate")
	if !ok {
		*condFailed = true
	}
	return value
}

// evaluateGuardRaising evaluates a cond, raising error.execution when it cannot
// be evaluated (W3C SCXML 5.9.1); ok is false then, where a bare false could
// not say so.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) evaluateGuardRaising(guard string, eng *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent], reason string) (value bool, ok bool) {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	result, err := engine.EvaluateExpression(p.SessionID, guard)
	if err != nil {
		eng.Raise(sce.NewPlatformError(ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventErrorExecution, reason))
		return false, false
	}
	return sce.ScriptToBool(result), true
}

// executeScript executes a script block via script engine.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) executeScript(script string) error {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	return engine.ExecuteScript(p.SessionID, script)
}

// setCurrentEvent binds _event system variable (W3C SCXML 5.10) and answers
// which rung of §scxml-B-2-8-1 the payload got, because the binding is the
// only place that knows.
//
// This used to be `_ = engine.SetCurrentEvent(...)`: the ladder decided
// between a DOM, a value and a space-normalized string, and the decision was
// dropped one line later. A payload that announced structure and would not
// parse therefore reached the document as raw characters, every
// _event.data.<field> read empty, and nothing anywhere could say so — see
// sce.PayloadReading.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) setCurrentEvent(name string) sce.PayloadReading {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	data := p.pendingEventData
	eventType := p.pendingEventType
	sendID := p.pendingEventSendid
	// W3C SCXML C.1: `_event.origin` is the sender's published
	// `_ioprocessors` location, not its bare session id — and this is the one
	// place that publishes `_event` to the document, so this is where the id
	// becomes a location. The engine keeps the bare id in
	// `EventMetadata.Origin` because its session-keyed lookups (<finalize>
	// dispatch, cancelled-invoke filtering) match on it; converting at the
	// raise would make one value serve two consumers that need different
	// spellings. The conversion itself lives in `sce.PublishedOrigin`, the
	// port of the `IOProcessorHelper::publishedOrigin` the C++ engines share:
	// a second spelling of the rule is how the backends would stop agreeing.
	origin := sce.PublishedOrigin(p.pendingEventOrigin)
	originType := p.pendingEventOrigintype
	invokeID := p.pendingEventInvokeid
	reading, err := engine.SetCurrentEvent(p.SessionID, sce.SetCurrentEventArgs{
		Name:       name,
		Data:       data,
		Type:       eventType,
		SendID:     sendID,
		Origin:     origin,
		OriginType: originType,
		InvokeID:   invokeID,
	})
	if err != nil {
		// An engine that could not bind _event at all has a larger problem
		// than an unreadable payload, and reporting PayloadUndecodable for it
		// would point a host at the wrong thing.
		return sce.PayloadAbsent
	}
	return reading
}

// assignVariable assigns a value to a datamodel variable via script engine.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) assignVariable(location, expr string) error {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	script := location + " = " + expr
	return engine.ExecuteScript(p.SessionID, script)
}

// getVariable reads a datamodel variable from the script engine.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) getVariable(name string) interface{} {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	result, err := engine.GetVariable(p.SessionID, name)
	if err != nil {
		return nil
	}
	return result
}

// SetParamValueInScriptEngine stores an invoke param's VALUE for deferred
// application after datamodel init (§scxml-6.4.3).
//
// Params are applied at the end of InitializeDataModel, overriding the
// `<data>` default only for names the child declares. The value crosses as a
// value: this took the parent's value rendered as Lua source and
// re-evaluated it here until 2026-08-21, which survived every value a test
// had tried and lost the ones Lua cannot spell — `ToScriptLiteral` renders a
// non-finite number as `+Inf`, which is not a Lua expression, so an
// `<invoke>` `<param expr="1/0"/>` arrived as nothing at all.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) SetParamValueInScriptEngine(name string, value interface{}) {
	if p.pendingParams == nil {
		p.pendingParams = make(map[string]interface{})
	}
	p.pendingParams[name] = value
}


// ExecutePendingInvokes is a no-op (no invokes in this SM).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) ExecutePendingInvokes(engine *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent]) {}

// TickChildren is a no-op (no invokes in this SM).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) TickChildren(engine *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent]) {}

// DeliverToParent delivers a delayed `<send target="#_parent">` whose wait is
// over, with the payload an immediate one carries (W3C SCXML 6.2 + 6.4). It
// waited in this machine's own queue, so `<cancel>` reached it and a child that
// ended first dropped it — the engine dispatches nothing once final. Emitted for
// every machine, since the one that needs it is an invoked child, which need not
// invoke anything itself.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) DeliverToParent(eventName, eventData string) bool {
	if p.ParentExternalQueue == nil {
		return false
	}
	p.ParentExternalQueue.Push(sce.ParentEvent{Name: eventName, Data: eventData})
	return true
}

// HasParentSession answers whether a session invoked this one (W3C SCXML C.1):
// the queue the invoking parent installs is the link to it.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) HasParentSession() bool {
	return p.ParentExternalQueue != nil
}

// ======================================================================
// StatePolicy interface implementation
// ======================================================================

// InitialState returns the initial state (W3C SCXML 3.3).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) InitialState() ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState {
	return ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateWait
}

// IsFinalState returns true if state is a <final> state (W3C SCXML 3.7).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) IsFinalState(state ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState) bool {
	switch state {
	}
	return false
}

// GetParent returns the parent of state, or (zero, false) if root (W3C SCXML 3.3).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) GetParent(state ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState) (ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, bool) {
	switch state {
	}
	return 0, false
}

// IsCompoundState returns true if state is a <state> with child states — exactly
// the states that have an initial transition. A <parallel> is not compound
// (W3C SCXML 3.3).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) IsCompoundState(state ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState) bool {
	return len(initialTargetsOfADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKid[state]) > 0
}

func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) IsParallelState(_ ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState) bool { return false }

// GetChildStates returns state's <state>, <parallel> and <final> children, in
// document order — for a <parallel>, its regions (§scxml-D-getChildStates).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) GetChildStates(state ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState) []ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState {
	return childStatesOfADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKid[state]
}

// GetInitialTargets returns a compound state's initial transition target, as
// written; the engine's entry procedures dereference a <history> among them
// (W3C SCXML 3.3).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) GetInitialTargets(state ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState) []ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidTarget {
	return initialTargetsOfADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKid[state]
}

// GetDocumentInitialTargets returns the target of the document's own initial
// transition, as written (W3C SCXML 3.2).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) GetDocumentInitialTargets() []ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidTarget {
	return documentInitialTargetsOfADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKid
}

// W3C SCXML 3.10: this document declares no <history>, so no target list names
// one and the engine never asks the two below; answering would mean inventing
// one.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) GetHistoryParent(history sce.HistoryID) ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState {
	panic(fmt.Sprintf("ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy declares no <history>; asked for %d", history))
}
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) GetHistoryDefaultTargets(history sce.HistoryID) []ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidTarget {
	panic(fmt.Sprintf("ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy declares no <history>; asked for %d", history))
}
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) HistoryValue(_ sce.HistoryID) ([]ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, bool) {
	return nil, false
}

// GetDocumentOrder returns the document order index (W3C SCXML Appendix D).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) GetDocumentOrder(state ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState) int {
	switch state {
	case ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateWait:
		return 0
	}
	return -1
}

// GetEventName returns the string name of an event (W3C SCXML 3.12).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) GetEventName(event ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent) string {
	return event.String()
}

// GetEventFromName looks up an event by name (W3C SCXML 3.12).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) GetEventFromName(name string) (ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent, bool) {
	switch name {
	case "error.execution":
		return ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventErrorExecution, true
	case "hello":
		return ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventHello, true
	case "late":
		return ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventLate, true
	case "ping":
		return ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventPing, true
	case "pong":
		return ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventPong, true
	}
	return ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventNull, false
}

// GetStateName returns the string name of a state (W3C SCXML 3.3).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) GetStateName(state ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState) string {
	return state.String()
}

// GetStateFromName reads a state id back into the state it names (W3C SCXML 3.3).
// The reverse of GetStateName, and what turns a host's recorded configuration
// back into the argument sce.Engine.EnterAt takes.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) GetStateFromName(name string) (ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, bool) {
	return ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateFromName(name)
}

// NullEvent returns the sentinel for eventless transition dispatch (W3C SCXML 3.13).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) NullEvent() ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent {
	return ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventNull
}


// HasParallelStates returns whether the SM has parallel states.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) HasParallelStates() bool {
	return false
}

// NeedsScriptEngine returns whether the SM needs a script engine.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) NeedsScriptEngine() bool {
	return true
}

// NeedsEventScheduler reports whether a host must drive this machine with
// Tick rather than Step alone.
//
// W3C SCXML 6.2: Step runs a macrostep and never drains the delayed-send
// scheduler nor ticks an invoked child, so a host that only ever calls it
// waits forever with nothing said. Same verdict the generate manifest
// publishes as needs_event_scheduler.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) NeedsEventScheduler() bool {
	return true
}

// NeedsDataModelInit returns whether the SM needs datamodel init.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) NeedsDataModelInit() bool {
	return true
}

func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) HasInvokeSupport() bool { return false }
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) HasChildTick() bool { return false }
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) HasFinalize() bool { return false }
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) HasAutoforward() bool { return false }
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) HasActiveStates() bool { return false }
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) GetActiveStates() []ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState { return nil }
// W3C SCXML 3.4: this machine keeps no active set — its configuration is the
// parent walk from the current state — so there is nothing for a restore to
// hand back here. sce.Engine.EnterAt reaches this only through HasActiveStates,
// which is false above; the method exists because the interface is one contract.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) SetActiveStates(_ []ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState) {}
// ExecuteFinalizeForChildEvent is a no-op (no finalize invokes).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) ExecuteFinalizeForChildEvent(_ *sce.EventWithMetadata[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent], _ *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent]) {}
// ForwardToAutoforwardChildren is a no-op (no autoforward invokes).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) ForwardToAutoforwardChildren(_ string, _ sce.EventMetadata, _ *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent]) {}

// PopulateEventMetadata stores pending event metadata (W3C SCXML 5.10).
// Note: event name is set separately via setCurrentEvent(), not from metadata.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) PopulateEventMetadata(meta *sce.EventMetadata) {
	p.pendingEventData = meta.Data
	p.pendingEventType = meta.EventType.String()
	p.pendingEventSendid = meta.SendID
	p.pendingEventOrigin = meta.Origin
	p.pendingEventOrigintype = meta.OriginType
	p.pendingEventInvokeid = meta.InvokeID
}

// LiftTypedPayload binds the dequeued event's typed `_event.data` view from
// the data it carries (NL→IR Item C1 Path A).
//
// The typed carrier PopulateEventMetadata reads is filled by one producer, the
// generated Raise<Event> inject seam. Every other producer — <send> with
// <param>, an invoke forwarding either way, autoforward, BasicHTTP, mesh —
// fills EventMetadata.Data, so the schema's fields are read out of that here.
// A refusal is returned for the engine to raise as error.execution, which is
// what W3C SCXML 3.13 gives for a guard that cannot be evaluated.
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) LiftTypedPayload(event ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent, meta *sce.EventMetadata) error {
	// This document lowered no typed guard, so no event carries a typed view.
	return nil
}

// ClearEventMetadata resets pending event metadata (W3C SCXML 5.10).
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) ClearEventMetadata() {
	p.pendingEventName = ""
	p.pendingEventData = ""
	p.pendingEventType = ""
	p.pendingEventSendid = ""
	p.pendingEventOrigin = ""
	p.pendingEventOrigintype = ""
	p.pendingEventInvokeid = ""
}



// ExecuteEntryActions enters one state (W3C SCXML 3.8): adds it to the
// configuration, runs its <onentry>, and its <initial> transition's content when
// its initial state is entered by default.
//line a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid.scxml:3
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) ExecuteEntryActions(state ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, engine *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent], isDefaultEntry bool) {
	p.ensureScriptEngine()
	switch state {
	case ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateWait:
		//line a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid.scxml:5
		// W3C SCXML 3.8 + 4.9: onentry block 0, its own function so an
		// error ends it with `return` from however deep a <foreach> it came.
		func() {

	// W3C SCXML 6.2: send id="__send_1"
	{
	{
		eventDataStr := ""
		_ = eventDataStr
	// W3C SCXML 6.2: Send to parent
	if p.ParentExternalQueue != nil {
		p.ParentExternalQueue.Push(sce.ParentEvent{Name: "hello", Data: eventDataStr})
	}
	}
	}

	// W3C SCXML 6.2: send id="__send_2"
	{
	{
		// W3C SCXML 5.6.2: the value of <content expr> is the output of
		// <content>, the event's data — serialized so the far end parses.
		// "If the evaluation of 'expr' produces an error, the Processor MUST
		// place error.execution in the internal event queue and use the empty
		// string as the value of the <content> element."
		paramFailed := false
		p.ensureScriptEngine()
		eventDataStr := sce.ScriptValueToJSON("")
		if contentVal, contentErr := p.ScriptEngine.EvaluateExpression(p.SessionID, `5`); contentErr == nil {
			eventDataStr = sce.ScriptValueToJSON(contentVal)
		} else {
			engine.Raise(sce.NewPlatformError(ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventErrorExecution, "<send> contentexpr failed to evaluate"))
			paramFailed = true
		}
		_ = eventDataStr
	// W3C SCXML 6.2: Send to parent
	// W3C SCXML 6.2 + 6.4: delayed to the parent. It waits in this child's own
	// queue, so `<cancel>` reaches it and a child that ends first drops it, and
	// it carries its payload when the delay has elapsed.
	engine.ScheduleRoutedEvent(*new(ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent), time.Duration(20) * time.Millisecond, "__send_2", eventDataStr, p.SessionID,
		sce.ScheduledRoute{Kind: sce.RouteParent, EventName: "late"})
		// W3C SCXML 4.9: the <param> error ends the block, from however deep a
		// <foreach> it came — the block is its own function.
		if paramFailed {
			return
		}
	}
	}
		}()
	default:
		// No entry actions
	}
}

// ExecuteHistoryDefaultContent runs a <history>'s default transition content
// (W3C SCXML 3.10.2), after its parent's onentry (and after the parent's own
// <initial> content) when the history was taken with nothing recorded. The
// engine asks for it by the entry set's defaultHistoryContent answer; a history
// that restored what it recorded runs nothing.
//line a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid.scxml:3
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) ExecuteHistoryDefaultContent(history sce.HistoryID, engine *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent]) {
	// W3C SCXML 3.10.2: no <history> in this document has default content.
}

// ExecuteExitActions exits one state (W3C SCXML 3.9): records its histories,
// runs its <onexit>, cancels its invocations and removes it from the
// configuration — §scxml-D-exitStates's order.
//line a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid.scxml:3
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) ExecuteExitActions(state ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, engine *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent], configurationBeforeExit []ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState) {
	p.ensureScriptEngine()
	// §scxml-D-exitStates orders one state's exit as onexit, then
	// cancelInvoke, then configuration.delete(s), so `In(s)` inside s's own
	// handler is true: the <onexit> switch comes first and the removal from
	// the configuration last.
	switch state {
	default:
		// No exit actions
	}
}



// BindCurrentEvent binds the event whose transitions are about to be selected as
// the _event their guards read (W3C SCXML 5.10) — before the first guard runs,
// and not for an eventless selection, which has no event of its own.
//line a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid.scxml:3
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) BindCurrentEvent(event ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent, engine *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent]) {
	if event != ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventNull {
		// §scxml-B-2-8-1: the rung the payload got, handed to the engine
		// rather than dropped. This is the only frame that has both the
		// reading and the event it belongs to.
		engine.NotePayloadReading(event, p.setCurrentEvent(p.GetEventName(event)))
	}
}

// FirstEnabledTransition is Appendix D selectTransitions, the half only this
// document can answer: the first of state's own transitions, in document order,
// that event enables and whose guard holds. The engine walks the atomic states
// and their ancestors and keeps the ordered set; the null event asks for
// eventless transitions.
//line a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid.scxml:3
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) FirstEnabledTransition(state ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, event ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent, engine *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent]) (sce.EnabledTransition[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, sce.HistoryID], bool) {
	switch state {
	case ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateWait:
		if event == ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventPing {
			if p.evaluateGuard(`(_event.data == 7)`, engine) {
				return sce.EnabledTransition[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 0,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
	}
	return sce.EnabledTransition[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, sce.HistoryID]{}, false
}

// ExecuteTransitionContent runs one transition's executable content (W3C SCXML
// 3.13), between the microstep's exits and its entries.
//line a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid.scxml:3
func (p *ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidPolicy) ExecuteTransitionContent(source ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, transitionIndex int, engine *sce.Engine[ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidState, ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEvent]) {
	p.ensureScriptEngine()
	switch source {
	case ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidStateWait:
		switch transitionIndex {
		case 0:
			//line a_delayed_send_reaches_what_its_target_names__sce_synth_invoke__kid.scxml:12
			// W3C SCXML 4.9: a transition's content is one block; an error ends it.
			func() {

	// W3C SCXML 6.2: send id="__send_0"
	{
	{
		// W3C SCXML 5.6.2: the value of <content expr> is the output of
		// <content>, the event's data — serialized so the far end parses.
		// "If the evaluation of 'expr' produces an error, the Processor MUST
		// place error.execution in the internal event queue and use the empty
		// string as the value of the <content> element."
		paramFailed := false
		p.ensureScriptEngine()
		eventDataStr := sce.ScriptValueToJSON("")
		if contentVal, contentErr := p.ScriptEngine.EvaluateExpression(p.SessionID, `_scxml_add(_event.data, 1)`); contentErr == nil {
			eventDataStr = sce.ScriptValueToJSON(contentVal)
		} else {
			engine.Raise(sce.NewPlatformError(ADelayedSendReachesWhatItsTargetNamesSceSynthInvokeKidEventErrorExecution, "<send> contentexpr failed to evaluate"))
			paramFailed = true
		}
		_ = eventDataStr
	// W3C SCXML 6.2: Send to parent
	if p.ParentExternalQueue != nil {
		p.ParentExternalQueue.Push(sce.ParentEvent{Name: "pong", Data: eventDataStr})
	}
		// W3C SCXML 4.9: the <param> error ends the block, from however deep a
		// <foreach> it came — the block is its own function.
		if paramFailed {
			return
		}
	}
	}
			}()
		}
	}
}
