// SCE-GENERATED — DO NOT EDIT
// source-hash: a9b3d7b7ea8a5bd6001a98d04817a6efb870e7f83add64eb3bb769017877144d


// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 [Author of input SCXML file]
//
// Generated by SCE Code Generator (Go backend)
// From: integration_resources/invoke_param_seeds_declared_child_data/invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow.scxml
//
// This generated code is MIT licensed and may be freely used in any project.
// Runtime engine dependency (sce-go-runtime): LGPL-2.1-or-later WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// Full license: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE
// Generated Go state machine for `invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow`.
//
// Generated by SCE Code Generator (Go backend).
// Implements sce.StatePolicy with full transition logic,
// entry/exit actions, and event processing.


// SCE-MAP: invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow.scxml:3 :: _machine

package invoke_param_seeds_declared_child_data

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	sce "github.com/newmassrael/sce-go-runtime"
)

// Ensure imports are used
var (
	_ = fmt.Sprintf
	_ = filepath.Join
	_ = strings.HasPrefix
	_ = time.Duration(0)
)

// ======================================================================
// State type (W3C SCXML 3.3)
// ======================================================================

type InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState int

const (
	InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateDone InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState = 0
	InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateReport InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState = 1
)

func (s InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState) String() string {
	switch s {
	case InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateDone:
		return "done"
	case InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateReport:
		return "report"
	}
	return "unknown"
}

// InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateFromName is the read half of the pair above — a state
// id back into the state it names (W3C SCXML 3.3).
//
// A host that persists where a machine was has to write it down as TEXT: the
// constants above are a build artefact of one binary, and the process that
// resumes is a different one. String publishes the name and this reads it back,
// which is what lets a journal survive its own record and reach
// sce.Engine.EnterAt.
//
// The second return is false for a name this document does not declare. A name
// guessed at rather than refused is how a restore reaches a configuration
// nobody recorded — and the refusal is what makes a typo in a journal a
// reported failure instead of a machine quietly somewhere else.
//
// Emitted from the same loop over the document's states as String, so the two
// age together.
func InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateFromName(name string) (InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, bool) {
	switch name {
	case "done":
		return InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateDone, true
	case "report":
		return InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateReport, true
	}
	var zero InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState
	return zero, false
}

// InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowAllStates is every state this document declares, in the
// order the constants above are issued.
//
// Emitted from the same loop, so a walk over it is a walk over the document
// rather than over a list somebody maintained beside it — a test that spells
// its own list goes on passing when the document grows a state.
var InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowAllStates = []InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState{
	InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateDone,
	InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateReport,
}

// InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowTarget is one token of a target list, as the document wrote
// it (W3C SCXML 3.13): a state, or a <history> the engine dereferences.
type InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowTarget = sce.EntryTarget[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, sce.HistoryID]

// ======================================================================
// Document structure (W3C SCXML 3.2-3.4, 3.10)
//
// Package-level tables, because the structure is a fact about the document
// and not about a run: the engine's Appendix D procedures read them through
// the policy methods below, and a transition's target list is handed out as
// a slice of them rather than rebuilt on every selection.
// ======================================================================

// childStatesOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow is §scxml-D-getChildStates per state: its
// <state>, <parallel> and <final> children, in document order.
var childStatesOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow = [2][]InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState{
}

// initialTargetsOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow is each compound state's initial transition
// target, as written (§scxml-3.3).
var initialTargetsOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow = [2][]InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowTarget{
}

// documentInitialTargetsOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow is the target of the document's own
// initial transition, as written (§scxml-3.2).
var documentInitialTargetsOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow = []InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowTarget{sce.StateTarget[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, sce.HistoryID](InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateReport)}

// transitionTargetsOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow is each transition's target list, as
// written (§scxml-3.13), by source state and the transition's index among its
// source's own transitions. A targetless transition's entry is empty.
var transitionTargetsOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow = [2][][]InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowTarget{
	InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateReport: {
		0: {sce.StateTarget[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, sce.HistoryID](InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateDone)},
		1: {sce.StateTarget[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, sce.HistoryID](InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateDone)},
		2: {sce.StateTarget[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, sce.HistoryID](InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateDone)},
	},
}

// ======================================================================
// Event type (W3C SCXML 3.12)
// ======================================================================

type InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent int

const (
	InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventErrorExecution InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent = 0
	InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventSeedMissing InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent = 1
	InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventSeedOk InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent = 2
	InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventSeedShadowed InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent = 3
	// W3C SCXML 3.13: Sentinel for eventless transition dispatch
	InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventNull InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent = 4
)

func (e InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent) String() string {
	switch e {
	case InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventErrorExecution:
		return "error.execution"
	case InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventSeedMissing:
		return "seed.missing"
	case InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventSeedOk:
		return "seed.ok"
	case InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventSeedShadowed:
		return "seed.shadowed"
	case InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventNull:
		return ""
	}
	return "unknown"
}

// ======================================================================
// Policy struct
// ======================================================================

type InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy struct {
	// W3C SCXML 5.10.1: External event flag
	nextEventIsExternal bool
	pendingEventName string
	pendingEventData string
	pendingEventType string
	pendingEventSendid string
	pendingEventOrigin string
	pendingEventOrigintype string
	pendingEventInvokeid string
	// W3C SCXML 5.10: Session ID
	SessionID string
	// W3C SCXML B.1: Script engine handle (per-instance, Path B+ Q1=(d) Go=interface ref)
	ScriptEngine sce.IScriptEngine
	scriptEngineInitialized bool
	// W3C SCXML C.2.3: inbound BasicHTTP endpoint serving this machine,
	// declared by the deployment before Initialize(). The address belongs to
	// whoever runs the listener, so the machine takes it from here rather than
	// guessing one. Empty means no such endpoint is deployed, and no BasicHTTP
	// entry is published in _ioprocessors.
	BasicHTTPAccessURI string
	// W3C SCXML 6.4: Parent communication
	ParentExternalQueue chan sce.ParentEvent
	InvokeID           string
	ChildSessionID     string
	// §scxml-6.4.3: invoke param VALUES staged by the parent, applied after
	// this machine's datamodel init so they override its `<data>` defaults.
	pendingParams      map[string]interface{}
}

// NewInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy creates a new policy with default values.
func NewInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy() InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy {
	return InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy{
	}
}

// Seen reports what the `seen` datamodel variable is holding now
// (W3C SCXML 5.3).
//
// The live value, not the authored one: `<assign>` writes into the session, so
// a reader frozen at generation time would answer the document's literal for
// the whole run. The second return value is false when the machine cannot
// answer — no script engine is set, the session is not initialised yet,
// `seen` was assigned a value of another type, or the engine refused.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) Seen() (string, bool) {
	return sce.ReadDatamodelString(p.ScriptEngine, p.SessionID, "seen")
}

// Token reports what the `token` datamodel variable is holding now
// (W3C SCXML 5.3).
//
// The live value, not the authored one: `<assign>` writes into the session, so
// a reader frozen at generation time would answer the document's literal for
// the whole run. The second return value is false when the machine cannot
// answer — no script engine is set, the session is not initialised yet,
// `token` was assigned a value of another type, or the engine refused.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) Token() (string, bool) {
	return sce.ReadDatamodelString(p.ScriptEngine, p.SessionID, "token")
}




// ensureScriptEngine lazily initializes the script engine session.
//
// Engine DI Parity RFC: panics if ScriptEngine was not set on the policy
// before Initialize() — mirrors Kotlin's mandatory constructor parameter
// contract. Silent no-op would otherwise turn missed injection into a
// hidden runtime regression (every <assign>/<log>/guard becomes a no-op
// and the SM walks to its default-state final without diagnostic).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) ensureScriptEngine() {
	if p.scriptEngineInitialized {
		return
	}
	engine := p.ScriptEngine
	if engine == nil {
		panic("InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy: ScriptEngine field must be set before Initialize()")
	}
	sessionID := p.SessionID
	if sessionID == "" {
		sessionID = sce.GenerateSessionID()
		p.SessionID = sessionID
	}
	if !engine.HasSession(sessionID) {
		_ = engine.CreateSession(sessionID)
	}
	// W3C SCXML C.1.1 / C.2.3: the _ioprocessors entries come from the same
	// helper every other backend uses, so a machine reads the same entry names
	// and the same addresses whichever one runs it.
	_ = engine.SetupSystemVariables(sessionID, "invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow",
		sce.BuildIoProcessors(sessionID, p.BasicHTTPAccessURI))
	p.scriptEngineInitialized = true
}

// InitializeDataModel sets up datamodel via script engine (W3C SCXML 5.3).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) InitializeDataModel(eng *sce.Engine[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent]) {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	sessionID := p.SessionID

	// W3C SCXML 5.3: Initialize _sessionid
	_ = engine.SetVariable(sessionID, "_sessionid", sessionID)

	// W3C SCXML 5.3: Initialize _name
	_ = engine.SetVariable(sessionID, "_name", "invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow")

	// W3C SCXML 5.2.2: Initialize global datamodel variables
	// W3C SCXML 5.2/5.3: Initialize seen from expr="'unset'"
	{
		result, err := engine.EvaluateExpression(sessionID, `"unset"`)
		if err == nil {
			_ = engine.SetVariable(sessionID, "seen", result)
		} else {
			eng.Raise(sce.NewPlatformError(InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventErrorExecution, "<data id='seen'> expr failed to evaluate"))
			_ = engine.SetVariable(sessionID, "seen", nil)
		}
	}
	// W3C SCXML 5.2/5.3: Initialize token from expr="'child'"
	{
		result, err := engine.EvaluateExpression(sessionID, `"child"`)
		if err == nil {
			_ = engine.SetVariable(sessionID, "token", result)
		} else {
			eng.Raise(sce.NewPlatformError(InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventErrorExecution, "<data id='token'> expr failed to evaluate"))
			_ = engine.SetVariable(sessionID, "token", nil)
		}
	}



	// §scxml-6.4.3: apply the invoke params the parent staged — overriding the
	// `<data>` default this block just seeded, and only for a name the child
	// declares ("if the names do not match, the Processor MUST NOT add the
	// value ... to the invoked session's data model"). `HasVariable` is that
	// filter, and it is this channel's only copy of the rule.
	if len(p.pendingParams) > 0 {
		for paramName, paramValue := range p.pendingParams {
			if engine.HasVariable(sessionID, paramName) {
				_ = engine.SetVariable(sessionID, paramName, paramValue)
			}
		}
		p.pendingParams = nil
	}
}

// evaluateGuard evaluates a guard condition via script engine.
// W3C SCXML 4.3.2: If a condition expression cannot be evaluated, the processor
// MUST treat it as false and MUST raise error.execution.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) evaluateGuard(guard string, eng *sce.Engine[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent]) bool {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	result, err := engine.EvaluateExpression(p.SessionID, guard)
	if err != nil {
		eng.Raise(sce.NewPlatformError(InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventErrorExecution, "a <transition> cond failed to evaluate"))
		return false
	}
	return sce.ScriptToBool(result)
}

// executeScript executes a script block via script engine.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) executeScript(script string) error {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	return engine.ExecuteScript(p.SessionID, script)
}

// setCurrentEvent binds _event system variable (W3C SCXML 5.10) and answers
// which rung of §scxml-B-2-8-1 the payload got, because the binding is the
// only place that knows.
//
// This used to be `_ = engine.SetCurrentEvent(...)`: the ladder decided
// between a DOM, a value and a space-normalized string, and the decision was
// dropped one line later. A payload that announced structure and would not
// parse therefore reached the document as raw characters, every
// _event.data.<field> read empty, and nothing anywhere could say so — see
// sce.PayloadReading.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) setCurrentEvent(name string) sce.PayloadReading {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	data := p.pendingEventData
	eventType := p.pendingEventType
	sendID := p.pendingEventSendid
	// W3C SCXML C.1: `_event.origin` is the sender's published
	// `_ioprocessors` location, not its bare session id — and this is the one
	// place that publishes `_event` to the document, so this is where the id
	// becomes a location. The engine keeps the bare id in
	// `EventMetadata.Origin` because its session-keyed lookups (<finalize>
	// dispatch, cancelled-invoke filtering) match on it; converting at the
	// raise would make one value serve two consumers that need different
	// spellings. The conversion itself lives in `sce.PublishedOrigin`, the
	// port of the `IOProcessorHelper::publishedOrigin` the C++ engines share:
	// a second spelling of the rule is how the backends would stop agreeing.
	origin := sce.PublishedOrigin(p.pendingEventOrigin)
	originType := p.pendingEventOrigintype
	invokeID := p.pendingEventInvokeid
	reading, err := engine.SetCurrentEvent(p.SessionID, sce.SetCurrentEventArgs{
		Name:       name,
		Data:       data,
		Type:       eventType,
		SendID:     sendID,
		Origin:     origin,
		OriginType: originType,
		InvokeID:   invokeID,
	})
	if err != nil {
		// An engine that could not bind _event at all has a larger problem
		// than an unreadable payload, and reporting PayloadUndecodable for it
		// would point a host at the wrong thing.
		return sce.PayloadAbsent
	}
	return reading
}

// assignVariable assigns a value to a datamodel variable via script engine.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) assignVariable(location, expr string) error {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	script := location + " = " + expr
	return engine.ExecuteScript(p.SessionID, script)
}

// getVariable reads a datamodel variable from the script engine.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) getVariable(name string) interface{} {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	result, err := engine.GetVariable(p.SessionID, name)
	if err != nil {
		return nil
	}
	return result
}

// SetParamValueInScriptEngine stores an invoke param's VALUE for deferred
// application after datamodel init (§scxml-6.4.3).
//
// Params are applied at the end of InitializeDataModel, overriding the
// `<data>` default only for names the child declares. The value crosses as a
// value: this took the parent's value rendered as Lua source and
// re-evaluated it here until 2026-08-21, which survived every value a test
// had tried and lost the ones Lua cannot spell — `ToScriptLiteral` renders a
// non-finite number as `+Inf`, which is not a Lua expression, so an
// `<invoke>` `<param expr="1/0"/>` arrived as nothing at all.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) SetParamValueInScriptEngine(name string, value interface{}) {
	if p.pendingParams == nil {
		p.pendingParams = make(map[string]interface{})
	}
	p.pendingParams[name] = value
}


// ExecutePendingInvokes is a no-op (no invokes in this SM).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) ExecutePendingInvokes(engine *sce.Engine[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent]) {}

// TickChildren is a no-op (no invokes in this SM).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) TickChildren(engine *sce.Engine[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent]) {}

// ======================================================================
// StatePolicy interface implementation
// ======================================================================

// InitialState returns the initial state (W3C SCXML 3.3).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) InitialState() InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState {
	return InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateReport
}

// IsFinalState returns true if state is a <final> state (W3C SCXML 3.7).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) IsFinalState(state InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState) bool {
	switch state {
	case InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateDone:
		return true
	}
	return false
}

// GetParent returns the parent of state, or (zero, false) if root (W3C SCXML 3.3).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) GetParent(state InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState) (InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, bool) {
	switch state {
	}
	return 0, false
}

// IsCompoundState returns true if state is a <state> with child states — exactly
// the states that have an initial transition. A <parallel> is not compound
// (W3C SCXML 3.3).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) IsCompoundState(state InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState) bool {
	return len(initialTargetsOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow[state]) > 0
}

func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) IsParallelState(_ InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState) bool { return false }

// GetChildStates returns state's <state>, <parallel> and <final> children, in
// document order — for a <parallel>, its regions (§scxml-D-getChildStates).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) GetChildStates(state InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState) []InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState {
	return childStatesOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow[state]
}

// GetInitialTargets returns a compound state's initial transition target, as
// written; the engine's entry procedures dereference a <history> among them
// (W3C SCXML 3.3).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) GetInitialTargets(state InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState) []InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowTarget {
	return initialTargetsOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow[state]
}

// GetDocumentInitialTargets returns the target of the document's own initial
// transition, as written (W3C SCXML 3.2).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) GetDocumentInitialTargets() []InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowTarget {
	return documentInitialTargetsOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow
}

// W3C SCXML 3.10: this document declares no <history>, so no target list names
// one and the engine never asks the two below; answering would mean inventing
// one.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) GetHistoryParent(history sce.HistoryID) InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState {
	panic(fmt.Sprintf("InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy declares no <history>; asked for %d", history))
}
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) GetHistoryDefaultTargets(history sce.HistoryID) []InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowTarget {
	panic(fmt.Sprintf("InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy declares no <history>; asked for %d", history))
}
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) HistoryValue(_ sce.HistoryID) ([]InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, bool) {
	return nil, false
}

// GetDocumentOrder returns the document order index (W3C SCXML Appendix D).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) GetDocumentOrder(state InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState) int {
	switch state {
	case InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateDone:
		return 1
	case InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateReport:
		return 0
	}
	return -1
}

// GetEventName returns the string name of an event (W3C SCXML 3.12).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) GetEventName(event InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent) string {
	return event.String()
}

// GetEventFromName looks up an event by name (W3C SCXML 3.12).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) GetEventFromName(name string) (InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent, bool) {
	switch name {
	case "error.execution":
		return InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventErrorExecution, true
	case "seed.missing":
		return InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventSeedMissing, true
	case "seed.ok":
		return InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventSeedOk, true
	case "seed.shadowed":
		return InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventSeedShadowed, true
	}
	return InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventNull, false
}

// GetStateName returns the string name of a state (W3C SCXML 3.3).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) GetStateName(state InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState) string {
	return state.String()
}

// GetStateFromName reads a state id back into the state it names (W3C SCXML 3.3).
// The reverse of GetStateName, and what turns a host's recorded configuration
// back into the argument sce.Engine.EnterAt takes.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) GetStateFromName(name string) (InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, bool) {
	return InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateFromName(name)
}

// NullEvent returns the sentinel for eventless transition dispatch (W3C SCXML 3.13).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) NullEvent() InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent {
	return InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventNull
}


// SetNextEventIsExternal sets the external event flag (W3C SCXML 5.10.1).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) SetNextEventIsExternal(value bool) {
	p.nextEventIsExternal = value
}

// HasParallelStates returns whether the SM has parallel states.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) HasParallelStates() bool {
	return false
}

// NeedsScriptEngine returns whether the SM needs a script engine.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) NeedsScriptEngine() bool {
	return true
}

// NeedsEventScheduler reports whether a host must drive this machine with
// Tick rather than Step alone.
//
// W3C SCXML 6.2: Step runs a macrostep and never drains the delayed-send
// scheduler nor ticks an invoked child, so a host that only ever calls it
// waits forever with nothing said. Same verdict the generate manifest
// publishes as needs_event_scheduler.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) NeedsEventScheduler() bool {
	return false
}

// NeedsDataModelInit returns whether the SM needs datamodel init.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) NeedsDataModelInit() bool {
	return true
}

func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) HasInvokeSupport() bool { return false }
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) HasChildTick() bool { return false }
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) HasFinalize() bool { return false }
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) HasAutoforward() bool { return false }
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) HasActiveStates() bool { return false }
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) GetActiveStates() []InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState { return nil }
// W3C SCXML 3.4: this machine keeps no active set — its configuration is the
// parent walk from the current state — so there is nothing for a restore to
// hand back here. sce.Engine.EnterAt reaches this only through HasActiveStates,
// which is false above; the method exists because the interface is one contract.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) SetActiveStates(_ []InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState) {}
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) HasExternalEventFlag() bool { return true }
// ExecuteFinalizeForChildEvent is a no-op (no finalize invokes).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) ExecuteFinalizeForChildEvent(_ *sce.EventWithMetadata[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent], _ *sce.Engine[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent]) {}
// ForwardToAutoforwardChildren is a no-op (no autoforward invokes).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) ForwardToAutoforwardChildren(_ string, _ sce.EventMetadata, _ *sce.Engine[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent]) {}

// PopulateEventMetadata stores pending event metadata (W3C SCXML 5.10).
// Note: event name is set separately via setCurrentEvent(), not from metadata.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) PopulateEventMetadata(meta *sce.EventMetadata) {
	p.pendingEventData = meta.Data
	p.pendingEventType = meta.EventType.String()
	p.pendingEventSendid = meta.SendID
	p.pendingEventOrigin = meta.Origin
	p.pendingEventOrigintype = meta.OriginType
	p.pendingEventInvokeid = meta.InvokeID
}

// LiftTypedPayload binds the dequeued event's typed `_event.data` view from
// the data it carries (NL→IR Item C1 Path A).
//
// The typed carrier PopulateEventMetadata reads is filled by one producer, the
// generated Raise<Event> inject seam. Every other producer — <send> with
// <param>, an invoke forwarding either way, autoforward, BasicHTTP, mesh —
// fills EventMetadata.Data, so the schema's fields are read out of that here.
// A refusal is returned for the engine to raise as error.execution, which is
// what W3C SCXML 3.13 gives for a guard that cannot be evaluated.
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) LiftTypedPayload(event InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent, meta *sce.EventMetadata) error {
	// This document lowered no typed guard, so no event carries a typed view.
	return nil
}

// ClearEventMetadata resets pending event metadata (W3C SCXML 5.10).
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) ClearEventMetadata() {
	p.pendingEventName = ""
	p.pendingEventData = ""
	p.pendingEventType = ""
	p.pendingEventSendid = ""
	p.pendingEventOrigin = ""
	p.pendingEventOrigintype = ""
	p.pendingEventInvokeid = ""
}



// ExecuteEntryActions enters one state (W3C SCXML 3.8): adds it to the
// configuration, runs its <onentry>, and its <initial> transition's content when
// its initial state is entered by default.
//line invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow.scxml:3
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) ExecuteEntryActions(state InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, engine *sce.Engine[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent], isDefaultEntry bool) {
	p.ensureScriptEngine()
	switch state {
	default:
		// No entry actions
	}
}

// ExecuteHistoryDefaultContent runs a <history>'s default transition content
// (W3C SCXML 3.10.2), after its parent's onentry (and after the parent's own
// <initial> content) when the history was taken with nothing recorded. The
// engine asks for it by the entry set's defaultHistoryContent answer; a history
// that restored what it recorded runs nothing.
//line invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow.scxml:3
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) ExecuteHistoryDefaultContent(history sce.HistoryID, engine *sce.Engine[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent]) {
	// W3C SCXML 3.10.2: no <history> in this document has default content.
}

// ExecuteExitActions exits one state (W3C SCXML 3.9): records its histories,
// removes it from the configuration, cancels its invocations and runs its
// <onexit>.
//line invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow.scxml:3
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) ExecuteExitActions(state InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, engine *sce.Engine[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent], configurationBeforeExit []InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState) {
	p.ensureScriptEngine()
	switch state {
	default:
		// No exit actions
	}
}



// BindCurrentEvent binds the event whose transitions are about to be selected as
// the _event their guards read (W3C SCXML 5.10) — before the first guard runs,
// and not for an eventless selection, which has no event of its own.
//line invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow.scxml:3
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) BindCurrentEvent(event InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent, engine *sce.Engine[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent]) {
	if event != InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventNull {
		// §scxml-B-2-8-1: the rung the payload got, handed to the engine
		// rather than dropped. This is the only frame that has both the
		// reading and the event it belongs to.
		engine.NotePayloadReading(event, p.setCurrentEvent(p.GetEventName(event)))
	}
}

// FirstEnabledTransition is Appendix D selectTransitions, the half only this
// document can answer: the first of state's own transitions, in document order,
// that event enables and whose guard holds. The engine walks the atomic states
// and their ancestors and keeps the ordered set; the null event asks for
// eventless transitions.
//line invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow.scxml:3
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) FirstEnabledTransition(state InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, event InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent, engine *sce.Engine[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent]) (sce.EnabledTransition[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, sce.HistoryID], bool) {
	switch state {
	case InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateReport:
		if event == InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventNull {
			if p.evaluateGuard(`(seen == "parent")`, engine) {
				return sce.EnabledTransition[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow[state][0],
					TransitionIndex: 0,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
		if event == InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventNull {
			if p.evaluateGuard(`(seen == "child")`, engine) {
				return sce.EnabledTransition[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow[state][1],
					TransitionIndex: 1,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
		if event == InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEventNull {
			{
				return sce.EnabledTransition[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfInvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadow[state][2],
					TransitionIndex: 2,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
	}
	return sce.EnabledTransition[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, sce.HistoryID]{}, false
}

// ExecuteTransitionContent runs one transition's executable content (W3C SCXML
// 3.13), between the microstep's exits and its entries.
//line invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow.scxml:3
func (p *InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowPolicy) ExecuteTransitionContent(source InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, transitionIndex int, engine *sce.Engine[InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowState, InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowEvent]) {
	p.ensureScriptEngine()
	switch source {
	case InvokeParamSeedsDeclaredChildDataSceSynthInvokeInvShadowStateReport:
		switch transitionIndex {
		case 0:
			//line invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow.scxml:10

	// W3C SCXML 6.2: send id="__send_0"
	{
		eventDataStr := ""
		_ = eventDataStr
	// W3C SCXML 6.2: Send to parent
	if p.ParentExternalQueue != nil {
		p.ParentExternalQueue <- sce.ParentEvent{Name: "seed.ok", Data: eventDataStr}
	}
	}

		case 1:
			//line invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow.scxml:13

	// W3C SCXML 6.2: send id="__send_1"
	{
		eventDataStr := ""
		_ = eventDataStr
	// W3C SCXML 6.2: Send to parent
	if p.ParentExternalQueue != nil {
		p.ParentExternalQueue <- sce.ParentEvent{Name: "seed.shadowed", Data: eventDataStr}
	}
	}

		case 2:
			//line invoke_param_seeds_declared_child_data__sce_synth_invoke__inv_shadow.scxml:16

	// W3C SCXML 6.2: send id="__send_2"
	{
		eventDataStr := ""
		_ = eventDataStr
	// W3C SCXML 6.2: Send to parent
	if p.ParentExternalQueue != nil {
		p.ParentExternalQueue <- sce.ParentEvent{Name: "seed.missing", Data: eventDataStr}
	}
	}

		}
	}
}
