// SCE-GENERATED — DO NOT EDIT
// source-hash: 484e7440f07c529b155abfa6f79282de908af5e2fc4314e70bd834573adce55b
// template-hash: 85660c1341dd8abf7326f61f4efe828117f6cbaf56814ccb03d3fd81b42e6ed0
// generated-at: 0


// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 [Author of input SCXML file]
//
// Generated by SCE Code Generator (Go backend)
// From: sce-build/tests/fixtures/host_processor/statechart_host_invoker.scxml
//
// This generated code is MIT licensed and may be freely used in any project.
// Runtime engine dependency (sce-go-runtime): LGPL-2.1-or-later WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// Full license: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE
// Generated Go state machine for `statechart_host_invoker`.
//
// Generated by SCE Code Generator (Go backend).
// Implements sce.StatePolicy with full transition logic,
// entry/exit actions, and event processing.


// SCE-MAP: statechart_host_invoker.scxml:26 :: _machine

package statechart_host_invoker

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	sce "github.com/newmassrael/sce-go-runtime"
)

// Ensure imports are used
var (
	_ = fmt.Sprintf
	_ = filepath.Join
	_ = strings.HasPrefix
	_ = time.Duration(0)
)

// ======================================================================
// State type (W3C SCXML 3.3)
// ======================================================================

type StatechartHostInvokerState int

const (
	StatechartHostInvokerStateDone StatechartHostInvokerState = 0
	StatechartHostInvokerStateInvoking StatechartHostInvokerState = 1
)

func (s StatechartHostInvokerState) String() string {
	switch s {
	case StatechartHostInvokerStateDone:
		return "done"
	case StatechartHostInvokerStateInvoking:
		return "invoking"
	}
	return "unknown"
}

// StatechartHostInvokerStateFromName is the read half of the pair above — a state
// id back into the state it names (W3C SCXML 3.3).
//
// A host that persists where a machine was has to write it down as TEXT: the
// constants above are a build artefact of one binary, and the process that
// resumes is a different one. String publishes the name and this reads it back,
// which is what lets a journal survive its own record and reach
// sce.Engine.EnterAt.
//
// The second return is false for a name this document does not declare. A name
// guessed at rather than refused is how a restore reaches a configuration
// nobody recorded — and the refusal is what makes a typo in a journal a
// reported failure instead of a machine quietly somewhere else.
//
// Emitted from the same loop over the document's states as String, so the two
// age together.
func StatechartHostInvokerStateFromName(name string) (StatechartHostInvokerState, bool) {
	switch name {
	case "done":
		return StatechartHostInvokerStateDone, true
	case "invoking":
		return StatechartHostInvokerStateInvoking, true
	}
	var zero StatechartHostInvokerState
	return zero, false
}

// StatechartHostInvokerAllStates is every state this document declares, in the
// order the constants above are issued.
//
// Emitted from the same loop, so a walk over it is a walk over the document
// rather than over a list somebody maintained beside it — a test that spells
// its own list goes on passing when the document grows a state.
var StatechartHostInvokerAllStates = []StatechartHostInvokerState{
	StatechartHostInvokerStateDone,
	StatechartHostInvokerStateInvoking,
}

// ======================================================================
// Event type (W3C SCXML 3.12)
// ======================================================================

type StatechartHostInvokerEvent int

const (
	StatechartHostInvokerEventDoneInvokeProbe StatechartHostInvokerEvent = 0
	StatechartHostInvokerEventErrorExecution StatechartHostInvokerEvent = 1
	StatechartHostInvokerEventLeave StatechartHostInvokerEvent = 2
	// W3C SCXML 3.13: Sentinel for eventless transition dispatch
	StatechartHostInvokerEventNull StatechartHostInvokerEvent = 3
)

func (e StatechartHostInvokerEvent) String() string {
	switch e {
	case StatechartHostInvokerEventDoneInvokeProbe:
		return "done.invoke.probe"
	case StatechartHostInvokerEventErrorExecution:
		return "error.execution"
	case StatechartHostInvokerEventLeave:
		return "leave"
	case StatechartHostInvokerEventNull:
		return ""
	}
	return "unknown"
}

// ======================================================================
// Policy struct
// ======================================================================

type StatechartHostInvokerPolicy struct {
	// W3C SCXML 3.13: Last transition metadata
	lastTransitionIsInternal  bool
	lastTransitionIsTargetless bool
	lastTransitionSourceState StatechartHostInvokerState
	// W3C SCXML 3.13: Transition action tracking
	lastTransitionIndex   int
	hasTransitionActions   bool
	// W3C SCXML 5.10.1: External event flag
	nextEventIsExternal bool
	pendingEventName string
	pendingEventData string
	pendingEventType string
	pendingEventSendid string
	pendingEventOrigin string
	pendingEventOrigintype string
	pendingEventInvokeid string
	// W3C SCXML 5.10: Session ID
	SessionID string
	// W3C SCXML B.1: Script engine handle (per-instance, Path B+ Q1=(d) Go=interface ref)
	ScriptEngine sce.IScriptEngine
	scriptEngineInitialized bool
	// W3C SCXML C.2.3: inbound BasicHTTP endpoint serving this machine,
	// declared by the deployment before Initialize(). The address belongs to
	// whoever runs the listener, so the machine takes it from here rather than
	// guessing one. Empty means no such endpoint is deployed, and no BasicHTTP
	// entry is published in _ioprocessors.
	BasicHTTPAccessURI string
	pendingInvokes []sce.PendingInvoke[StatechartHostInvokerState]
	activeInvokes  map[string]*sce.ChildSession
	// W3C SCXML 6.4: Parent communication
	ParentExternalQueue chan sce.ParentEvent
	InvokeID           string
	ChildSessionID     string
	// §scxml-6.4.3: invoke param VALUES staged by the parent, applied after
	// this machine's datamodel init so they override its `<data>` defaults.
	pendingParams      map[string]interface{}
}

// NewStatechartHostInvokerPolicy creates a new policy with default values.
func NewStatechartHostInvokerPolicy() StatechartHostInvokerPolicy {
	return StatechartHostInvokerPolicy{
		lastTransitionSourceState: StatechartHostInvokerStateInvoking,
		pendingInvokes: make([]sce.PendingInvoke[StatechartHostInvokerState], 0),
		activeInvokes:  make(map[string]*sce.ChildSession),
	}
}

// Started reports what the `started` datamodel variable is holding now
// (W3C SCXML 5.3).
//
// The live value, not the authored one: `<assign>` writes into the session, so
// a reader frozen at generation time would answer the document's literal for
// the whole run. The second return value is false when the machine cannot
// answer — no script engine is set, the session is not initialised yet,
// `started` was assigned a value of another type, or the engine refused.
func (p *StatechartHostInvokerPolicy) Started() (int64, bool) {
	return sce.ReadDatamodelInt(p.ScriptEngine, p.SessionID, "started")
}

// Refused reports what the `refused` datamodel variable is holding now
// (W3C SCXML 5.3).
//
// The live value, not the authored one: `<assign>` writes into the session, so
// a reader frozen at generation time would answer the document's literal for
// the whole run. The second return value is false when the machine cannot
// answer — no script engine is set, the session is not initialised yet,
// `refused` was assigned a value of another type, or the engine refused.
func (p *StatechartHostInvokerPolicy) Refused() (int64, bool) {
	return sce.ReadDatamodelInt(p.ScriptEngine, p.SessionID, "refused")
}

// Ended reports what the `ended` datamodel variable is holding now
// (W3C SCXML 5.3).
//
// The live value, not the authored one: `<assign>` writes into the session, so
// a reader frozen at generation time would answer the document's literal for
// the whole run. The second return value is false when the machine cannot
// answer — no script engine is set, the session is not initialised yet,
// `ended` was assigned a value of another type, or the engine refused.
func (p *StatechartHostInvokerPolicy) Ended() (int64, bool) {
	return sce.ReadDatamodelInt(p.ScriptEngine, p.SessionID, "ended")
}

// Entered reports what the `entered` datamodel variable is holding now
// (W3C SCXML 5.3).
//
// The live value, not the authored one: `<assign>` writes into the session, so
// a reader frozen at generation time would answer the document's literal for
// the whole run. The second return value is false when the machine cannot
// answer — no script engine is set, the session is not initialised yet,
// `entered` was assigned a value of another type, or the engine refused.
func (p *StatechartHostInvokerPolicy) Entered() (int64, bool) {
	return sce.ReadDatamodelInt(p.ScriptEngine, p.SessionID, "entered")
}




// ensureScriptEngine lazily initializes the script engine session.
//
// Engine DI Parity RFC: panics if ScriptEngine was not set on the policy
// before Initialize() — mirrors Kotlin's mandatory constructor parameter
// contract. Silent no-op would otherwise turn missed injection into a
// hidden runtime regression (every <assign>/<log>/guard becomes a no-op
// and the SM walks to its default-state final without diagnostic).
func (p *StatechartHostInvokerPolicy) ensureScriptEngine() {
	if p.scriptEngineInitialized {
		return
	}
	engine := p.ScriptEngine
	if engine == nil {
		panic("StatechartHostInvokerPolicy: ScriptEngine field must be set before Initialize()")
	}
	sessionID := p.SessionID
	if sessionID == "" {
		sessionID = sce.GenerateSessionID()
		p.SessionID = sessionID
	}
	if !engine.HasSession(sessionID) {
		_ = engine.CreateSession(sessionID)
	}
	// W3C SCXML C.1.1 / C.2.3: the _ioprocessors entries come from the same
	// helper every other backend uses, so a machine reads the same entry names
	// and the same addresses whichever one runs it.
	_ = engine.SetupSystemVariables(sessionID, "statechart_host_invoker",
		sce.BuildIoProcessors(sessionID, p.BasicHTTPAccessURI))
	p.scriptEngineInitialized = true
}

// InitializeDataModel sets up datamodel via script engine (W3C SCXML 5.3).
func (p *StatechartHostInvokerPolicy) InitializeDataModel(eng *sce.Engine[StatechartHostInvokerState, StatechartHostInvokerEvent]) {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	sessionID := p.SessionID

	// W3C SCXML 5.3: Initialize _sessionid
	_ = engine.SetVariable(sessionID, "_sessionid", sessionID)

	// W3C SCXML 5.3: Initialize _name
	_ = engine.SetVariable(sessionID, "_name", "statechart_host_invoker")

	// W3C SCXML 5.2.2: Initialize global datamodel variables
	// W3C SCXML 5.2/5.3: Initialize started from expr="0"
	{
		result, err := engine.EvaluateExpression(sessionID, `0`)
		if err == nil {
			_ = engine.SetVariable(sessionID, "started", result)
		} else {
			eng.Raise(sce.NewPlatformError(StatechartHostInvokerEventErrorExecution, "<data id='started'> expr failed to evaluate"))
			_ = engine.SetVariable(sessionID, "started", nil)
		}
	}
	// W3C SCXML 5.2/5.3: Initialize refused from expr="0"
	{
		result, err := engine.EvaluateExpression(sessionID, `0`)
		if err == nil {
			_ = engine.SetVariable(sessionID, "refused", result)
		} else {
			eng.Raise(sce.NewPlatformError(StatechartHostInvokerEventErrorExecution, "<data id='refused'> expr failed to evaluate"))
			_ = engine.SetVariable(sessionID, "refused", nil)
		}
	}
	// W3C SCXML 5.2/5.3: Initialize ended from expr="0"
	{
		result, err := engine.EvaluateExpression(sessionID, `0`)
		if err == nil {
			_ = engine.SetVariable(sessionID, "ended", result)
		} else {
			eng.Raise(sce.NewPlatformError(StatechartHostInvokerEventErrorExecution, "<data id='ended'> expr failed to evaluate"))
			_ = engine.SetVariable(sessionID, "ended", nil)
		}
	}
	// W3C SCXML 5.2/5.3: Initialize entered from expr="0"
	{
		result, err := engine.EvaluateExpression(sessionID, `0`)
		if err == nil {
			_ = engine.SetVariable(sessionID, "entered", result)
		} else {
			eng.Raise(sce.NewPlatformError(StatechartHostInvokerEventErrorExecution, "<data id='entered'> expr failed to evaluate"))
			_ = engine.SetVariable(sessionID, "entered", nil)
		}
	}



	// §scxml-6.4.3: apply the invoke params the parent staged — overriding the
	// `<data>` default this block just seeded, and only for a name the child
	// declares ("if the names do not match, the Processor MUST NOT add the
	// value ... to the invoked session's data model"). `HasVariable` is that
	// filter, and it is this channel's only copy of the rule.
	if len(p.pendingParams) > 0 {
		for paramName, paramValue := range p.pendingParams {
			if engine.HasVariable(sessionID, paramName) {
				_ = engine.SetVariable(sessionID, paramName, paramValue)
			}
		}
		p.pendingParams = nil
	}
}

// evaluateGuard evaluates a guard condition via script engine.
// W3C SCXML 4.3.2: If a condition expression cannot be evaluated, the processor
// MUST treat it as false and MUST raise error.execution.
func (p *StatechartHostInvokerPolicy) evaluateGuard(guard string, eng *sce.Engine[StatechartHostInvokerState, StatechartHostInvokerEvent]) bool {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	result, err := engine.EvaluateExpression(p.SessionID, guard)
	if err != nil {
		eng.Raise(sce.NewPlatformError(StatechartHostInvokerEventErrorExecution, "a <transition> cond failed to evaluate"))
		return false
	}
	return sce.ScriptToBool(result)
}

// executeScript executes a script block via script engine.
func (p *StatechartHostInvokerPolicy) executeScript(script string) error {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	return engine.ExecuteScript(p.SessionID, script)
}

// setCurrentEvent binds _event system variable (W3C SCXML 5.10) and answers
// which rung of §scxml-B-2-8-1 the payload got, because the binding is the
// only place that knows.
//
// This used to be `_ = engine.SetCurrentEvent(...)`: the ladder decided
// between a DOM, a value and a space-normalized string, and the decision was
// dropped one line later. A payload that announced structure and would not
// parse therefore reached the document as raw characters, every
// _event.data.<field> read empty, and nothing anywhere could say so — see
// sce.PayloadReading.
func (p *StatechartHostInvokerPolicy) setCurrentEvent(name string) sce.PayloadReading {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	data := p.pendingEventData
	eventType := p.pendingEventType
	sendID := p.pendingEventSendid
	// W3C SCXML C.1: `_event.origin` is the sender's published
	// `_ioprocessors` location, not its bare session id — and this is the one
	// place that publishes `_event` to the document, so this is where the id
	// becomes a location. The engine keeps the bare id in
	// `EventMetadata.Origin` because its session-keyed lookups (<finalize>
	// dispatch, cancelled-invoke filtering) match on it; converting at the
	// raise would make one value serve two consumers that need different
	// spellings. The conversion itself lives in `sce.PublishedOrigin`, the
	// port of the `IOProcessorHelper::publishedOrigin` the C++ engines share:
	// a second spelling of the rule is how the backends would stop agreeing.
	origin := sce.PublishedOrigin(p.pendingEventOrigin)
	originType := p.pendingEventOrigintype
	invokeID := p.pendingEventInvokeid
	reading, err := engine.SetCurrentEvent(p.SessionID, sce.SetCurrentEventArgs{
		Name:       name,
		Data:       data,
		Type:       eventType,
		SendID:     sendID,
		Origin:     origin,
		OriginType: originType,
		InvokeID:   invokeID,
	})
	if err != nil {
		// An engine that could not bind _event at all has a larger problem
		// than an unreadable payload, and reporting PayloadUndecodable for it
		// would point a host at the wrong thing.
		return sce.PayloadAbsent
	}
	return reading
}

// assignVariable assigns a value to a datamodel variable via script engine.
func (p *StatechartHostInvokerPolicy) assignVariable(location, expr string) error {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	script := location + " = " + expr
	return engine.ExecuteScript(p.SessionID, script)
}

// getVariable reads a datamodel variable from the script engine.
func (p *StatechartHostInvokerPolicy) getVariable(name string) interface{} {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	result, err := engine.GetVariable(p.SessionID, name)
	if err != nil {
		return nil
	}
	return result
}

// SetParamValueInScriptEngine stores an invoke param's VALUE for deferred
// application after datamodel init (§scxml-6.4.3).
//
// Params are applied at the end of InitializeDataModel, overriding the
// `<data>` default only for names the child declares. The value crosses as a
// value: this took the parent's value rendered as Lua source and
// re-evaluated it here until 2026-08-21, which survived every value a test
// had tried and lost the ones Lua cannot spell — `ToScriptLiteral` renders a
// non-finite number as `+Inf`, which is not a Lua expression, so an
// `<invoke>` `<param expr="1/0"/>` arrived as nothing at all.
func (p *StatechartHostInvokerPolicy) SetParamValueInScriptEngine(name string, value interface{}) {
	if p.pendingParams == nil {
		p.pendingParams = make(map[string]interface{})
	}
	p.pendingParams[name] = value
}


// ExecutePendingInvokes starts deferred child state machines (W3C SCXML 6.4).
// Port of Rust do_execute_pending_invokes().
func (p *StatechartHostInvokerPolicy) ExecutePendingInvokes(engine *sce.Engine[StatechartHostInvokerState, StatechartHostInvokerEvent]) {
	if len(p.pendingInvokes) == 0 {
		return
	}

	// W3C SCXML 6.4: Copy-and-clear to prevent iterator invalidation
	invokesToExecute := make([]sce.PendingInvoke[StatechartHostInvokerState], len(p.pendingInvokes))
	copy(invokesToExecute, p.pendingInvokes)
	p.pendingInvokes = p.pendingInvokes[:0]

	for _, pending := range invokesToExecute {
		if strings.Contains(pending.InvokeID, ".probe") {
			// W3C SCXML 6.4.1: the host declared this `type`, so START the
			// invocation rather than refusing it. The id handed over is the
			// DOCUMENT's, not the per-instance one the pending queue carries:
			// `done.invoke.<id>` is the name the author wrote a transition
			// for, so it is the name the host must answer on.
			hostInvokeParams := map[string][]string{}
			hostInvokeParams["within"] = append(hostInvokeParams["within"], "2500")
			if !engine.PerformHostInvoke(sce.HostInvokeRequest{
				ProcessorType: "x-sce-host",
				InvokeID:      "probe",
				Src:           "pane://turn",
				Params:        hostInvokeParams,
				Content:       "",
			}) {
				// W3C SCXML 6.4.1: declared but no invoker registered. The
				// document asked for a process to be run and none was, which
				// is the same fact as an unsupported type — so the same
				// event, rather than a silence that reads as started.
				engine.Raise(sce.NewPlatformError(StatechartHostInvokerEventErrorExecution, "<invoke> names an invoker the host declared but never registered"))
			}
			continue
		}
	}
}

// TickChildren ticks child state machines (W3C SCXML 6.4).
// Port of Rust do_tick_children().
func (p *StatechartHostInvokerPolicy) TickChildren(engine *sce.Engine[StatechartHostInvokerState, StatechartHostInvokerEvent]) {
}




// ── Child engine wrappers (implement sce.ChildEngine interface) ──



// ======================================================================
// StatePolicy interface implementation
// ======================================================================

// InitialState returns the initial state (W3C SCXML 3.3).
func (p *StatechartHostInvokerPolicy) InitialState() StatechartHostInvokerState {
	return StatechartHostInvokerStateInvoking
}

// IsFinalState returns true if state is a <final> state (W3C SCXML 3.7).
func (p *StatechartHostInvokerPolicy) IsFinalState(state StatechartHostInvokerState) bool {
	switch state {
	}
	return false
}

// GetParent returns the parent of state, or (zero, false) if root (W3C SCXML 3.3).
func (p *StatechartHostInvokerPolicy) GetParent(state StatechartHostInvokerState) (StatechartHostInvokerState, bool) {
	switch state {
	}
	return 0, false
}

// IsCompoundState returns true if state has children (W3C SCXML 3.3).
func (p *StatechartHostInvokerPolicy) IsCompoundState(state StatechartHostInvokerState) bool {
	switch state {
	}
	return false
}

func (p *StatechartHostInvokerPolicy) IsParallelState(_ StatechartHostInvokerState) bool { return false }
func (p *StatechartHostInvokerPolicy) GetParallelRegions(_ StatechartHostInvokerState) []StatechartHostInvokerState { return nil }

// IsDescendantOf returns true if desc is a descendant of anc (W3C SCXML 3.12).
func (p *StatechartHostInvokerPolicy) IsDescendantOf(desc, anc StatechartHostInvokerState) bool {
	current := desc
	for {
		parent, ok := p.GetParent(current)
		if !ok {
			return false
		}
		if parent == anc {
			return true
		}
		current = parent
	}
}

// GetDocumentOrder returns the document order index (W3C SCXML Appendix D).
func (p *StatechartHostInvokerPolicy) GetDocumentOrder(state StatechartHostInvokerState) int {
	switch state {
	case StatechartHostInvokerStateDone:
		return 1
	case StatechartHostInvokerStateInvoking:
		return 0
	}
	return -1
}

// GetEventName returns the string name of an event (W3C SCXML 3.12).
func (p *StatechartHostInvokerPolicy) GetEventName(event StatechartHostInvokerEvent) string {
	return event.String()
}

// GetEventFromName looks up an event by name (W3C SCXML 3.12).
func (p *StatechartHostInvokerPolicy) GetEventFromName(name string) (StatechartHostInvokerEvent, bool) {
	switch name {
	case "done.invoke.probe":
		return StatechartHostInvokerEventDoneInvokeProbe, true
	case "error.execution":
		return StatechartHostInvokerEventErrorExecution, true
	case "leave":
		return StatechartHostInvokerEventLeave, true
	}
	return StatechartHostInvokerEventNull, false
}

// GetStateName returns the string name of a state (W3C SCXML 3.3).
func (p *StatechartHostInvokerPolicy) GetStateName(state StatechartHostInvokerState) string {
	return state.String()
}

// GetStateFromName reads a state id back into the state it names (W3C SCXML 3.3).
// The reverse of GetStateName, and what turns a host's recorded configuration
// back into the argument sce.Engine.EnterAt takes.
func (p *StatechartHostInvokerPolicy) GetStateFromName(name string) (StatechartHostInvokerState, bool) {
	return StatechartHostInvokerStateFromName(name)
}

// NullEvent returns the sentinel for eventless transition dispatch (W3C SCXML 3.13).
func (p *StatechartHostInvokerPolicy) NullEvent() StatechartHostInvokerEvent {
	return StatechartHostInvokerEventNull
}

// GetInitialChildren returns initial children of a compound state (W3C SCXML 3.6).
func (p *StatechartHostInvokerPolicy) GetInitialChildren(state StatechartHostInvokerState) []StatechartHostInvokerState {
	switch state {
	}
	return nil
}

// LastTransitionIsInternal returns the internal transition flag (W3C SCXML 3.13).
func (p *StatechartHostInvokerPolicy) LastTransitionIsInternal() bool {
	return p.lastTransitionIsInternal
}

// SetLastTransitionIsInternal sets the internal transition flag.
func (p *StatechartHostInvokerPolicy) SetLastTransitionIsInternal(value bool) {
	p.lastTransitionIsInternal = value
}

// LastTransitionIsTargetless returns the targetless transition flag (W3C SCXML 3.13).
func (p *StatechartHostInvokerPolicy) LastTransitionIsTargetless() bool {
	return p.lastTransitionIsTargetless
}

// SetLastTransitionIsTargetless sets the targetless transition flag.
func (p *StatechartHostInvokerPolicy) SetLastTransitionIsTargetless(value bool) {
	p.lastTransitionIsTargetless = value
}

// LastTransitionSourceState returns the source state of the last transition.
func (p *StatechartHostInvokerPolicy) LastTransitionSourceState() StatechartHostInvokerState {
	return p.lastTransitionSourceState
}

// SetLastTransitionSourceState sets the source state of the last transition.
func (p *StatechartHostInvokerPolicy) SetLastTransitionSourceState(state StatechartHostInvokerState) {
	p.lastTransitionSourceState = state
}


// SetNextEventIsExternal sets the external event flag (W3C SCXML 5.10.1).
func (p *StatechartHostInvokerPolicy) SetNextEventIsExternal(value bool) {
	p.nextEventIsExternal = value
}

// HasParallelStates returns whether the SM has parallel states.
func (p *StatechartHostInvokerPolicy) HasParallelStates() bool {
	return false
}

// NeedsScriptEngine returns whether the SM needs a script engine.
func (p *StatechartHostInvokerPolicy) NeedsScriptEngine() bool {
	return true
}

// NeedsEventScheduler reports whether a host must drive this machine with
// Tick rather than Step alone.
//
// W3C SCXML 6.2: Step runs a macrostep and never drains the delayed-send
// scheduler nor ticks an invoked child, so a host that only ever calls it
// waits forever with nothing said. Same verdict the generate manifest
// publishes as needs_event_scheduler.
func (p *StatechartHostInvokerPolicy) NeedsEventScheduler() bool {
	return false
}

// NeedsDataModelInit returns whether the SM needs datamodel init.
func (p *StatechartHostInvokerPolicy) NeedsDataModelInit() bool {
	return true
}

// HasInvokeSupport returns true for invoke-capable SMs.
func (p *StatechartHostInvokerPolicy) HasInvokeSupport() bool { return true }
func (p *StatechartHostInvokerPolicy) HasChildTick() bool { return false }
func (p *StatechartHostInvokerPolicy) HasFinalize() bool { return false }
func (p *StatechartHostInvokerPolicy) HasAutoforward() bool { return false }
func (p *StatechartHostInvokerPolicy) HasActiveStates() bool { return false }
func (p *StatechartHostInvokerPolicy) GetActiveStates() []StatechartHostInvokerState { return nil }
// W3C SCXML 3.4: this machine keeps no active set — its configuration is the
// parent walk from the current state — so there is nothing for a restore to
// hand back here. sce.Engine.EnterAt reaches this only through HasActiveStates,
// which is false above; the method exists because the interface is one contract.
func (p *StatechartHostInvokerPolicy) SetActiveStates(_ []StatechartHostInvokerState) {}
func (p *StatechartHostInvokerPolicy) HasExternalEventFlag() bool { return true }
// GetInitialOrHistoryChild returns the initial child considering history (W3C SCXML 3.11).
func (p *StatechartHostInvokerPolicy) GetInitialOrHistoryChild(state StatechartHostInvokerState) StatechartHostInvokerState {
	children := p.GetInitialChildren(state)
	if len(children) > 0 {
		return children[0]
	}
	return state
}
// ExecuteFinalizeForChildEvent is a no-op (no finalize invokes).
func (p *StatechartHostInvokerPolicy) ExecuteFinalizeForChildEvent(_ *sce.EventWithMetadata[StatechartHostInvokerEvent], _ *sce.Engine[StatechartHostInvokerState, StatechartHostInvokerEvent]) {}
// ForwardToAutoforwardChildren is a no-op (no autoforward invokes).
func (p *StatechartHostInvokerPolicy) ForwardToAutoforwardChildren(_ string, _ sce.EventMetadata, _ *sce.Engine[StatechartHostInvokerState, StatechartHostInvokerEvent]) {}

// PopulateEventMetadata stores pending event metadata (W3C SCXML 5.10).
// Note: event name is set separately via setCurrentEvent(), not from metadata.
func (p *StatechartHostInvokerPolicy) PopulateEventMetadata(meta *sce.EventMetadata) {
	p.pendingEventData = meta.Data
	p.pendingEventType = meta.EventType.String()
	p.pendingEventSendid = meta.SendID
	p.pendingEventOrigin = meta.Origin
	p.pendingEventOrigintype = meta.OriginType
	p.pendingEventInvokeid = meta.InvokeID
}

// ClearEventMetadata resets pending event metadata (W3C SCXML 5.10).
func (p *StatechartHostInvokerPolicy) ClearEventMetadata() {
	p.pendingEventName = ""
	p.pendingEventData = ""
	p.pendingEventType = ""
	p.pendingEventSendid = ""
	p.pendingEventOrigin = ""
	p.pendingEventOrigintype = ""
	p.pendingEventInvokeid = ""
}




// ExecuteEntryActions executes onentry actions for a state (W3C SCXML 3.8).
//line statechart_host_invoker.scxml:26
func (p *StatechartHostInvokerPolicy) ExecuteEntryActions(state StatechartHostInvokerState, engine *sce.Engine[StatechartHostInvokerState, StatechartHostInvokerEvent], pathChild *StatechartHostInvokerState) {
	// Only a `<parallel>` machine descends into defaults here, so a machine
	// without one has nothing to tell an ancestor entry from a target entry.
	_ = pathChild
	p.ensureScriptEngine()
	switch state {
	case StatechartHostInvokerStateDone:
		//line statechart_host_invoker.scxml:56
		// W3C SCXML 3.8: onentry block 0 (break on error stops subsequent actions)
		for actionBlock0 := 0; actionBlock0 < 1; actionBlock0++ {
			_ = actionBlock0

	// W3C SCXML 5.3: <assign location="ended" expr="ended + 1">
	if err := p.assignVariable(`ended`, `_scxml_add(ended, 1)`); err != nil {
		engine.Raise(sce.NewPlatformError(StatechartHostInvokerEventErrorExecution, "<assign> to 'ended' failed"))
		break
	}

		}
	case StatechartHostInvokerStateInvoking:
		//line statechart_host_invoker.scxml:36
		// W3C SCXML 3.8: onentry block 0 (break on error stops subsequent actions)
		for actionBlock0 := 0; actionBlock0 < 1; actionBlock0++ {
			_ = actionBlock0

	// W3C SCXML 5.3: <assign location="entered" expr="entered + 1">
	if err := p.assignVariable(`entered`, `_scxml_add(entered, 1)`); err != nil {
		engine.Raise(sce.NewPlatformError(StatechartHostInvokerEventErrorExecution, "<assign> to 'entered' failed"))
		break
	}

		}
		// W3C SCXML 6.4.1: `type` names no processor this platform implements.
		// Defer only — the error.execution raise happens in
		// ExecutePendingInvokes, so §scxml-6.4 ordering holds and
		// CancelInvokesForState drops the entry if the state exits first.
		{
			generatedInvokeID := fmt.Sprintf("%s.%d.probe", "invoking", sce.NextInvokeCounter())
			sce.DeferInvoke(&p.pendingInvokes, sce.PendingInvoke[StatechartHostInvokerState]{
				InvokeID: generatedInvokeID,
				State:    StatechartHostInvokerStateInvoking,
			})
		}
	default:
		// No entry actions
	}
}

// ExecuteExitActions executes onexit actions for a state (W3C SCXML 3.9).
//line statechart_host_invoker.scxml:26
func (p *StatechartHostInvokerPolicy) ExecuteExitActions(state StatechartHostInvokerState, engine *sce.Engine[StatechartHostInvokerState, StatechartHostInvokerEvent], preTransitionActive []StatechartHostInvokerState) {
	p.ensureScriptEngine()
	// W3C SCXML 6.4: Cancel pending invokes and cleanup active children on state exit
	switch state {
	case StatechartHostInvokerStateInvoking:
		sce.CancelInvokesForState(&p.pendingInvokes, StatechartHostInvokerStateInvoking)
		// W3C SCXML 6.4: the host's invocation ends with the state that
		// started it. Unconditional here: the engine knows whether this one
		// ever started and stays silent when it did not, so the emitted chain
		// does not need its own bookkeeping.
		engine.CancelHostInvoke("x-sce-host", "probe")
	default:
	}
	switch state {
	default:
		// No exit actions
	}
}

// ProcessTransition evaluates guards and takes a matching transition (W3C SCXML 3.13).
// Returns true if a transition was taken.
//line statechart_host_invoker.scxml:26
func (p *StatechartHostInvokerPolicy) ProcessTransition(currentState *StatechartHostInvokerState, event StatechartHostInvokerEvent, engine *sce.Engine[StatechartHostInvokerState, StatechartHostInvokerEvent]) bool {
	// W3C SCXML 5.10: Bind _event system variable for guard evaluation
	if event != StatechartHostInvokerEventNull {
		// §scxml-B-2-8-1: the rung the payload got, handed to the engine
		// rather than dropped. This is the only frame that has both the
		// reading and the event it belongs to.
		engine.NotePayloadReading(event, p.setCurrentEvent(p.GetEventName(event)))
	}

	// W3C SCXML 3.12: Try transitions in current state first
	if p.tryTransitionInState(*currentState, event, currentState, engine) {
		return true
	}


	return false
}


// tryTransitionInState checks transitions for a single state.
//line statechart_host_invoker.scxml:26
func (p *StatechartHostInvokerPolicy) tryTransitionInState(checkState StatechartHostInvokerState, event StatechartHostInvokerEvent, currentState *StatechartHostInvokerState, engine *sce.Engine[StatechartHostInvokerState, StatechartHostInvokerEvent]) bool {
	switch checkState {
	case StatechartHostInvokerStateInvoking:
		// W3C SCXML 5.9.3: Direct enum comparison
		if event == StatechartHostInvokerEventDoneInvokeProbe {
			p.lastTransitionIsInternal = false
			p.lastTransitionIsTargetless = true
			p.lastTransitionSourceState = StatechartHostInvokerStateInvoking
			p.lastTransitionIndex = 0
			p.hasTransitionActions = true
			return true
		}
		// W3C SCXML 5.9.3: Direct enum comparison
		if event == StatechartHostInvokerEventErrorExecution {
			p.lastTransitionIsInternal = false
			p.lastTransitionIsTargetless = true
			p.lastTransitionSourceState = StatechartHostInvokerStateInvoking
			p.lastTransitionIndex = 1
			p.hasTransitionActions = true
			return true
		}
		// W3C SCXML 5.9.3: Direct enum comparison
		if event == StatechartHostInvokerEventLeave {
			*currentState = StatechartHostInvokerStateDone
			p.lastTransitionIsInternal = false
			p.lastTransitionIsTargetless = false
			p.lastTransitionSourceState = StatechartHostInvokerStateInvoking
			p.lastTransitionIndex = 2
			p.hasTransitionActions = false
			return true
		}
	}
	return false
}

// ExecuteTransitionActions executes actions for the last taken transition (W3C SCXML 3.13).
//line statechart_host_invoker.scxml:26
func (p *StatechartHostInvokerPolicy) ExecuteTransitionActions(engine *sce.Engine[StatechartHostInvokerState, StatechartHostInvokerEvent]) {
	p.ensureScriptEngine()
	if !p.hasTransitionActions {
		return
	}
	source := p.lastTransitionSourceState
	idx := p.lastTransitionIndex
	if source == StatechartHostInvokerStateInvoking && idx == 0 {
		//line statechart_host_invoker.scxml:45

	// W3C SCXML 5.3: <assign location="started" expr="started + 1">
	if err := p.assignVariable(`started`, `_scxml_add(started, 1)`); err != nil {
		engine.Raise(sce.NewPlatformError(StatechartHostInvokerEventErrorExecution, "<assign> to 'started' failed"))
	}

		return
	}
	if source == StatechartHostInvokerStateInvoking && idx == 1 {
		//line statechart_host_invoker.scxml:48

	// W3C SCXML 5.3: <assign location="refused" expr="refused + 1">
	if err := p.assignVariable(`refused`, `_scxml_add(refused, 1)`); err != nil {
		engine.Raise(sce.NewPlatformError(StatechartHostInvokerEventErrorExecution, "<assign> to 'refused' failed"))
	}

		return
	}
}
