// SCE-GENERATED — DO NOT EDIT
// source-hash: 23347f5c092342ad5655a09f8c78eecec8de3c0705a0affd88f1ecbcd658f869


// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 [Author of input SCXML file]
//
// Generated by SCE Code Generator (Go backend)
// From: integration_resources/targetless_transition_completes_macrostep/targetless_transition_completes_macrostep.scxml
//
// This generated code is MIT licensed and may be freely used in any project.
// Runtime engine dependency (sce-go-runtime): LGPL-2.1-or-later WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// Full license: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE
// Generated Go state machine for `targetless_transition_completes_macrostep`.
//
// Generated by SCE Code Generator (Go backend).
// Implements sce.StatePolicy with full transition logic,
// entry/exit actions, and event processing.


// SCE-MAP: targetless_transition_completes_macrostep.scxml:51 :: _machine

package targetless_transition_completes_macrostep

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	sce "github.com/newmassrael/sce-go-runtime"
)

// Ensure imports are used
var (
	_ = fmt.Sprintf
	_ = filepath.Join
	_ = strings.HasPrefix
	_ = time.Duration(0)
)

// ======================================================================
// State type (W3C SCXML 3.3)
// ======================================================================

type TargetlessTransitionCompletesMacrostepState int

const (
	TargetlessTransitionCompletesMacrostepStateIdle TargetlessTransitionCompletesMacrostepState = 0
	TargetlessTransitionCompletesMacrostepStateRecycled TargetlessTransitionCompletesMacrostepState = 1
	TargetlessTransitionCompletesMacrostepStateSettled TargetlessTransitionCompletesMacrostepState = 2
)

func (s TargetlessTransitionCompletesMacrostepState) String() string {
	switch s {
	case TargetlessTransitionCompletesMacrostepStateIdle:
		return "idle"
	case TargetlessTransitionCompletesMacrostepStateRecycled:
		return "recycled"
	case TargetlessTransitionCompletesMacrostepStateSettled:
		return "settled"
	}
	return "unknown"
}

// TargetlessTransitionCompletesMacrostepStateFromName is the read half of the pair above — a state
// id back into the state it names (W3C SCXML 3.3).
//
// A host that persists where a machine was has to write it down as TEXT: the
// constants above are a build artefact of one binary, and the process that
// resumes is a different one. String publishes the name and this reads it back,
// which is what lets a journal survive its own record and reach
// sce.Engine.EnterAt.
//
// The second return is false for a name this document does not declare. A name
// guessed at rather than refused is how a restore reaches a configuration
// nobody recorded — and the refusal is what makes a typo in a journal a
// reported failure instead of a machine quietly somewhere else.
//
// Emitted from the same loop over the document's states as String, so the two
// age together.
func TargetlessTransitionCompletesMacrostepStateFromName(name string) (TargetlessTransitionCompletesMacrostepState, bool) {
	switch name {
	case "idle":
		return TargetlessTransitionCompletesMacrostepStateIdle, true
	case "recycled":
		return TargetlessTransitionCompletesMacrostepStateRecycled, true
	case "settled":
		return TargetlessTransitionCompletesMacrostepStateSettled, true
	}
	var zero TargetlessTransitionCompletesMacrostepState
	return zero, false
}

// TargetlessTransitionCompletesMacrostepAllStates is every state this document declares, in the
// order the constants above are issued.
//
// Emitted from the same loop, so a walk over it is a walk over the document
// rather than over a list somebody maintained beside it — a test that spells
// its own list goes on passing when the document grows a state.
var TargetlessTransitionCompletesMacrostepAllStates = []TargetlessTransitionCompletesMacrostepState{
	TargetlessTransitionCompletesMacrostepStateIdle,
	TargetlessTransitionCompletesMacrostepStateRecycled,
	TargetlessTransitionCompletesMacrostepStateSettled,
}

// TargetlessTransitionCompletesMacrostepTarget is one token of a target list, as the document wrote
// it (W3C SCXML 3.13): a state, or a <history> the engine dereferences.
type TargetlessTransitionCompletesMacrostepTarget = sce.EntryTarget[TargetlessTransitionCompletesMacrostepState, sce.HistoryID]

// ======================================================================
// Document structure (W3C SCXML 3.2-3.4, 3.10)
//
// Package-level tables, because the structure is a fact about the document
// and not about a run: the engine's Appendix D procedures read them through
// the policy methods below, and a transition's target list is handed out as
// a slice of them rather than rebuilt on every selection.
// ======================================================================

// childStatesOfTargetlessTransitionCompletesMacrostep is §scxml-D-getChildStates per state: its
// <state>, <parallel> and <final> children, in document order.
var childStatesOfTargetlessTransitionCompletesMacrostep = [3][]TargetlessTransitionCompletesMacrostepState{
}

// initialTargetsOfTargetlessTransitionCompletesMacrostep is each compound state's initial transition
// target, as written (§scxml-3.3).
var initialTargetsOfTargetlessTransitionCompletesMacrostep = [3][]TargetlessTransitionCompletesMacrostepTarget{
}

// documentInitialTargetsOfTargetlessTransitionCompletesMacrostep is the target of the document's own
// initial transition, as written (§scxml-3.2).
var documentInitialTargetsOfTargetlessTransitionCompletesMacrostep = []TargetlessTransitionCompletesMacrostepTarget{sce.StateTarget[TargetlessTransitionCompletesMacrostepState, sce.HistoryID](TargetlessTransitionCompletesMacrostepStateIdle)}

// transitionTargetsOfTargetlessTransitionCompletesMacrostep is each transition's target list, as
// written (§scxml-3.13), by source state and the transition's index among its
// source's own transitions. A targetless transition's entry is empty.
var transitionTargetsOfTargetlessTransitionCompletesMacrostep = [3][][]TargetlessTransitionCompletesMacrostepTarget{
	TargetlessTransitionCompletesMacrostepStateIdle: {
		0: {sce.StateTarget[TargetlessTransitionCompletesMacrostepState, sce.HistoryID](TargetlessTransitionCompletesMacrostepStateSettled)},
		5: {sce.StateTarget[TargetlessTransitionCompletesMacrostepState, sce.HistoryID](TargetlessTransitionCompletesMacrostepStateRecycled)},
	},
	TargetlessTransitionCompletesMacrostepStateRecycled: {
		0: {sce.StateTarget[TargetlessTransitionCompletesMacrostepState, sce.HistoryID](TargetlessTransitionCompletesMacrostepStateRecycled)},
	},
}

// ======================================================================
// Event type (W3C SCXML 3.12)
// ======================================================================

type TargetlessTransitionCompletesMacrostepEvent int

const (
	TargetlessTransitionCompletesMacrostepEventArm TargetlessTransitionCompletesMacrostepEvent = 0
	TargetlessTransitionCompletesMacrostepEventErrorExecution TargetlessTransitionCompletesMacrostepEvent = 1
	TargetlessTransitionCompletesMacrostepEventPing TargetlessTransitionCompletesMacrostepEvent = 2
	TargetlessTransitionCompletesMacrostepEventPong TargetlessTransitionCompletesMacrostepEvent = 3
	TargetlessTransitionCompletesMacrostepEventQuiet TargetlessTransitionCompletesMacrostepEvent = 4
	TargetlessTransitionCompletesMacrostepEventRecycle TargetlessTransitionCompletesMacrostepEvent = 5
	// W3C SCXML 3.13: Sentinel for eventless transition dispatch
	TargetlessTransitionCompletesMacrostepEventNull TargetlessTransitionCompletesMacrostepEvent = 6
)

func (e TargetlessTransitionCompletesMacrostepEvent) String() string {
	switch e {
	case TargetlessTransitionCompletesMacrostepEventArm:
		return "arm"
	case TargetlessTransitionCompletesMacrostepEventErrorExecution:
		return "error.execution"
	case TargetlessTransitionCompletesMacrostepEventPing:
		return "ping"
	case TargetlessTransitionCompletesMacrostepEventPong:
		return "pong"
	case TargetlessTransitionCompletesMacrostepEventQuiet:
		return "quiet"
	case TargetlessTransitionCompletesMacrostepEventRecycle:
		return "recycle"
	case TargetlessTransitionCompletesMacrostepEventNull:
		return ""
	}
	return "unknown"
}

// ======================================================================
// Policy struct
// ======================================================================

type TargetlessTransitionCompletesMacrostepPolicy struct {
	// W3C SCXML 5.10.1: External event flag
	nextEventIsExternal bool
	pendingEventName string
	pendingEventData string
	pendingEventType string
	pendingEventSendid string
	pendingEventOrigin string
	pendingEventOrigintype string
	pendingEventInvokeid string
	// W3C SCXML 5.10: Session ID
	SessionID string
	// W3C SCXML B.1: Script engine handle (per-instance, Path B+ Q1=(d) Go=interface ref)
	ScriptEngine sce.IScriptEngine
	scriptEngineInitialized bool
	// W3C SCXML C.2.3: inbound BasicHTTP endpoint serving this machine,
	// declared by the deployment before Initialize(). The address belongs to
	// whoever runs the listener, so the machine takes it from here rather than
	// guessing one. Empty means no such endpoint is deployed, and no BasicHTTP
	// entry is published in _ioprocessors.
	BasicHTTPAccessURI string
	// W3C SCXML 6.4: Parent communication
	ParentExternalQueue chan sce.ParentEvent
	InvokeID           string
	ChildSessionID     string
	// §scxml-6.4.3: invoke param VALUES staged by the parent, applied after
	// this machine's datamodel init so they override its `<data>` defaults.
	pendingParams      map[string]interface{}
}

// NewTargetlessTransitionCompletesMacrostepPolicy creates a new policy with default values.
func NewTargetlessTransitionCompletesMacrostepPolicy() TargetlessTransitionCompletesMacrostepPolicy {
	return TargetlessTransitionCompletesMacrostepPolicy{
	}
}

// Quiet reports what the `quiet` datamodel variable is holding now
// (W3C SCXML 5.3).
//
// The live value, not the authored one: `<assign>` writes into the session, so
// a reader frozen at generation time would answer the document's literal for
// the whole run. The second return value is false when the machine cannot
// answer — no script engine is set, the session is not initialised yet,
// `quiet` was assigned a value of another type, or the engine refused.
func (p *TargetlessTransitionCompletesMacrostepPolicy) Quiet() (int64, bool) {
	return sce.ReadDatamodelInt(p.ScriptEngine, p.SessionID, "quiet")
}

// Armed reports what the `armed` datamodel variable is holding now
// (W3C SCXML 5.3).
//
// The live value, not the authored one: `<assign>` writes into the session, so
// a reader frozen at generation time would answer the document's literal for
// the whole run. The second return value is false when the machine cannot
// answer — no script engine is set, the session is not initialised yet,
// `armed` was assigned a value of another type, or the engine refused.
func (p *TargetlessTransitionCompletesMacrostepPolicy) Armed() (int64, bool) {
	return sce.ReadDatamodelInt(p.ScriptEngine, p.SessionID, "armed")
}

// Chained reports what the `chained` datamodel variable is holding now
// (W3C SCXML 5.3).
//
// The live value, not the authored one: `<assign>` writes into the session, so
// a reader frozen at generation time would answer the document's literal for
// the whole run. The second return value is false when the machine cannot
// answer — no script engine is set, the session is not initialised yet,
// `chained` was assigned a value of another type, or the engine refused.
func (p *TargetlessTransitionCompletesMacrostepPolicy) Chained() (int64, bool) {
	return sce.ReadDatamodelInt(p.ScriptEngine, p.SessionID, "chained")
}

// Polished reports what the `polished` datamodel variable is holding now
// (W3C SCXML 5.3).
//
// The live value, not the authored one: `<assign>` writes into the session, so
// a reader frozen at generation time would answer the document's literal for
// the whole run. The second return value is false when the machine cannot
// answer — no script engine is set, the session is not initialised yet,
// `polished` was assigned a value of another type, or the engine refused.
func (p *TargetlessTransitionCompletesMacrostepPolicy) Polished() (int64, bool) {
	return sce.ReadDatamodelInt(p.ScriptEngine, p.SessionID, "polished")
}

// Answered reports what the `answered` datamodel variable is holding now
// (W3C SCXML 5.3).
//
// The live value, not the authored one: `<assign>` writes into the session, so
// a reader frozen at generation time would answer the document's literal for
// the whole run. The second return value is false when the machine cannot
// answer — no script engine is set, the session is not initialised yet,
// `answered` was assigned a value of another type, or the engine refused.
func (p *TargetlessTransitionCompletesMacrostepPolicy) Answered() (int64, bool) {
	return sce.ReadDatamodelInt(p.ScriptEngine, p.SessionID, "answered")
}

// Entries reports what the `entries` datamodel variable is holding now
// (W3C SCXML 5.3).
//
// The live value, not the authored one: `<assign>` writes into the session, so
// a reader frozen at generation time would answer the document's literal for
// the whole run. The second return value is false when the machine cannot
// answer — no script engine is set, the session is not initialised yet,
// `entries` was assigned a value of another type, or the engine refused.
func (p *TargetlessTransitionCompletesMacrostepPolicy) Entries() (int64, bool) {
	return sce.ReadDatamodelInt(p.ScriptEngine, p.SessionID, "entries")
}




// ensureScriptEngine lazily initializes the script engine session.
//
// Engine DI Parity RFC: panics if ScriptEngine was not set on the policy
// before Initialize() — mirrors Kotlin's mandatory constructor parameter
// contract. Silent no-op would otherwise turn missed injection into a
// hidden runtime regression (every <assign>/<log>/guard becomes a no-op
// and the SM walks to its default-state final without diagnostic).
func (p *TargetlessTransitionCompletesMacrostepPolicy) ensureScriptEngine() {
	if p.scriptEngineInitialized {
		return
	}
	engine := p.ScriptEngine
	if engine == nil {
		panic("TargetlessTransitionCompletesMacrostepPolicy: ScriptEngine field must be set before Initialize()")
	}
	sessionID := p.SessionID
	if sessionID == "" {
		sessionID = sce.GenerateSessionID()
		p.SessionID = sessionID
	}
	if !engine.HasSession(sessionID) {
		_ = engine.CreateSession(sessionID)
	}
	// W3C SCXML C.1.1 / C.2.3: the _ioprocessors entries come from the same
	// helper every other backend uses, so a machine reads the same entry names
	// and the same addresses whichever one runs it.
	_ = engine.SetupSystemVariables(sessionID, "targetless_transition_completes_macrostep",
		sce.BuildIoProcessors(sessionID, p.BasicHTTPAccessURI))
	p.scriptEngineInitialized = true
}


// InitializeDataModel sets up datamodel via script engine (W3C SCXML 5.3).
func (p *TargetlessTransitionCompletesMacrostepPolicy) InitializeDataModel(eng *sce.Engine[TargetlessTransitionCompletesMacrostepState, TargetlessTransitionCompletesMacrostepEvent]) {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	sessionID := p.SessionID

	// W3C SCXML 5.3: Initialize _sessionid
	_ = engine.SetVariable(sessionID, "_sessionid", sessionID)

	// W3C SCXML 5.3: Initialize _name
	_ = engine.SetVariable(sessionID, "_name", "targetless_transition_completes_macrostep")

	// W3C SCXML 5.2.2: Initialize global datamodel variables
	// W3C SCXML 5.2/5.3: Initialize quiet from expr="0"
	{
		result, err := engine.EvaluateExpression(sessionID, `0`)
		if err == nil {
			_ = engine.SetVariable(sessionID, "quiet", result)
		} else {
			eng.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "<data id='quiet'> expr failed to evaluate"))
			_ = engine.SetVariable(sessionID, "quiet", nil)
		}
	}
	// W3C SCXML 5.2/5.3: Initialize armed from expr="0"
	{
		result, err := engine.EvaluateExpression(sessionID, `0`)
		if err == nil {
			_ = engine.SetVariable(sessionID, "armed", result)
		} else {
			eng.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "<data id='armed'> expr failed to evaluate"))
			_ = engine.SetVariable(sessionID, "armed", nil)
		}
	}
	// W3C SCXML 5.2/5.3: Initialize chained from expr="0"
	{
		result, err := engine.EvaluateExpression(sessionID, `0`)
		if err == nil {
			_ = engine.SetVariable(sessionID, "chained", result)
		} else {
			eng.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "<data id='chained'> expr failed to evaluate"))
			_ = engine.SetVariable(sessionID, "chained", nil)
		}
	}
	// W3C SCXML 5.2/5.3: Initialize polished from expr="0"
	{
		result, err := engine.EvaluateExpression(sessionID, `0`)
		if err == nil {
			_ = engine.SetVariable(sessionID, "polished", result)
		} else {
			eng.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "<data id='polished'> expr failed to evaluate"))
			_ = engine.SetVariable(sessionID, "polished", nil)
		}
	}
	// W3C SCXML 5.2/5.3: Initialize answered from expr="0"
	{
		result, err := engine.EvaluateExpression(sessionID, `0`)
		if err == nil {
			_ = engine.SetVariable(sessionID, "answered", result)
		} else {
			eng.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "<data id='answered'> expr failed to evaluate"))
			_ = engine.SetVariable(sessionID, "answered", nil)
		}
	}
	// W3C SCXML 5.2/5.3: Initialize entries from expr="0"
	{
		result, err := engine.EvaluateExpression(sessionID, `0`)
		if err == nil {
			_ = engine.SetVariable(sessionID, "entries", result)
		} else {
			eng.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "<data id='entries'> expr failed to evaluate"))
			_ = engine.SetVariable(sessionID, "entries", nil)
		}
	}



	// §scxml-6.4.3: apply the invoke params the parent staged — overriding the
	// `<data>` default this block just seeded, and only for a name the child
	// declares ("if the names do not match, the Processor MUST NOT add the
	// value ... to the invoked session's data model"). `HasVariable` is that
	// filter, and it is this channel's only copy of the rule.
	if len(p.pendingParams) > 0 {
		for paramName, paramValue := range p.pendingParams {
			if engine.HasVariable(sessionID, paramName) {
				_ = engine.SetVariable(sessionID, paramName, paramValue)
			}
		}
		p.pendingParams = nil
	}
}

// evaluateGuard evaluates a guard condition via script engine.
// W3C SCXML 4.3.2: If a condition expression cannot be evaluated, the processor
// MUST treat it as false and MUST raise error.execution.
func (p *TargetlessTransitionCompletesMacrostepPolicy) evaluateGuard(guard string, eng *sce.Engine[TargetlessTransitionCompletesMacrostepState, TargetlessTransitionCompletesMacrostepEvent]) bool {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	result, err := engine.EvaluateExpression(p.SessionID, guard)
	if err != nil {
		eng.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "a <transition> cond failed to evaluate"))
		return false
	}
	return sce.ScriptToBool(result)
}

// executeScript executes a script block via script engine.
func (p *TargetlessTransitionCompletesMacrostepPolicy) executeScript(script string) error {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	return engine.ExecuteScript(p.SessionID, script)
}

// setCurrentEvent binds _event system variable (W3C SCXML 5.10) and answers
// which rung of §scxml-B-2-8-1 the payload got, because the binding is the
// only place that knows.
//
// This used to be `_ = engine.SetCurrentEvent(...)`: the ladder decided
// between a DOM, a value and a space-normalized string, and the decision was
// dropped one line later. A payload that announced structure and would not
// parse therefore reached the document as raw characters, every
// _event.data.<field> read empty, and nothing anywhere could say so — see
// sce.PayloadReading.
func (p *TargetlessTransitionCompletesMacrostepPolicy) setCurrentEvent(name string) sce.PayloadReading {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	data := p.pendingEventData
	eventType := p.pendingEventType
	sendID := p.pendingEventSendid
	// W3C SCXML C.1: `_event.origin` is the sender's published
	// `_ioprocessors` location, not its bare session id — and this is the one
	// place that publishes `_event` to the document, so this is where the id
	// becomes a location. The engine keeps the bare id in
	// `EventMetadata.Origin` because its session-keyed lookups (<finalize>
	// dispatch, cancelled-invoke filtering) match on it; converting at the
	// raise would make one value serve two consumers that need different
	// spellings. The conversion itself lives in `sce.PublishedOrigin`, the
	// port of the `IOProcessorHelper::publishedOrigin` the C++ engines share:
	// a second spelling of the rule is how the backends would stop agreeing.
	origin := sce.PublishedOrigin(p.pendingEventOrigin)
	originType := p.pendingEventOrigintype
	invokeID := p.pendingEventInvokeid
	reading, err := engine.SetCurrentEvent(p.SessionID, sce.SetCurrentEventArgs{
		Name:       name,
		Data:       data,
		Type:       eventType,
		SendID:     sendID,
		Origin:     origin,
		OriginType: originType,
		InvokeID:   invokeID,
	})
	if err != nil {
		// An engine that could not bind _event at all has a larger problem
		// than an unreadable payload, and reporting PayloadUndecodable for it
		// would point a host at the wrong thing.
		return sce.PayloadAbsent
	}
	return reading
}

// assignVariable assigns a value to a datamodel variable via script engine.
func (p *TargetlessTransitionCompletesMacrostepPolicy) assignVariable(location, expr string) error {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	script := location + " = " + expr
	return engine.ExecuteScript(p.SessionID, script)
}

// getVariable reads a datamodel variable from the script engine.
func (p *TargetlessTransitionCompletesMacrostepPolicy) getVariable(name string) interface{} {
	p.ensureScriptEngine()
	engine := p.ScriptEngine
	result, err := engine.GetVariable(p.SessionID, name)
	if err != nil {
		return nil
	}
	return result
}

// SetParamValueInScriptEngine stores an invoke param's VALUE for deferred
// application after datamodel init (§scxml-6.4.3).
//
// Params are applied at the end of InitializeDataModel, overriding the
// `<data>` default only for names the child declares. The value crosses as a
// value: this took the parent's value rendered as Lua source and
// re-evaluated it here until 2026-08-21, which survived every value a test
// had tried and lost the ones Lua cannot spell — `ToScriptLiteral` renders a
// non-finite number as `+Inf`, which is not a Lua expression, so an
// `<invoke>` `<param expr="1/0"/>` arrived as nothing at all.
func (p *TargetlessTransitionCompletesMacrostepPolicy) SetParamValueInScriptEngine(name string, value interface{}) {
	if p.pendingParams == nil {
		p.pendingParams = make(map[string]interface{})
	}
	p.pendingParams[name] = value
}


// ExecutePendingInvokes is a no-op (no invokes in this SM).
func (p *TargetlessTransitionCompletesMacrostepPolicy) ExecutePendingInvokes(engine *sce.Engine[TargetlessTransitionCompletesMacrostepState, TargetlessTransitionCompletesMacrostepEvent]) {}

// TickChildren is a no-op (no invokes in this SM).
func (p *TargetlessTransitionCompletesMacrostepPolicy) TickChildren(engine *sce.Engine[TargetlessTransitionCompletesMacrostepState, TargetlessTransitionCompletesMacrostepEvent]) {}

// ======================================================================
// StatePolicy interface implementation
// ======================================================================

// InitialState returns the initial state (W3C SCXML 3.3).
func (p *TargetlessTransitionCompletesMacrostepPolicy) InitialState() TargetlessTransitionCompletesMacrostepState {
	return TargetlessTransitionCompletesMacrostepStateIdle
}

// IsFinalState returns true if state is a <final> state (W3C SCXML 3.7).
func (p *TargetlessTransitionCompletesMacrostepPolicy) IsFinalState(state TargetlessTransitionCompletesMacrostepState) bool {
	switch state {
	}
	return false
}

// GetParent returns the parent of state, or (zero, false) if root (W3C SCXML 3.3).
func (p *TargetlessTransitionCompletesMacrostepPolicy) GetParent(state TargetlessTransitionCompletesMacrostepState) (TargetlessTransitionCompletesMacrostepState, bool) {
	switch state {
	}
	return 0, false
}

// IsCompoundState returns true if state is a <state> with child states — exactly
// the states that have an initial transition. A <parallel> is not compound
// (W3C SCXML 3.3).
func (p *TargetlessTransitionCompletesMacrostepPolicy) IsCompoundState(state TargetlessTransitionCompletesMacrostepState) bool {
	return len(initialTargetsOfTargetlessTransitionCompletesMacrostep[state]) > 0
}

func (p *TargetlessTransitionCompletesMacrostepPolicy) IsParallelState(_ TargetlessTransitionCompletesMacrostepState) bool { return false }

// GetChildStates returns state's <state>, <parallel> and <final> children, in
// document order — for a <parallel>, its regions (§scxml-D-getChildStates).
func (p *TargetlessTransitionCompletesMacrostepPolicy) GetChildStates(state TargetlessTransitionCompletesMacrostepState) []TargetlessTransitionCompletesMacrostepState {
	return childStatesOfTargetlessTransitionCompletesMacrostep[state]
}

// GetInitialTargets returns a compound state's initial transition target, as
// written; the engine's entry procedures dereference a <history> among them
// (W3C SCXML 3.3).
func (p *TargetlessTransitionCompletesMacrostepPolicy) GetInitialTargets(state TargetlessTransitionCompletesMacrostepState) []TargetlessTransitionCompletesMacrostepTarget {
	return initialTargetsOfTargetlessTransitionCompletesMacrostep[state]
}

// GetDocumentInitialTargets returns the target of the document's own initial
// transition, as written (W3C SCXML 3.2).
func (p *TargetlessTransitionCompletesMacrostepPolicy) GetDocumentInitialTargets() []TargetlessTransitionCompletesMacrostepTarget {
	return documentInitialTargetsOfTargetlessTransitionCompletesMacrostep
}

// W3C SCXML 3.10: this document declares no <history>, so no target list names
// one and the engine never asks the two below; answering would mean inventing
// one.
func (p *TargetlessTransitionCompletesMacrostepPolicy) GetHistoryParent(history sce.HistoryID) TargetlessTransitionCompletesMacrostepState {
	panic(fmt.Sprintf("TargetlessTransitionCompletesMacrostepPolicy declares no <history>; asked for %d", history))
}
func (p *TargetlessTransitionCompletesMacrostepPolicy) GetHistoryDefaultTargets(history sce.HistoryID) []TargetlessTransitionCompletesMacrostepTarget {
	panic(fmt.Sprintf("TargetlessTransitionCompletesMacrostepPolicy declares no <history>; asked for %d", history))
}
func (p *TargetlessTransitionCompletesMacrostepPolicy) HistoryValue(_ sce.HistoryID) ([]TargetlessTransitionCompletesMacrostepState, bool) {
	return nil, false
}

// GetDocumentOrder returns the document order index (W3C SCXML Appendix D).
func (p *TargetlessTransitionCompletesMacrostepPolicy) GetDocumentOrder(state TargetlessTransitionCompletesMacrostepState) int {
	switch state {
	case TargetlessTransitionCompletesMacrostepStateIdle:
		return 0
	case TargetlessTransitionCompletesMacrostepStateRecycled:
		return 2
	case TargetlessTransitionCompletesMacrostepStateSettled:
		return 1
	}
	return -1
}

// GetEventName returns the string name of an event (W3C SCXML 3.12).
func (p *TargetlessTransitionCompletesMacrostepPolicy) GetEventName(event TargetlessTransitionCompletesMacrostepEvent) string {
	return event.String()
}

// GetEventFromName looks up an event by name (W3C SCXML 3.12).
func (p *TargetlessTransitionCompletesMacrostepPolicy) GetEventFromName(name string) (TargetlessTransitionCompletesMacrostepEvent, bool) {
	switch name {
	case "arm":
		return TargetlessTransitionCompletesMacrostepEventArm, true
	case "error.execution":
		return TargetlessTransitionCompletesMacrostepEventErrorExecution, true
	case "ping":
		return TargetlessTransitionCompletesMacrostepEventPing, true
	case "pong":
		return TargetlessTransitionCompletesMacrostepEventPong, true
	case "quiet":
		return TargetlessTransitionCompletesMacrostepEventQuiet, true
	case "recycle":
		return TargetlessTransitionCompletesMacrostepEventRecycle, true
	}
	return TargetlessTransitionCompletesMacrostepEventNull, false
}

// GetStateName returns the string name of a state (W3C SCXML 3.3).
func (p *TargetlessTransitionCompletesMacrostepPolicy) GetStateName(state TargetlessTransitionCompletesMacrostepState) string {
	return state.String()
}

// GetStateFromName reads a state id back into the state it names (W3C SCXML 3.3).
// The reverse of GetStateName, and what turns a host's recorded configuration
// back into the argument sce.Engine.EnterAt takes.
func (p *TargetlessTransitionCompletesMacrostepPolicy) GetStateFromName(name string) (TargetlessTransitionCompletesMacrostepState, bool) {
	return TargetlessTransitionCompletesMacrostepStateFromName(name)
}

// NullEvent returns the sentinel for eventless transition dispatch (W3C SCXML 3.13).
func (p *TargetlessTransitionCompletesMacrostepPolicy) NullEvent() TargetlessTransitionCompletesMacrostepEvent {
	return TargetlessTransitionCompletesMacrostepEventNull
}


// SetNextEventIsExternal sets the external event flag (W3C SCXML 5.10.1).
func (p *TargetlessTransitionCompletesMacrostepPolicy) SetNextEventIsExternal(value bool) {
	p.nextEventIsExternal = value
}

// HasParallelStates returns whether the SM has parallel states.
func (p *TargetlessTransitionCompletesMacrostepPolicy) HasParallelStates() bool {
	return false
}

// NeedsScriptEngine returns whether the SM needs a script engine.
func (p *TargetlessTransitionCompletesMacrostepPolicy) NeedsScriptEngine() bool {
	return true
}

// NeedsEventScheduler reports whether a host must drive this machine with
// Tick rather than Step alone.
//
// W3C SCXML 6.2: Step runs a macrostep and never drains the delayed-send
// scheduler nor ticks an invoked child, so a host that only ever calls it
// waits forever with nothing said. Same verdict the generate manifest
// publishes as needs_event_scheduler.
func (p *TargetlessTransitionCompletesMacrostepPolicy) NeedsEventScheduler() bool {
	return false
}

// NeedsDataModelInit returns whether the SM needs datamodel init.
func (p *TargetlessTransitionCompletesMacrostepPolicy) NeedsDataModelInit() bool {
	return true
}

func (p *TargetlessTransitionCompletesMacrostepPolicy) HasInvokeSupport() bool { return false }
func (p *TargetlessTransitionCompletesMacrostepPolicy) HasChildTick() bool { return false }
func (p *TargetlessTransitionCompletesMacrostepPolicy) HasFinalize() bool { return false }
func (p *TargetlessTransitionCompletesMacrostepPolicy) HasAutoforward() bool { return false }
func (p *TargetlessTransitionCompletesMacrostepPolicy) HasActiveStates() bool { return false }
func (p *TargetlessTransitionCompletesMacrostepPolicy) GetActiveStates() []TargetlessTransitionCompletesMacrostepState { return nil }
// W3C SCXML 3.4: this machine keeps no active set — its configuration is the
// parent walk from the current state — so there is nothing for a restore to
// hand back here. sce.Engine.EnterAt reaches this only through HasActiveStates,
// which is false above; the method exists because the interface is one contract.
func (p *TargetlessTransitionCompletesMacrostepPolicy) SetActiveStates(_ []TargetlessTransitionCompletesMacrostepState) {}
func (p *TargetlessTransitionCompletesMacrostepPolicy) HasExternalEventFlag() bool { return true }
// ExecuteFinalizeForChildEvent is a no-op (no finalize invokes).
func (p *TargetlessTransitionCompletesMacrostepPolicy) ExecuteFinalizeForChildEvent(_ *sce.EventWithMetadata[TargetlessTransitionCompletesMacrostepEvent], _ *sce.Engine[TargetlessTransitionCompletesMacrostepState, TargetlessTransitionCompletesMacrostepEvent]) {}
// ForwardToAutoforwardChildren is a no-op (no autoforward invokes).
func (p *TargetlessTransitionCompletesMacrostepPolicy) ForwardToAutoforwardChildren(_ string, _ sce.EventMetadata, _ *sce.Engine[TargetlessTransitionCompletesMacrostepState, TargetlessTransitionCompletesMacrostepEvent]) {}

// PopulateEventMetadata stores pending event metadata (W3C SCXML 5.10).
// Note: event name is set separately via setCurrentEvent(), not from metadata.
func (p *TargetlessTransitionCompletesMacrostepPolicy) PopulateEventMetadata(meta *sce.EventMetadata) {
	p.pendingEventData = meta.Data
	p.pendingEventType = meta.EventType.String()
	p.pendingEventSendid = meta.SendID
	p.pendingEventOrigin = meta.Origin
	p.pendingEventOrigintype = meta.OriginType
	p.pendingEventInvokeid = meta.InvokeID
}

// LiftTypedPayload binds the dequeued event's typed `_event.data` view from
// the data it carries (NL→IR Item C1 Path A).
//
// The typed carrier PopulateEventMetadata reads is filled by one producer, the
// generated Raise<Event> inject seam. Every other producer — <send> with
// <param>, an invoke forwarding either way, autoforward, BasicHTTP, mesh —
// fills EventMetadata.Data, so the schema's fields are read out of that here.
// A refusal is returned for the engine to raise as error.execution, which is
// what W3C SCXML 3.13 gives for a guard that cannot be evaluated.
func (p *TargetlessTransitionCompletesMacrostepPolicy) LiftTypedPayload(event TargetlessTransitionCompletesMacrostepEvent, meta *sce.EventMetadata) error {
	// This document lowered no typed guard, so no event carries a typed view.
	return nil
}

// ClearEventMetadata resets pending event metadata (W3C SCXML 5.10).
func (p *TargetlessTransitionCompletesMacrostepPolicy) ClearEventMetadata() {
	p.pendingEventName = ""
	p.pendingEventData = ""
	p.pendingEventType = ""
	p.pendingEventSendid = ""
	p.pendingEventOrigin = ""
	p.pendingEventOrigintype = ""
	p.pendingEventInvokeid = ""
}



// ExecuteEntryActions enters one state (W3C SCXML 3.8): adds it to the
// configuration, runs its <onentry>, and its <initial> transition's content when
// its initial state is entered by default.
//line targetless_transition_completes_macrostep.scxml:51
func (p *TargetlessTransitionCompletesMacrostepPolicy) ExecuteEntryActions(state TargetlessTransitionCompletesMacrostepState, engine *sce.Engine[TargetlessTransitionCompletesMacrostepState, TargetlessTransitionCompletesMacrostepEvent], isDefaultEntry bool) {
	p.ensureScriptEngine()
	switch state {
	case TargetlessTransitionCompletesMacrostepStateRecycled:
		//line targetless_transition_completes_macrostep.scxml:147
		// W3C SCXML 3.8: onentry block 0 (break on error stops subsequent actions)
		for actionBlock0 := 0; actionBlock0 < 1; actionBlock0++ {
			_ = actionBlock0

	// W3C SCXML 5.3: <assign location="entries" expr="entries + 1">
	if err := p.assignVariable(`entries`, `_scxml_add(entries, 1)`); err != nil {
		engine.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "<assign> to 'entries' failed"))
		break
	}

		}
	default:
		// No entry actions
	}
}

// ExecuteHistoryDefaultContent runs a <history>'s default transition content
// (W3C SCXML 3.10.2), after its parent's onentry (and after the parent's own
// <initial> content) when the history was taken with nothing recorded. The
// engine asks for it by the entry set's defaultHistoryContent answer; a history
// that restored what it recorded runs nothing.
//line targetless_transition_completes_macrostep.scxml:51
func (p *TargetlessTransitionCompletesMacrostepPolicy) ExecuteHistoryDefaultContent(history sce.HistoryID, engine *sce.Engine[TargetlessTransitionCompletesMacrostepState, TargetlessTransitionCompletesMacrostepEvent]) {
	// W3C SCXML 3.10.2: no <history> in this document has default content.
}

// ExecuteExitActions exits one state (W3C SCXML 3.9): records its histories,
// runs its <onexit>, cancels its invocations and removes it from the
// configuration — §scxml-D-exitStates's order.
//line targetless_transition_completes_macrostep.scxml:51
func (p *TargetlessTransitionCompletesMacrostepPolicy) ExecuteExitActions(state TargetlessTransitionCompletesMacrostepState, engine *sce.Engine[TargetlessTransitionCompletesMacrostepState, TargetlessTransitionCompletesMacrostepEvent], configurationBeforeExit []TargetlessTransitionCompletesMacrostepState) {
	p.ensureScriptEngine()
	// §scxml-D-exitStates orders one state's exit as onexit, then
	// cancelInvoke, then configuration.delete(s), so `In(s)` inside s's own
	// handler is true: the <onexit> switch comes first and the removal from
	// the configuration last.
	switch state {
	default:
		// No exit actions
	}
}



// BindCurrentEvent binds the event whose transitions are about to be selected as
// the _event their guards read (W3C SCXML 5.10) — before the first guard runs,
// and not for an eventless selection, which has no event of its own.
//line targetless_transition_completes_macrostep.scxml:51
func (p *TargetlessTransitionCompletesMacrostepPolicy) BindCurrentEvent(event TargetlessTransitionCompletesMacrostepEvent, engine *sce.Engine[TargetlessTransitionCompletesMacrostepState, TargetlessTransitionCompletesMacrostepEvent]) {
	if event != TargetlessTransitionCompletesMacrostepEventNull {
		// §scxml-B-2-8-1: the rung the payload got, handed to the engine
		// rather than dropped. This is the only frame that has both the
		// reading and the event it belongs to.
		engine.NotePayloadReading(event, p.setCurrentEvent(p.GetEventName(event)))
	}
}

// FirstEnabledTransition is Appendix D selectTransitions, the half only this
// document can answer: the first of state's own transitions, in document order,
// that event enables and whose guard holds. The engine walks the atomic states
// and their ancestors and keeps the ordered set; the null event asks for
// eventless transitions.
//line targetless_transition_completes_macrostep.scxml:51
func (p *TargetlessTransitionCompletesMacrostepPolicy) FirstEnabledTransition(state TargetlessTransitionCompletesMacrostepState, event TargetlessTransitionCompletesMacrostepEvent, engine *sce.Engine[TargetlessTransitionCompletesMacrostepState, TargetlessTransitionCompletesMacrostepEvent]) (sce.EnabledTransition[TargetlessTransitionCompletesMacrostepState, sce.HistoryID], bool) {
	switch state {
	case TargetlessTransitionCompletesMacrostepStateIdle:
		if event == TargetlessTransitionCompletesMacrostepEventNull {
			if p.evaluateGuard(`_scxml_eq(armed, 1)`, engine) {
				return sce.EnabledTransition[TargetlessTransitionCompletesMacrostepState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfTargetlessTransitionCompletesMacrostep[state][0],
					TransitionIndex: 0,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
		if event == TargetlessTransitionCompletesMacrostepEventQuiet {
			{
				return sce.EnabledTransition[TargetlessTransitionCompletesMacrostepState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 1,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
		if event == TargetlessTransitionCompletesMacrostepEventArm {
			{
				return sce.EnabledTransition[TargetlessTransitionCompletesMacrostepState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 2,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
		if event == TargetlessTransitionCompletesMacrostepEventPing {
			{
				return sce.EnabledTransition[TargetlessTransitionCompletesMacrostepState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 3,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
		if event == TargetlessTransitionCompletesMacrostepEventPong {
			{
				return sce.EnabledTransition[TargetlessTransitionCompletesMacrostepState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 4,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
		if event == TargetlessTransitionCompletesMacrostepEventRecycle {
			{
				return sce.EnabledTransition[TargetlessTransitionCompletesMacrostepState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfTargetlessTransitionCompletesMacrostep[state][5],
					TransitionIndex: 5,
					HasActions:      false,
					IsInternal:      false,
				}, true
			}
		}
	case TargetlessTransitionCompletesMacrostepStateRecycled:
		if event == TargetlessTransitionCompletesMacrostepEventNull {
			if p.evaluateGuard(`(entries < 2)`, engine) {
				return sce.EnabledTransition[TargetlessTransitionCompletesMacrostepState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfTargetlessTransitionCompletesMacrostep[state][0],
					TransitionIndex: 0,
					HasActions:      false,
					IsInternal:      false,
				}, true
			}
		}
	case TargetlessTransitionCompletesMacrostepStateSettled:
		if event == TargetlessTransitionCompletesMacrostepEventNull {
			if p.evaluateGuard(`_scxml_eq(polished, 0)`, engine) {
				return sce.EnabledTransition[TargetlessTransitionCompletesMacrostepState, sce.HistoryID]{
					Source:          state,
					TransitionIndex: 0,
					HasActions:      true,
					IsInternal:      false,
				}, true
			}
		}
	}
	return sce.EnabledTransition[TargetlessTransitionCompletesMacrostepState, sce.HistoryID]{}, false
}

// ExecuteTransitionContent runs one transition's executable content (W3C SCXML
// 3.13), between the microstep's exits and its entries.
//line targetless_transition_completes_macrostep.scxml:51
func (p *TargetlessTransitionCompletesMacrostepPolicy) ExecuteTransitionContent(source TargetlessTransitionCompletesMacrostepState, transitionIndex int, engine *sce.Engine[TargetlessTransitionCompletesMacrostepState, TargetlessTransitionCompletesMacrostepEvent]) {
	p.ensureScriptEngine()
	switch source {
	case TargetlessTransitionCompletesMacrostepStateIdle:
		switch transitionIndex {
		case 0:
			//line targetless_transition_completes_macrostep.scxml:86

	// W3C SCXML 5.3: <assign location="chained" expr="chained + 1">
	if err := p.assignVariable(`chained`, `_scxml_add(chained, 1)`); err != nil {
		engine.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "<assign> to 'chained' failed"))
	}

		case 1:
			//line targetless_transition_completes_macrostep.scxml:93

	// W3C SCXML 5.3: <assign location="quiet" expr="quiet + 1">
	if err := p.assignVariable(`quiet`, `_scxml_add(quiet, 1)`); err != nil {
		engine.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "<assign> to 'quiet' failed"))
	}

		case 2:
			//line targetless_transition_completes_macrostep.scxml:100

	// W3C SCXML 5.3: <assign location="armed" expr="1">
	if err := p.assignVariable(`armed`, `1`); err != nil {
		engine.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "<assign> to 'armed' failed"))
	}

		case 3:
			//line targetless_transition_completes_macrostep.scxml:107

	engine.Raise(sce.NewEventWithMetadata(TargetlessTransitionCompletesMacrostepEventPong))

		case 4:
			//line targetless_transition_completes_macrostep.scxml:111

	// W3C SCXML 5.3: <assign location="answered" expr="answered + 1">
	if err := p.assignVariable(`answered`, `_scxml_add(answered, 1)`); err != nil {
		engine.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "<assign> to 'answered' failed"))
	}

		}
	case TargetlessTransitionCompletesMacrostepStateSettled:
		switch transitionIndex {
		case 0:
			//line targetless_transition_completes_macrostep.scxml:126

	// W3C SCXML 5.3: <assign location="polished" expr="polished + 1">
	if err := p.assignVariable(`polished`, `_scxml_add(polished, 1)`); err != nil {
		engine.Raise(sce.NewPlatformError(TargetlessTransitionCompletesMacrostepEventErrorExecution, "<assign> to 'polished' failed"))
	}

		}
	}
}
