// SCE-GENERATED — DO NOT EDIT
// source-hash: f9bc2e3a10834cc236cb284a28c51c227951af5f2785c6dda5a820794a76e2ca


// SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 [Author of input SCXML file] (content derived from the input document)
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 newmassrael (content copied from SCE templates)
//
// Generated by SCE Code Generator (Go backend)
// From: sce-build/tests/fixtures/static_datamodel/static_invoke_params__sce_synth_invoke__watcher.scxml
//
// This generated code is usable under terms of your choice when it was produced
// by an unmodified sce-codegen and is not part of a competing product
// (SCE Linking Exception, section 3; see LICENSE-GENERATED.md).
// Full license: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE
// Generated Go state machine for `static_invoke_params__sce_synth_invoke__watcher`.
//
// Generated by SCE Code Generator (Go backend).
// Implements sce.StatePolicy with full transition logic,
// entry/exit actions, and event processing.


// SCE-MAP: static_invoke_params__sce_synth_invoke__watcher.scxml:3 :: _machine

package static_invoke_params

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	sce "github.com/newmassrael/sce-go-runtime"
	scealgorithm "github.com/newmassrael/sce-forge-runtime/algorithm"
)

// Ensure imports are used
var (
	_ = fmt.Sprintf
	_ = filepath.Join
	_ = strings.HasPrefix
	_ = time.Duration(0)
	_ scealgorithm.Failure
)

// ======================================================================
// State type (W3C SCXML 3.3)
// ======================================================================

type StaticInvokeParamsSceSynthInvokeWatcherState int

const (
	StaticInvokeParamsSceSynthInvokeWatcherStateLeaf StaticInvokeParamsSceSynthInvokeWatcherState = 0
	StaticInvokeParamsSceSynthInvokeWatcherStateWaiting StaticInvokeParamsSceSynthInvokeWatcherState = 1
)

func (s StaticInvokeParamsSceSynthInvokeWatcherState) String() string {
	switch s {
	case StaticInvokeParamsSceSynthInvokeWatcherStateLeaf:
		return "leaf"
	case StaticInvokeParamsSceSynthInvokeWatcherStateWaiting:
		return "waiting"
	}
	return "unknown"
}

// StaticInvokeParamsSceSynthInvokeWatcherStateFromName is the read half of the pair above — a state
// id back into the state it names (W3C SCXML 3.3).
//
// A host that persists where a machine was has to write it down as TEXT: the
// constants above are a build artefact of one binary, and the process that
// resumes is a different one. String publishes the name and this reads it back,
// which is what lets a journal survive its own record and reach
// sce.Engine.EnterAt.
//
// The second return is false for a name this document does not declare. A name
// guessed at rather than refused is how a restore reaches a configuration
// nobody recorded — and the refusal is what makes a typo in a journal a
// reported failure instead of a machine quietly somewhere else.
//
// Emitted from the same loop over the document's states as String, so the two
// age together.
func StaticInvokeParamsSceSynthInvokeWatcherStateFromName(name string) (StaticInvokeParamsSceSynthInvokeWatcherState, bool) {
	switch name {
	case "leaf":
		return StaticInvokeParamsSceSynthInvokeWatcherStateLeaf, true
	case "waiting":
		return StaticInvokeParamsSceSynthInvokeWatcherStateWaiting, true
	}
	var zero StaticInvokeParamsSceSynthInvokeWatcherState
	return zero, false
}

// StaticInvokeParamsSceSynthInvokeWatcherAllStates is every state this document declares, in the
// order the constants above are issued.
//
// Emitted from the same loop, so a walk over it is a walk over the document
// rather than over a list somebody maintained beside it — a test that spells
// its own list goes on passing when the document grows a state.
var StaticInvokeParamsSceSynthInvokeWatcherAllStates = []StaticInvokeParamsSceSynthInvokeWatcherState{
	StaticInvokeParamsSceSynthInvokeWatcherStateLeaf,
	StaticInvokeParamsSceSynthInvokeWatcherStateWaiting,
}

// StaticInvokeParamsSceSynthInvokeWatcherTarget is one token of a target list, as the document wrote
// it (W3C SCXML 3.13): a state, or a <history> the engine dereferences.
type StaticInvokeParamsSceSynthInvokeWatcherTarget = sce.EntryTarget[StaticInvokeParamsSceSynthInvokeWatcherState, sce.HistoryID]

// ======================================================================
// Document structure (W3C SCXML 3.2-3.4, 3.10)
//
// Package-level tables, because the structure is a fact about the document
// and not about a run: the engine's Appendix D procedures read them through
// the policy methods below, and a transition's target list is handed out as
// a slice of them rather than rebuilt on every selection.
// ======================================================================

// childStatesOfStaticInvokeParamsSceSynthInvokeWatcher is §scxml-D-getChildStates per state: its
// <state>, <parallel> and <final> children, in document order.
var childStatesOfStaticInvokeParamsSceSynthInvokeWatcher = [2][]StaticInvokeParamsSceSynthInvokeWatcherState{
}

// initialTargetsOfStaticInvokeParamsSceSynthInvokeWatcher is each compound state's initial transition
// target, as written (§scxml-3.3).
var initialTargetsOfStaticInvokeParamsSceSynthInvokeWatcher = [2][]StaticInvokeParamsSceSynthInvokeWatcherTarget{
}

// documentInitialTargetsOfStaticInvokeParamsSceSynthInvokeWatcher is the target of the document's own
// initial transition, as written (§scxml-3.2).
var documentInitialTargetsOfStaticInvokeParamsSceSynthInvokeWatcher = []StaticInvokeParamsSceSynthInvokeWatcherTarget{sce.StateTarget[StaticInvokeParamsSceSynthInvokeWatcherState, sce.HistoryID](StaticInvokeParamsSceSynthInvokeWatcherStateWaiting)}

// transitionTargetsOfStaticInvokeParamsSceSynthInvokeWatcher is each transition's target list, as
// written (§scxml-3.13), by source state and the transition's index among its
// source's own transitions. A targetless transition's entry is empty.
var transitionTargetsOfStaticInvokeParamsSceSynthInvokeWatcher = [2][][]StaticInvokeParamsSceSynthInvokeWatcherTarget{
	StaticInvokeParamsSceSynthInvokeWatcherStateWaiting: {
		0: {sce.StateTarget[StaticInvokeParamsSceSynthInvokeWatcherState, sce.HistoryID](StaticInvokeParamsSceSynthInvokeWatcherStateLeaf)},
	},
}

// ======================================================================
// Event type (W3C SCXML 3.12)
// ======================================================================

type StaticInvokeParamsSceSynthInvokeWatcherEvent int

const (
	// W3C SCXML 3.13: Sentinel for eventless transition dispatch
	StaticInvokeParamsSceSynthInvokeWatcherEventNull StaticInvokeParamsSceSynthInvokeWatcherEvent = 0
)

func (e StaticInvokeParamsSceSynthInvokeWatcherEvent) String() string {
	switch e {
	case StaticInvokeParamsSceSynthInvokeWatcherEventNull:
		return ""
	}
	return "unknown"
}

// ======================================================================
// Policy struct
// ======================================================================

type StaticInvokeParamsSceSynthInvokeWatcherPolicy struct {
	// W3C SCXML 5.10: Session ID
	SessionID string
	// ── SCE Accepted Subset §2.15: the datamodel="sce-static" variables ──
	// W3C SCXML 5.2: the `start` datamodel variable.
	vStart uint32
	// W3C SCXML 6.4: Parent communication (unbounded — see sce.ParentEventQueue)
	ParentExternalQueue *sce.ParentEventQueue
	InvokeID           string
	ChildSessionID     string
	// §scxml-6.4.3: invoke param VALUES staged by the parent, applied after
	// this machine's datamodel init so they override its `<data>` defaults.
	pendingParams      map[string]interface{}
}

// NewStaticInvokeParamsSceSynthInvokeWatcherPolicy creates a new policy with default values.
func NewStaticInvokeParamsSceSynthInvokeWatcherPolicy() StaticInvokeParamsSceSynthInvokeWatcherPolicy {
	return StaticInvokeParamsSceSynthInvokeWatcherPolicy{
		vStart: 0,
	}
}

// StaticInvokeParamsSceSynthInvokeWatcherInvokeParams holds the values a parent's `<param>` and
// `namelist` give this machine's variables before it starts (§scxml-6.4.1). A
// variable left nil keeps the value its `<data>` gave it.
type StaticInvokeParamsSceSynthInvokeWatcherInvokeParams struct {
	VStart *uint32
}

// AcceptParams gives this machine the values params carries, in place of the
// ones its `<data>` gave. Called before it initializes (§scxml-6.4.1).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) AcceptParams(params StaticInvokeParamsSceSynthInvokeWatcherInvokeParams) {
	if params.VStart != nil {
		p.vStart = *params.VStart
	}
}



// No script engine needed for this state machine.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) InitializeDataModel(eng *sce.Engine[StaticInvokeParamsSceSynthInvokeWatcherState, StaticInvokeParamsSceSynthInvokeWatcherEvent]) {}

// SetParamValueInScriptEngine is a no-op for state machines without script engine.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) SetParamValueInScriptEngine(name string, value interface{}) {}


// ExecutePendingInvokes is a no-op (no invokes in this SM).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) ExecutePendingInvokes(engine *sce.Engine[StaticInvokeParamsSceSynthInvokeWatcherState, StaticInvokeParamsSceSynthInvokeWatcherEvent]) {}

// TickChildren is a no-op (no invokes in this SM).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) TickChildren(engine *sce.Engine[StaticInvokeParamsSceSynthInvokeWatcherState, StaticInvokeParamsSceSynthInvokeWatcherEvent]) {}

// DeliverToParent delivers a delayed `<send target="#_parent">` whose wait is
// over, with the payload an immediate one carries (W3C SCXML 6.2 + 6.4). It
// waited in this machine's own queue, so `<cancel>` reached it and a child that
// ended first dropped it — the engine dispatches nothing once final. Emitted for
// every machine, since the one that needs it is an invoked child, which need not
// invoke anything itself.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) DeliverToParent(eventName, eventData string) bool {
	if p.ParentExternalQueue == nil {
		return false
	}
	p.ParentExternalQueue.Push(sce.ParentEvent{Name: eventName, Data: eventData})
	return true
}

// HasParentSession answers whether a session invoked this one (W3C SCXML C.1):
// the queue the invoking parent installs is the link to it.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) HasParentSession() bool {
	return p.ParentExternalQueue != nil
}

// ======================================================================
// StatePolicy interface implementation
// ======================================================================

// InitialState returns the initial state (W3C SCXML 3.3).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) InitialState() StaticInvokeParamsSceSynthInvokeWatcherState {
	return StaticInvokeParamsSceSynthInvokeWatcherStateWaiting
}

// IsFinalState returns true if state is a <final> state (W3C SCXML 3.7).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) IsFinalState(state StaticInvokeParamsSceSynthInvokeWatcherState) bool {
	switch state {
	case StaticInvokeParamsSceSynthInvokeWatcherStateLeaf:
		return true
	}
	return false
}

// GetParent returns the parent of state, or (zero, false) if root (W3C SCXML 3.3).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) GetParent(state StaticInvokeParamsSceSynthInvokeWatcherState) (StaticInvokeParamsSceSynthInvokeWatcherState, bool) {
	switch state {
	}
	return 0, false
}

// IsCompoundState returns true if state is a <state> with child states — exactly
// the states that have an initial transition. A <parallel> is not compound
// (W3C SCXML 3.3).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) IsCompoundState(state StaticInvokeParamsSceSynthInvokeWatcherState) bool {
	return len(initialTargetsOfStaticInvokeParamsSceSynthInvokeWatcher[state]) > 0
}

func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) IsParallelState(_ StaticInvokeParamsSceSynthInvokeWatcherState) bool { return false }

// GetChildStates returns state's <state>, <parallel> and <final> children, in
// document order — for a <parallel>, its regions (§scxml-D-getChildStates).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) GetChildStates(state StaticInvokeParamsSceSynthInvokeWatcherState) []StaticInvokeParamsSceSynthInvokeWatcherState {
	return childStatesOfStaticInvokeParamsSceSynthInvokeWatcher[state]
}

// GetInitialTargets returns a compound state's initial transition target, as
// written; the engine's entry procedures dereference a <history> among them
// (W3C SCXML 3.3).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) GetInitialTargets(state StaticInvokeParamsSceSynthInvokeWatcherState) []StaticInvokeParamsSceSynthInvokeWatcherTarget {
	return initialTargetsOfStaticInvokeParamsSceSynthInvokeWatcher[state]
}

// GetDocumentInitialTargets returns the target of the document's own initial
// transition, as written (W3C SCXML 3.2).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) GetDocumentInitialTargets() []StaticInvokeParamsSceSynthInvokeWatcherTarget {
	return documentInitialTargetsOfStaticInvokeParamsSceSynthInvokeWatcher
}

// W3C SCXML 3.10: this document declares no <history>, so no target list names
// one and the engine never asks the two below; answering would mean inventing
// one.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) GetHistoryParent(history sce.HistoryID) StaticInvokeParamsSceSynthInvokeWatcherState {
	panic(fmt.Sprintf("StaticInvokeParamsSceSynthInvokeWatcherPolicy declares no <history>; asked for %d", history))
}
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) GetHistoryDefaultTargets(history sce.HistoryID) []StaticInvokeParamsSceSynthInvokeWatcherTarget {
	panic(fmt.Sprintf("StaticInvokeParamsSceSynthInvokeWatcherPolicy declares no <history>; asked for %d", history))
}
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) HistoryValue(_ sce.HistoryID) ([]StaticInvokeParamsSceSynthInvokeWatcherState, bool) {
	return nil, false
}

// GetDocumentOrder returns the document order index (W3C SCXML Appendix D).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) GetDocumentOrder(state StaticInvokeParamsSceSynthInvokeWatcherState) int {
	switch state {
	case StaticInvokeParamsSceSynthInvokeWatcherStateLeaf:
		return 1
	case StaticInvokeParamsSceSynthInvokeWatcherStateWaiting:
		return 0
	}
	return -1
}

// GetEventName returns the string name of an event (W3C SCXML 3.12).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) GetEventName(event StaticInvokeParamsSceSynthInvokeWatcherEvent) string {
	return event.String()
}

// GetEventFromName looks up an event by name (W3C SCXML 3.12).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) GetEventFromName(name string) (StaticInvokeParamsSceSynthInvokeWatcherEvent, bool) {
	switch name {
	}
	return StaticInvokeParamsSceSynthInvokeWatcherEventNull, false
}

// GetStateName returns the string name of a state (W3C SCXML 3.3).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) GetStateName(state StaticInvokeParamsSceSynthInvokeWatcherState) string {
	return state.String()
}

// GetStateFromName reads a state id back into the state it names (W3C SCXML 3.3).
// The reverse of GetStateName, and what turns a host's recorded configuration
// back into the argument sce.Engine.EnterAt takes.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) GetStateFromName(name string) (StaticInvokeParamsSceSynthInvokeWatcherState, bool) {
	return StaticInvokeParamsSceSynthInvokeWatcherStateFromName(name)
}

// NullEvent returns the sentinel for eventless transition dispatch (W3C SCXML 3.13).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) NullEvent() StaticInvokeParamsSceSynthInvokeWatcherEvent {
	return StaticInvokeParamsSceSynthInvokeWatcherEventNull
}


// HasParallelStates returns whether the SM has parallel states.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) HasParallelStates() bool {
	return false
}

// NeedsScriptEngine returns whether the SM needs a script engine.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) NeedsScriptEngine() bool {
	return false
}

// NeedsEventScheduler reports whether a host must drive this machine with
// Tick rather than Step alone.
//
// W3C SCXML 6.2: Step runs a macrostep and never drains the delayed-send
// scheduler nor ticks an invoked child, so a host that only ever calls it
// waits forever with nothing said. Same verdict the generate manifest
// publishes as needs_event_scheduler.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) NeedsEventScheduler() bool {
	return false
}

// NeedsParent reports whether the document sends to its parent session — the
// generate manifest's needs_parent, read by Engine.RootStartRefusal.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) NeedsParent() bool {
	return false
}

// NeedsDataModelInit returns whether the SM needs datamodel init.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) NeedsDataModelInit() bool {
	return false
}

func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) HasInvokeSupport() bool { return false }
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) HasChildTick() bool { return false }
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) HasFinalize() bool { return false }
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) HasAutoforward() bool { return false }
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) HasActiveStates() bool { return false }
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) GetActiveStates() []StaticInvokeParamsSceSynthInvokeWatcherState { return nil }
// W3C SCXML 3.4: this machine keeps no active set — its configuration is the
// parent walk from the current state — so there is nothing for a restore to
// hand back here. sce.Engine.EnterAt reaches this only through HasActiveStates,
// which is false above; the method exists because the interface is one contract.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) SetActiveStates(_ []StaticInvokeParamsSceSynthInvokeWatcherState) {}
// ExecuteFinalizeForChildEvent is a no-op (no finalize invokes).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) ExecuteFinalizeForChildEvent(_ *sce.EventWithMetadata[StaticInvokeParamsSceSynthInvokeWatcherEvent], _ *sce.Engine[StaticInvokeParamsSceSynthInvokeWatcherState, StaticInvokeParamsSceSynthInvokeWatcherEvent]) {}
// ForwardToAutoforwardChildren is a no-op (no autoforward invokes).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) ForwardToAutoforwardChildren(_ string, _ sce.EventMetadata, _ *sce.Engine[StaticInvokeParamsSceSynthInvokeWatcherState, StaticInvokeParamsSceSynthInvokeWatcherEvent]) {}

// PopulateEventMetadata stores pending event metadata (W3C SCXML 5.10).
// Note: event name is set separately via setCurrentEvent(); metadata supplies
// only the name the event ARRIVED under, when that is not its value's own.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) PopulateEventMetadata(meta *sce.EventMetadata) {
}

// LiftTypedPayload binds the dequeued event's typed `_event.data` view from
// the data it carries (NL→IR Item C1 Path A).
//
// The typed carrier PopulateEventMetadata reads is filled by one producer, the
// generated Raise<Event> inject seam. Every other producer — <send> with
// <param>, an invoke forwarding either way, autoforward, BasicHTTP, mesh —
// fills EventMetadata.Data, so the schema's fields are read out of that here.
// A refusal is returned for the engine to raise as error.execution, which is
// what W3C SCXML 3.13 gives for a guard that cannot be evaluated.
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) LiftTypedPayload(event StaticInvokeParamsSceSynthInvokeWatcherEvent, meta *sce.EventMetadata) error {
	// This document lowered no typed guard, so no event carries a typed view.
	return nil
}

// ClearEventMetadata resets pending event metadata (W3C SCXML 5.10).
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) ClearEventMetadata() {
}



// ExecuteEntryActions enters one state (W3C SCXML 3.8): adds it to the
// configuration, runs its <onentry>, and its <initial> transition's content when
// its initial state is entered by default.
//line static_invoke_params__sce_synth_invoke__watcher.scxml:3
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) ExecuteEntryActions(state StaticInvokeParamsSceSynthInvokeWatcherState, engine *sce.Engine[StaticInvokeParamsSceSynthInvokeWatcherState, StaticInvokeParamsSceSynthInvokeWatcherEvent], isDefaultEntry bool) {
	switch state {
	default:
		// No entry actions
	}
}

// ExecuteHistoryDefaultContent runs a <history>'s default transition content
// (W3C SCXML 3.10.2), after its parent's onentry (and after the parent's own
// <initial> content) when the history was taken with nothing recorded. The
// engine asks for it by the entry set's defaultHistoryContent answer; a history
// that restored what it recorded runs nothing.
//line static_invoke_params__sce_synth_invoke__watcher.scxml:3
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) ExecuteHistoryDefaultContent(history sce.HistoryID, engine *sce.Engine[StaticInvokeParamsSceSynthInvokeWatcherState, StaticInvokeParamsSceSynthInvokeWatcherEvent]) {
	// W3C SCXML 3.10.2: no <history> in this document has default content.
}

// ExecuteExitActions exits one state (W3C SCXML 3.9): records its histories,
// runs its <onexit>, cancels its invocations and removes it from the
// configuration — §scxml-D-exitStates's order.
//line static_invoke_params__sce_synth_invoke__watcher.scxml:3
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) ExecuteExitActions(state StaticInvokeParamsSceSynthInvokeWatcherState, engine *sce.Engine[StaticInvokeParamsSceSynthInvokeWatcherState, StaticInvokeParamsSceSynthInvokeWatcherEvent], configurationBeforeExit []StaticInvokeParamsSceSynthInvokeWatcherState) {
	// §scxml-D-exitStates orders one state's exit as onexit, then
	// cancelInvoke, then configuration.delete(s), so `In(s)` inside s's own
	// handler is true: the <onexit> switch comes first and the removal from
	// the configuration last.
	switch state {
	default:
		// No exit actions
	}
}



// BindCurrentEvent binds the event whose transitions are about to be selected as
// the _event their guards read (W3C SCXML 5.10) — before the first guard runs,
// and not for an eventless selection, which has no event of its own.
//line static_invoke_params__sce_synth_invoke__watcher.scxml:3
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) BindCurrentEvent(event StaticInvokeParamsSceSynthInvokeWatcherEvent, engine *sce.Engine[StaticInvokeParamsSceSynthInvokeWatcherState, StaticInvokeParamsSceSynthInvokeWatcherEvent]) {
	// This document's guards never read _event, so there is nothing to bind.
}

// FirstEnabledTransition is Appendix D selectTransitions, the half only this
// document can answer: the first of state's own transitions, in document order,
// that event enables and whose guard holds. The engine walks the atomic states
// and their ancestors and keeps the ordered set; the null event asks for
// eventless transitions.
//line static_invoke_params__sce_synth_invoke__watcher.scxml:3
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) FirstEnabledTransition(state StaticInvokeParamsSceSynthInvokeWatcherState, event StaticInvokeParamsSceSynthInvokeWatcherEvent, engine *sce.Engine[StaticInvokeParamsSceSynthInvokeWatcherState, StaticInvokeParamsSceSynthInvokeWatcherEvent]) (sce.EnabledTransition[StaticInvokeParamsSceSynthInvokeWatcherState, sce.HistoryID], bool) {
	switch state {
	case StaticInvokeParamsSceSynthInvokeWatcherStateWaiting:
		if event == StaticInvokeParamsSceSynthInvokeWatcherEventNull {
			// NL→IR Item C1 Path A: native typed `_event.data` guard — cond
			// "start === 8" lowered to a tag-checked field comparison on
			// the lifted `pending<Event>Payload` (no script engine).
			if p.vStart == 8 {
				return sce.EnabledTransition[StaticInvokeParamsSceSynthInvokeWatcherState, sce.HistoryID]{
					Source:          state,
					Targets:         transitionTargetsOfStaticInvokeParamsSceSynthInvokeWatcher[state][0],
					TransitionIndex: 0,
					HasActions:      false,
					IsInternal:      false,
				}, true
			}
		}
	}
	return sce.EnabledTransition[StaticInvokeParamsSceSynthInvokeWatcherState, sce.HistoryID]{}, false
}

// ExecuteTransitionContent runs one transition's executable content (W3C SCXML
// 3.13), between the microstep's exits and its entries.
//line static_invoke_params__sce_synth_invoke__watcher.scxml:3
func (p *StaticInvokeParamsSceSynthInvokeWatcherPolicy) ExecuteTransitionContent(source StaticInvokeParamsSceSynthInvokeWatcherState, transitionIndex int, engine *sce.Engine[StaticInvokeParamsSceSynthInvokeWatcherState, StaticInvokeParamsSceSynthInvokeWatcherEvent]) {
	// W3C SCXML 3.13: no transition in this document has content.
}
