// SCE-GENERATED — DO NOT EDIT
// source-hash: f5e0b70b0a1d16d32d7cde8ac02eebab0c5a8961575091a650bdf8b84a251d4d

// SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 [Author of input SCXML file] (content derived from the input document)
// SPDX-FileCopyrightText: Copyright (c) 2025-2026 newmassrael (content copied from SCE templates)
//
// Generated by SCE Code Generator (Rust backend)
// From: sce-build/tests/fixtures/static_datamodel/static_timers.scxml
//
// This generated code is usable under terms of your choice when it was produced
// by an unmodified sce-codegen and is not part of a competing product
// (SCE Linking Exception, section 3; see LICENSE-GENERATED.md).
// Full license: https://github.com/newmassrael/scxml-core-engine/blob/main/LICENSE

//! Generated Rust state machine for `static_timers`.
//!
//! Generated by SCE Code Generator (Rust backend).
//! Implements `sce_rust_runtime::StatePolicy` with full transition logic,
//! entry/exit actions, and event processing.

// Suppression budget audited 2026-04-15 against the full sce-rust-tests
// W3C suite (202 fixtures). Each allow below corresponds to a lint that
// actually fires on generated code today; see file:line callouts in the
// inline justifications. Adding a new allow here requires reproducing the
// warning on a real fixture and recording it in the same form. Removing an
// allow is safe whenever its justifying pattern stops being emitted.

// Source-faithful identifier names: W3C SCXML 6.4.1 lets users supply
// arbitrary id strings (e.g. `<invoke id="invokedChild">`); preserving the
// camelCase verbatim into Rust field names like `child_invokedChild`
// keeps the generated code traceable back to the SCXML source.
#![allow(non_snake_case)]
// Codegen always emits `use core::time::Duration` and the umbrella
// `use sce_rust_runtime::{Engine, StatePolicy};`; fixtures with no
// `<send delay=...>` and no engine-borrowing actions never reference
// `Duration`/`Engine`, leaving the imports unused.
#![allow(unused_imports)]
// Method parameters such as `_engine: &mut Engine<Self>` and per-state
// fields (`pending_event_invokeid`, `script_engine_initialized`, ...) are
// emitted on every fixture for the StatePolicy trait shape but read only
// by fixtures that actually exercise the corresponding W3C feature.
#![allow(dead_code)]
#![allow(unused_variables)]
// Bindings emitted `mut` for the documents that write them: `json_parts` in
// `<donedata>` evaluation is pushed only by a param that evaluates (test298
// pushes nothing), and a send's `err_meta` gets a `send_id` only when the
// document has a datamodel (test194, test199). Measured 2026-09-24: removing
// this allow reds those fixtures under `-D warnings`.
#![allow(unused_mut)]
// `'action_block:` early-exit label wraps every onentry block but is only
// `break`-ed to from fixtures that emit error-on-action sequences.
#![allow(unused_labels)]
// Codegen emits the catch-all `else => {}` arm on every closed-enum match
// for forward compatibility; rustc proves it unreachable once every
// variant is handled.
#![allow(unreachable_patterns)]
#![allow(unreachable_code)]
// W3C SCXML 5.5 donedata pattern: `let mut done_event_data = String::new();`
// is declared once for every kind of `<donedata>`, and a `<param>` list
// always overwrites it with the surviving pairs, so those documents never
// read the initial empty string.
#![allow(unused_assignments)]
// Generated code is uniform across 200+ fixtures and intentionally avoids
// per-fixture style optimisation passes. The `clippy::style` and
// `clippy::complexity` categories cover suggestions a human author would
// apply by hand (match_like_matches_macro, needless_range_loop,
// type_complexity, single_match, ...) — none of these affect correctness,
// but each one would force the codegen to special-case its output.
// Correctness-relevant clippy categories (`clippy::correctness`,
// `clippy::suspicious`, `clippy::perf`) remain at warn so any genuine bug
// the generator emits still surfaces.
#![allow(clippy::style)]
#![allow(clippy::complexity)]
#![doc = "SCE-MAP: static_timers.scxml:22 :: _machine"]
// SCE-MAP: static_timers.scxml:22 :: _machine

use core::time::Duration;
use sce_rust_runtime::{Engine, StatePolicy};

// ======================================================================
// State enum (W3C SCXML 3.3)
// ======================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum StaticTimersState {
    Done,
    // W3C SCXML 3.2: `<scxml initial>` state — the machine's `Default`.
    #[default]
    Waiting,
}

// ======================================================================
// Event enum (W3C SCXML 3.12)
// ======================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StaticTimersEvent {
    Beat,
    Echo,
    ErrorExecution,
    Inner,
    Stop,
    Timeout,
    /// W3C SCXML 3.13: Sentinel for eventless transition dispatch
    Null,
}

// ======================================================================
// Externally-drivable event surface (W3C SCXML 3.12 / 5.10)
// ======================================================================

impl StaticTimersEvent {
    /// Events that can arrive from OUTSIDE the machine — external
    /// `<send>` / platform ingress — as opposed to internal `<raise>`
    /// signals and the W3C SCXML 3.13 `Null` sentinel (neither is a
    /// member). This is the machine's structural external trigger
    /// surface: every non-reserved `<transition event>` target minus
    /// every internally-raised event. A consumer that maps event names
    /// back to variants admits only these as externally injectable,
    /// without re-deriving the partition. Structural and consumer-
    /// agnostic; inert when unused. Associated (not a free `const`) so
    /// several machines glob-re-exported into one module never collide
    /// on the name.
    pub const EXTERNALLY_DRIVABLE_EVENTS: &'static [StaticTimersEvent] = &[
        StaticTimersEvent::Beat,
        StaticTimersEvent::Echo,
        StaticTimersEvent::Stop,
        StaticTimersEvent::Timeout,
    ];
}

// ── SCE Accepted Subset §2.15: what a host observes of a sce-static machine ──

/// The published variables (`sce:direction="out"`) as one owned value, in
/// declaration order.
#[derive(Debug, Clone, PartialEq)]
#[allow(non_snake_case)]
pub struct StaticTimersData {
    pub trace: u32,
}

/// What a host observes: the full active configuration — every active state,
/// each region of a `<parallel>` included — and the published variables,
/// taken together between two host calls, which is a macrostep boundary (W3C
/// SCXML Appendix D). `truncated` is `true` when that macrostep was stopped at
/// the microstep ceiling, so the configuration is not a stable one. Owned: a
/// host holding one keeps what it saw whatever the machine does next.
#[derive(Debug, Clone, PartialEq)]
pub struct StaticTimersSnapshot {
    pub configuration: ::sce_rust_runtime::helpers::hierarchy::StateChain<StaticTimersState>,
    pub data: StaticTimersData,
    pub truncated: bool,
}

/// The snapshot of a running machine, as an extension of the runtime's
/// `Engine` (a foreign type, so a local trait — the `Inject` shape).
pub trait StaticTimersObserve {
    /// The machine as the host sees it now: one [`StaticTimersSnapshot`],
    /// never a state between two microsteps.
    fn snapshot(&self) -> StaticTimersSnapshot;
}

impl StaticTimersObserve for Engine<StaticTimersPolicy> {
    fn snapshot(&self) -> StaticTimersSnapshot {
        let policy = self.policy();
        StaticTimersSnapshot {
            configuration: self.get_active_states(),
            data: StaticTimersData {
                trace: policy.trace,
            },
            truncated: self.last_macrostep_truncated(),
        }
    }
}

// ── SCE Accepted Subset §2.15: saving a sce-static machine and restoring it ──

/// A running machine saved at a macrostep boundary, and restored into a new
/// process in place of `initialize` — every variable, the machine's own
/// included, and where the machine stands. The saved state is JSON
/// (`SavedState::to_json`), the same on every backend.
pub trait StaticTimersPersist: Sized {
    /// The policy a restored machine is built around, constructed by the host
    /// as it would be for `initialize`.
    type Policy;

    /// The shape a saved state of this document is bound to: a state saved
    /// from a document that renamed, re-typed or moved a state or a variable
    /// is refused, one saved before a guard or an action changed is not.
    const SHAPE: &'static str;

    /// The document's `<history>` pseudo-states, by the id a saved state keys
    /// them by — what a saved state records of each, and what a restore reads
    /// back. Empty for a document that declares none.
    const HISTORIES: &'static [::sce_rust_runtime::saved_state::HistoryDecl<
        ::sce_rust_runtime::NoHistory,
    >];

    /// The machine's whole state, each delayed `<send>` still waiting written
    /// as the moment it comes due on the wall clock whose reading now is
    /// `wall_now_ms`, in milliseconds since the Unix epoch. Refused for a
    /// machine that is not running, and for one whose last macrostep stopped
    /// at the microstep ceiling.
    fn save_at(
        &self,
        wall_now_ms: u64,
    ) -> Result<
        ::sce_rust_runtime::saved_state::SavedState,
        ::sce_rust_runtime::saved_state::StateRefusal,
    >;

    /// [`save_at`](Self::save_at) at the host's wall clock now.
    fn save(
        &self,
    ) -> Result<
        ::sce_rust_runtime::saved_state::SavedState,
        ::sce_rust_runtime::saved_state::StateRefusal,
    > {
        self.save_at(::sce_rust_runtime::saved_state::wall_clock_ms())
    }

    /// A machine of `policy` standing where `saved` left one, measuring time
    /// by `clock` and told by `wall_now_ms` what time it is on the wall clock
    /// the saved `due`s were written against: a waiting send comes due when
    /// its saved moment does, and one already due comes due now. No
    /// `<onentry>` runs and no `<data>` is evaluated: the saved run already
    /// did both.
    fn restore_with(
        policy: Self::Policy,
        saved: &::sce_rust_runtime::saved_state::SavedState,
        clock: ::sce_rust_runtime::SceClock,
        wall_now_ms: u64,
    ) -> Result<Self, ::sce_rust_runtime::saved_state::StateRefusal>;

    /// [`restore_with`](Self::restore_with) on the engine's own clock, at the
    /// host's wall clock now.
    fn restore(
        policy: Self::Policy,
        saved: &::sce_rust_runtime::saved_state::SavedState,
    ) -> Result<Self, ::sce_rust_runtime::saved_state::StateRefusal> {
        Self::restore_with(
            policy,
            saved,
            ::sce_rust_runtime::SceClock::default(),
            ::sce_rust_runtime::saved_state::wall_clock_ms(),
        )
    }
}

impl StaticTimersPersist for Engine<StaticTimersPolicy> {
    type Policy = StaticTimersPolicy;

    const SHAPE: &'static str = "4ccb8b35ee15410c2fa524072e0d2cc992b50980b7db00f5ea7bd0635c1a5b68";

    const HISTORIES: &'static [::sce_rust_runtime::saved_state::HistoryDecl<
        ::sce_rust_runtime::NoHistory,
    >] = &[];

    fn save_at(
        &self,
        wall_now_ms: u64,
    ) -> Result<
        ::sce_rust_runtime::saved_state::SavedState,
        ::sce_rust_runtime::saved_state::StateRefusal,
    > {
        let policy = self.policy();
        ::sce_rust_runtime::saved_state::save(
            self,
            Self::SHAPE,
            vec![(
                "trace".to_string(),
                ::sce_rust_runtime::saved_state::SavedValue::to_saved(&policy.trace),
            )],
            ::sce_rust_runtime::saved_state::save_history(self.policy(), Self::HISTORIES),
            wall_now_ms,
        )
    }

    fn restore_with(
        mut policy: StaticTimersPolicy,
        saved: &::sce_rust_runtime::saved_state::SavedState,
        clock: ::sce_rust_runtime::SceClock,
        wall_now_ms: u64,
    ) -> Result<Self, ::sce_rust_runtime::saved_state::StateRefusal> {
        ::sce_rust_runtime::saved_state::check_shape(saved, Self::SHAPE)?;
        // Judged with the configuration and before any value is written, so a
        // refused restore holds no half of a state. A document with no
        // `<history>` refuses any a saved state records.
        ::sce_rust_runtime::saved_state::restore_history::<StaticTimersPolicy>(
            saved,
            Self::HISTORIES,
        )?;
        policy.trace = ::sce_rust_runtime::saved_state::SavedValue::from_saved(
            saved.variable("trace")?,
            "trace",
        )?;
        ::sce_rust_runtime::saved_state::enter(policy, saved, clock, wall_now_ms)
    }
}

// ======================================================================
// Policy struct
// ======================================================================

pub struct StaticTimersPolicy {
    /// W3C SCXML 5.2: the `trace` datamodel variable, published (`sce:direction="out"`).
    trace: u32,
    // W3C SCXML 5.10: Session ID (script engine + invoke tracking).
    //
    // SCE Protocol-Synthesis RFC §synth-5-J-2: gated to !no_std. Under `--no-std` both the
    // script engine (`codegen/no-std-script-not-supported`) and `<invoke>`
    // (`codegen/no-std-invoke-not-supported`) are codegen-rejected, so no
    // session identity is ever tracked and the alloc-coupled `String` is omitted.
    pub session_id: Option<String>,
    // W3C SCXML 6.4: Parent engine external queue for #_parent send routing
    // Always generated under std — any SM can be invoked as a child. Under
    // `--no-std` (SCE Protocol-Synthesis RFC §synth-5-J-2) the SCXML `<invoke>` element
    // is codegen-rejected, so no parent_external_queue handle is ever
    // wired in, and the Arc<Mutex<...>> (alloc-coupled) is omitted.
    pub parent_external_queue: Option<std::sync::Arc<std::sync::Mutex<Vec<(String, String)>>>>,
    // W3C SCXML 6.4.1: This child's invoke ID (for _event.invokeid in parent).
    // SCE Protocol-Synthesis RFC §synth-5-J-2: gated to !no_std — `<invoke>` is codegen-rejected
    // under no_std, so a machine is never instantiated as a child and this
    // identity is dead. Mirrors the `parent_external_queue` / `invoke` module gate.
    pub invoke_id: String,
    // W3C SCXML 6.5: Child session ID for finalize origin matching.
    pub child_session_id: String,
}

impl StaticTimersPolicy {
    pub fn new() -> Self {
        let trace: u32 = 0;
        Self {
            trace,
            session_id: None,
            parent_external_queue: None,
            invoke_id: String::new(),
            child_session_id: String::new(),
        }
    }

    /// W3C SCXML 5.2: what the published `trace` datamodel variable
    /// holds now. Only the machine writes it.
    pub fn trace(&self) -> u32 {
        self.trace
    }
}

impl Default for StaticTimersPolicy {
    fn default() -> Self {
        Self::new()
    }
}

// ======================================================================
// StatePolicy trait implementation
// ======================================================================

impl StatePolicy for StaticTimersPolicy {
    type State = StaticTimersState;
    type Event = StaticTimersEvent;
    // W3C SCXML 3.10: this document declares no <history>, so no target list
    // can name one.
    type History = sce_rust_runtime::NoHistory;
    // EventSchema native lowering: `()` = schemaless (dynamic
    // `_event.data` baseline); a `<Machine>Payload` sum is emitted when a
    // transition guard reads a typed `_event.data.<field>` (NL→IR C1 Path A).
    type Payload = ();
    type Hal = sce_rust_runtime::StdHal;

    // W3C SCXML Appendix D internalQueue / externalQueue. Under no_std the
    // depth is the per-document `<scxml sce:capacity>` / deploy value (emitted
    // as the const consumed below); absent a declared capacity the bare form
    // inherits the runtime default `MAX_EVENT_QUEUE_DEPTH` (the single source of
    // the default). Inert under std (`VecDeque`), so this one emission compiles
    // on both runtime profiles.
    type EventQueue = sce_rust_runtime::EventQueueManager<
        sce_rust_runtime::EventWithMetadata<Self::Event, Self::Payload>,
    >;

    // W3C SCXML 6.3: the delayed-send scheduler keeps a per-entry `send_id` only
    // so `<cancel sendid>` can find and drop the matching entry; the timer-fire
    // drain never reads it. A document with no `<cancel>` therefore emits the
    // zero-size `ElidedSendId`, shedding the scheduler ring's per-entry
    // `heapless::String<256>` (~256 B x MAX_SCHEDULED_EVENTS) under no_std --
    // dead weight with no cancel reader. A cancelling document keeps the
    // load-bearing `SceString`. Behaviour-preserving under std either way, so
    // this one emission compiles on both runtime profiles. Mirrors the
    // EventQueue per-machine sizing lever above.
    type ScheduledSendId = sce_rust_runtime::SceString;

    // W3C SCXML feature flags
    const HAS_PARALLEL_STATES: bool = false;
    const NEEDS_SCRIPT_ENGINE: bool = false;
    const NEEDS_DATA_MODEL_INIT: bool = false;
    // The same fact the generate manifest publishes as `needs_event_scheduler`.
    // A `build.rs` consumer never sees that manifest — `compile_scxml` returns
    // `()` — so without this constant a host had no route to the knowledge that
    // its driving loop must call `tick()` rather than `step()`.
    const NEEDS_EVENT_SCHEDULER: bool = true;
    // The generate manifest's `needs_parent`: what a root-start policy reads.
    const NEEDS_PARENT: bool = false;

    // ======================================================================
    // Static metadata methods (W3C SCXML document structure)
    // ======================================================================

    fn initial_state() -> Self::State {
        // The runtime entry state and the type's `Default` derive are one
        // concept, sourced from one computation (`default_state_id`) so
        // they can never diverge: `<scxml initial>`, or the first sorted
        // state when the initial attribute is unset.
        StaticTimersState::Waiting
    }

    fn is_final_state(state: Self::State) -> bool {
        match state {
            StaticTimersState::Done => true,
            _ => false,
        }
    }

    fn get_parent(state: Self::State) -> Option<Self::State> {
        match state {
            _ => None,
        }
    }

    // W3C SCXML 3.3: a <state> with child states — exactly the states that have
    // an initial transition. A <parallel> is not compound.
    fn is_compound_state(state: Self::State) -> bool {
        match state {
            _ => false,
        }
    }

    // §scxml-D-getChildStates: a state's <state>, <parallel> and <final>
    // children, in document order — for a <parallel>, its regions.
    fn get_child_states(state: Self::State) -> &'static [Self::State] {
        match state {
            _ => &[],
        }
    }

    // §scxml-3.3: a compound state's initial transition target, as written —
    // the engine's entry procedures dereference a <history> among them.
    fn get_initial_targets(
        state: Self::State,
    ) -> &'static [::sce_rust_runtime::EntryTarget<Self::State, Self::History>] {
        match state {
            _ => &[],
        }
    }

    // §scxml-3.2: the target of the document's own initial transition, as written.
    fn get_document_initial_targets(
    ) -> &'static [::sce_rust_runtime::EntryTarget<Self::State, Self::History>] {
        &[::sce_rust_runtime::EntryTarget::State(
            StaticTimersState::Waiting,
        )]
    }

    // §scxml-3.10: the state a <history> is declared in.
    fn get_history_parent(history: Self::History) -> Self::State {
        match history {}
    }

    // §scxml-3.10.2: a <history>'s default transition target, as written.
    fn get_history_default_targets(
        history: Self::History,
    ) -> &'static [::sce_rust_runtime::EntryTarget<Self::State, Self::History>] {
        match history {}
    }

    fn get_document_order(state: Self::State) -> u32 {
        match state {
            StaticTimersState::Done => 1,
            StaticTimersState::Waiting => 0,
        }
    }

    fn get_event_name(event: Self::Event) -> &'static str {
        match event {
            StaticTimersEvent::Beat => "beat",
            StaticTimersEvent::Echo => "echo",
            StaticTimersEvent::ErrorExecution => "error.execution",
            StaticTimersEvent::Inner => "inner",
            StaticTimersEvent::Stop => "stop",
            StaticTimersEvent::Timeout => "timeout",
            StaticTimersEvent::Null => "",
        }
    }

    fn get_event_from_name(name: &str) -> Option<Self::Event> {
        match name {
            "beat" => Some(StaticTimersEvent::Beat),
            "echo" => Some(StaticTimersEvent::Echo),
            "error.execution" => Some(StaticTimersEvent::ErrorExecution),
            "inner" => Some(StaticTimersEvent::Inner),
            "stop" => Some(StaticTimersEvent::Stop),
            "timeout" => Some(StaticTimersEvent::Timeout),
            _ => None,
        }
    }

    fn get_state_name(state: Self::State) -> &'static str {
        match state {
            StaticTimersState::Done => "done",
            StaticTimersState::Waiting => "waiting",
        }
    }

    // The inverse of the table above, emitted from the same loop over the
    // document's states so the two age together. It is what lets a host turn a
    // recorded configuration back into the `StateChain` `enter_at` takes.
    fn get_state_from_name(name: &str) -> Option<Self::State> {
        match name {
            "done" => Some(StaticTimersState::Done),
            "waiting" => Some(StaticTimersState::Waiting),
            _ => None,
        }
    }

    fn null_event() -> Self::Event {
        StaticTimersEvent::Null
    }

    // ======================================================================
    // Run-time state the entry procedures read
    // ======================================================================

    // §scxml-3.10: what a <history> recorded when its parent was last exited;
    // None before that ever happened.
    fn history_value(&self, history: Self::History) -> Option<&[Self::State]> {
        match history {}
    }

    // ======================================================================
    // Instance methods - generated executable content
    // ======================================================================

    // W3C SCXML 3.7: Execute <onentry> actions for a state
    #[doc = "SCE-MAP: static_timers.scxml:22 :: _machine"]
    // SCE-MAP: static_timers.scxml:22 :: _machine
    fn execute_entry_actions(
        &mut self,
        state: Self::State,
        engine: &mut sce_rust_runtime::Engine<Self>,
        is_default_entry: bool,
    ) {
        match state {
            StaticTimersState::Waiting => {
                // SCE-MAP: static_timers.scxml:27 :: waiting :: _state_body
                // W3C SCXML 3.8: onentry block 1/1
                // Labeled block allows actions to break out on error (W3C 3.8: error stops block)
                'action_block: {
                    {
                        let send_id = ::sce_rust_runtime::sce_string_from_str("timer");

                        let event_data: &str = "";

                        // W3C SCXML 6.2: Default send (no target = external event)
                        // W3C SCXML 6.2: delayed to this session's external queue. §scxml-C-1: the
                        // origin is this session, as on the immediate path.
                        engine.schedule_event(
                            StaticTimersEvent::Timeout,
                            core::time::Duration::from_millis(5000_u64),
                            &send_id,
                            event_data,
                            &::sce_rust_runtime::sce_string_from_str(
                                self.session_id.as_deref().unwrap_or(""),
                            ),
                        );

                        let _ = event_data; // suppress unused warning in branches that skip dispatch
                        let _ = send_id; // suppress unused warning when no send operation
                    }

                    {
                        let send_id = ::sce_rust_runtime::sce_string_from_str("__send_0");

                        let event_data: &str = "";

                        // W3C SCXML 6.2: Default send (no target = external event)
                        // W3C SCXML 6.2: delayed to this session's external queue. §scxml-C-1: the
                        // origin is this session, as on the immediate path.
                        engine.schedule_event(
                            StaticTimersEvent::Beat,
                            core::time::Duration::from_millis(2000_u64),
                            &send_id,
                            event_data,
                            &::sce_rust_runtime::sce_string_from_str(
                                self.session_id.as_deref().unwrap_or(""),
                            ),
                        );

                        let _ = event_data; // suppress unused warning in branches that skip dispatch
                        let _ = send_id; // suppress unused warning when no send operation
                    }

                    {
                        let send_id = ::sce_rust_runtime::sce_string_from_str("__send_1");

                        let event_data: &str = "";

                        // W3C SCXML 6.2: Default send (no target = external event)
                        // W3C SCXML 6.2: delayed to this session's external queue. §scxml-C-1: the
                        // origin is this session, as on the immediate path.
                        engine.schedule_event(
                            StaticTimersEvent::Echo,
                            core::time::Duration::from_millis(2000_u64),
                            &send_id,
                            event_data,
                            &::sce_rust_runtime::sce_string_from_str(
                                self.session_id.as_deref().unwrap_or(""),
                            ),
                        );

                        let _ = event_data; // suppress unused warning in branches that skip dispatch
                        let _ = send_id; // suppress unused warning when no send operation
                    }

                    {
                        let send_id = ::sce_rust_runtime::sce_string_from_str("__send_2");

                        let event_data: &str = "";

                        // W3C SCXML 6.2: Internal target (#_internal) - raise as internal event.
                        // A delay postpones it and does not change the queue.
                        engine.schedule_routed_event(
                            Some(StaticTimersEvent::Inner),
                            core::time::Duration::from_millis(1000_u64),
                            &send_id,
                            event_data,
                            &::sce_rust_runtime::sce_string_from_str(
                                self.session_id.as_deref().unwrap_or(""),
                            ),
                            sce_rust_runtime::ScheduledRoute::InternalQueue,
                        );

                        let _ = event_data; // suppress unused warning in branches that skip dispatch
                        let _ = send_id; // suppress unused warning when no send operation
                    }
                }
            }
            _ => {}
        }
    }

    // §scxml-3.10.2: a <history>'s default transition content, run after its
    // parent's onentry (and after the parent's own <initial> content) when the
    // history was taken with nothing recorded. The engine asks for it by the
    // entry set's defaultHistoryContent answer; a history that restored what it
    // recorded runs nothing.

    // W3C SCXML 3.8: Execute <onexit> actions for a state
    #[doc = "SCE-MAP: static_timers.scxml:22 :: _machine"]
    // SCE-MAP: static_timers.scxml:22 :: _machine
    fn execute_exit_actions(
        &mut self,
        state: Self::State,
        engine: &mut sce_rust_runtime::Engine<Self>,
        configuration_before_exit: &[Self::State],
    ) {
        // §scxml-D-exitStates orders one state's exit as onexit, then
        // cancelInvoke, then configuration.delete(s), so `In(s)` inside s's
        // own handler is true: the deactivation is the LAST step here.
    }

    // Appendix D selectTransitions, the half only this document can answer:
    // the first of `state`'s own transitions, in document order, that `event`
    // enables. The engine walks the atomic states and their ancestors and
    // keeps the ordered set. `Event::Null` asks for eventless transitions.
    #[doc = "SCE-MAP: static_timers.scxml:22 :: _machine"]
    // SCE-MAP: static_timers.scxml:22 :: _machine
    fn first_enabled_transition(
        &mut self,
        state: Self::State,
        event: Self::Event,
        engine: &mut sce_rust_runtime::Engine<Self>,
    ) -> Option<::sce_rust_runtime::EnabledTransition<Self::State, Self::History>> {
        match state {
            StaticTimersState::Waiting => {
                if event == StaticTimersEvent::Inner {
                    {
                        return Some(::sce_rust_runtime::EnabledTransition {
                            source: state,
                            targets: &[],
                            transition_index: 0,
                            has_actions: true,
                            is_internal: false,
                        });
                    }
                }
                if event == StaticTimersEvent::Beat {
                    {
                        return Some(::sce_rust_runtime::EnabledTransition {
                            source: state,
                            targets: &[],
                            transition_index: 1,
                            has_actions: true,
                            is_internal: false,
                        });
                    }
                }
                if event == StaticTimersEvent::Echo {
                    {
                        return Some(::sce_rust_runtime::EnabledTransition {
                            source: state,
                            targets: &[],
                            transition_index: 2,
                            has_actions: true,
                            is_internal: false,
                        });
                    }
                }
                if event == StaticTimersEvent::Timeout {
                    {
                        return Some(::sce_rust_runtime::EnabledTransition {
                            source: state,
                            targets: &[::sce_rust_runtime::EntryTarget::State(
                                StaticTimersState::Done,
                            )],
                            transition_index: 3,
                            has_actions: true,
                            is_internal: false,
                        });
                    }
                }
                if event == StaticTimersEvent::Stop {
                    {
                        return Some(::sce_rust_runtime::EnabledTransition {
                            source: state,
                            targets: &[],
                            transition_index: 4,
                            has_actions: true,
                            is_internal: false,
                        });
                    }
                }
                None
            }
            _ => None,
        }
    }

    // W3C SCXML 3.13: a transition's executable content, run by the engine
    // between the microstep's exits and its entries.
    #[doc = "SCE-MAP: static_timers.scxml:22 :: _machine"]
    // SCE-MAP: static_timers.scxml:22 :: _machine
    fn execute_transition_content(
        &mut self,
        source: Self::State,
        transition_index: usize,
        engine: &mut sce_rust_runtime::Engine<Self>,
    ) {
        match source {
            StaticTimersState::Waiting => {
                match transition_index {
                    0 => {
                        // SCE-MAP: static_timers.scxml:34 :: waiting :: _transition_0
                        // W3C SCXML 3.13: Transition 0 actions
                        // W3C SCXML 4.9: a transition's content is one block; an error ends it.
                        'action_block: {
                            // W3C SCXML 5.3: <assign location="trace">
                            let sce_failed = match (|| -> Result<(), sce_forge_runtime::algorithm::AlgorithmError> {
    self.trace = sce_forge_runtime::algorithm::add::<u32>(sce_forge_runtime::algorithm::mul::<u32>(self.trace, 10)?, 1)?;
    Ok(())
})() {
    Ok(()) => false,
    Err(_) => {
        engine.raise(sce_rust_runtime::EventWithMetadata::platform_error(StaticTimersEvent::ErrorExecution, "<assign location='trace'>: an integer operation overflowed or failed"));
        true
    }
};
                            if sce_failed {
                                break 'action_block; // W3C SCXML 4.9: the error ends the block
                            }
                        }
                    }
                    1 => {
                        // SCE-MAP: static_timers.scxml:37 :: waiting :: _transition_1
                        // W3C SCXML 3.13: Transition 1 actions
                        // W3C SCXML 4.9: a transition's content is one block; an error ends it.
                        'action_block: {
                            // W3C SCXML 5.3: <assign location="trace">
                            let sce_failed = match (|| -> Result<(), sce_forge_runtime::algorithm::AlgorithmError> {
    self.trace = sce_forge_runtime::algorithm::add::<u32>(sce_forge_runtime::algorithm::mul::<u32>(self.trace, 10)?, 2)?;
    Ok(())
})() {
    Ok(()) => false,
    Err(_) => {
        engine.raise(sce_rust_runtime::EventWithMetadata::platform_error(StaticTimersEvent::ErrorExecution, "<assign location='trace'>: an integer operation overflowed or failed"));
        true
    }
};
                            if sce_failed {
                                break 'action_block; // W3C SCXML 4.9: the error ends the block
                            }
                        }
                    }
                    2 => {
                        // SCE-MAP: static_timers.scxml:40 :: waiting :: _transition_2
                        // W3C SCXML 3.13: Transition 2 actions
                        // W3C SCXML 4.9: a transition's content is one block; an error ends it.
                        'action_block: {
                            // W3C SCXML 5.3: <assign location="trace">
                            let sce_failed = match (|| -> Result<(), sce_forge_runtime::algorithm::AlgorithmError> {
    self.trace = sce_forge_runtime::algorithm::add::<u32>(sce_forge_runtime::algorithm::mul::<u32>(self.trace, 10)?, 4)?;
    Ok(())
})() {
    Ok(()) => false,
    Err(_) => {
        engine.raise(sce_rust_runtime::EventWithMetadata::platform_error(StaticTimersEvent::ErrorExecution, "<assign location='trace'>: an integer operation overflowed or failed"));
        true
    }
};
                            if sce_failed {
                                break 'action_block; // W3C SCXML 4.9: the error ends the block
                            }
                        }
                    }
                    3 => {
                        // SCE-MAP: static_timers.scxml:43 :: waiting :: _transition_3
                        // W3C SCXML 3.13: Transition 3 actions
                        // W3C SCXML 4.9: a transition's content is one block; an error ends it.
                        'action_block: {
                            // W3C SCXML 5.3: <assign location="trace">
                            let sce_failed = match (|| -> Result<(), sce_forge_runtime::algorithm::AlgorithmError> {
    self.trace = sce_forge_runtime::algorithm::add::<u32>(sce_forge_runtime::algorithm::mul::<u32>(self.trace, 10)?, 3)?;
    Ok(())
})() {
    Ok(()) => false,
    Err(_) => {
        engine.raise(sce_rust_runtime::EventWithMetadata::platform_error(StaticTimersEvent::ErrorExecution, "<assign location='trace'>: an integer operation overflowed or failed"));
        true
    }
};
                            if sce_failed {
                                break 'action_block; // W3C SCXML 4.9: the error ends the block
                            }
                        }
                    }
                    4 => {
                        // SCE-MAP: static_timers.scxml:46 :: waiting :: _transition_4
                        // W3C SCXML 3.13: Transition 4 actions
                        // W3C SCXML 4.9: a transition's content is one block; an error ends it.
                        'action_block: {
                            // W3C SCXML 6.3: <cancel sendid="timer">
                            engine.cancel_event("timer");
                        }
                    }
                    _ => {}
                }
            }
            _ => {}
        }
    }

    // W3C SCXML 6.2 + 6.4: a delayed `<send target="#_parent">` whose wait is
    // over, with the payload an immediate one carries. It waited in this
    // machine's own queue, so `<cancel>` reached it and a child that ended
    // first dropped it — the engine dispatches nothing once final.
    fn deliver_to_parent(&mut self, event_name: &str, event_data: &str) -> bool {
        if let Some(ref parent_queue) = self.parent_external_queue {
            if let Ok(mut q) = parent_queue.lock() {
                q.push((event_name.to_string(), event_data.to_string()));
                return true;
            }
        }
        false
    }

    // W3C SCXML C.1: whether a session invoked this one — the queue the
    // invoking parent installs is the link to it.
    fn has_parent_session(&self) -> bool {
        self.parent_external_queue.is_some()
    }
}
