// SPDX-License-Identifier: LGPL-2.1-or-later WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael
//
// W3C SCXML G.7 `<sce:action>` — C11 compile+run gate for native host
// dispatch.
//
// A native action names a host operation and lowers to a DIRECT call
// through a struct of function pointers: no Lua state, no registry
// lookup, nothing to register at run time. That is the point of the
// construct on this backend in particular — it is the one action a
// machine with no `lua_State` at all can still perform, which is what
// makes an MCU document able to DO something rather than only decide.
//
// Fixture: sce-build/tests/fixtures/event_schema/statechart_native_action.scxml
// (the same document the Rust, C++, Go, Kotlin and Python channels
// drive), generated by `backends/c/tests/CMakeLists.txt`.
//
// Five scenarios drive it, and two of them are the ones the other five
// backends get from their type systems for free:
//
//   * `_init_with_actions` REFUSES a vtable with a NULL member, because
//     C cannot make an unimplemented operation a compile error the way
//     an interface does everywhere else;
//   * an event raised BY NAME carries no typed payload, and the
//     arg-bearing action must not fire against a zeroed buffer it would
//     take for data. The machine reaches `assembling` either way, so
//     only the host's record can tell the two apart.

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "statechart_native_action_sm.h"

// What the host saw, so each dispatch can be asserted rather than just
// its arrival.
typedef struct {
    int append_calls;
    uint8_t last_payload[64];
    size_t last_payload_len;
    uint32_t last_offset;
    int resets;
    int idle_entries;
    int assembling_exits;
} recorder_t;

static void on_append(void *user_data, const uint8_t *payload, size_t payload_len, uint32_t offset) {
    recorder_t *r = (recorder_t *)user_data;
    r->append_calls++;
    r->last_payload_len = payload_len < sizeof(r->last_payload) ? payload_len : sizeof(r->last_payload);
    memcpy(r->last_payload, payload, r->last_payload_len);
    r->last_offset = offset;
}

static void on_reset(void *user_data) {
    ((recorder_t *)user_data)->resets++;
}

static void on_idle_entry(void *user_data) {
    ((recorder_t *)user_data)->idle_entries++;
}

static void on_assembling_exit(void *user_data) {
    ((recorder_t *)user_data)->assembling_exits++;
}

static statechart_native_action_actions_t host_vtable(recorder_t *r) {
    statechart_native_action_actions_t v;
    memset(&v, 0, sizeof(v));
    v.append_fragment_payload = on_append;
    v.reset_slot = on_reset;
    v.on_idle_entry = on_idle_entry;
    v.on_assembling_exit = on_assembling_exit;
    v.user_data = r;
    return v;
}

static int check(const char *scenario, const char *what, long got, long want) {
    if (got == want) {
        return 0;
    }
    (void)fprintf(stderr, "native_action: FAIL [%s] - %s: got %ld, want %ld\n", scenario, what, got, want);
    return 1;
}

// The whole contract in one run: the entry effect on the initial entry,
// the arg-bearing transition action reading the typed payload, the
// no-argument transition action, the exit effect, and the re-entry.
static int a_host_receives_every_declared_act(void) {
    recorder_t r;
    memset(&r, 0, sizeof(r));
    statechart_native_action_actions_t v = host_vtable(&r);

    statechart_native_action_t sm;
    if (!statechart_native_action_init_with_actions(&sm, &v)) {
        (void)fprintf(stderr, "native_action: FAIL [every_act] - a complete vtable was refused\n");
        return 1;
    }

    int bad = 0;
    bad |= check("every_act", "in idle after init",
                 statechart_native_action_in_state(&sm, STATECHART_NATIVE_ACTION_STATE_IDLE), 1);
    // `<onentry>` of the initial state fires on entry — the engine-free
    // entry-effect path, with no transition having to carry the action.
    bad |= check("every_act", "on_idle_entry", r.idle_entries, 1);

    // Per-event typed inject: `fragment.received` with a bytes payload
    // and an offset. The transition fires append_fragment_payload.
    statechart_native_action_fragment_received_payload_t p;
    memset(&p, 0, sizeof(p));
    memcpy(p.payload, "abc", 3);
    p.payload_len = 3;
    p.offset = 7;
    statechart_native_action_raise_fragment_received_typed(&sm, &p);
    statechart_native_action_step(&sm);

    bad |= check("every_act", "in assembling",
                 statechart_native_action_in_state(&sm, STATECHART_NATIVE_ACTION_STATE_ASSEMBLING), 1);
    bad |= check("every_act", "append_fragment_payload calls", r.append_calls, 1);
    bad |= check("every_act", "payload length", (long)r.last_payload_len, 3);
    if (r.last_payload_len == 3 && memcmp(r.last_payload, "abc", 3) != 0) {
        (void)fprintf(stderr, "native_action: FAIL [every_act] - the typed bytes payload did not arrive\n");
        bad = 1;
    }
    bad |= check("every_act", "offset", (long)r.last_offset, 7);

    // `reset` fires the no-argument reset_slot and returns to idle.
    // Exiting `assembling` fires its `<onexit>` effect; re-entering
    // `idle` fires `<onentry>` a second time.
    statechart_native_action_event_with_meta_t evt;
    memset(&evt, 0, sizeof(evt));
    evt.event = STATECHART_NATIVE_ACTION_EVENT_RESET;
    statechart_native_action_raise_external(&sm, &evt);
    statechart_native_action_step(&sm);

    bad |= check("every_act", "back in idle",
                 statechart_native_action_in_state(&sm, STATECHART_NATIVE_ACTION_STATE_IDLE), 1);
    bad |= check("every_act", "reset_slot", r.resets, 1);
    bad |= check("every_act", "on_assembling_exit", r.assembling_exits, 1);
    bad |= check("every_act", "on_idle_entry after re-entry", r.idle_entries, 2);

    statechart_native_action_destroy(&sm);
    return bad;
}

// An event raised by NAME carries no typed payload. The transition still
// fires — the guard is the event name — but the arg-bearing action has
// nothing to read, and handing the host a zeroed buffer it would take
// for data is the one outcome this seam must never produce.
static int an_untyped_delivery_does_not_fire_the_arg_bearing_act(void) {
    recorder_t r;
    memset(&r, 0, sizeof(r));
    statechart_native_action_actions_t v = host_vtable(&r);

    statechart_native_action_t sm;
    if (!statechart_native_action_init_with_actions(&sm, &v)) {
        (void)fprintf(stderr, "native_action: FAIL [untyped] - a complete vtable was refused\n");
        return 1;
    }

    statechart_native_action_event_with_meta_t evt;
    memset(&evt, 0, sizeof(evt));
    evt.event = STATECHART_NATIVE_ACTION_EVENT_FRAGMENT_RECEIVED;
    statechart_native_action_raise_external(&sm, &evt);
    statechart_native_action_step(&sm);

    int bad = 0;
    // The machine moves either way, which is exactly why the host's
    // record is what this scenario reads.
    bad |= check("untyped", "in assembling",
                 statechart_native_action_in_state(&sm, STATECHART_NATIVE_ACTION_STATE_ASSEMBLING), 1);
    bad |= check("untyped", "append_fragment_payload calls", r.append_calls, 0);
    // The eventless effects still ran: they read no payload, so nothing
    // about this delivery should have stopped them.
    bad |= check("untyped", "on_idle_entry", r.idle_entries, 1);

    statechart_native_action_destroy(&sm);
    return bad;
}

// The check the other five backends get from their type systems. A host
// that forgot one operation is a host that does not perform an act the
// document declared, and discovering that at the first entry action is
// discovering it as a null call.
static int a_vtable_missing_an_operation_is_refused(void) {
    recorder_t r;
    memset(&r, 0, sizeof(r));
    statechart_native_action_actions_t v = host_vtable(&r);
    v.reset_slot = NULL;

    statechart_native_action_t sm;
    if (statechart_native_action_init_with_actions(&sm, &v)) {
        (void)fprintf(stderr, "native_action: FAIL [incomplete] - a vtable missing reset_slot was accepted\n");
        statechart_native_action_destroy(&sm);
        return 1;
    }
    // A refused call must not have run anything: the entry effect is the
    // first thing `_init` would reach, so its absence is what says the
    // refusal came before the walk rather than during it.
    return check("incomplete", "on_idle_entry after a refused init", r.idle_entries, 0);
}

static int a_null_vtable_is_refused(void) {
    statechart_native_action_t sm;
    if (statechart_native_action_init_with_actions(&sm, NULL)) {
        (void)fprintf(stderr, "native_action: FAIL [null] - a NULL vtable was accepted\n");
        statechart_native_action_destroy(&sm);
        return 1;
    }
    return 0;
}

// Two machines, two hosts, one binary: the vtable is per-machine state
// and not a process-global registry, so a second host cannot receive the
// first one's acts.
static int two_machines_reach_their_own_hosts(void) {
    recorder_t a;
    recorder_t b;
    memset(&a, 0, sizeof(a));
    memset(&b, 0, sizeof(b));
    statechart_native_action_actions_t va = host_vtable(&a);
    statechart_native_action_actions_t vb = host_vtable(&b);

    statechart_native_action_t sm_a;
    statechart_native_action_t sm_b;
    if (!statechart_native_action_init_with_actions(&sm_a, &va) ||
        !statechart_native_action_init_with_actions(&sm_b, &vb)) {
        (void)fprintf(stderr, "native_action: FAIL [two_hosts] - a complete vtable was refused\n");
        return 1;
    }

    statechart_native_action_event_with_meta_t evt;
    memset(&evt, 0, sizeof(evt));
    evt.event = STATECHART_NATIVE_ACTION_EVENT_FRAGMENT_RECEIVED;
    statechart_native_action_raise_external(&sm_a, &evt);
    statechart_native_action_step(&sm_a);

    int bad = 0;
    bad |= check("two_hosts", "first host entered idle once", a.idle_entries, 1);
    bad |= check("two_hosts", "second host entered idle once", b.idle_entries, 1);
    bad |= check("two_hosts", "second host saw no exit", b.assembling_exits, 0);

    statechart_native_action_destroy(&sm_a);
    statechart_native_action_destroy(&sm_b);
    return bad;
}

int main(void) {
    int bad = 0;
    bad |= a_host_receives_every_declared_act();
    bad |= an_untyped_delivery_does_not_fire_the_arg_bearing_act();
    bad |= a_vtable_missing_an_operation_is_refused();
    bad |= a_null_vtable_is_refused();
    bad |= two_machines_reach_their_own_hosts();

    if (bad != 0) {
        (void)fprintf(stderr, "native_action: FAIL - see the scenario(s) named above\n");
        return 1;
    }
    (void)printf("native_action: PASS - 5 scenarios\n");
    return 0;
}
