#!/usr/bin/env bash
# SPDX-License-Identifier: LGPL-2.1-or-later WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
# SPDX-FileCopyrightText: Copyright (c) 2025 newmassrael
#
# clang-format conformance check shared by the pre-commit hook
# (tools/git-hooks/pre-commit) and the CI gate
# (.github/workflows/clang-format-check.yml) so file enumeration and
# the generated-source policy live in exactly one place.
#
# Usage:
#   scripts/check_clang_format.sh              # every tracked C/C++ file
#   scripts/check_clang_format.sh FILE...      # only the given files
#
# Exclusions:
#   - Vendored subtrees (third_party/, examples/doom_wasm/doomgeneric/)
#     carry a .clang-format with DisableFormat: true, so clang-format
#     itself skips them — no path logic needed here.
#   - Generated sources are recognized by their provenance header
#     (first 10 lines) and skipped: their formatting is owned by the
#     codegen templates, and reformatting them would break byte-golden
#     comparisons and the drift-verify gates.
#
# Override the binary with CLANG_FORMAT=clang-format-19 (CI pins the
# major version; the tree was normalized with clang-format 19).
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# Fanning out over every tracked C/C++ file is a parallel workload like any
# build, and this runs from the pre-commit hook and a CI gate — both of which
# share the machine with whatever else is on it.
source "$(pwd)/scripts/lib/sce_build_jobs.sh"

CLANG_FORMAT="${CLANG_FORMAT:-clang-format}"
GENERATED_MARKER='SCE-GENERATED|Auto-generated|SCE-MAP:|Generated by SCE|@generated'

if [ $# -gt 0 ]; then
    candidates=("$@")
else
    mapfile -t candidates < <(git ls-files '*.c' '*.cc' '*.cpp' '*.h' '*.hpp')
fi

targets=()
for f in "${candidates[@]}"; do
    case "$f" in
        *.c | *.cc | *.cpp | *.h | *.hpp) ;;
        *) continue ;;
    esac
    [ -f "$f" ] || continue
    if head -10 "$f" | grep -qE "$GENERATED_MARKER"; then
        continue
    fi
    targets+=("$f")
done

if [ ${#targets[@]} -eq 0 ]; then
    echo "check_clang_format: no eligible C/C++ files to check."
    exit 0
fi

printf '%s\0' "${targets[@]}" \
    | xargs -0 -P "$(sce_build_jobs_value)" -n 32 "$CLANG_FORMAT" --dry-run --Werror
