// SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-SCE-Linking-Exception OR LicenseRef-SCE-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2026 newmassrael

//! What an event does to a generation request, decided by the machine the request's document
//! generates (`machines/request_life/request_life.scxml`, regenerated by
//! `machines/generate.sh`).
//!
//! `requests.rs` keeps the record: the inputs a request was made from, its pin, the candidate an
//! executor wrote, the notes and the timestamps. This module is the seam to the rules. A request
//! stands where its state, attempt, holder, lease end and outcome say it does; [`decide`] stands a
//! machine there, hands it one event, and reads back what the machine holds: whether the event was
//! taken, why it was not, and the state, attempt, holder, lease end and outcome that result. No rule
//! is written here, and none is written in `requests.rs`: which events a state takes, by whom, and
//! what the lease ran out of, are the document's.
//!
//! The machine is stood where a request stands by taking the saved state the engine writes of a
//! fresh one and replacing the parts a request keeps (where it is, and its five variables). The
//! rest of that text (its format, the shape of the document it is bound to, its empty queues) is the
//! engine's own, so this module names no more of the saved-state format than it has to.

use std::sync::OnceLock;

use sce_rust_runtime::saved_state::SavedState;
use sce_rust_runtime::Engine;
use serde_json::{json, Value};

use crate::requests::State;

#[path = "generated/request_life_sm.rs"]
mod machine;

use machine::{RequestLifePersist, RequestLifePolicy};

/// The most bytes a holder or a bundle may be: the capacity the document gives its strings
/// (`sce:capacity` and the schemas' `sce:max-size`). The store names an executor by at most
/// this many bytes (`request_store::NAME_MAX`), and a bundle is a revision's 64 hex digits.
pub(crate) const TEXT_MAX: usize = 64;

/// One thing said to a request. What each carries is what a rule reads and nothing more.
#[derive(Debug, Clone, Copy)]
pub(crate) enum Event<'a> {
    /// An executor takes the request. `offered_matches`: the connection it offers is the one the
    /// request was made for.
    Claim {
        holder: &'a str,
        ttl: u64,
        resume: bool,
        offered_matches: bool,
        now: u64,
    },
    /// The executor of `attempt` says it is still there.
    Heartbeat {
        holder: &'a str,
        attempt: u32,
        ttl: u64,
        now: u64,
    },
    /// The executor of `attempt` says it is done, and names the bundle it made.
    Publish {
        holder: &'a str,
        attempt: u32,
        bundle: &'a str,
    },
    /// The executor of `attempt` says it could not.
    Fail { holder: &'a str, attempt: u32 },
    /// The executor of `attempt` wrote something for the request.
    Write { holder: &'a str, attempt: u32 },
    /// The owner calls the request off.
    Cancel,
    /// The request is replaced, or what it was asked about moved.
    Supersede,
    /// The request is looked at: a running one whose lease ran out is written down.
    Normalize { now: u64 },
}

impl Event<'_> {
    /// The event as the machine is told it: its name and its payload, as JSON.
    fn wire(&self) -> (&'static str, String) {
        match *self {
            Event::Claim {
                holder,
                ttl,
                resume,
                offered_matches,
                now,
            } => (
                "claim",
                json!({
                    "holder": holder, "ttl": ttl, "resume": resume,
                    "offeredMatches": offered_matches, "now": now,
                })
                .to_string(),
            ),
            Event::Heartbeat {
                holder,
                attempt,
                ttl,
                now,
            } => (
                "heartbeat",
                json!({ "holder": holder, "attempt": attempt, "ttl": ttl, "now": now }).to_string(),
            ),
            Event::Publish {
                holder,
                attempt,
                bundle,
            } => (
                "publish",
                json!({ "holder": holder, "attempt": attempt, "bundle": bundle }).to_string(),
            ),
            Event::Fail { holder, attempt } => (
                "fail",
                json!({ "holder": holder, "attempt": attempt }).to_string(),
            ),
            Event::Write { holder, attempt } => (
                "write",
                json!({ "holder": holder, "attempt": attempt }).to_string(),
            ),
            Event::Cancel => ("cancel", String::new()),
            Event::Supersede => ("supersede", String::new()),
            Event::Normalize { now } => ("normalize", json!({ "now": now }).to_string()),
        }
    }
}

/// What the machine said of an event.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Verdict {
    /// The event was taken.
    Ok,
    /// The request had ended.
    Ended,
    /// An executor holds it under a lease that has not run out.
    Held,
    /// The caller is not the executor of the current attempt.
    NotHolder,
    /// It was let go of, and the caller did not say it resumes.
    NotResuming,
    /// It was made for another connection than the caller offers.
    WrongConnection,
    /// There was nothing for the event to do.
    Nothing,
}

/// Where a request stands, as far as a rule reads it.
#[derive(Debug, Clone, Copy)]
pub(crate) struct Standing<'a> {
    pub state: State,
    pub attempt: u32,
    /// The executor of the last claim; empty for a request nobody took.
    pub holder: &'a str,
    /// Seconds since the Unix epoch the last claim runs out at; 0 for a request nobody took.
    pub expires_at: u64,
    /// The bundle a completed request published; empty for one that did not.
    pub outcome: &'a str,
}

/// What the machine holds after an event.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Answer {
    pub verdict: Verdict,
    pub state: State,
    pub attempt: u32,
    pub holder: String,
    pub expires_at: u64,
    pub outcome: String,
}

const STATES: [State; 7] = [
    State::Queued,
    State::Running,
    State::Completed,
    State::Failed,
    State::Cancelled,
    State::Interrupted,
    State::Superseded,
];

/// The states a machine is in at once when it is in `state`: the document's root, the group the
/// state belongs to, and the state.
fn configuration(state: State) -> [&'static str; 3] {
    let group = if state.is_open() { "open" } else { "ended" };
    ["request", group, state.word()]
}

/// The saved state of a machine nothing has happened to, written by the engine. Its format and
/// the shape it is bound to are the engine's to say.
fn fresh() -> &'static Value {
    static FRESH: OnceLock<Value> = OnceLock::new();
    FRESH.get_or_init(|| {
        let mut engine = Engine::new(RequestLifePolicy::new());
        engine.initialize();
        let text = engine
            .save()
            .expect("a machine that was just started can be saved")
            .to_json();
        serde_json::from_str(&text).expect("a saved state is JSON")
    })
}

fn number(value: &Value, what: &str) -> u64 {
    // A 64-bit integer is saved as its decimal text, so that no reader that holds numbers as
    // doubles loses its low bits; a narrower one is a JSON number.
    let parsed = match value {
        Value::String(text) => text.parse::<u64>().ok(),
        other => other.as_u64(),
    };
    parsed.unwrap_or_else(|| panic!("the machine's `{what}` is not a number: {value}"))
}

/// A machine standing where `standing` says a request stands.
///
/// A holder or a bundle of more than [`TEXT_MAX`] bytes is one the machine cannot hold, and the
/// caller has not validated it: that is a bug of the caller, so it is refused with a panic that
/// names it and not answered as if the request had been asked something else.
fn stand(standing: &Standing<'_>) -> Engine<RequestLifePolicy> {
    let mut saved = fresh().clone();
    saved["configuration"] = json!(configuration(standing.state));
    saved["current"] = json!(standing.state.word());
    let variables = &mut saved["variables"];
    variables["holder"] = json!(standing.holder);
    variables["attempt"] = json!(standing.attempt);
    variables["expiresAt"] = json!(standing.expires_at.to_string());
    variables["outcome"] = json!(standing.outcome);
    variables["verdict"] = json!("unanswered");

    let saved = SavedState::from_json(&saved.to_string()).unwrap_or_else(|why| {
        panic!(
            "the request machine cannot stand where {standing:?} says (text longer than {TEXT_MAX} bytes?): {}",
            why.reason()
        )
    });
    Engine::<RequestLifePolicy>::restore(RequestLifePolicy::new(), &saved).unwrap_or_else(|why| {
        panic!(
            "the request machine cannot stand where {standing:?} says: {}",
            why.reason()
        )
    })
}

/// Stand a machine where `standing` says a request stands, say `event` to it, and read what it
/// holds.
pub(crate) fn decide(standing: &Standing<'_>, event: &Event<'_>) -> Answer {
    let mut engine = stand(standing);
    let (name, data) = event.wire();
    engine.raise_external_by_name(name, &data);
    engine.step();
    let text = engine
        .save()
        .unwrap_or_else(|why| panic!("the request machine cannot be saved: {}", why.reason()))
        .to_json();
    let after: Value = serde_json::from_str(&text).expect("a saved state is JSON");

    let word = |value: &Value| value.as_str().unwrap_or_default().to_string();
    let verdict = match word(&after["variables"]["verdict"]).as_str() {
        "ok" => Verdict::Ok,
        "ended" => Verdict::Ended,
        "held" => Verdict::Held,
        "not_holder" => Verdict::NotHolder,
        "not_resuming" => Verdict::NotResuming,
        "wrong_connection" => Verdict::WrongConnection,
        "nothing" => Verdict::Nothing,
        _ => panic!(
            "the request machine took no `{name}` event from {standing:?}: its payload was refused \
             (a holder or a bundle longer than {TEXT_MAX} bytes?)"
        ),
    };
    let current = word(&after["current"]);
    let state = STATES
        .into_iter()
        .find(|state| state.word() == current)
        .unwrap_or_else(|| panic!("the request machine stands in `{current}`, which is no state"));
    Answer {
        verdict,
        state,
        attempt: u32::try_from(number(&after["variables"]["attempt"], "attempt"))
            .expect("an attempt is a 32-bit number"),
        holder: word(&after["variables"]["holder"]),
        expires_at: number(&after["variables"]["expiresAt"], "expiresAt"),
        outcome: word(&after["variables"]["outcome"]),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const T0: u64 = 1_000;
    const BUNDLE: &str = "bundle-0";

    /// A request in `state`, held by `a` as its first attempt under a lease that runs out at
    /// `T0 + 60`, and a completed one with its bundle.
    fn standing(state: State) -> Standing<'static> {
        match state {
            State::Queued => Standing {
                state,
                attempt: 0,
                holder: "",
                expires_at: 0,
                outcome: "",
            },
            State::Completed => Standing {
                state,
                attempt: 1,
                holder: "a",
                expires_at: T0 + 60,
                outcome: BUNDLE,
            },
            _ => Standing {
                state,
                attempt: 1,
                holder: "a",
                expires_at: T0 + 60,
                outcome: "",
            },
        }
    }

    fn claim(holder: &str, resume: bool, offered_matches: bool, now: u64) -> Event<'_> {
        Event::Claim {
            holder,
            ttl: 60,
            resume,
            offered_matches,
            now,
        }
    }

    fn heartbeat(holder: &str, attempt: u32) -> Event<'_> {
        Event::Heartbeat {
            holder,
            attempt,
            ttl: 60,
            now: T0 + 30,
        }
    }

    fn publish<'a>(holder: &'a str, attempt: u32, bundle: &'a str) -> Event<'a> {
        Event::Publish {
            holder,
            attempt,
            bundle,
        }
    }

    /// Every state against every event, with the callers that tell one rule from another: the
    /// holder of the attempt, another executor, the right executor naming the wrong attempt, and
    /// the clock before and at the end of the lease. What each comes to is written out, so a
    /// rule that changed in the document shows here as the row it moved.
    #[test]
    fn what_each_state_does_with_each_event_is_the_table_of_the_request_life() {
        use State::*;
        use Verdict as V;
        let cases: Vec<(State, Event<'_>, Verdict, State)> = vec![
            // Nobody took it: only a claim, the owner, and the clock mean anything.
            (Queued, claim("a", false, true, T0), V::Ok, Running),
            (Queued, claim("a", true, true, T0), V::Ok, Running),
            (
                Queued,
                claim("a", false, false, T0),
                V::WrongConnection,
                Queued,
            ),
            (Queued, heartbeat("a", 0), V::NotHolder, Queued),
            (Queued, publish("a", 0, BUNDLE), V::NotHolder, Queued),
            (
                Queued,
                Event::Fail {
                    holder: "a",
                    attempt: 0,
                },
                V::NotHolder,
                Queued,
            ),
            (
                Queued,
                Event::Write {
                    holder: "a",
                    attempt: 0,
                },
                V::NotHolder,
                Queued,
            ),
            (Queued, Event::Cancel, V::Ok, Cancelled),
            (Queued, Event::Supersede, V::Ok, Superseded),
            (
                Queued,
                Event::Normalize { now: T0 + 999 },
                V::Nothing,
                Queued,
            ),
            // Held under a lease: renewed, finished or written for by its attempt, and by nobody else.
            (Running, claim("a", true, true, T0 + 59), V::Held, Running),
            (Running, claim("b", true, true, T0 + 59), V::Held, Running),
            (
                Running,
                claim("b", true, false, T0 + 59),
                V::WrongConnection,
                Running,
            ),
            (
                Running,
                claim("b", false, true, T0 + 60),
                V::NotResuming,
                Running,
            ),
            (Running, claim("b", true, true, T0 + 60), V::Ok, Running),
            (Running, heartbeat("a", 1), V::Ok, Running),
            (Running, heartbeat("b", 1), V::NotHolder, Running),
            (Running, heartbeat("a", 2), V::NotHolder, Running),
            (Running, publish("a", 1, BUNDLE), V::Ok, Completed),
            (Running, publish("b", 1, BUNDLE), V::NotHolder, Running),
            (
                Running,
                Event::Fail {
                    holder: "a",
                    attempt: 1,
                },
                V::Ok,
                Failed,
            ),
            (
                Running,
                Event::Fail {
                    holder: "a",
                    attempt: 7,
                },
                V::NotHolder,
                Running,
            ),
            (
                Running,
                Event::Write {
                    holder: "a",
                    attempt: 1,
                },
                V::Ok,
                Running,
            ),
            (
                Running,
                Event::Write {
                    holder: "b",
                    attempt: 1,
                },
                V::NotHolder,
                Running,
            ),
            (Running, Event::Cancel, V::Ok, Cancelled),
            (Running, Event::Supersede, V::Ok, Superseded),
            (
                Running,
                Event::Normalize { now: T0 + 59 },
                V::Nothing,
                Running,
            ),
            (
                Running,
                Event::Normalize { now: T0 + 60 },
                V::Ok,
                Interrupted,
            ),
            // Let go of: taken again only by a caller that resumes it, and still the holder's.
            (
                Interrupted,
                claim("b", false, true, T0 + 100),
                V::NotResuming,
                Interrupted,
            ),
            (
                Interrupted,
                claim("b", true, true, T0 + 100),
                V::Ok,
                Running,
            ),
            (
                Interrupted,
                claim("b", true, false, T0 + 100),
                V::WrongConnection,
                Interrupted,
            ),
            (Interrupted, heartbeat("a", 1), V::Ok, Running),
            (Interrupted, heartbeat("b", 1), V::NotHolder, Interrupted),
            (Interrupted, publish("a", 1, BUNDLE), V::Ok, Completed),
            (
                Interrupted,
                Event::Fail {
                    holder: "a",
                    attempt: 1,
                },
                V::Ok,
                Failed,
            ),
            (
                Interrupted,
                Event::Write {
                    holder: "a",
                    attempt: 1,
                },
                V::Ok,
                Interrupted,
            ),
            (
                Interrupted,
                Event::Write {
                    holder: "a",
                    attempt: 2,
                },
                V::NotHolder,
                Interrupted,
            ),
            (Interrupted, Event::Cancel, V::Ok, Cancelled),
            (Interrupted, Event::Supersede, V::Ok, Superseded),
            (
                Interrupted,
                Event::Normalize { now: T0 + 999 },
                V::Nothing,
                Interrupted,
            ),
            // Ended: it takes nothing more, except the same word said again by the same attempt.
            (Completed, publish("a", 1, BUNDLE), V::Ok, Completed),
            (Completed, publish("a", 1, "another"), V::Ended, Completed),
            (Completed, publish("b", 1, BUNDLE), V::Ended, Completed),
            (Completed, publish("a", 2, BUNDLE), V::Ended, Completed),
            (Completed, heartbeat("a", 1), V::Ended, Completed),
            (
                Completed,
                Event::Fail {
                    holder: "a",
                    attempt: 1,
                },
                V::Ended,
                Completed,
            ),
            (
                Completed,
                Event::Write {
                    holder: "a",
                    attempt: 1,
                },
                V::Ended,
                Completed,
            ),
            (Completed, Event::Cancel, V::Ended, Completed),
            (
                Completed,
                claim("b", true, true, T0 + 999),
                V::Ended,
                Completed,
            ),
            (
                Completed,
                claim("b", true, false, T0 + 999),
                V::WrongConnection,
                Completed,
            ),
            (Completed, Event::Supersede, V::Nothing, Completed),
            (
                Completed,
                Event::Normalize { now: T0 + 999 },
                V::Nothing,
                Completed,
            ),
            (
                Failed,
                Event::Fail {
                    holder: "a",
                    attempt: 1,
                },
                V::Ok,
                Failed,
            ),
            (
                Failed,
                Event::Fail {
                    holder: "b",
                    attempt: 1,
                },
                V::Ended,
                Failed,
            ),
            (Failed, publish("a", 1, BUNDLE), V::Ended, Failed),
            (Failed, heartbeat("a", 1), V::Ended, Failed),
            (Failed, Event::Cancel, V::Ended, Failed),
            (Failed, claim("b", true, true, T0 + 999), V::Ended, Failed),
            (Failed, Event::Supersede, V::Nothing, Failed),
            (Cancelled, Event::Cancel, V::Ok, Cancelled),
            (Cancelled, publish("a", 1, BUNDLE), V::Ended, Cancelled),
            (Cancelled, heartbeat("a", 1), V::Ended, Cancelled),
            (
                Cancelled,
                Event::Fail {
                    holder: "a",
                    attempt: 1,
                },
                V::Ended,
                Cancelled,
            ),
            (
                Cancelled,
                claim("b", true, true, T0 + 999),
                V::Ended,
                Cancelled,
            ),
            (Cancelled, Event::Supersede, V::Nothing, Cancelled),
            (Superseded, Event::Cancel, V::Ended, Superseded),
            (Superseded, publish("a", 1, BUNDLE), V::Ended, Superseded),
            (Superseded, heartbeat("a", 1), V::Ended, Superseded),
            (
                Superseded,
                claim("b", true, true, T0 + 999),
                V::Ended,
                Superseded,
            ),
            (Superseded, Event::Supersede, V::Nothing, Superseded),
            (
                Superseded,
                Event::Normalize { now: T0 + 999 },
                V::Nothing,
                Superseded,
            ),
        ];
        for (state, event, verdict, then) in cases {
            let answer = decide(&standing(state), &event);
            assert_eq!(
                (answer.verdict, answer.state),
                (verdict, then),
                "{state:?} told {event:?}"
            );
        }
    }

    /// What a taken event leaves in the machine's variables is what the record is written from.
    #[test]
    fn a_taken_event_leaves_the_attempt_the_holder_and_the_end_of_the_lease_it_made() {
        let taken = decide(&standing(State::Queued), &claim("b", false, true, T0));
        assert_eq!(
            (taken.attempt, taken.holder.as_str(), taken.expires_at),
            (1, "b", T0 + 60)
        );
        // A claim by a caller that resumes a request whose lease ran out is the next attempt.
        let resumed = decide(&standing(State::Running), &claim("b", true, true, T0 + 100));
        assert_eq!(
            (resumed.attempt, resumed.holder.as_str(), resumed.expires_at),
            (2, "b", T0 + 160)
        );
        // A renewal moves the end of the lease and nothing else.
        let renewed = decide(&standing(State::Running), &heartbeat("a", 1));
        assert_eq!(
            (renewed.attempt, renewed.holder.as_str(), renewed.expires_at),
            (1, "a", T0 + 90)
        );
        let done = decide(&standing(State::Running), &publish("a", 1, BUNDLE));
        assert_eq!(done.outcome, BUNDLE);
        // A refusal leaves everything as it stood.
        let refused = decide(&standing(State::Running), &heartbeat("b", 1));
        assert_eq!(
            (refused.attempt, refused.holder.as_str(), refused.expires_at),
            (1, "a", T0 + 60)
        );
    }

    /// The states a machine is in at once, which [`configuration`] writes from the group a state
    /// belongs to, are the ones the machine itself reaches. Each state is arrived at by an event,
    /// and the saved state the machine writes is compared with the table.
    #[test]
    fn the_group_a_state_belongs_to_is_the_one_the_machine_puts_it_in() {
        let arrivals = [
            (State::Queued, Event::Normalize { now: T0 }, State::Queued),
            (State::Queued, claim("a", false, true, T0), State::Running),
            (
                State::Running,
                Event::Normalize { now: T0 + 60 },
                State::Interrupted,
            ),
            (State::Running, publish("a", 1, BUNDLE), State::Completed),
            (
                State::Running,
                Event::Fail {
                    holder: "a",
                    attempt: 1,
                },
                State::Failed,
            ),
            (State::Running, Event::Cancel, State::Cancelled),
            (State::Running, Event::Supersede, State::Superseded),
        ];
        let mut reached = Vec::new();
        for (from, event, to) in arrivals {
            let mut engine = stand(&standing(from));
            let (name, data) = event.wire();
            engine.raise_external_by_name(name, &data);
            engine.step();
            let saved: Value =
                serde_json::from_str(&engine.save().expect("saves").to_json()).expect("JSON");
            assert_eq!(
                saved["configuration"],
                json!(configuration(to)),
                "{from:?} to {to:?}"
            );
            assert_eq!(saved["current"], json!(to.word()));
            reached.push(to);
        }
        for state in STATES {
            assert!(
                reached.contains(&state),
                "{state:?} is never arrived at here"
            );
        }
    }

    /// A name the store accepts is one a request holds: the longest one is a holder, and a byte
    /// more is not a name the machine can be told.
    #[test]
    fn a_holder_of_the_longest_name_is_held_and_one_byte_more_cannot_be_told() {
        let longest = "h".repeat(TEXT_MAX);
        let taken = decide(&standing(State::Queued), &claim(&longest, false, true, T0));
        assert_eq!(
            (taken.verdict, taken.holder),
            (Verdict::Ok, longest.clone())
        );
        let held = Standing {
            holder: &longest,
            ..standing(State::Running)
        };
        assert_eq!(decide(&held, &heartbeat(&longest, 1)).verdict, Verdict::Ok);
    }

    #[test]
    #[should_panic(expected = "took no `claim` event")]
    fn a_holder_longer_than_the_machine_holds_is_a_caller_that_did_not_check() {
        let too_long = "h".repeat(TEXT_MAX + 1);
        decide(&standing(State::Queued), &claim(&too_long, false, true, T0));
    }

    #[test]
    #[should_panic(expected = "cannot stand where")]
    fn a_request_whose_holder_is_longer_than_the_machine_holds_cannot_be_stood() {
        let too_long = "h".repeat(TEXT_MAX + 1);
        let standing = Standing {
            holder: &too_long,
            ..standing(State::Running)
        };
        decide(&standing, &Event::Cancel);
    }
}
