// SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-SCE-Commercial
// SPDX-FileCopyrightText: Copyright (c) 2025 newmassrael

//! W3C SCXML 5.10.1: Event type classification helpers.
//!
//! 1:1 port of `sce/include/common/EventTypeHelper.h`. Provides the single
//! source of truth for event type detection shared between engines.

use crate::event::EventType;
use crate::helpers::string_utils;

/// W3C SCXML 5.10.1: Classify event type by name and origin.
///
/// Classification rules:
/// - `"platform"`: Events generated by the platform (`error.*`, `done.*`)
/// - `"external"`: Events from `<send>` (external event queue)
/// - `"internal"`: Events from `<raise>` (internal event queue)
///
/// Ports C++ `EventTypeHelper::classifyEventType`.
pub fn classify_event_type(event_name: &str, is_external: bool) -> EventType {
    // W3C SCXML 5.10.1: Platform events have highest priority
    if string_utils::is_platform_event(event_name) {
        return EventType::Platform;
    }

    // W3C SCXML 5.10.1: External events from <send>
    if is_external {
        return EventType::External;
    }

    // W3C SCXML 5.10.1: Default to internal (from <raise>)
    EventType::Internal
}
